### ISSUE TITLE
[Discuss] What capabilities do you expect VMind to provide?

### ISSUE THREAD

**Issue by xuanhun** [VisActor/VChart#1014]
1. If you would like to integrate VMind into your project and require additional support from us, please write down your requirements.
2. If you are interested in this project and would like to contribute, feel free to leave a comment.
3. If you have new ideas that you would like to discuss, we welcome open communication.
4. Welcome to give VisActor a star，if you  think it's great.

**Comment by yyhack110** [comment]
期待VMind开源

**Comment by xiaoluoHe** [comment]
> 期待VMind开源

已经开源啦，仓库链接：https://github.com/VisActor/VChart/tree/develop/packages/vmind

欢迎交流
