### ISSUE TITLE
[Bug] Tooltip is displayed incorrectly when scrolling on mobile 

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#105]
### Version

1.0.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

trigger dimension tooltip and then scroll page

### Current Behavior

https://github.com/VisActor/VChart/assets/15776277/1632bc2f-3252-41f1-be59-623b9a96ccc6

### Expected Behavior

tooltip is displayed incorrectly in this case

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by zamhown** [comment]
Merged to another issue for resolution, verification indicates that the problem has disappeared
