### ISSUE TITLE
[Feature] Label support labelLine

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#1087]
### What problem does this feature solve?

Label component can support the labelLine which can connect the label and mark, and it should be a common property no matter what type of mark.

```ts
label: {
  line: {
    visible: true,
  }
}
```
|bar | line |
|--------|--------|
|![image](https://github.com/VisActor/VChart/assets/135952300/cecc1733-723e-4cf1-b755-f17f86feb14d) |![image](https://github.com/VisActor/VChart/assets/135952300/af354f76-ac2a-4c04-bcba-4147fb9d5fe9) | 

### What does the proposed API look like?

refer to:
1. https://echarts.apache.org/en/option.html#series-line.labelLine
2. https://echarts.apache.org/en/option.html#series-bar.labelLine

**Comment by xiaoluoHe** [comment]
`label.line.visible: true`
![image](https://github.com/VisActor/VChart/assets/11360419/e1af0e58-0475-4ee9-a283-f5d8f8dac1a5)
