### ISSUE TITLE
[Feature] total label: stack chart support total label

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#110]
### What problem does this feature solve?

![image](https://github.com/VisActor/VChart/assets/8744196/063d0b76-fec6-4ca8-aa02-0aa78c516a68)
![image](https://github.com/VisActor/VChart/assets/8744196/ab5f3eb1-0257-4290-8993-34d59a9c8d9c)

### What does the proposed API look like?

totalLabel: {
  visable: true,
}

**Comment by kkxxkk2019** [comment]
Vrender 0.14.0 already released

**Comment by kkxxkk2019** [comment]
https://github.com/VisActor/VChart/pull/510
