### ISSUE TITLE
[Bug] Event intercept

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#1115]
1. brush
2. datazoom
3. scroll bar
4. size, color legend 
5. map drag
6. player
7. ....

**Comment by xiaoluoHe** [comment]
> 在有地图、有滚动条时, 滚动时,触发wheel事件, 这个也得拦截

vchart 已经配置了consume了，但是不生效
![f51afca8-aca5-41b1-bda4-9fc08b8925d3](https://github.com/VisActor/VChart/assets/11360419/86e1807a-30ce-4d6c-9c14-b79dd6d7a1bb)

排查了下，应该是底层事件代理的问题
![img_v2_8669a17b-f896-4a45-b7c1-254e2f610f1g](https://github.com/VisActor/VChart/assets/11360419/cb7373a2-0c7c-49a8-a798-c52561c8e111)

**Comment by xiaoluoHe** [comment]
> 组件场景如：brush/datazoom/scroll bar/size, color legend/player
> 定位过程如下：

一开始发现在 handler 里是主动停止冒泡了。
![752c4129-8f13-41da-a3a2-b9f4c3a1f262](https://github.com/VisActor/VChart/assets/11360419/474e43cd-0653-4efe-bff5-f30181bb1cfb)

然而我手动添加的 pointermove 事件依然会被触发
![691af4a6-aaf2-4550-9990-a0f582c79a5e](https://github.com/VisActor/VChart/assets/11360419/db7d815f-318a-4eb7-8d6b-130e558aadcb)

那猜测，事件冒泡先触发了 div （我主动挂载的事件监听），后触发了图例的事件；
由于事件默认是在冒泡阶段处理的，这就意味着图例的事件，大概率被挂载在 window 上了；
验证一下，发现确实只打印了 ' div:pointermove'
![3470a507-de5f-48ac-8dc3-582e5f8213c8](https://github.com/VisActor/VChart/assets/11360419/2e51ed48-00e6-45c1-858a-dbfef7641c98)

于是我尝试下，把图例 pointermove 事件改在捕获阶段处理；
![40543790-ac60-4461-a00b-0ac1db05f38e](https://github.com/VisActor/VChart/assets/11360419/f0b4c6da-ac51-4151-93fd-c710deac5277)

同时再测试了一下，这会儿就都不会打印了
![3470a507-de5f-48ac-8dc3-582e5f8213c8](https://github.com/VisActor/VChart/assets/11360419/a8ce8c1d-982b-4f74-8cf6-ddb53e96faee)
