### ISSUE TITLE
[Feature] responsive adaptation for chart container size in new themes

### ISSUE THREAD

**Issue by zamhown** [VisActor/VChart#1137]
- 主题中 padding、size、fontSize 等配置随图表尺寸变化而自动变化（包含移动端尺寸）
- 优先对标竞品 https://echarts.apache.org/zh/tutorial.html#%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%87%AA%E9%80%82%E5%BA%94

**Comment by kkxxkk2019** [comment]
[A Declarative Grammar for Responsive Visualization.pdf](https://github.com/VisActor/VChart/files/12840121/A.Declarative.Grammar.for.Responsive.Visualization.pdf)

**Comment by kkxxkk2019** [comment]
Highchart: https://api.highcharts.com/highcharts/responsive
