### ISSUE TITLE
[Feature] [3.x] log轴 新增tick type，让tick保持与之前一致

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#1139]
### What problem does this feature solve?

目前log和symlog按照底数的指数进行nice，希望按照最终结果进行nice，保证tick展示的结果是底数的整数倍。
log 2:
<img width="128" alt="image" src="https://github.com/VisActor/VChart/assets/20367445/3d29b929-89eb-4463-8215-08c8a9635adf">
log 10:
<img width="144" alt="image" src="https://github.com/VisActor/VChart/assets/20367445/0af61c02-d508-4e6c-a1e2-e0048782ea53">
log 32：
<img width="140" alt="image" src="https://github.com/VisActor/VChart/assets/20367445/a1c5ec5c-6d30-45c0-9b77-9f0f1f5d21e9">

### What does the proposed API look like?

{
type:'symlog',
tick:{
niceType: 'integerMultiple'
}

}

**Comment by skie1997** [comment]
1. 3.x的tick效果是基于log轴类型实现的，所以在4.x中使用log轴，并配置tickMode: '3d' 可以与之前的效果保持一致。
2. 现在之所以想使用symlog，是因为想兼容数据为负的情况（log无法计算 value <= 0的情况）

总结：
1. log轴的tick效果好，但无法兼容数据为负的情况
2. symlog轴的tick效果不好，但可以兼容数据为负的情况

解法：
可以在业务层做判断，如果domain包含 <= 0 的value，则使用symlog；反之，使用log
