### ISSUE TITLE
[Bug] Scatter Map position error

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#1146]
甘肃省位置偏了.

![Image](https://github.com/VisActor/VChart/assets/49136199/99a5da7f-67b6-4e38-9123-320af331c0dc)

**Comment by xiaoluoHe** [comment]
计划新增 `centroidProperty` 来支持自定义 feature 中心位置的需求
![image](https://github.com/VisActor/VChart/assets/11360419/266db7e4-b4aa-4ea1-912c-cd15eedb2956)
