### ISSUE TITLE
[Feature] Encapsulates the annotation position acquisition capability to support customized html annotations

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#1150]
### What problem does this feature solve?

to enable custom marker

### What does the proposed API look like?

markWithPoint(datum, content:html/jsx)

**Comment by xuefei1313** [comment]
将获取数据位置与重绘时更新位置逻辑封装，支持用户通过api传入jsx或者html内容，实现自定义数据标注的能力

**Comment by xile611** [comment]
1.11.0支持了html和react
