### ISSUE TITLE
[Feature] 饼图在无数据时支持展示占位圆

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#1156]
参考 echarts 的如下配置：

- [showEmptyCircle](https://echarts.apache.org/zh/option.html#series-pie.showEmptyCircle)
- [emptyCircleStyle](https://echarts.apache.org/zh/option.html#series-pie.emptyCircleStyle)

**Comment by FunctionEurus** [comment]
hello，我正在尝试实现这个feature，但是似乎遇到了一点问题。
```
  // VChart\packages\vchart\src\data\transforms\pie.ts
  if (data.length === 0 && showEmptyCircle) {
    data[0] = {};
    appendArcInfo(data[0], startAngle, endAngle);
  }
```
![bad_pie](https://github.com/VisActor/VChart/assets/104673088/6941c412-544b-4df6-a1ea-f45f17af76c8)

我使用的spec是`VChart\packages\vchart\__tests__\runtime\browser\test-page\pie.ts`，只对`data`项作了修改（将`values`设为空数组），不确定为什么默认情况下绘制的圆仅有3/4，想冒昧问一下。

**Comment by FunctionEurus** [comment]
非常感谢您的回复！我尝试在上述pr的基础上实现`emptyCircleStyle`接口时仍然遇到了一些问题，并且囿于我本身的能力以及对VChart源码的理解有限，尝试完成该feature还是有些操之过急，但我依然希望提出我的思路并得到斧正。

我的接口设计如下：
* `pieChart.pie.showEmptyCircle`
* `pieChart.pie.emptyCircleStyle`

在绘制过程中，我发现只有`this._pieMark`可以获取完整的style spec，`initMarkStyleWithSpec`在处理`this._emptyArcMark`时所接收到的`spec`是空对象（`undefined`则是`initMarkStyleWithSpec`的第三个参数`key`）。

![problem](https://github.com/VisActor/VChart/assets/104673088/ed974db0-a9f0-497a-9b2a-99965ee03a16)

我期望当数据为空且`showEmptyCircle`为`true`时，能够通过`initMarkStyleWithSpec`方法为`emptyMark`设置自定义样式。但由于`spec`接收到的是空对象，导致样式没有正确应用。虽然以下实现可以绕开这个问题实现自定义占位圆样式，但我认为这不应该是正确的方法。

```
initMarkStyleWithSpec(mark?: IMark, spec?: any, key?: string): void {
    super.initMarkStyleWithSpec(mark, spec, key);
    if (mark.name === this._pieMarkName) {
      // radius 配置需要额外处理比例值
      const pieSpec = this.getSpec()[mark.name];
      if (pieSpec) {
        for (const state in pieSpec.state || {}) {
          this.setMarkStyle(mark, this.generateRadiusStyle(pieSpec.state[state]), state, AttributeLevel.User_Mark);
        }
      }
    }
    // 我的实现
    if (this.getRawData().latestData.length === 0 && mark.name === 'emptyMark' && this._showEmptyCircle) {
      super.initMarkStyleWithSpec(mark, { style: this._spec.pie.emptyCircleStyle }, key);
    }
  }
```

如果可以，我希望能够获得以下方面的帮助：

* 确认`initMarkStyleWithSpec`方法中的`spec`接收空对象的原因。
* 确定如何正确传递`emptyCircleStyle`配置到`emptyMark`。
* 任何关于理解VChart源码结构和流程的建议。

如有需要，完整的修改请见[此处](https://github.com/FunctionEurus/VChart/commit/96806093b92153341cfc4780d707eebf071b6a5f#diff-b993136e1958eb24c0f2c9d477e2e6f238f4c85e128a8b4258b86e4856a5ecba)，再次感谢您的时间。

**Comment by youngwinds** [comment]
@FunctionEurus 
确认initMarkStyleWithSpec方法中的spec接收空对象的原因。
答: 这个方法不应使用, 接收到的空对象, 纯粹是因为漏了初始化.

确定如何正确传递emptyCircleStyle配置到emptyMark。
答: initSpec的过程中, 执行transformSpec即可. 将chart spec转换为series spec.

任何关于理解VChart源码结构和流程的建议。
答: 简单写了一下 初始化spec的流程, 你可以参考一下.

**Comment by youngwinds** [comment]
一、首先, 需要了解VChart的图表组成: chart、component、region、series.
https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Understanding_VChart
VChart的设计约束: 1个chart对应多个series

二、spec init的逻辑
Step1: 调用renderSync, 在beforeRender中, 有一个spec的转换逻辑, 代码位置在这: packages/vchart/src/core/vchart.ts:657
![img_v3_02bo_32326bb3-d55d-44e5-87b8-409c62e9048g](https://github.com/VisActor/VChart/assets/49136199/1f0ee01e-97c0-4665-9c1b-46d5419db9d0)

需要重点阅读 this._chartSpecTransformer.transformSpec, 由Factory.createChartSpecTransformer创建.
![img_v3_02bo_4320fe50-c8b3-4f5a-a84e-4af2c0b222cg](https://github.com/VisActor/VChart/assets/49136199/68bc2c20-deba-40cb-a988-d079c6738e97)


Step2: 在pie chart的实现中, 调用了registerPieChart向Factory注册了饼图, 包含了transformer的实现, 代码位置在:packages/vchart/src/chart/pie/pie.ts
![img_v3_02bo_8a7e5d02-5a61-401a-a460-f04b3b60501g](https://github.com/VisActor/VChart/assets/49136199/9802ce73-1605-4e0b-829c-00762e53075e)


Step3: 执行transformSpec: 
将一个图表spec 拆成 多个series的spec

packages/vchart/src/chart/polar/polar-transformer.ts
![img_v3_02bo_ae2f22e0-92b0-411a-8cdd-4cfa09ad340g](https://github.com/VisActor/VChart/assets/49136199/584e7177-8f68-4d78-8bbd-5fe386f37dcb)

![img_v3_02bo_82db8323-615a-4cff-a8ca-8d7f95f7dcag](https://github.com/VisActor/VChart/assets/49136199/c946f519-1e92-4160-8a3e-fba276f5aff1)

![img_v3_02bo_e20f9350-3e76-4d96-9c57-15eca264113g](https://github.com/VisActor/VChart/assets/49136199/8f3d07db-a121-482a-9858-74cbc26970d6)

![img_v3_02bo_693fa1d3-a1ac-404c-9992-67fb74222ebg](https://github.com/VisActor/VChart/assets/49136199/653151e3-9e7f-4809-a797-d56987b85eeb)



Step4: pie series中, 使用series spec.
![img_v3_02bo_d8c449b5-36ff-4e12-ada6-4652317c48eg](https://github.com/VisActor/VChart/assets/49136199/e1e51a63-dd97-44b3-854d-6dadf6f1f940)


三: 接口设计与补齐类型
接口的确定要谨慎,  因为要避免breakChange, 所以只能增加, 不能修改或删除, 需要对功能进行抽象, 考虑是否可以成为一个所有图表都需要的足够通用功能.

饼图这次如果实现了 showEmptyCircle、emptyCircleStyle, 在未来可能会出现这些情况:
饼图不想要占位圆, 想要占位的文本 或 icon.
除了饼图之外, 其他图表, 也想在没有数据的场景, 拥有类似能力

因此可以针对这个场景, 把功能做的更加的“抽象”和“通用”, 因此该feature的实现, 需要考虑到未来的快速扩展.

建议把showEmptyCircle、emptyCircleStyle的命名更改为 “placeholder” 或者 “emptyPlaceholder”, 结构可以由你自行设计.

**Comment by youngwinds** [comment]
@FunctionEurus 
确认initMarkStyleWithSpec方法中的spec接收空对象的原因。
答: 这个方法不应使用, 接收到的空对象, 纯粹是因为漏了初始化.

确定如何正确传递emptyCircleStyle配置到emptyMark。
答: initSpec的过程中, 执行transformSpec即可. 将chart spec转换为series spec.

任何关于理解VChart源码结构和流程的建议。
答: 简单写了一下 初始化spec的流程, 你可以参考一下.

**Comment by xile611** [comment]
released in 1.12.0
