### ISSUE TITLE
[Discuss] 饼图在数据全为 0 时是否可以提供一个类似 echarts 的 `stillShowZeroSum` 配置，将扇形根据数据个数均分

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#1157]
如题，echarts 提供了这个配置，VChart 是否也可以提供？

![Image](https://github.com/VisActor/VChart/assets/135952300/29fba9e5-35b0-4ff0-9adc-bd0766d69ab1)

**Comment by xuanhun** [comment]
I think it's necessary
