### ISSUE TITLE
[Feature] Pictorial chart（象形图）

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#1159]
* https://echarts.apache.org/examples/en/editor.html?c=geo-beef-cuts

![Image](https://user-images.githubusercontent.com/135952300/250035508-69be5801-fd5d-411d-ad87-46e94fc82f58.png)

* https://www.highcharts.com/demo/highcharts/pictorial-stackshadow

![Image](https://user-images.githubusercontent.com/135952300/250035597-7b480c49-a4c6-4a91-962d-b7c13bf72d4d.png)

**Comment by xiaoluoHe** [comment]
pictogram chart will be supported in v1.13.0.
related https://github.com/VisActor/VChart/pull/3392
