### ISSUE TITLE
[Feature] 离散图例图例项支持 align 配置，用于控制图例标记和文本的展示位置

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#1178]
![Image](https://github.com/VisActor/VChart/assets/135952300/d37c0c99-b55d-443f-a533-576fa6be1b65)

**Comment by xile611** [comment]
1. `legend: {
    orient: 'vertical',
    left: 'left',
    align: 'right'
  },`

<img width="125" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/eafa1544-0bc5-4e1a-9c6c-3837ae31f721">

2. `legend: {
    orient: 'vertical',
    left: 'left',
    align: 'left'
  }`
<img width="159" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/d47a76ae-63df-4713-a4e5-935c77d3e0b7">

3. `legend: {
    orient: 'vertical',
    left: 'left',
    align: 'center'
  }`
<img width="117" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/369c230c-3939-4388-81e2-fb923ac5f506">

4. `align: 'center'`
<img width="300" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/d9794b4b-f83d-496a-9773-2d6fde5d62fe">


5. `align: 'left'`
<img width="407" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/9185fc5d-954a-4aea-a2dc-594ec1568fe7">

6. `align: 'right'`

<img width="389" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/3c361d7a-a441-497d-89d2-a7e9efd67f1f">
