### ISSUE TITLE
[Bug] legend position change after resize

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#120]
### Version

latest

### Link to Minimal Reproduction

none

### Steps to Reproduce

![bug1](https://github.com/VisActor/VChart/assets/11360419/27355401-7387-4dd9-91e5-a07918163d45)

### Current Behavior

configured legend position in `right`, but after reszing it changes to `top`

### Expected Behavior

legend should be in `right`

### Environment

```markdown
- OS: macOS
- Browser: Chrome
- Framework:
```

**Comment by kkxxkk2019** [comment]
Sorry, it can not reproduction in the develop branch.
