### ISSUE TITLE
[Bug] 初始化报错

### ISSUE THREAD

**Issue by X-smart** [VisActor/VChart#1202]
### Version

1.3.2-hotfix.0

### Link to Minimal Reproduction

——

### Steps to Reproduce

{
    "type": "bar",
    "data": [
        {
            "dataSet": {
                "isDataSet": true,
                "transformMap": {},
                "parserMap": {},
                "dataViewMap": {},
                "target": {
                    "_events": {},
                    "_eventsCount": 0
                },
                "_callMap": {},
                "name": "dataset_17"
            },
            "options": {},
            "isDataView": true,
            "target": {
                "_events": {
                    "change": [
                        null,
                        null
                    ],
                    "markRunning": [
                        null,
                        {
                            "once": false
                        }
                    ]
                },
                "_eventsCount": 2
            },
            "parseOption": {
                "clone": true
            },
            "transformsArr": [
                {
                    "type": "addVChartProperty",
                    "options": {}
                }
            ],
            "isRunning": false,
            "rawData": [],
            "history": false,
            "historyData": [],
            "parserData": [],
            "latestData": [],
            "_diffData": false,
            "_diffKeys": null,
            "_diffMap": {},
            "_diffRank": 0,
            "name": "dataview_18"
        }
    ],
    "legends": [],
    "tooltip": {},
    "color": [],
    "theme": {},
    "stack": true,
    "stackValue": "",
    "direction": "vertical",
    "barMinWidth": 20,
    "barMaxWidth": 30,
    "axes": [
        {
            "orient": "bottom"
        },
        {
            "orient": "left"
        }
    ],
    "region": [
        {}
    ],
    "series": [
        {
            "data": {
                "dataSet": {
                    "isDataSet": true,
                    "transformMap": {},
                    "parserMap": {},
                    "dataViewMap": {},
                    "target": {
                        "_events": {},
                        "_eventsCount": 0
                    },
                    "_callMap": {},
                    "name": "dataset_17"
                },
                "options": {},
                "isDataView": true,
                "target": {
                    "_events": {
                        "change": [
                            null,
                            null
                        ],
                        "markRunning": [
                            null,
                            {
                                "once": false
                            }
                        ]
                    },
                    "_eventsCount": 2
                },
                "parseOption": {
                    "clone": true
                },
                "transformsArr": [
                    {
                        "type": "addVChartProperty",
                        "options": {}
                    }
                ],
                "isRunning": false,
                "rawData": [],
                "history": false,
                "historyData": [],
                "parserData": [],
                "latestData": [],
                "_diffData": false,
                "_diffKeys": null,
                "_diffMap": {},
                "_diffRank": 0,
                "name": "dataview_18"
            },
            "animationThreshold": 2000,
            "direction": "vertical",
            "stack": true,
            "type": "bar",
            "barMaxWidth": 30,
            "barMinWidth": 20
        }
    ],
    "crosshair": [
        {
            "xField": {
                "visible": true,
                "line": {
                    "visible": true,
                    "type": "rect"
                }
            }
        }
    ]
}

### Current Behavior

TypeError: cyclic object value

### Expected Behavior

——

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by zamhown** [comment]
修整过的 spec（放了假数据）：
```ts
{
  type: 'bar',
  xField: 'x',
  yField: 'y',
  data: [
    {
      id: '11',
      values: [
        { type: '11', x: 'A', y: 80 },
        { type: '11', x: 'B', y: 40 },
        { type: '11', x: 'C', y: 10 },
        { type: '11', x: 'D', y: 20 },
        { type: '22', x: 'A', y: 80 },
        { type: '22', x: 'B', y: 40 },
        { type: '22', x: 'C', y: 10 },
        { type: '22', x: 'D', y: 20 }
      ]
    }
  ],
  legends: [],
  tooltip: {},
  color: [],
  theme: {},
  stack: true,
  stackValue: '',
  direction: 'vertical',
  barMinWidth: 20,
  barMaxWidth: 30,
  axes: [
    {
      orient: 'bottom'
    },
    {
      orient: 'left'
    }
  ],
  region: [{}],
  series: [
    {
      animationThreshold: 2000,
      direction: 'vertical',
      stack: true,
      type: 'bar',
      barMaxWidth: 30,
      barMinWidth: 20
    }
  ],
  crosshair: [
    {
      xField: {
        visible: true,
        line: {
          visible: true,
          type: 'rect'
        }
      }
    }
  ]
}
```
