### ISSUE TITLE
[Bug] pie label formatMethod not work

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#121]
### Version

1.0.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

config pie series label.formatMethod
//example
{
  series: [
    {
       type: 'pie',
       label: {
         visible: true,
         formatMethod: ()=>return 'test',
       }
    }
  ]
}

### Current Behavior

formatMethod not work

### Expected Behavior

support formatMethod in label that of pie series

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pairone** [comment]
![image](https://github.com/VisActor/VChart/assets/40026218/8e0fc987-6c1a-4c61-a968-fad9d8b74461)

https://github.com/VisActor/VChart/pull/523
