### ISSUE TITLE
[Enhancement] 优化布局元素的 padding 概念

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#1234]
优化布局元素 `padding` 属性的计算逻辑，目前它是当做了 CSS 盒模型的 `marigin` 属性逻辑来处理的，和 CSS 盒模型的含义不符合，建议按照 CSS 盒模型的概念增加 `margin` 含义。

* 目前的 layoutItem padding 对应 css 的 margin

**Comment by xile611** [comment]
* region 支持 indent 配置
* indent 的类型定义为： `ILayoutPaddingSpec`

盒模型如下图



![Image](https://github.com/VisActor/VChart/assets/6111424/f29d72c5-550e-43c5-bec2-b0f9670fa089)

**Comment by xile611** [comment]
fixed in https://github.com/VisActor/VChart/pull/2104
