### ISSUE TITLE
[Feature] label data filter strategy & custom layout strategy

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#124]
### What problem does this feature solve?

Customize the data label display and priority

### What does the proposed API look like?

label: {
      dataFilterStrategy: ([a,b,c,d,e]) => {
            return [e,b,c,d]
      }

      layoutStrategy: ([a,b,c,d,e]) => {
            a.visible = false
            b.position.x = 100
      }
}

**Comment by kkxxkk2019** [comment]
https://github.com/VisActor/VChart/pull/446
