### ISSUE TITLE
[Bug] 形状词云 设置了fontSizeLimitMin，数据较多时不贴合形状，且没有适应画布尺寸

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#1240]
### Version

1.4.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

spec太大，见文件

### Current Behavior

<img width="1268" alt="image" src="https://github.com/VisActor/VChart/assets/20367445/8a584e0c-756a-436a-8848-1da91247b883">
markShape=triangle, 画布尺寸=1270*674，没有贴合形状，且没有适应画布尺寸

### Expected Behavior

像3.x一样：
<img width="1236" alt="image" src="https://github.com/VisActor/VChart/assets/20367445/7eb85801-dcb5-466c-add4-83f825591557">

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by skie1997** [comment]
暂时通过不设置fontSizeLimitMin的方式解决，后续定位到问题后修复

**Comment by skie1997** [comment]
related to https://github.com/VisActor/VGrammar/pull/302
