### ISSUE TITLE
[Bug] lark-vchar 飞书小程序如果一个页面存在两个图表的

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#1259]
### Version

latest

### Link to Minimal Reproduction

none

### Steps to Reproduce

none

### Current Behavior

<img width="923" alt="image" src="https://github.com/VisActor/VChart/assets/135952300/38246a23-6b24-433a-83f0-8efbd78ef344">

### Expected Behavior

fix it

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
已定位到问题，需要 VRender 协助修复

**Comment by mathYang1224** [comment]
我也出现了这样的问题

**Comment by mathYang1224** [comment]
有没有给解决一下啊

**Comment by mathYang1224** [comment]
第一次进页面正常，第二次进页面渲染也是报这个错，同时渲染两个也是这个问题

**Comment by mathYang1224** [comment]
我的是"@visactor/lark-vchart": "^1.4.3", 版本
代码
![image](https://github.com/VisActor/VChart/assets/45762245/2a996228-9987-4f07-8dcc-98d0a1caaada)

**Comment by kkxxkk2019** [comment]
> 第一次进页面正常，第二次进页面渲染也是报这个错，同时渲染两个也是这个问题

嗯，这个问题已经定位到了，会在 1.5.2 版本修复，今天或者明天就发本

**Comment by kkxxkk2019** [comment]
> 有没有给解决一下啊

升级下 @visactor/lark-vchart 版本到 1.5.2 即可
