### ISSUE TITLE
[Bug] react-vchart 在配置了轴标签的formatMethod时，进行数据更新会报错

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#1274]
### Version

1.3.1

### Link to Minimal Reproduction

null

### Steps to Reproduce

1. 
![img_v2_fe37d7d8-5113-4392-9f7f-8c7c56bee28g](https://github.com/VisActor/VChart/assets/15776277/67876be6-d58c-4a06-b5e9-94831fb88247)
2. 更新 data values 就会报错，不配置就不报错 
![img_v2_5be57bf8-bf7d-4c65-b6e6-ace831f1ef8g](https://github.com/VisActor/VChart/assets/15776277/10f2791e-6c09-4cde-af3e-39bda27e9fd4)

### Current Behavior

![img_v2_5be57bf8-bf7d-4c65-b6e6-ace831f1ef8g](https://github.com/VisActor/VChart/assets/15776277/ad2890e8-c80b-4ecb-b2f7-34973c9b7f6c)

### Expected Behavior

没有报错并且正常绘图

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
formatMethod should be wrapped by `useCallback`
