### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mathYang1224** [VisActor/VChart#1277]
### Version

1.4.3

### Link to Minimal Reproduction

无

### Steps to Reproduce

![image](https://github.com/VisActor/VChart/assets/45762245/82b0ccf0-8d77-4545-99d6-8cc8748ec5ee)
![image](https://github.com/VisActor/VChart/assets/45762245/502bad5b-3fac-4dbc-95f6-319d1d9c683a)

### Current Behavior

飞书小程序怎么更新图表， 飞书小程序怎么设置y坐标轴不是从0开始， 更新图表后坐标轴丢失

### Expected Behavior

 更新图表后坐标轴丢失

### Environment

```markdown
飞书小程序  "@visactor/lark-vchart": "1.4.3",
```

**Comment by kkxxkk2019** [comment]
1. 飞书小程序怎么更新图表

飞书小程序更新图表的话，需要先拿到对应的图表实例，然后调用对应的 vchart api 即可。如何拿到 chart 实例可以参考 ：https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/mini-app/lark#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

* 更新数据：https://www.visactor.io/vchart/api/API/vchart
* 更新 spec: https://www.visactor.io/vchart/api/API/vchart

2. 飞书小程序怎么设置y坐标轴不是从0开始

这个配置对应坐标轴的 `zero` 属性为 false，假设 y 轴是现在在左侧对应的配置为

```ts
axes: [
  {
    orient: 'left',
    zero: false
  }
]
```

**Comment by mathYang1224** [comment]
图表更新渲染有问题是报这个错误，我又提了个新的bug，详细描述了环境，以及操作过程
TypeError: Converting circular structure to JSON
--> starting at object with constructor 't'
| property 'dataSet' -> object with constructor 't'
| property 'dataViewMap' -> object with constructor 'Object'
--- property 'dataview_26' closes the circle
at JSON.stringify ()
at Object.sendData (bgWebview.js:1)
at P (bgWebview.js:1)
at bgWebview.js:1
at bgWebview.js:1
at Array.forEach ()
at Object.apply (bgWebview.js:1)
at Proxy. (bgWebview.js:1)
at t.realInvoke (tma-core.js:1)
at t.invoke (tma-core.js:1)
