### ISSUE TITLE
[Bug] 飞书小程序更新渲染图表，报json循环引用错误

### ISSUE THREAD

**Issue by mathYang1224** [VisActor/VChart#1285]
### Version

1.5.2

### Link to Minimal Reproduction

暂无生产链接

### Steps to Reproduce

1. 飞书小程序 chart 组件
2. view 配置如下
export default {
  type: 'line',
  width: '638rpx',
  height: '478rpx',
  autoFit: true,
  color: ['#3370FF', '#34C724'],
  sortDataByAxis: false,
  axes: [
    {
      orient: 'left',
      zero: false
    }
  ],
  data: {
    values: [
      { date: '1月', type: '目标', value: 95 },
      { date: '1月', type: '实际', value: 95 },
      { date: '2月', type: '目标', value: 97 },
      { date: '2月', type: '实际', value: 99 },
      { date: '3月', type: '目标', value: 97.8 },
      { date: '3月', type: '实际', value: 99.4 },
      { date: '4月', type: '目标', value: 96 },
      { date: '4月', type: '实际', value: 98 },
      { date: '5月', type: '目标', value: 99 },
      { date: '5月', type: '实际', value: 97 },
      { date: '6月', type: '目标', value: 99.8 },
      { date: '6月', type: '实际', value: 99.5 },
      { date: '7月', type: '目标', value: 95.3 },
      { date: '7月', type: '实际', value: 89.2 }
    ]
  },
  xField: 'date',
  yField: 'value',
  seriesField: 'type',
  invalidType: 'link',
  point: {
    visible: false
  },
  line: {
    style: {
      lineWidth: 2
    }
  },
  padding: {
    left: 18,
    right:0,
    top: 24,
    bottom: 16,
  },
  tooltip: {
    dimension: {
      title: {
        visible: false,
      },
    },
    style: {
      keyLabel: {
        fontColor: '#1F2329',
        textAlign: 'left',
        textBaseline: 'bottom',
        wordBreak: 'break-all',
      },
      valueLabel: {
        fontColor: '#1F2329',
        textAlign: 'left',
        wordBreak: 'break-all',
        spacing: 1,
        textBaseline: 'top',
        multiLine: true
      },
    }
  },
  legends: {
    type: 'discrete',
    visible: true,
    item: {
      width: 40,
      maxWidth: 100,
      value: {
        alignRight: true,
        style: {
          zIndex: 100,
        }
      }
    },
  }
};
3. 更新图表给data.values 重新赋值任意 setData 字段的时候， 或者调用chart示例的updateSpec 或者 updateData 的时候 ，报json循环引用的bug， 报错error日志截图如下
![image](https://github.com/VisActor/VChart/assets/45762245/86cf51dd-4a36-4f8c-81dc-9b677c9c3678)
报错日志：
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 't'
    |     property 'dataSet' -> object with constructor 't'
    |     property 'dataViewMap' -> object with constructor 'Object'
    --- property 'dataview_26' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.sendData (bgWebview.js:1)
    at P (bgWebview.js:1)
    at bgWebview.js:1
    at bgWebview.js:1
    at Array.forEach (<anonymous>)
    at Object.apply (bgWebview.js:1)
    at Proxy.<anonymous> (bgWebview.js:1)
    at t.realInvoke (tma-core.js:1)
    at t.invoke (tma-core.js:1)

### Current Behavior

图表无法更新 

### Expected Behavior

自测 1.4.3 和 1.5.1 和 1.5.2 都有这个问题，期望能更新图表，修复bug。 

### Environment

```markdown
飞书小程序 调试基础库: 1.9.96.0  启用小程序新框架
最低兼容飞书版本 5.30
```

**Comment by mathYang1224** [comment]
就是不设置图表相关的数据 setData 其他任何字段都会报这个错误。然后如果删除图表， 页面上不显示任何图表。setData时候就不会报这个错

**Comment by mathYang1224** [comment]
只要page.data有图表配置数据，就会有这个问题

**Comment by mathYang1224** [comment]
![image](https://github.com/VisActor/VChart/assets/45762245/d509fed8-b4a7-4132-9875-db6f9488bd35)
![image](https://github.com/VisActor/VChart/assets/45762245/21d16282-c8f0-4ea3-b1c1-7c22727b9e47)
![image](https://github.com/VisActor/VChart/assets/45762245/cf90e846-77a1-4680-8ead-a792a7a5a526)

全部代码如下
package.json 

"dependencies": {
    "@visactor/lark-vchart": "1.5.2",
    "request": "^2.88.0"
  },

<chart
           tt:if="{{specLai}}"
           id="chartLai"
           canvas-id="chartLai"
           spec="{{ specLai }}"
           bind:chartinit="onChartLaiInit"
   />

onChartLaiInit() {
    console.log('初始化完成:::');
    this.selectComponent("#chartLai", res => {
      this.data.chartLaiInstance = res && res.chart; // 获取 chart 实例
      console.log('获取 VChart 实例:::', this.data.chartLaiInstance);
    });
  },


let spec = deepClone(this.data.specLai)
    this.data.specLai.data = null
    this.setData({
      specLai: spec,
    })
    const specLaiId = document.getElementById('chartLai')
    const updateRes = await this.data.chartLaiInstance.updateSpec(spec, true)
    console.log('updateRes:::', updateRes)

**Comment by simaQ** [comment]
这个报错应该是使用问题，存在了循环引用导致的，你要不给一个完整的实例，或者直接起一个飞书 oncall 把，我们帮你看一下

**Comment by mathYang1224** [comment]
> 这个报错应该是使用问题，存在了循环引用导致的，你要不给一个完整的代码 zip，或者直接起一个飞书 oncall 把，我们帮你看一下
[feisu-app-qms.zip](https://github.com/VisActor/VChart/files/13111312/feisu-app-qms.zip)
完整s示例

**Comment by mathYang1224** [comment]
![image](https://github.com/VisActor/VChart/assets/45762245/c5a7454e-aea4-4f9b-9a59-e888fafde3f8)
我这里只有这个互助交流群，群里你这边叫什么名字。在飞书里沟通也可以

**Comment by mathYang1224** [comment]
小程序示例，供应商质量页面

**Comment by kkxxkk2019** [comment]
![image](https://github.com/VisActor/VChart/assets/135952300/d2919486-2967-48ce-96f2-fb79b9d42dd1)

这个报错问题是因为这里把图表实例赋值给 this.data 了，注释掉就行
![image](https://github.com/VisActor/VChart/assets/135952300/67e3d943-b1b9-4937-b5bf-b5d6fcc3c731)

**Comment by kkxxkk2019** [comment]
数据不更新的问题，我看了下你的代码，是数据结构不对导致的：

1. specLai 对应的 data 是一个数组

![image](https://github.com/VisActor/VChart/assets/135952300/c3e0056b-21ee-4eb5-bcf7-53be70fbc35f)

2. 而这里你直接赋值了
![image](https://github.com/VisActor/VChart/assets/135952300/5bf4270b-6a66-4d8f-a7cc-7f8f796e4572)

**Comment by mathYang1224** [comment]
好的，我先试试

**Comment by mathYang1224** [comment]
> 数据不更新的问题，我看了下你的代码，是数据结构前后不匹配导致的：
> 
> 1. specLai 对应的 data 是一个数组
> 
> ![image](https://user-images.githubusercontent.com/135952300/277585071-c3e0056b-21ee-4eb5-bcf7-53be70fbc35f.png)
> 
> 2. 而这里你直接赋值了
>    ![image](https://user-images.githubusercontent.com/135952300/277585215-5bf4270b-6a66-4d8f-a7cc-7f8f796e4572.png)

去掉this.data.chartLaiInstance 确实不报错了 但是第二个问题还有，是我写法不对吗
![image](https://github.com/VisActor/VChart/assets/45762245/10c80da3-9f9c-4e7e-9f38-1e6dc4337226)
我这样写，图表也是不更新。你上边的图片好像看错嘞看的柱状图和折线图混合的。就看供应商质量折线图就行，就有这问题，手机型号iphone13mini

**Comment by mathYang1224** [comment]
> 数据不更新的问题，我看了下你的代码，是数据结构前后不匹配导致的：
> 
> 1. specLai 对应的 data 是一个数组
> 
> ![image](https://user-images.githubusercontent.com/135952300/277585071-c3e0056b-21ee-4eb5-bcf7-53be70fbc35f.png)
> 
> 2. 而这里你直接赋值了
>    ![image](https://user-images.githubusercontent.com/135952300/277585215-5bf4270b-6a66-4d8f-a7cc-7f8f796e4572.png)

如果不这么直接赋值，就要拿到chart实例去调用updateSpec, chart示例挂到data上就报循环引用是这样的

**Comment by kkxxkk2019** [comment]
是你的写法不对，你自己打印下看下你的数据格式是什么样子的

**Comment by mathYang1224** [comment]
> 是你的写法不对，你自己打印下看下你的数据格式是什么样子的

![image](https://github.com/VisActor/VChart/assets/45762245/c0d26ff3-015e-4454-83c8-4d0c288d9779)
这是待更新的specLai，我对了一遍是这个结构啊。是代码下载下来不一样了吗

**Comment by mathYang1224** [comment]
> > 是你的写法不对，你自己打印下看下你的数据格式是什么样子的
> 
> ![image](https://user-images.githubusercontent.com/45762245/277591471-c0d26ff3-015e-4454-83c8-4d0c288d9779.png) 这是待更新的specLai，我对了一遍是这个结构啊。是代码下载下来不一样了吗

没更新之前 是 7个月 数据 ， 更新之后横轴 4 个月 是图表没更新 现在， 坐标轴更新了 。图表的交互也没了

**Comment by mathYang1224** [comment]
> simaQ

继续沟通解决一下，问题没有解决。谢谢了

**Comment by mathYang1224** [comment]
> 这个报错应该是使用问题，存在了循环引用导致的，你要不给一个完整的代码 zip，或者直接起一个飞书 oncall 把，我们帮你看一下

this.selectComponent("#chartLai", res => {
      const chartInstance = res && res.chart
      chartInstance.updateSpec(spec)
});
就算这么写，图表也是不更新，失去交互。能给看看吗。谢谢

**Comment by kkxxkk2019** [comment]
> > 这个报错应该是使用问题，存在了循环引用导致的，你要不给一个完整的代码 zip，或者直接起一个飞书 oncall 把，我们帮你看一下
> 
> this.selectComponent("#chartLai", res => { const chartInstance = res && res.chart chartInstance.updateSpec(spec) }); 就算这么写，图表也是不更新，失去交互。能给看看吗。谢谢

嗯，今天排期看

**Comment by mathYang1224** [comment]
好的👌🏻

**Comment by mathYang1224** [comment]
> > > 这个报错应该是使用问题，存在了循环引用导致的，你要不给一个完整的代码 zip，或者直接起一个飞书 oncall 把，我们帮你看一下
> > 
> > 
> > this.selectComponent("#chartLai", res => { const chartInstance = res && res.chart chartInstance.updateSpec(spec) }); 就算这么写，图表也是不更新，失去交互。能给看看吗。谢谢
> 
> 嗯，今天排期看

#1314bug 上传报编译错误，这个也一起排期了吧看看。都是很严重的问题，上传不了代码。 谢谢

**Comment by mathYang1224** [comment]
> 传报编译错误，这个也一起排期了吧看看。都是很严重的问题

计划这个问题什么时候在哪个版本解决啊。我们业务卡在这个问题上了

**Comment by kkxxkk2019** [comment]
编译错误已经回复了。不是 vchart 包报出来的，建议走飞书 oncall，updateSpec 后交互失效正在看，需要一些时间

**Comment by kkxxkk2019** [comment]
> 编译错误已经回复了。不是 vchart 包报出来的，建议走飞书 oncall，updateSpec 后交互失效正在看，需要一些时间
![image](https://github.com/VisActor/VChart/assets/135952300/0785b7c5-1d95-46e9-a0d1-4d431b208ac5)

@mathYang1224 你好，这个问题排查到是因为你的 spec 中更新给 `width` 和 `height` 属性定义为 `width: '638rpx',height: '478rpx',` 导致的，我们的 `width` 和 `height` 需要定义为数值，不支持这种带单位的，把这两个属性去掉就正常了，另外更新后抖动的问题 1.5.3 版本已经修复了，你升级下即可。

**Comment by mathYang1224** [comment]
> > 编译错误已经回复了。不是 vchart 包报出来的，建议走飞书 oncall，updateSpec 后交互失效正在看，需要一些时间
> > ![image](https://user-images.githubusercontent.com/135952300/278922894-0785b7c5-1d95-46e9-a0d1-4d431b208ac5.png)
> 
> @mathYang1224 你好，这个问题排查到是因为你的 spec 中更新给 `width` 和 `height` 属性定义为 `width: '638rpx',height: '478rpx',` 导致的，我们的 `width` 和 `height` 需要定义为数值，不支持这种带单位的，把这两个属性去掉就正常了，另外更新后抖动的问题 1.5.3 版本已经修复了，你升级下即可。

请看1358bug, width 更改成数值交互问题消失嘞，可以点击了。但是图表渲染异常

**Comment by kkxxkk2019** [comment]
> > > 编译错误已经回复了。不是 vchart 包报出来的，建议走飞书 oncall，updateSpec 后交互失效正在看，需要一些时间
> > > ![image](https://user-images.githubusercontent.com/135952300/278922894-0785b7c5-1d95-46e9-a0d1-4d431b208ac5.png)
> > 
> > 
> > @mathYang1224 你好，这个问题排查到是因为你的 spec 中更新给 `width` 和 `height` 属性定义为 `width: '638rpx',height: '478rpx',` 导致的，我们的 `width` 和 `height` 需要定义为数值，不支持这种带单位的，把这两个属性去掉就正常了，另外更新后抖动的问题 1.5.3 版本已经修复了，你升级下即可。
> 
> 请看1358bug, width 更改成数值交互问题消失嘞，可以点击了。但是图表渲染异常

重新安装依赖了吗？另外建议走飞书 oncall 高效沟通
