### ISSUE TITLE
[Bug] 飞书小程序 纵坐标轴label文字函数更改不生效

### ISSUE THREAD

**Issue by mathYang1224** [VisActor/VChart#1286]
### Version

1.5.2

### Link to Minimal Reproduction

暂无生产链接

### Steps to Reproduce

![image](https://github.com/VisActor/VChart/assets/45762245/f1864ce6-0829-4762-93ba-130519d81450)
![image](https://github.com/VisActor/VChart/assets/45762245/beacb68d-99ef-4e1f-8f27-0e9d69eefbca)
飞书小程序， formatMethod 坐标轴标签文字更改没有生效

### Current Behavior

飞书小程序， formatMethod 坐标轴标签文字更改没有生效

### Expected Behavior

飞书小程序， formatMethod 坐标轴标签文字更改生效

### Environment

```markdown
飞书小程序， 最低兼容版本5.30 调试基础库 1.9.96.0
```

**Comment by simaQ** [comment]
小程序目前是不支持函数序列化的，目前提供的方案是在 chartready 事件中获取到 chart 实例，然后通过 updateSpec 方式来结局，1.6.0 我们会提供函数注册机制来解决这个问题。

具体的教程文档：https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/mini-app/lark#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by mathYang1224** [comment]
好的，了解了

**Comment by nianba23** [comment]
1.8.x 版本支持 formatMethod 了吗？
