### ISSUE TITLE
[Bug] 飞书小程序legends不能自适应，图例重叠,  只能设置width 才会展开

### ISSUE THREAD

**Issue by mathYang1224** [VisActor/VChart#1292]
### Version

1.5.2

### Link to Minimal Reproduction

暂无生产链接

### Steps to Reproduce

![img_v2_5a3cbe27-d26b-4ad4-84df-e0d3bc23606g](https://github.com/VisActor/VChart/assets/45762245/fcd8eb98-30fd-46b1-a267-d1f91276f63f)

### Current Behavior

默认情况饼图下示例， 图例重叠
legends: {
        visible: true,
        orient: 'bottom'
},

### Expected Behavior

默认情况下自动有宽度，不会重叠

**Comment by kkxxkk2019** [comment]
emmm，图例默认就是宽度自动适配的，能给下最后传给 vchart 完整的 spec 吗？我这里正常的 😂

![img_v2_aa6d6288-33c2-4e4b-9d44-e9855abac08g](https://github.com/VisActor/VChart/assets/135952300/b138f294-fcae-4516-bd31-1c75be7daef7)
