### ISSUE TITLE
[Bug] 飞书小程序部署报错编译失败

### ISSUE THREAD

**Issue by mathYang1224** [VisActor/VChart#1314]
### Version

1.5.2

### Link to Minimal Reproduction

暂无生产链接

### Steps to Reproduce

开发者工具 => 点击上传 => 报编译错误

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/45762245/9d8bdf3e-6bf4-45a8-b744-4aa22a503442)

### Expected Behavior

期望能上传部署代码，不报错。或者有什么规避的方法更改配置也好。期望能上传代码到开发者后台。

### Environment

```markdown
本地设置
调试基础库: 1.9.96.0
该基础支持客户端: iOS 6.8 Android 6.8
启用代码自动热重载
使用npm
启用小程序新框架
最低兼容飞书版本 5.30
```

**Comment by mathYang1224** [comment]
图中的appId是测试企业appId, 下面是代码包
feisu-app-qms.zip

**Comment by mathYang1224** [comment]
[feisu-app-qms.zip](https://github.com/VisActor/VChart/files/13162915/feisu-app-qms.zip)
上面是可供测试的代码包

**Comment by kkxxkk2019** [comment]
好的，我们尽快排查下，有结论通知你，或者你可以关注下我们的微信公众号，有问题可以直接发消息给公众号进我们的专门的答疑群沟通哈

![image](https://github.com/VisActor/VChart/assets/135952300/ca1243c7-9e71-4ce8-9c9c-5cb797b8355a)

**Comment by kkxxkk2019** [comment]
看了下，这个报错不是 @visactor/lark-vchart 上报的，建议通过飞书技术支持咨询解决下，地址：https://applink.feishu.cn/TLJpeNdW
