### ISSUE TITLE
在使用vchart的时候页面会提示报错

### ISSUE THREAD

**Issue by ahuihuihuihui0326** [VisActor/VChart#1334]
在使用vchart的时候页面经常会出现报错提示，是否是项目配置需要做更改？需要什么样的配置？
![1239b07fdd87533bccd4254e4c19012](https://github.com/VisActor/VChart/assets/149071370/e21f4631-8b4a-4421-b506-7a2c86ab4b43)

**Comment by kkxxkk2019** [comment]
这个看起来是事件模块报出的问题，你看下方便提供下源码不

**Comment by ahuihuihuihui0326** [comment]
你好，源码附件已上传，麻烦你帮忙看一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisActor/VChart"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月27日(星期五) 上午9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334)





 
这个看起来是事件模块报出的问题，你看下方便提供下源码不

**Comment by kkxxkk2019** [comment]
> 你好，源码附件已上传，麻烦你帮忙看一下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "VisActor/VChart" ***@***.***&gt;; 发送时间:&nbsp;2023年10月27日(星期五) 上午9:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334) 这个看起来是事件模块报出的问题，你看下方便提供下源码不 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，是邮件发送的吗？

**Comment by ahuihuihuihui0326** [comment]
是的，或者其他的能发送源码的方式你方便告知一下我重新发送




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisActor/VChart"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 上午9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334)





  
你好，源码附件已上传，麻烦你帮忙看一下
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "VisActor/VChart" @.&gt;; 发送时间:&nbsp;2023年10月27日(星期五) 上午9:42 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334) 这个看起来是事件模块报出的问题，你看下方便提供下源码不 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你好，是邮件发送的吗？

**Comment by kkxxkk2019** [comment]
> 是的，或者其他的能发送源码的方式你方便告知一下我重新发送

麻烦发到这个邮箱吧~  sima.zhang1990@gmail.com

**Comment by kkxxkk2019** [comment]
> 是的，或者其他的能发送源码的方式你方便告知一下我重新发送
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "VisActor/VChart" ***@***.***&gt;; 发送时间:&nbsp;2023年10月30日(星期一) 上午9:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334) 你好，源码附件已上传，麻烦你帮忙看一下 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "VisActor/VChart" @.&gt;; 发送时间:&nbsp;2023年10月27日(星期五) 上午9:42 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334) 这个看起来是事件模块报出的问题，你看下方便提供下源码不 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 你好，是邮件发送的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

再问下，你这个是发送到哪个邮箱的，我们这边确定下~

**Comment by ahuihuihuihui0326** [comment]
***@***.***



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisActor/VChart"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334)





  
是的，或者其他的能发送源码的方式你方便告知一下我重新发送
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "VisActor/VChart" @.&gt;; 发送时间:&nbsp;2023年10月30日(星期一) 上午9:56 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334) 你好，源码附件已上传，麻烦你帮忙看一下 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "VisActor/VChart" @.&gt;; 发送时间:&nbsp;2023年10月27日(星期五) 上午9:42 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334) 这个看起来是事件模块报出的问题，你看下方便提供下源码不 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 你好，是邮件发送的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
再问下，你这个是发送到哪个邮箱的，我们这边确定下~

**Comment by kkxxkk2019** [comment]
> ***@***.***

emmm, 这个加密了，麻烦直接发到 [sima.zhang1990@gmail.com](mailto:sima.zhang1990@gmail.com)

**Comment by ahuihuihuihui0326** [comment]
尝试了多个邮箱给你发送，邮件都被退回了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisActor/VChart"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 下午2:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334)





  
@.***
  
emmm, 这个加密了，麻烦直接发到 ***@***.***

**Comment by kkxxkk2019** [comment]
> 尝试了多个邮箱给你发送，邮件都被退回了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "VisActor/VChart" ***@***.***&gt;; 发送时间:&nbsp;2023年10月30日(星期一) 下午2:09 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334) @.*** emmm, 这个加密了，麻烦直接发到 ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

尴尬。。。。just_start@qq.com 这个邮箱试一下呢

**Comment by kkxxkk2019** [comment]
或者可以直接在 comment 这里上传

**Comment by ahuihuihuihui0326** [comment]
好吧，公司是内网，没办法上传，我晚上回家尝试一下吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisActor/VChart"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334)





 
或者可以直接在 comment 这里上传

**Comment by aHuihuihuihui0315** [comment]
链接：https://pan.baidu.com/s/18I7L1mraTH2RjsnlhyOcpA 
提取码：cueg

**Comment by kkxxkk2019** [comment]
你好，看了下应该是多版本问题，你讲 vchart 和 vtable 升级到最新的版本应该就没有问题了，https://github.com/VisActor/VChart/issues/1333 这个问题我验证是可以的，然后这个 issue 的问题我咋没有复现呢~anyway，你先将依赖升级到最新的版本试试。


```bash
    "@visactor/vchart": "^1.5.4",
    "@visactor/vtable": "^0.13.1",
```

**Comment by kkxxkk2019** [comment]
> 你好，看了下应该是多版本问题，你讲 vchart 和 vtable 升级到最新的版本应该就没有问题了，#1333 这个问题我验证是可以的，�然后这个 issue 的问题我咋没有复现呢~anyway，你先将依赖升级到最新的版本试试。
> 
> ```shell
>     "@visactor/vchart": "^1.5.4",
>     "@visactor/vtable": "^0.13.1",
> ```

你好，这个方法能解决你的问题吗

**Comment by ahuihuihuihui0326** [comment]
版本升级了以后把所有的问题都解决了




阿辉辉辉辉辉辉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisActor/VChart"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 下午2:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VisActor/VChart] 在使用vchart的时候页面会提示报错 (Issue #1334)





  
你好，看了下应该是多版本问题，你讲 vchart 和 vtable 升级到最新的版本应该就没有问题了，#1333 这个问题我验证是可以的，�然后这个 issue 的问题我咋没有复现呢~anyway，你先将依赖升级到最新的版本试试。
     ***@***.***/vchart": "^1.5.4",     ***@***.***/vtable": "^0.13.1",
  
你好，这个方法能解决你的问题吗

**Comment by kkxxkk2019** [comment]
好滴，那我把 issue 关闭了
