### ISSUE TITLE
[Bug] miniapp updatespec wh uncurrectly

### ISSUE THREAD

**Issue by neuqzxy** [VisActor/VChart#1336]
### Version

1.5.2

### Link to Minimal Reproduction

xxx

### Steps to Reproduce

![image](https://github.com/VisActor/VChart/assets/26994055/acaba7e3-3d50-40fa-8a38-7cf1c5e4e889)

### Current Behavior

Feishu mini program environment updateSpec can cause chart width and height errors

### Expected Behavior

The width and height are still correct after updating spec

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
already fixed in 1.5.2
