### ISSUE TITLE
[Bug] 使用cdn引入构建好的文件，按照快速上手示例报错： VChart is not a constructor

### ISSUE THREAD

**Issue by baotongw** [VisActor/VChart#1341]
### Version

1.4.3,1.5.2

### Link to Minimal Reproduction

见下文代码

### Steps to Reproduce

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>vchart</title>
  <script src="https://cdn.jsdelivr.net/npm/@visactor/vchart/build/index.min.js"></script>
</head>

<body>
  
  <div id="chart" style="width: 600px;height:1000px;"></div>
  <script>
    const spec = {
      data: [
        {
          id: 'barData',
          values: [
            { month: 'Monday', sales: 22 },
            { month: 'Tuesday', sales: 13 },
            { month: 'Wednesday', sales: 25 },
            { month: 'Thursday', sales: 29 },
            { month: 'Friday', sales: 38 }
          ]
        }
      ],
      type: 'bar',
      xField: 'month',
      yField: 'sales'
    };

    // 创建 vchart 实例
    const vchart = new VChart(spec, { dom: 'chart' });
    // 绘制
    vchart.renderAsync();
  </script>
</body>

</html>

### Current Behavior

 throw error: VChart is not a constructor

### Expected Behavior

正常显示图表

### Environment

```markdown
- OS: windows
- Browser: chrome 
- Framework: --
```

**Comment by kkxxkk2019** [comment]
抱歉，我们纠正下文档，如果是使用 cdn 引入的话，需要

```js
const vchart = new VChart.default(spec, { dom: "container" });

```

**Comment by baotongw** [comment]
收到 不过官方文档中不应该出现这样的问题

**Comment by iamflowerdog** [comment]
官方文档还是 没有更新，我今天也遇到同样的问题。

**Comment by qinglangee** [comment]
这都好几个月了，文档为啥不标明下呀

**Comment by xile611** [comment]
> 这都好几个月了，文档为啥不标明下呀

我更新一下，欢迎贡献文档～
