### ISSUE TITLE
[Feature] tooltip的trigger能增加个同时【悬浮和点击】的触发吗

### ISSUE THREAD

**Issue by imyuanandyou** [VisActor/VChart#1357]
### What problem does this feature solve?

在使用AreaChart的过程中发现tooltip的trigger的值仅允许trigger?: 'hover' | 'click' | 'none';
翻了文档发现其他Chart不支持同时触发

希望：
能和crosshair的trigger一样：CrossHairTrigger = 'click' | 'hover' | ['click', 'hover']。多一个同时触发的选项。
hover在pc下使用较多、手机端上还是click使用体验比较好（hover的话要去左右滑动屏幕的操作、很容易误触浏览器的返回上一页）

### What does the proposed API look like?

```
export interface ITooltipSpec extends Partial<ITooltipActiveTypeAsKeys<ITooltipPattern, ITooltipPattern>> {
    trigger?: 'hover' | 'click' | 'none';
}
```
增加选项['click', 'hover']
```
export interface ITooltipSpec extends Partial<ITooltipActiveTypeAsKeys<ITooltipPattern, ITooltipPattern>> {
    trigger?: 'click' | 'hover' | 'none' | ['click', 'hover'];
}
```

**Comment by kkxxkk2019** [comment]
手机端的话我们默认的方式是点按 + 滑动，你在创建 VChart 实例的时候可以声明下模式 `mode: 'mobile-browser'` 即可：


```ts
const vchart = new VChart(spec, {
  mode: 'mobile-browser'
})
```

**Comment by imyuanandyou** [comment]
多谢🙏，照着设置后成功实现了
