### ISSUE TITLE
[Bug] 图表更新之后渲染异常

### ISSUE THREAD

**Issue by mathYang1224** [VisActor/VChart#1358]
### Version

1.5.3

### Link to Minimal Reproduction

暂无生产链接

### Steps to Reproduce

图表更新之后渲染异常，横纵坐标丢失。折线图渲染异常

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/45762245/dd44f990-b119-490c-874f-f640cb107d50)

### Expected Behavior

渲染正常

### Environment

```markdown
飞书小程序 调试基础库: 1.9.96.0  启用小程序新框架
最低兼容飞书版本 5.30
```

**Comment by mathYang1224** [comment]
此为样例，数据可以自己随意设置feisu-app-qms.zip

**Comment by kkxxkk2019** [comment]
https://github.com/VisActor/VChart/assets/135952300/269e133a-74c7-4400-b8ec-9af3445f9b56

我这里正常的，你更新了版本之后，需要重新安装依赖，否则你的 node_modules 里还是 1.5.2，下面是我基于你给我的 zip 修改后的包
[feisu-app-qms 2.zip](https://github.com/VisActor/VChart/files/13201311/feisu-app-qms.2.zip)

**Comment by mathYang1224** [comment]
[feisu-app-qms.zip](https://github.com/VisActor/VChart/files/13201392/feisu-app-qms.zip)

**Comment by mathYang1224** [comment]
> REC-20231030135527.mp4 
> 我这里正常的，你更新了版本之后，需要重新安装依赖，否则你的 node_modules 里还是 1.5.2，下面是我基于你给我的 zip 修改后的包 [feisu-app-qms 2.zip](https://github.com/VisActor/VChart/files/13201311/feisu-app-qms.2.zip)
![image](https://github.com/VisActor/VChart/assets/45762245/a6092610-2e81-4a37-bef0-247d95cf3dbf)

你拿到的不是最新的包，下面我发这个是最新的。麻烦你再试试， 版本已经是最新版本了

**Comment by mathYang1224** [comment]
> REC-20231030135527.mp4 
> 我这里正常的，你更新了版本之后，需要重新安装依赖，否则你的 node_modules 里还是 1.5.2，下面是我基于你给我的 zip 修改后的包 [feisu-app-qms 2.zip](https://github.com/VisActor/VChart/files/13201311/feisu-app-qms.2.zip)

[feisu-app-qms.zip](https://github.com/VisActor/VChart/files/13201442/feisu-app-qms.zip)
我这里是1.5.3 更改编译问题要去掉request包，去掉request就是这样了

**Comment by kkxxkk2019** [comment]
> > REC-20231030135527.mp4
> > 我这里正常的，你更新了版本之后，需要重新安装依赖，否则你的 node_modules 里还是 1.5.2，下面是我基于你给我的 zip 修改后的包 [feisu-app-qms 2.zip](https://github.com/VisActor/VChart/files/13201311/feisu-app-qms.2.zip)
> 
> [feisu-app-qms.zip](https://github.com/VisActor/VChart/files/13201442/feisu-app-qms.zip) 我这里是1.5.3 更改编译问题要去掉request包，去掉request就是这样了

![image](https://github.com/VisActor/VChart/assets/135952300/e9bc3ace-ec01-4490-970e-4e04df594d9b)

你自己这里锁定了宽高啊，其他地方也请自己检查下吧
![image](https://github.com/VisActor/VChart/assets/135952300/0d09d351-097e-4c61-a24b-e42f25d6fda8)

**Comment by mathYang1224** [comment]
> 合预期的，都检查下有没有在 spec 中锁定

去掉width height 固定宽度好了，更新了，谢谢
