### ISSUE TITLE
当时基础折线图或者柱状图时，设置图例legends,显示line+数字

### ISSUE THREAD

**Issue by zzsssssss** [VisActor/VChart#1359]
![legends配置](https://github.com/VisActor/VChart/assets/82629043/2ea53c5e-aeac-458a-a7cd-36b60151e494)

如何指定legends图例文本内容。

**Comment by pairone** [comment]
You can configure legend.item.label.formatMethd to format the legend text content. Refer to the link below:
https://www.visactor.io/vchart/option/barChart-legends-discrete#item.label.formatMethod

---------------------------------

你可以配置下legend.item.label.formatMethd，为图例文本内容设置格式化，参考下面的链接：
https://www.visactor.io/vchart/option/barChart-legends-discrete#item.label.formatMethod
