### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Webming19** [VisActor/VChart#1371]
### Version

1.4.5

### Link to Minimal Reproduction

https://www.visactor.io/vchart/demo/progress/circular-progress-with-text

### Steps to Reproduce

1.使用文档
2.图标示例
3.进度图最后一个示例-带文本标注的环形进度图，缩略图无法显示。

### Current Behavior

1.使用文档-图标示例-进度图最后一个示例-带文本标注的环形进度图，缩略图无法显示。
2.影响页面，不论中英文：https://www.visactor.io/vchart/example。https://www.visactor.io/vchart/demo/progress/circular-progress-with-text
3.推断为图片地址错误/图片不存在导致，影响到示例首页和该图表详情页

### Expected Behavior

缩略图正常显示

### Environment

```markdown
- OS: macOS Monterey 12.7
- Browser: Chrome 118.0.5993.117
- Framework: None
```

### Any additional comments?

英文能力较差，使用中文，望见谅

**Comment by xiaoluoHe** [comment]
感谢反馈，是预览图地址的问题，我们修复一下
