### ISSUE TITLE
[Bug]  need add @visactor/vdataset & @visactor/vrender into requirements

### ISSUE THREAD

**Issue by bestony** [VisActor/VChart#1372]
### Version

1.0.6-alpha.3

### Link to Minimal Reproduction

https://codesandbox.io/s/hardcore-turing-kr3vf2?file=/src/index.ts

### Steps to Reproduce

1. 安装 VMind
2. 直接引入 VMind 到程序中。

### Current Behavior

执行 `yarn add @visactor/vmind` 无法完成 VMind 的安装，仍需加装 `@visactor/vdataset` 和 `@visactor/vrender`

<img width="842" alt="image" src="https://github.com/VisActor/VChart/assets/13283837/1ccc332f-691a-495e-9b02-99a8eab49de5">

### Expected Behavior

执行 `yarn add @visactor/vmind` 即可完成 VMind 的安装

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

应该是 这两行依赖被放置在 devDependencies 当中导致的

https://github.com/VisActor/VChart/blob/develop/packages/vmind/package.json#L45-L46

**Comment by da730** [comment]
fixed in 1.0.6-alpha.5
