### ISSUE TITLE
[Bug] @visactor/tt-lark throws an error in 抖音开发者工具

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#138]
### Version

0.1.0-alpha.1

### Link to Minimal Reproduction

none

### Steps to Reproduce

load `packages/tt-chart` 

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/135952300/26b3c208-f1f2-4d8c-ba27-87304cb98dcc)

### Expected Behavior

none

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by simaQ** [comment]
Relate https://github.com/VisActor/VChart/pull/172， https://github.com/VisActor/VUtil/pull/32
