### ISSUE TITLE
[Feature] chart label display content expanded

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#1382]
### What problem does this feature solve?

![img_v2_92c810b1-8a27-49ea-8c47-616de9a537dg](https://github.com/VisActor/VChart/assets/40026218/8abfb975-94e9-4d80-9b33-2b4270794d3f)

Labels now display the categoryField content by default. 

--------------

标签现在默认显示categoryField内容

### What does the proposed API look like?

Open a configuration to allow labels to display name values, name value combinations, percentages, etc.

-----------------

开一个配置，允许标签显示名称 数值，名称数值组合，还有百分比等内容

**Comment by kkxxkk2019** [comment]
目前饼图标签这块的展示内容，可以总结为以下几种：
1.  数值
2. 分类值
3. 百分比值
4. 以上三种数值的随意组合

看了下 echarts 和 highcharts 的是通过字符串模板来满足需求的：

1. echarts: `formatter`: https://echarts.apache.org/zh/option.html#series-bar.label.formatter
2. highcharts: https://api.highcharts.com/highcharts/series.pie.dataLabels.format

不过这两个框架中这个配置是对所有序列的 label 生效的，我们如果要实现也要考虑这个，目前我们有 `formatMethod` 回调，对应可以新增一个 `formatter` 属性，用于支持 `label` 的字符串模板，另外需要整理下现在label 属性的回调参数
