### ISSUE TITLE
brush框选怎么获取对应x轴y轴的坐标

### ISSUE THREAD

**Issue by echo713** [VisActor/VChart#1396]
![WX20231102-103803](https://github.com/VisActor/VChart/assets/29811135/4773fb75-357b-4d8d-8cb0-9730cb426a61)
brush框选怎么获取对应x轴y轴的坐标

**Comment by skie1997** [comment]
- step1: 获取brush选框的位置，

**Comment by echo713** [comment]
> * step1: 通过`vchart.getAllComponents()`找到brush组件
>   ![image](https://user-images.githubusercontent.com/40675330/279885146-0617fa1f-32c2-4ff9-b892-a5abcf1f44b0.png)
> * step2: 在brush组件中找到`_brushComponent.AABBBounds` ，这是选框在region中的相对位置
>   ![image](https://user-images.githubusercontent.com/40675330/279885372-3ff4ae1c-bb12-4db5-9f58-8cbab0586fa9.png)
> * step3: 通过`vchart.getAllComponents()`找到x/y轴组件
>   ![image](https://user-images.githubusercontent.com/40675330/279885741-89232e6c-807e-44fc-8cef-b8fedaffa185.png)
> * step4: 在轴组件中调用`_scale.invert(position)`就可以把刚才的AABBBounds中的位置转换为x/y轴的具体值
>   ![image](https://user-images.githubusercontent.com/40675330/279886853-5844d594-c6f6-4bd0-9531-f5edc4e0df21.png)


![WX20231102-152149](https://github.com/VisActor/VChart/assets/29811135/d03cd5fb-3e17-46e5-94e1-64d732e93d94)

**Comment by echo713** [comment]
> * step1: 通过`vchart.getAllComponents()`找到brush组件
>   ![image](https://user-images.githubusercontent.com/40675330/279885146-0617fa1f-32c2-4ff9-b892-a5abcf1f44b0.png)
> * step2: 在brush组件中找到`_brushComponent.AABBBounds` ，这是选框在region中的相对位置
>   ![image](https://user-images.githubusercontent.com/40675330/279885372-3ff4ae1c-bb12-4db5-9f58-8cbab0586fa9.png)
> * step3: 通过`vchart.getAllComponents()`找到x/y轴组件
>   ![image](https://user-images.githubusercontent.com/40675330/279885741-89232e6c-807e-44fc-8cef-b8fedaffa185.png)
> * step4: 在轴组件中调用`_scale.invert(position)`就可以把刚才的AABBBounds中的位置转换为x/y轴的具体值
>   ![image](https://user-images.githubusercontent.com/40675330/279886853-5844d594-c6f6-4bd0-9531-f5edc4e0df21.png)

![WX20231102-152149](https://github.com/VisActor/VChart/assets/29811135/d7ae3b03-4d6f-43e6-8f9f-af401eef3d23)
![WX20231102-152157](https://github.com/VisActor/VChart/assets/29811135/c8e6a26e-a564-41f3-af2e-cdaa0965890e)

x的坐标对不上

**Comment by skie1997** [comment]
是要获取在图表中的相对坐标吗？如果是的话

> > * step1: 通过`vchart.getAllComponents()`找到brush组件
> >   ![image](https://user-images.githubusercontent.com/40675330/279885146-0617fa1f-32c2-4ff9-b892-a5abcf1f44b0.png)
> > * step2: 在brush组件中找到`_brushComponent.AABBBounds` ，这是选框在region中的相对位置
> >   ![image](https://user-images.githubusercontent.com/40675330/279885372-3ff4ae1c-bb12-4db5-9f58-8cbab0586fa9.png)
> > * step3: 通过`vchart.getAllComponents()`找到x/y轴组件
> >   ![image](https://user-images.githubusercontent.com/40675330/279885741-89232e6c-807e-44fc-8cef-b8fedaffa185.png)
> > * step4: 在轴组件中调用`_scale.invert(position)`就可以把刚才的AABBBounds中的位置转换为x/y轴的具体值
> >   ![image](https://user-images.githubusercontent.com/40675330/279886853-5844d594-c6f6-4bd0-9531-f5edc4e0df21.png)
> 
> ![WX20231102-152149](https://user-images.githubusercontent.com/29811135/279897524-d7ae3b03-4d6f-43e6-8f9f-af401eef3d23.png) ![WX20231102-152157](https://user-images.githubusercontent.com/29811135/279897540-c8e6a26e-a564-41f3-af2e-cdaa0965890e.png)
> 
> x的坐标对不上

是需要获取画布的绝对坐标吗？如果是获取画布的绝对坐标的话，在AABBBounds的基础上+vchart.getChart().getAllRegions()[对应region的index].getLayoutStartPoint().x。

如果是需要获取对应的坐标值（也就是上图的300um），那么拿到AABBBounds只是step1的结果，需要按照step2、step3、step4的步骤计算和获取
