### ISSUE TITLE
[Bug] 饼状图点击图例不隐藏

### ISSUE THREAD

**Issue by mathYang1224** [VisActor/VChart#1403]
### Version

1.5.4

### Link to Minimal Reproduction

暂无生产链接

### Steps to Reproduce

点击饼状图图例，相应饼状图不隐藏

### Current Behavior

飞书20231102-160502.mp4

### Expected Behavior

点击 饼状图图例能隐藏对应图表

### Environment

```markdown
机型:xs max
手机版本:ios 15.0  
飞书版本号:V7.3.19-207957569
```

**Comment by mathYang1224** [comment]
以下为录屏
https://github.com/VisActor/VChart/assets/45762245/a54a2bd9-af3c-4546-a8cb-2f7b0403d1d7

**Comment by mathYang1224** [comment]
vivo V2046A / Android 13  不正常 14p是正常的

**Comment by xuefei1313** [comment]
收到，我们找一些设备调试下

**Comment by kkxxkk2019** [comment]
> vivo V2046A / Android 13 不正常 14p是正常的

你好，能帮忙尝试关闭下动画看看是否复现

**Comment by mathYang1224** [comment]
> > vivo V2046A / Android 13 不正常 14p是正常的
> 
> 你好，能帮忙尝试关闭下动画看看是否复现

怎么关闭，是手机的设置里关闭吗，你指的是哪里的动画还是图表里的配置

**Comment by kkxxkk2019** [comment]
你好，麻烦升级到 1.6.1 版本验证下
