### ISSUE TITLE
[Docs] 主题使用说明，补充具体用法

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#1411]
主题配置文档，各个样式类型加上链接。不然也不知道可配样式，以及去哪里找样式。
案例：
![image](https://github.com/VisActor/VChart/assets/15776277/fda5467c-24bc-4278-a475-074b00bc6278)
![image](https://github.com/VisActor/VChart/assets/15776277/87a630ca-1b5f-455c-92d3-a1a662f69ce5)

**Comment by xuanhun** [comment]
markByName 的使用看不懂，需要在教程里提供详细说明和例子。
具体可用的mark 的定义 在配置文档中添加链接，否则不知道这些mark 的定义去哪看

@zamhown
