### ISSUE TITLE
[Feature] Provides linear shape legend icon

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#1458]
### What problem does this feature solve?

`legends.item.shape.style.symbolType` 支持线形的图例图标形状
![img_v3_0251_b19c2659-25e9-45e9-a7e5-d3892a359e8g](https://github.com/VisActor/VChart/assets/40026218/e55c715e-044c-437e-a066-9e96dee4eb45)

### What does the proposed API look like?

![img_v3_0251_f2d6e91d-28e1-4bb9-bd06-745e2993821g](https://github.com/VisActor/VChart/assets/40026218/ede390f5-9cd9-4fd2-b315-8fef805598ea)

**Comment by xile611** [comment]
vrender symbolType `lineH`已支持
