### ISSUE TITLE
[Bug] Tooltip trigger background color does not update when switching from dark to light theme

### ISSUE THREAD

**Issue by Loongphy** [VisActor/VChart#1500]
### Version

1.6.3

### Link to Minimal Reproduction

https://www.visactor.io/vchart/demo/theme/theme-style

### Steps to Reproduce

1. Be sure not to trigger the tooltip, select the dark option, then mouseover to trigger the tooltip
2. Switch to the light option, notice the tooltip retains the dark theme color

https://github.com/VisActor/VChart/assets/42089082/6caf065b-d5d1-44e7-a786-f47ee9623218

### Current Behavior

Tooltip trigger color will remains the last theme color when change the theme.

### Expected Behavior

When change the theme, the tooltip color should be the theme color.

### Environment

```markdown
- OS: Windows 11
- Browser: Edge 119.0.2151.58
- Framework: Website exmamples
```

**Comment by zamhown** [comment]
1.8.0 已解决
