### ISSUE TITLE
柱状图图表展示问题

### ISSUE THREAD

**Issue by mathYang1224** [VisActor/VChart#1537]
### Version

1.6.1

### Link to Minimal Reproduction

无生产链接

### Steps to Reproduce

![img_v3_0259_0fa57ab7-b5ba-48ab-b6d4-0c352cd6a35g](https://github.com/VisActor/VChart/assets/45762245/554b49d9-f226-4dfa-941e-80f7651b1fd9)

### Current Behavior

数字展示异常， 坐标轴间隔展示

### Expected Behavior

数字展示正常， 坐标轴不想间隔展示，有什么方法可以展示完全

**Comment by mathYang1224** [comment]
飞书小程序线上手机存在此问题

**Comment by mathYang1224** [comment]
json格式如下::::
{
    "type": "bar",
    "barWidth": 8,
    "bar": {
        "style": {
            "lineCap": "round",
            "lineJoin": "round"
        }
    },
    "style": {
        "lineCap": "round"
    },
    "data": [
        {
            "id": "barData",
            "values": [
                {
                    "name": "海外调仓组",
                    "value": 1
                },
                {
                    "name": "生产4组",
                    "value": 1
                },
                {
                    "name": "生产1组",
                    "value": 1
                },
                {
                    "name": "产线工程组",
                    "value": 1
                },
                {
                    "name": "复核包装组",
                    "value": 1
                },
                {
                    "name": "产品出库组",
                    "value": 2
                },
                {
                    "name": "包材物料组",
                    "value": 2
                },
                {
                    "name": "生产5组",
                    "value": 2
                },
                {
                    "name": "产品入库组",
                    "value": 4
                },
                {
                    "name": "生产2组",
                    "value": 4
                },
                {
                    "name": "保税仓",
                    "value": 5
                },
                {
                    "name": "生产3组",
                    "value": 5
                }
            ]
        }
    ],
    "padding": {
        "left": 0,
        "right": 0,
        "top": 24,
        "bottom": 16
    },
    "tooltip": {
        "style": {
            "panel": {
                "border": {
                    "radius": 8
                },
                "shadow": {
                    "x": 0,
                    "y": 10,
                    "blur": 20,
                    "spread": 2,
                    "color": "#eee"
                },
                "backgroundColor": "#fff"
            },
            "shape": {
                "size": 8
            },
            "keyLabel": {
                "fontColor": "#1F2329",
                "textAlign": "left",
                "textBaseline": "bottom",
                "wordBreak": "break-all"
            },
            "valueLabel": {
                "fontColor": "#1F2329",
                "textAlign": "right",
                "wordBreak": "break-all",
                "spacing": 1,
                "textBaseline": "top",
                "multiLine": false
            }
        },
        "dimension": {
            "title": {
                "visible": true
            }
        }
    },
    "direction": "horizontal",
    "xField": "value",
    "yField": "name",
    "axes": [
        {
            "orient": "bottom",
            "grid": {
                "style": {
                    "lineDash": [
                        3,
                        3
                    ]
                }
            },
            "tick": {
                "visible": false
            },
            "visible": false,
            "style": {
                "fontSize": 10
            }
        },
        {
            "orient": "left",
            "grid": {
                "style": {
                    "lineDash": [
                        3,
                        3
                    ]
                }
            },
            "visible": true,
            "domainLine": {
                "visible": false
            },
            "tick": {
                "visible": false
            },
            "style": {
                "fontSize": 10
            }
        }
    ],
    "label": {
        "visible": true
    }
}

**Comment by mathYang1224** [comment]
手机ipone 13mini

**Comment by mathYang1224** [comment]
![img_v3_0259_3b825aa6-4d79-4301-8142-4006fa2f91fg](https://github.com/VisActor/VChart/assets/45762245/04e703c1-3d2d-406e-bf38-2aa886b9dad9)
手机iphone 13mini出现文案错乱

**Comment by mathYang1224** [comment]
[feisu-app-qms.zip](https://github.com/VisActor/VChart/files/13387394/feisu-app-qms.zip)
这是复现demo, 过程质量

**Comment by mathYang1224** [comment]
横着的柱状图在手机上坐标轴文字部分还不显示了

**Comment by xile611** [comment]
@mathYang1224 最新版试过了吗？问题还存在吗？

**Comment by xile611** [comment]
暂时先关闭了，如果最新版本还存在该问题，可以重新建issue 反馈
