### ISSUE TITLE
[Bug] DataZoom display very strange when lock is true

### ISSUE THREAD

**Issue by xile611** [VisActor/VChart#1565]
### Version

1.6.3

### Link to Minimal Reproduction

https://www.visactor.io/vchart/demo/data-zoom/data-zoom-lock?keyword=dataZoom

### Steps to Reproduce

<img width="161" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/97ea6a7b-5b11-4c94-80ec-a989cc97e4f1">
拖动最右侧的icon

### Current Behavior

1. 右侧handler鼠标有变量，理论上应该切换成`disabled` 禁用样式
2. 拖动的时候，坐标轴不应该闪动

### Expected Behavior

lock的时候，表现应该正常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
`zoomLock` 在`1.7.2`版本不生效了

**Comment by skie1997** [comment]
> `zoomLock` 在`1.7.2`版本不生效了

原因: bandsize根据图表size自适应时，会主动修改datazoom的start和end导致zoomLock失效

解决方法: 
1. 去除bandsize中对datazoom的setStartAndEnd逻辑，通过datazoom内置的minspan和maxspan实现auto bandsize @zamhown 
2. 优化datazoom交互，lock时handler交互转化为datazoom整体拖拽交互 @skie1997
