### ISSUE TITLE
[Bug] An Error occurred when converting a 3d Bar chart to a 3d Pie chart using UpdateSpec

### ISSUE THREAD

**Issue by changshou83** [VisActor/VChart#1608]
### Version

1.6.7

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/viscator-vchart-vue-demo-forked-4qcqdj?file=%2Fsrc%2FApp.vue%3A32%2C32&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp9hicrc00073j6f9vkb3fl7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp9hicrc00033j6fafopliz7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp9hicrc00043j6fdahjrqfu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp9hicrc00063j6fovs0f5ei%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B59.89789024609867%252C40.10210975390133%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp9hicrc00033j6fafopliz7%2522%253A%257B%2522id%2522%253A%2522clp9hicrc00033j6fafopliz7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpc5rxn3004j3j6f765idkdg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A207%252C%2522startColumn%2522%253A61%252C%2522endLineNumber%2522%253A207%252C%2522endColumn%2522%253A61%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FBarChart.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clpc7se6a00033j6fbwkfcact%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A32%252C%2522startColumn%2522%253A32%252C%2522endLineNumber%2522%253A32%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpc7se6a00033j6fbwkfcact%2522%257D%252C%2522clp9hicrc00063j6fovs0f5ei%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp9hicrc00053j6fv6x3fok3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clp9hicrc00063j6fovs0f5ei%2522%252C%2522activeTabId%2522%253A%2522clp9hicrc00053j6fv6x3fok3%2522%257D%252C%2522clp9hicrc00043j6fdahjrqfu%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clp9hicrc00043j6fdahjrqfu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A20.72916666666667%257D

### Steps to Reproduce

1. click the "update type" button

### Current Behavior

UpdateSpec throw an error and chart spec update failed.

### Expected Behavior

Conversion successful.

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 119.0.6045.124
- Framework: Vue@2.6
```

**Comment by xile611** [comment]
fixed in 1.11.0
