### ISSUE TITLE
目前的版本可以设置y轴上每一范围设置背景吗

### ISSUE THREAD

**Issue by AlexL0ng** [VisActor/VChart#1627]
目前的版本可以设置y轴上每一范围设置背景吗？

**Comment by kkxxkk2019** [comment]
https://www.visactor.io/vchart/demo/axis/grid-style 是类似这个需求吗？

![image](https://github.com/VisActor/VChart/assets/135952300/a8cf506f-0d3a-433f-bb91-57c349558860)

**Comment by AlexL0ng** [comment]
不是，是我没说清楚。
应该是折线图里面
![image](https://github.com/VisActor/VChart/assets/53669064/4aab0cd9-171b-46c1-8d9c-4ec6b567f186)
这样的

**Comment by kkxxkk2019** [comment]
这个可以使用 markArea 来绘制.

* 配置项说明：https://www.visactor.io/vchart/option/barChart#markArea.x
* demo:https://www.visactor.io/vchart/demo/marker/mark-area-basic

**Comment by AlexL0ng** [comment]
好的，我去试试；谢谢解答

**Comment by AlexL0ng** [comment]
@kkxxkk2019 我现在描出区域了，但是我使用label的background属性好像没有生效；
![image](https://github.com/VisActor/VChart/assets/53669064/c6b4a622-b31a-4cd2-81e9-0d7086e0ef47)
