### ISSUE TITLE
我在我的项目使用了visactor/taro-vchart

### ISSUE THREAD

**Issue by AlexL0ng** [VisActor/VChart#1632]
我是按照docs的example修改的；图是成功绘制出来了，但是整个图会随着下拉移动到最下面；它没有被固定在父容器里面；请问我该怎么把它固定到父容器里面不移动

**Comment by hipig** [comment]
想问一下你这个解决了吗

**Comment by AlexL0ng** [comment]
@hipig 解决了 page里面取消height：100%属性，不然会导致整个canvas异常浮动；但是现在我最后还是选择使用了ucharts的微信小程序版本
