### ISSUE TITLE
[Feature] tooltip value supports common number formatting

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#1677]
### What problem does this feature solve?

![img_v3_025n_39a4731d-3703-4695-b00b-1126b9512d2g](https://github.com/VisActor/VChart/assets/40026218/5102cd3f-5be3-431f-9b14-8b50d0f60495)

支持常见的数字格式化，例如

- “千分位” 划分
- 四舍五入保留2位

### What does the proposed API look like?

![image](https://github.com/VisActor/VChart/assets/40026218/93d94c5e-b8fc-49e4-8d12-f68036513eeb)

**Comment by kkxxkk2019** [comment]
这个建议用户自己格式化

**Comment by Loongphy** [comment]
I think you should consider using API like `toLocalString()` .
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#using_tolocalestring

**Comment by xiaoluoHe** [comment]
number formatter in tooltip has been supported in v1.10.0+
see: https://visactor.com/vchart/demo/label/label-formatter 
![image](https://github.com/VisActor/VChart/assets/11360419/a054fdfb-c3d5-4c81-a046-882aea9d5e85)

As for common tooltip formatter config, we will discuss in this issue https://github.com/VisActor/VChart/issues/2294
