### ISSUE TITLE
[Bug] window debounce event affects business logic

### ISSUE THREAD

**Issue by purpose233** [VisActor/VChart#1686]
### Version

1.5.4

### Link to Minimal Reproduction

null

### Steps to Reproduce

User local scenario.

### Current Behavior

Rendering charts causes editor events to fail to be monitored properly and text cannot be selected.

![img_v3_025q_1de91d21-8b76-4a88-8515-1ed94fc214hu](https://github.com/VisActor/VChart/assets/14228496/c9ba5aba-396a-4837-b616-8eaf30f7ecf3)

A pointermove debounced event is added on the document, will cause the editor problem.

### Expected Behavior

Editor text can be selected normally.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by zamhown** [comment]
排查到 datazoom 在 window 上挂载了带有 debounce 的 pointermove 事件，影响了用户挂载的其他 pointermove 事件。 
只要有 datazoom 组件就会复现
https://visactor.bytedance.net/vchart/demo/data-zoom/data-zoom-polar
