### ISSUE TITLE
[Bug] updatespec error in https://visactor.io/vchart/demo/word-cloud-chart/word-cloud-shape-basis

### ISSUE THREAD

**Issue by neuqzxy** [VisActor/VChart#1688]
### Version

1.7.2

### Link to Minimal Reproduction

1.7.2

### Steps to Reproduce

1. open https://visactor.io/vchart/demo/word-cloud-chart/word-cloud-shape-basis
2. updatespec

### Current Behavior

white screen

### Expected Behavior

work normally

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
fixed the v1.8.0
