### ISSUE TITLE
[Feature] 当坐标轴向内展示时，期望能够有一个配置支持轴与图元的安全间距

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#1690]
### What problem does this feature solve?

<img width="452" alt="image" src="https://github.com/VisActor/VChart/assets/135952300/b2ba6d6c-c812-4df1-bc77-e56c2f3ecc4d">

### What does the proposed API look like?

关联： https://github.com/VisActor/VChart/issues/1234

如果优化了布局元素的 padding 之后，是可以支持的

**Comment by xile611** [comment]
fixed in https://github.com/VisActor/VChart/pull/2104/files#diff-954e608518db4ac59a231bad7bd2f9b2770fa82dd0ced2ae535d6903016aa4ed
