### ISSUE TITLE
[Feature] Configure functions using strings and parse them

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#1702]
### What problem does this feature solve?

解决消息卡片等无法使用回调函数，且无法进行函数注册的场景

### What does the proposed API look like?

对label等文本类组件，支持对文本内容配置字符串模版。

- 不使用回调函数
- 支持使用数据及文本。例如 `${datum.value}$`
- 支持运算及格式化。例如百分比、千分位、拼接单位

可参考此demo对markLine标签内容的配置 （https://www.visactor.io/vchart/demo/marker/mark-line-total-diff）：
![image](https://github.com/VisActor/VChart/assets/40026218/136ca378-1894-49f5-92da-708588b37547)

spec:
{
   label: {
       text: `${({dutum.value}*100).toFixed(0)}%$`
   }
}

**Comment by xuanhun** [comment]
支持用户直接以字符串方式传入函数定义。 比如 “(datum)=>{return datum.value;}”

**Comment by xile611** [comment]
如果传入函数，不得执行 `eval`，这不好吧

**Comment by xuanhun** [comment]
> 如果传入函数，不得执行 `eval`，这不好吧

不然解决不了类似消息卡片这种只能传 spec 的场景下，需要自定义格式化的问题。 @xile611

**Comment by xile611** [comment]
> > 如果传入函数，不得执行 `eval`，这不好吧
> 
> 不然解决不了类似消息卡片这种只能传 spec 的场景下，需要自定义格式化的问题。 @xile611

可以考虑支持  d3-format 类似的格式化语法

**Comment by xile611** [comment]
相关issue: 

#1701 
https://github.com/VisActor/VChart/issues/1677
