### ISSUE TITLE
[Bug] shape wordcloud chart cannot render after editing in visactor site editor

### ISSUE THREAD

**Issue by purpose233** [VisActor/VChart#1713]
### Version

1.7.2

### Link to Minimal Reproduction

null

### Steps to Reproduce

https://www.visactor.io/vchart/demo/word-cloud-chart/word-cloud-shape-custom-color

Edit in site editor.

### Current Behavior

Chart cannot render after editing.

### Expected Behavior

Render chart correctly.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

This issue might related to the layout procedure. The dataflow before layout is executed but after layout dataflow will not be executed again, so that the text mark generate none elements.

**Comment by skie1997** [comment]
it has been solved in https://github.com/VisActor/VGrammar/pull/277
