### ISSUE TITLE
如何实现这种效果

### ISSUE THREAD

**Issue by ForeseeBear** [VisActor/VChart#1718]
![1341702024643_ pic_hd](https://github.com/VisActor/VChart/assets/15258339/f8ae96ef-47ef-4639-b2ab-60474aa008c3)
https://vega.github.io/editor/#/edited;
![1361702025053_ pic](https://github.com/VisActor/VChart/assets/15258339/72460b96-67bf-44dc-987c-00f052096311)
使用这种方法图例中的shape未跟随图形变化

**Comment by kkxxkk2019** [comment]
你好，排查下这是个 bug，你先这么配置吧：

```ts
{
  shapeField: 'type',
  shape: {
    type: 'ordinal',
    range: ['star', 'triangleLeft', 'diamond']
  },
}
```

<img width="1504" alt="image" src="https://github.com/VisActor/VChart/assets/135952300/3272ea6f-18b5-455d-9fce-856e7ae914ca">

**Comment by xile611** [comment]
<img width="1603" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/851499e5-e85c-4718-a9aa-cd9a2ae03757">
1.8.1版本已经修复，可以看看 @ForeseeBear
