### ISSUE TITLE
[Bug] Error: `No matching version found for @visactor/vrender-kits@0.16.21.`

### ISSUE THREAD

**Issue by fuchen** [VisActor/VChart#1730]
### Version

1.7.3

### Link to Minimal Reproduction

N/A

### Steps to Reproduce

`npm install @visactor/vchart`

Error: `No matching version found for @visactor/vrender-kits@0.16.21.`

### Current Behavior

Error: `No matching version found for @visactor/vrender-kits@0.16.21.`

### Expected Behavior

Should be installed normally.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
已修复
