### ISSUE TITLE
[Bug]  outerRadius 小于某个值的时候，0值的label就不展示了，但是如果不是0值，就算很小很小也能展示出来

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#1742]
### Version

latest

### Link to Minimal Reproduction

-

### Steps to Reproduce

![img_v3_0262_3fff356f-e4c7-489b-8650-1e8b821ff09g](https://github.com/VisActor/VChart/assets/25134429/9aae37ef-45cc-415c-bab5-3d006a6e9281)

### Current Behavior

-

### Expected Behavior

-

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
fixed in v1.8.3
