### ISSUE TITLE
[Bug] legend 文字过长省略显示异常

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#1743]
### Version

latest

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/hardcore-pond-njdxcs?file=%2Fsrc%2Findex.ts%3A96%2C18

### Steps to Reproduce

调整图标绘图区尺寸至较小时，legend文字出现省略，问题出现

### Current Behavior

![img_v3_0262_16be70b2-a0bd-4c31-8e86-febeb35410cg](https://github.com/VisActor/VChart/assets/25134429/db430d45-e1bb-4f40-bad3-87ef20ab2686)

### Expected Behavior

key省略，完整显示value

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
1.10.0 版本后，可以通过如下配置实现：

```
legends: {
  item: {
    autoEllipsisStrategy: 'value'
  }
}
```
