### ISSUE TITLE
[Feature] 雷达图绘图区过小是，标签折叠避免文字截断

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#1744]
### What problem does this feature solve?

![img_v3_0262_a91f2ee9-6387-4f98-9d8f-26227a2004fg](https://github.com/VisActor/VChart/assets/25134429/0a9c3ee3-6523-4733-b2b6-9845f3e40fb7)

### What does the proposed API look like?

-

**Comment by xiaoluoHe** [comment]
调研了下常用的图表库，普遍存在类似的问题。
考虑是否可以通过支持极坐标轴的 label.autoLimit 来优化这个情况 @kkxxkk2019 
![UZxSqzaU9U](https://github.com/VisActor/VChart/assets/11360419/486d0022-66f5-4c90-92cb-7b7e1ab8ca6f)

**Comment by kkxxkk2019** [comment]
> 调研了下其他常用的图表库，普遍存在类似的问题。 考虑是否可以通过支持极坐标轴的 label.autoLimit 来优化这个情况 @kkxxkk2019 ![UZxSqzaU9U](https://private-user-images.githubusercontent.com/11360419/310022603-486d0022-66f5-4c90-92cb-7b7e1ab8ca6f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjQzOTMsIm5iZiI6MTcwOTYyNDA5MywicGF0aCI6Ii8xMTM2MDQxOS8zMTAwMjI2MDMtNDg2ZDAwMjItNjZmNS00YzkwLTkyY2ItN2I3ZTFhYjhjYTZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA3MzQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjM4NmI0YTA4MTg4OGQzZWUzMjM0YjYxZGFmZjQ4YTQzZGJjMzZkNmZhZTE4NzM0MjAwMTI1NDY1ZmQ5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AYgYdaF7-9LX8bI-2MIkntETcuxyX-OB32oCNJGcUeY)

嗯，但是 autoLimit 这里需要考虑 limit 的位置

**Comment by xiaoluoHe** [comment]
后续还可以考虑在极坐标轴上支持标签沿圆环的布局方式，可以更好的规避这个问题。
> <image src="https://github.com/VisActor/VChart/assets/11360419/42a4c78f-3806-4096-96e1-1c1b945b2e89" width="400px">

**Comment by neuqzxy** [comment]
fs encountered the same question，synchronous when fixed

**Comment by xile611** [comment]
![img_v3_029b_76471db6-056d-4812-86cf-5945b80881bg](https://github.com/VisActor/VChart/assets/6111424/c171d2c3-a1ed-46c6-869d-82fd1231827e)

补充一下case

**Comment by xile611** [comment]
> 环的布局方式，可以更好的规避这

1. 这种和切线方向的旋转，可以作为 `autoRotate` 的一个策略吧
2. autoLimit还是需要考虑一下

**Comment by xile611** [comment]
supported in 1.12.6
support `autoHide`, `autoLimit` and `autoWrap`
https://www.visactor.io/vchart/option/radarChart-axes-band#label.autoLimit
