### ISSUE TITLE
[Bug] lineDash 配置function，在仅有一段时报错（面积图）

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#1746]
### Version

latest

### Link to Minimal Reproduction

-

### Steps to Reproduce

const spec = {
    "isNewVersion": true,
    "type": "area",
    "xField": "timeValue",
    "yField": "value",
    "seriesField": "groupName",
    "percent": true,
    "tooltip": {
        "visible": true,
        "target": {
            "visible": true,
            "title": {
                "hasShape": false,
                "key": "time"
            },
            "content": [
                {
                    "hasShape": true,
                    "shape": "circle",
                    "key": "key",
                    "value": "value"
                }
            ]
        },
        "dimension": {
            "visible": true,
            "sortReverse": true,
            "title": {
                "hasShape": false,
                "key": "x"
            },
            "content": [
                {
                    "hasShape": true,
                    "shape": "circle",
                    "key": "key",
                    "value": "value"
                }
            ]
        }
    },
    "crosshair": {
        "xField": {
            "visible": true,
            "line": {
                "type": "line",
                "style": {
                    "lineWidth": 1,
                    "opacity": 1,
                    "stroke": "#959DA5"
                }
            }
        }
    },
    "line": {
        "style": {
           lineDash: (data) => {
            if (data.latest) {
              return [5, 3];
            }
            return [1, 0];
          },
        }
    },
    "point": {
        "style": {
            "size": 4,
            "stroke": 0,
            "cursor": "pointer"
        },
        "state": {
            "dimension_hover": {
                "size": 6
            },
            "hover": {
                "size": 6
            }
        }
    },
    "padding": {
        "top": 32,
        "left": 20,
        "bottom": 10,
        "right": 20
    },
    "dataZoom": [
        {
            "orient": "bottom",
            "padding": {
                "top": 6
            }
        }
    ],
    "legends": [
        {
            "visible": false,
            "type": "discrete",
            "defaultSelected": [
                "b28a7cc47b8d9f3e453677c61401dd62,1,any_event,A",
                "b28a7cc47b8d9f3e453677c61401dd62,1,bulk_copy_dashboard,B"
            ]
        }
    ],
    "axes": [
        {
            "orient": "left",
            "zero": false,
            "label": {
                "labelPadding": 16
            }
        },
        {
            "bandPadding": 0,
            "paddingInner": 1,
            "paddingOuter": 0,
            "orient": "bottom",
            "label": {}
        }
    ],
    "color": {
        "type": "ordinal",
        "range": [
            "#1664FF",
            "#1AC6FF"
        ],
        "domain": [
            "b28a7cc47b8d9f3e453677c61401dd62,1,any_event,A",
            "b28a7cc47b8d9f3e453677c61401dd62,1,bulk_copy_dashboard,B"
        ]
    },
    "markLine": [],
    "data": [
        {
            "name": "area",
            "values": [
                {
                    "groupName": "b28a7cc47b8d9f3e453677c61401dd62,1,any_event,A",
                    "eventName": "A 任意事件",
                    "key": "b28a7cc47b8d9f3e453677c61401dd62,1,any_event,A",
                    "legendKey": "b28a7cc47b8d9f3e453677c61401dd62,1,any_event,A",
                    "showName": "任意事件（总次数）",
                    "time": "周二, 12-12",
                    "timeValue": "20231212",
                    "seriesName": "b28a7cc47b8d9f3e453677c61401dd62,1,any_event,A",
                    "axisValue": "20231212",
                    "value": 7223582,
                    "valueText": "7,223,582",
                    "labelName": "A1",
                    "latest": false
                },
                {
                    "groupName": "b28a7cc47b8d9f3e453677c61401dd62,1,any_event,A",
                    "eventName": "A 任意事件",
                    "key": "b28a7cc47b8d9f3e453677c61401dd62,1,any_event,A",
                    "legendKey": "b28a7cc47b8d9f3e453677c61401dd62,1,any_event,A",
                    "showName": "任意事件（总次数）",
                    "time": "周三, 12-13",
                    "timeValue": "20231213",
                    "seriesName": "b28a7cc47b8d9f3e453677c61401dd62,1,any_event,A",
                    "axisValue": "20231213",
                    "value": 369032,
                    "valueText": "369,032",
                    "labelName": "A1",
                    "latest": true
                },
                {
                    "groupName": "b28a7cc47b8d9f3e453677c61401dd62,1,bulk_copy_dashboard,B",
                    "eventName": "B 跨项目复制看板",
                    "key": "b28a7cc47b8d9f3e453677c61401dd62,1,bulk_copy_dashboard,B",
                    "legendKey": "b28a7cc47b8d9f3e453677c61401dd62,1,bulk_copy_dashboard,B",
                    "showName": "跨项目复制看板（总次数）",
                    "time": "周二, 12-12",
                    "timeValue": "20231212",
                    "seriesName": "b28a7cc47b8d9f3e453677c61401dd62,1,bulk_copy_dashboard,B",
                    "axisValue": "20231212",
                    "value": 1,
                    "valueText": "1",
                    "labelName": "B1",
                    "latest": false
                },
                {
                    "groupName": "b28a7cc47b8d9f3e453677c61401dd62,1,bulk_copy_dashboard,B",
                    "eventName": "B 跨项目复制看板",
                    "key": "b28a7cc47b8d9f3e453677c61401dd62,1,bulk_copy_dashboard,B",
                    "legendKey": "b28a7cc47b8d9f3e453677c61401dd62,1,bulk_copy_dashboard,B",
                    "showName": "跨项目复制看板（总次数）",
                    "time": "周三, 12-13",
                    "timeValue": "20231213",
                    "seriesName": "b28a7cc47b8d9f3e453677c61401dd62,1,bulk_copy_dashboard,B",
                    "axisValue": "20231213",
                    "value": 0,
                    "valueText": "0",
                    "labelName": "B1",
                    "latest": true
                }
            ],
            "fields": {
                "groupName": {
                    "sortIndex": 0,
                    "sortReverse": true,
                    "type": "ordinal"
                }
            }
        }
    ],
    "height": 402,
    "theme": {
        "component": {
            "axis": {
                "label": {
                    "style": {
                        "fontSize": 12
                    }
                }
            },
            "discreteLegend": {
                "orient": "bottom",
                "position": "middle",
                "padding": [
                    16,
                    24
                ],
                "item": {
                    "visible": true,
                    "spaceCol": 10,
                    "spaceRow": 10,
                    "padding": 2,
                    "background": {
                        "state": {
                            "selectedHover": {
                                "fillOpacity": 0
                            },
                            "unSelectedHover": {
                                "fillOpacity": 0
                            }
                        }
                    },
                    "shape": {
                        "space": 6,
                        "style": {
                            "symbolType": "circle",
                            "size": 6
                        },
                        "state": {
                            "unSelected": {
                                "fillOpacity": 1,
                                "fill": "#c6c2cc"
                            }
                        }
                    },
                    "label": {
                        "space": 6,
                        "style": {
                            "fill": "#333333",
                            "fontSize": 12
                        },
                        "state": {
                            "unSelected": {
                                "fill": "#999999"
                            }
                        }
                    }
                }
            }
        },
        "markByName": {
            "bar": {},
            "line": {},
            "point": {},
            "pie": {},
            "boxPlot": {},
            "label": {
                "offset": 5,
                "overlap": {
                    "clampForce": true,
                    "hideOnHit": true,
                    "strategy": []
                },
                "smartInvert": false,
                "animation": false,
                "style": {
                    "fontSize": 12
                }
            }
        }
    }
}

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

![img_v3_0262_eb7c355a-f61d-4733-8277-f70adca3df3g](https://github.com/VisActor/VChart/assets/25134429/90b50759-5e52-4314-9bee-58ef2def6782)
![img_v3_0262_cc1e2cfe-a343-47b8-8f28-d82bd1ba86cg](https://github.com/VisActor/VChart/assets/25134429/ed89d9d4-6842-4880-b48b-f7d9389f84a5)

### Expected Behavior

之前已经在折线图修复过，不过面积图任然有问题

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
fixed in https://github.com/VisActor/VRender/issues/801
