### ISSUE TITLE
[Feature] 图表支持渐变（字符串形式）

### ISSUE THREAD

**Issue by kuangyuliang** [VisActor/VChart#1751]
### What problem does this feature solve?

目前style的fill渐变色只能通过json配置，希望能支持字符串形式，如：
- linear-gradient(315deg, #c1e9fb 8.00%,#5473a1 92.00%)
- radial-gradient(circle at center, #ffff00 0.00%,#009966 50.00%,#800080 100.00%)

### What does the proposed API look like?

```
line: {
  style: {
    fill: 'linear-gradient(315deg, #c1e9fb 8.00%,#5473a1 92.00%)'
  }
}
```

**Comment by neuqzxy** [comment]
https://github.com/VisActor/VRender/pull/911
