### ISSUE TITLE
[Bug] 移动端 crosshairs 效果不正确

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#1779]
### Version

1.7.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

移动端使用crosshairs
const spec = {
    "type": "common",
    "data": [
        {
            "id": "7954",
            "values": [
                {
                    "dim": "2023-11-14",
                    "metric": "净资产收益率",
                    "val": 119.80189653036018
                },
                {
                    "dim": "2023-11-15",
                    "metric": "净资产收益率",
                    "val": 120.07537578516127
                },
                {
                    "dim": "2023-11-16",
                    "metric": "净资产收益率",
                    "val": 119.8049614492598
                },
                {
                    "dim": "2023-11-17",
                    "metric": "净资产收益率",
                    "val": 89.67157875833601
                },
                {
                    "dim": "2023-11-18",
                    "metric": "净资产收益率",
                    "val": 120.2778488219763
                },
                {
                    "dim": "2023-11-19",
                    "metric": "净资产收益率",
                    "val": 119.8880707575542
                },
                {
                    "dim": "2023-11-20",
                    "metric": "净资产收益率",
                    "val": 120.00015767487348
                },
                {
                    "dim": "2023-11-21",
                    "metric": "净资产收益率",
                    "val": 120.42649790458225
                },
                {
                    "dim": "2023-11-22",
                    "metric": "净资产收益率",
                    "val": 118.54514199434766
                },
                {
                    "dim": "2023-11-23",
                    "metric": "净资产收益率",
                    "val": 119.7731950260175
                },
                {
                    "dim": "2023-11-24",
                    "metric": "净资产收益率",
                    "val": 120.85799144982265
                },
                {
                    "dim": "2023-11-25",
                    "metric": "净资产收益率",
                    "val": 119.53007831186375
                },
                {
                    "dim": "2023-11-26",
                    "metric": "净资产收益率",
                    "val": 90.72824801586314
                },
                {
                    "dim": "2023-11-27",
                    "metric": "净资产收益率",
                    "val": 120.72836571122876
                },
                {
                    "dim": "2023-11-28",
                    "metric": "净资产收益率",
                    "val": 120.27482817606514
                },
                {
                    "dim": "2023-11-29",
                    "metric": "净资产收益率",
                    "val": 120.04620934639014
                },
                {
                    "dim": "2023-11-30",
                    "metric": "净资产收益率",
                    "val": 119.9269697562986
                },
                {
                    "dim": "2023-12-01",
                    "metric": "净资产收益率",
                    "val": 119.56059510351612
                },
                {
                    "dim": "2023-12-02",
                    "metric": "净资产收益率",
                    "val": 120.46316039483273
                },
                {
                    "dim": "2023-12-03",
                    "metric": "净资产收益率",
                    "val": 119.08644676533531
                },
                {
                    "dim": "2023-12-04",
                    "metric": "净资产收益率",
                    "val": 119.39849658546095
                },
                {
                    "dim": "2023-12-05",
                    "metric": "净资产收益率",
                    "val": 118.97077124318007
                },
                {
                    "dim": "2023-12-06",
                    "metric": "净资产收益率",
                    "val": 120.61357489281201
                },
                {
                    "dim": "2023-12-07",
                    "metric": "净资产收益率",
                    "val": 90.05052048989828
                },
                {
                    "dim": "2023-12-08",
                    "metric": "净资产收益率",
                    "val": 118.51745858724925
                },
                {
                    "dim": "2023-12-09",
                    "metric": "净资产收益率",
                    "val": 119.75980759131399
                },
                {
                    "dim": "2023-12-10",
                    "metric": "净资产收益率",
                    "val": 118.76081683481273
                },
                {
                    "dim": "2023-12-11",
                    "metric": "净资产收益率",
                    "val": 119.9468840193592
                },
                {
                    "dim": "2023-12-12",
                    "metric": "净资产收益率",
                    "val": 120.26479705532965
                },
                {
                    "dim": "2023-12-13",
                    "metric": "净资产收益率",
                    "val": 119.88296760780742
                },
                {
                    "dim": "2023-12-14",
                    "metric": "净资产收益率",
                    "val": 120.07845448019926
                }
            ]
        }
    ],
    "series": [
        {
            "id": "series7954",
            "type": "area",
            "dataId": "7954",
            "seriesField": "metric",
            "xField": [
                "dim"
            ],
            "yField": "val",
            "stack": false,
            "line": {
                "style": {
                    "curveType": "monotone",
                    "zIndex": 801
                }
            },
            "area": {
                "style": {
                    "curveType": "monotoneX",
                    "fill": {
                        "gradient": "linear",
                        "x0": 0.5,
                        "y0": 0,
                        "x1": 0.5,
                        "y1": 1,
                        "stops": [
                            {
                                "offset": 0,
                                "opacity": 0.5
                            },
                            {
                                "offset": 0.5,
                                "opacity": 0
                            },
                            {
                                "offset": 1,
                                "color": "#fff",
                                "opacity": 0
                            }
                        ]
                    }
                }
            },
            "point": {
                "style": {
                    "size": 0,
                    "lineWidth": 0,
                    "stroke": "#fff"
                },
                "state": {
                    "firstSelected": {
                        "size": 8,
                        "lineWidth": 2,
                        "stroke": {
                            "scale": "color",
                            "field": "metric"
                        },
                        "fill": "#fff"
                    },
                    "cutomizedLegendHover": {
                        "size": 8,
                        "lineWidth": 2,
                        "stroke": {
                            "scale": "color",
                            "field": "metric"
                        },
                        "fill": "#fff"
                    }
                }
            }
        }
    ],
    "color": [
        "#1664FF",
        "#1AC6FF"
    ],
    "markLine": [],
    "legends": {
        "visible": false
    },
    "axes": [
        {
            "orient": "bottom",
            "paddingInner": 1,
            "paddingOuter": 0,
            "visible": true,
            "label": {
                "autoRotate": true,
                "autoRotateAngle": [
                    0,
                    90
                ]
            },
            "title": {
                "visible": false
            }
        },
        {
            "orient": "left",
            "tick": {
                "inside": true
            },
            "grid": {
                "style": {
                    "lineDash": [
                        5,
                        3
                    ]
                }
            },
            "visible": true,
            "title": {
                "visible": false
            },
            "seriesId": [
                "series7954"
            ],
            "label": {
                "space": 8
            }
        },
        {
            "orient": "right",
            "tick": {
                "inside": true
            },
            "grid": {
                "style": {
                    "lineDash": [
                        5,
                        3
                    ]
                }
            },
            "visible": true,
            "title": {
                "visible": false
            },
            "seriesId": [
                "series7956"
            ],
            "label": {
                "space": 8
            }
        }
    ],
    "tooltip": {
        "trigger": "click"
    },
    "crosshair": {
        "trigger": "click",
        "gridZIndex": 401,
        "labelZIndex": 501,
        "xField": {
            "visible": true,
            "bindingAxesIndex": [
                0
            ],
            "line": {
                "visible": true,
                "type": "line",
                "style": {
                    "opacity": 1,
                    "lineDash": [
                        2,
                        2
                    ],
                    "lineWidth": 1,
                    "stroke": "#193D7A"
                }
            },
            "label": {
                "labelBackground": {
                    "style": {
                        "fill": "#193D7A",
                        "outerBorder": {
                            "stroke": "#193D7A"
                        }
                    }
                },
                "visible": true
            },
            "defaultSelect": {
                "axisIndex": 0,
                "datum": "2023-12-14"
            }
        },
        "yField": {
            "bindingAxesIndex": [
                1,
                2
            ],
            "visible": true,
            "line": {
                "visible": true,
                "type": "line",
                "style": {
                    "opacity": 1,
                    "lineDash": [
                        2,
                        2
                    ],
                    "lineWidth": 1,
                    "stroke": "#193D7A"
                }
            },
            "label": {
                "labelBackground": {
                    "style": {
                        "fill": "#193D7A",
                        "outerBorder": {
                            "stroke": "#193D7A"
                        }
                    }
                },
                "visible": true
            }
        }
    }
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

![img_v3_0265_2d95b167-c4ee-4c7d-b5b6-ca4769bc7ffg](https://github.com/VisActor/VChart/assets/15776277/feac4489-62a9-476f-a04b-f4d9ae6fab7c)

### Expected Behavior

null

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
@xuefei1313 这个手机型号有吗？

**Comment by xuefei1313** [comment]
设备信息：
iOS版本 ：17.1.2
型号名称： iPhone 13 mini
型号号码：MLDH3CH/A

**Comment by xile611** [comment]
不同操作系统计算文字高度和对文字对齐方式实现不一致导致的问题，没法做到完全一致
