### ISSUE TITLE
[Bug] Error: TypeError: null is not an object (evaluating 'this.axisLabelsContainer.AABBBounds')

### ISSUE THREAD

**Issue by AnneHuster** [VisActor/VChart#1783]
### Version

1.6.5

### Link to Minimal Reproduction

null

### Steps to Reproduce

用户图表配置轴标签不显示

### Current Behavior

监控到JS报错

### Expected Behavior

无JS报错

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
@xiaoluoHe 这个需要基于v1.6.5发布个bugfix版本

**Comment by xiaoluoHe** [comment]
@AnneHuster 请提供下可复现的图表配置

**Comment by xiaoluoHe** [comment]
已处理报错兼容逻辑。
https://github.com/VisActor/VRender/pull/816
