### ISSUE TITLE
block-vchart demo跑不起来 ThirdScriptError: at tt.createSelectorQuery callback TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by rongxiangcai** [VisActor/VChart#1807]
### Version

1.8.0

### Link to Minimal Reproduction

https://github.com/VisActor/VChart/tree/main/packages/block-vchart

### Steps to Reproduce

运行demo

### Current Behavior

报错
ThirdScriptError: at tt.createSelectorQuery callback
TypeError: Cannot read properties of undefined (reading 'id')

### Expected Behavior

不报错

### Environment

```markdown
- OS:macOS Sonoma
- Browser: 
- Framework:
```

**Comment by xile611** [comment]
@rongxiangcai 1.8.1版本应该解决了这个问题
