### ISSUE TITLE
您好，我想自定义Chart的背景颜色，但是为什么Chart的配置变化了，图表的背景颜色并未改变，实际上已经重新执行了这个函数了

### ISSUE THREAD

**Issue by LRboyz** [VisActor/VChart#1846]
![image](https://github.com/VisActor/VChart/assets/48092353/01ccb5fd-b301-41f0-8a64-54aa91bcf892)

**Comment by xile611** [comment]
@LRboyz 提供一下复现问题的demo吧

**Comment by xile611** [comment]
可以试一下最新版本，如果有问题，需要提供一下可复现问题的最小代码
