### ISSUE TITLE
[Bug] dimension_hover point is covered when the data are mass

### ISSUE THREAD

**Issue by pddpd** [VisActor/VChart#1847]
### Version

1.7.3

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/keen-bell-d4z39c?file=%2Fsrc%2Findex.ts

### Steps to Reproduce

Use the sandbox spec, and hover on a purple point
![image](https://github.com/VisActor/VChart/assets/15177000/31f38fa7-2a52-46c0-a5c0-078e59fda132)

### Current Behavior

dimension_hover point is covered

### Expected Behavior

dimension_hover point should have a higher z-index

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
@pddpd 通过在 `dimension_hover`中增加 `globalZIndex` 来提升至交互层，可以解决这个问题

<img width="463" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/eda362e3-8b73-449e-8ae7-86b4282a4e65">

https://codesandbox.io/p/sandbox/runtime-butterfly-lfh9wy?file=%2Fsrc%2Findex.ts%3A96%2C21

**Comment by pddpd** [comment]
> @pddpd 通过在 `dimension_hover`中增加 `globalZIndex` 来提升至交互层，可以解决这个问题
> 
> <img alt="image" width="463" src="https://private-user-images.githubusercontent.com/6111424/293135399-eda362e3-8b73-449e-8ae7-86b4282a4e65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3Mzk4MjIsIm5iZiI6MTcwMzczOTUyMiwicGF0aCI6Ii82MTExNDI0LzI5MzEzNTM5OS1lZGEzNjJlMy04YjczLTQ0OWUtOGFlNy04NmI0MjgyYTRlNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDQ1ODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI4YTZmNmJhZTU0NDNmNGRjYzJmN2QzNDY1ZGNjNWIxOGY0ZjE2MThkY2M1OTkwNzA4ZTgwYTQ3Yjc3YjZmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nq9iTPsZm2kxAhEaaZsRDK8HXO3Zl6fAxxcPylYTq28">
> https://codesandbox.io/p/sandbox/runtime-butterfly-lfh9wy?file=%2Fsrc%2Findex.ts%3A96%2C21

@xile611 官方文档上搜不到 `globalZIndex`，它和 `zIndex` 的区别是什么呢
![image](https://github.com/VisActor/VChart/assets/15177000/ad9c23ec-fbe8-4c17-ad68-1e743ea5944d)
![image](https://github.com/VisActor/VChart/assets/15177000/4e13d2f0-fbb0-4cfd-82de-094501a32a29)
