### ISSUE TITLE
Bug：React/VChart 折线图初始化未设置 xField，yField 渲染异常

### ISSUE THREAD

**Issue by wulucxy** [VisActor/VChart#1861]
![image](https://github.com/VisActor/VChart/assets/5326403/1a37884a-d5fa-48c3-874a-d757f050ffe0)

复现路径：
1. 初始化不设置 xField，yField（后续变更），折线图不展示

**Comment by zamhown** [comment]
用户没有使用 spec，使用具体 props 配置图表：
![image](https://github.com/VisActor/VChart/assets/15249097/05706b03-30fd-4d9a-bf30-0303260a9d74)

**Comment by wulucxy** [comment]
```
// @ts-ignore
import { useEffect, useState } from "react";

const LineChartDemo = () => {
  const [fields, setFields] = useState({
    xField: undefined,
    yField: undefined,
  });

  useEffect(() => {
    setTimeout(() => {
      setFields({
        xField: "month",
        yField: "sales",
      });
    }, 5000);
  }, []);

  return (
    <>
      <h2>折线图</h2>
      <LineChart
        dimension={[600, 400]}
        options={lineOptions}
        {...fields}
        padding={[100, 0, 20, 60]}
      />
    </>
  );
};
```

**Comment by xile611** [comment]
@wulucxy 需要给一下详细代码，本地没有复现
LineChart 用的是react-vchart封装的，还是自己封装的

**Comment by xile611** [comment]
也可以试一下最新的1.8.4 的版本
另外，建议下次按照我们的规范提交issue哈，感谢

**Comment by wulucxy** [comment]
> @wulucxy 需要给一下详细代码，本地没有复现 LineChart 用的是react-vchart封装的，还是自己封装的

未修复，复现代码上面已经给 demo 了
