### ISSUE TITLE
BUG: React/VChart BarChart data 初始为 undefined 直接报错

### ISSUE THREAD

**Issue by wulucxy** [VisActor/VChart#1862]
现在 react-vchart 是不是不支持动态数据更新，data 如果从 undefined 过渡会报错，直接传 undefine 或者 value 是没问题的

**Comment by xile611** [comment]
@wulucxy 不支持data为undefined

**Comment by xile611** [comment]
没有复现了，可以试一下最新的 1.8.4版本
如果还有问题，需要提供一下详细的复现方法
