### ISSUE TITLE
[Bug] react-vchart error

### ISSUE THREAD

**Issue by neuqzxy** [VisActor/VChart#1887]
### Version

1.8.1

### Link to Minimal Reproduction

1.8.1

### Steps to Reproduce

![image](https://github.com/VisActor/VChart/assets/26994055/d3c825f7-d99c-41f3-b93a-60aa793eb5df)

### Current Behavior

页面react路由跳转过程中报错

### Expected Behavior

不报错

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
fixed in 1.8.3
