### ISSUE TITLE
[Feature] 优化饼图标签布局：当文本不展示时，连接线也跟随不显示

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#1918]
### What problem does this feature solve?

饼图的标签在容器不大不小的时候会展示出一条线，能否优化下：展示下的都展示，展示不下也不要这条线：

![img_v3_026o_3183c172-bdb2-4727-83c5-5e528d20c4dg](https://github.com/VisActor/VChart/assets/135952300/a33fe527-ccf1-4506-9ecb-7ea27dc767f9)

### What does the proposed API look like?

none

**Comment by xiaoluoHe** [comment]
fixed in v1.8.7
