### ISSUE TITLE
修改冻结列的icon样式

### ISSUE THREAD

**Issue by Sunny20202020** [VisActor/VChart#1948]
![image](https://github.com/VisActor/VChart/assets/112694469/75e907d9-1a15-4862-aadf-f467dbafc827)
途中红框的列我都加了冻结,以下问题:
1.这个icon在没有激活的状态下或者hover的时候颜色不明显.我怎么修改这个样式呢?(我说的样式包含: 激活样式+未激活样式+hover样式+size)
2.如果我想换成别的icon怎么换

**Comment by xile611** [comment]
@Sunny20202020 这是 vtable 的issue吧

**Comment by Sunny20202020** [comment]
@xile611 是的 这个icon样式可以改吗 我看了好几遍文档都没看见哪里配置呢

**Comment by Sunny20202020** [comment]
@xile611 才看见我提到错到VChart了 我需要关了重新去VTable那边提吗
