### ISSUE TITLE
如何去除两端空白

### ISSUE THREAD

**Issue by way-jm** [VisActor/VChart#1997]
![image](https://github.com/VisActor/VChart/assets/18083432/4e0e0b7a-d0d5-4bd8-9c36-a078ff487532)
图示的z这两端空白如何配置去除呢？我已经设置了padding:{left:0,right:0,bottom:0,right:0},具体的配置如下:
`const spec = {
        type: 'bar',
        data: [
            {
                id: 'barData',
                values: [
                    { month: 'Monday', sales: 22 },
                    { month: 'Tuesday', sales: 13 },
                    { month: 'Wednesday', sales: 5 },
                    { month: 'Thursday', sales: 10 },
                    { month: 'Friday', sales: 1 },
                    { month: 'Friday1', sales: 23 },
                    { month: 'Friday2', sales: 12 },
                    { month: 'Friday3', sales: 29 },
                    { month: 'Friday4', sales: 40 },
                ]
            }
        ],
        xField: 'month',
        yField: 'sales',
        axes: [
            {
                orient: 'left',
                visible: false,
                padding:[0,0,0,0],
                left:0,
                right:0,
                range: {
                    min: 0,
                    max: 50
                }
            },
            {
                orient: 'bottom',
                visible: false
            }
        ],
        padding:{
          left:0,
          top:0,
          bottom:8,
          right:0,
        },
        animationNormal: {
            bar: [
                {
                    loop: true,
                    startTime: 100,
                    oneByOne: 100,
                    timeSlices: [
                        {
                            delay: 1000,
                            effects: {
                                channel: {
                                    fillOpacity: { to: 0.5 }
                                },
                                easing: 'linear'
                            },
                            duration: 500
                        },
                        {
                            effects: {
                                channel: {
                                    fillOpacity: { to: 1 }
                                },
                                easing: 'linear'
                            },
                            duration: 500
                        }
                    ]
                }
            ]
        }
    };`

**Comment by skie1997** [comment]
可以通过在band axes上配置trimPadding实现，配置项详见：https://www.visactor.io/vchart/option/barChart-axes-band#trimPadding

**Comment by skie1997** [comment]
> ![image](https://private-user-images.githubusercontent.com/18083432/295464214-4e0e0b7a-d0d5-4bd8-9c36-a078ff487532.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjI4MjYsIm5iZiI6MTcwNDk2MjUyNiwicGF0aCI6Ii8xODA4MzQzMi8yOTU0NjQyMTQtNGUwZTBiN2EtZDBkNS00YmQ4LTljMzYtYTA3OGZmNDg3NTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA4NDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YWNhZjNhZjgzMjAzMjIyN2I4OTZmZDY5NGUyMmUxMWNiMDZlZDY0ODhmOTNhMzBjNTJkN2RkNzE2ZDdlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6n73KgHPBUy6GEB9ao5wBOyoTA0snDAH7smU5kYkgyU) 图示的z这两端空白如何配置去除呢？我已经设置了padding:{left:0,right:0,bottom:0,right:0},具体的配置如下: `const spec = { type: 'bar', data: [ { id: 'barData', values: [ { month: 'Monday', sales: 22 }, { month: 'Tuesday', sales: 13 }, { month: 'Wednesday', sales: 5 }, { month: 'Thursday', sales: 10 }, { month: 'Friday', sales: 1 }, { month: 'Friday1', sales: 23 }, { month: 'Friday2', sales: 12 }, { month: 'Friday3', sales: 29 }, { month: 'Friday4', sales: 40 }, ] } ], xField: 'month', yField: 'sales', axes: [ { orient: 'left', visible: false, padding:[0,0,0,0], left:0, right:0, range: { min: 0, max: 50 } }, { orient: 'bottom', visible: false } ], padding:{ left:0, top:0, bottom:8, right:0, }, animationNormal: { bar: [ { loop: true, startTime: 100, oneByOne: 100, timeSlices: [ { delay: 1000, effects: { channel: { fillOpacity: { to: 0.5 } }, easing: 'linear' }, duration: 500 }, { effects: { channel: { fillOpacity: { to: 1 } }, easing: 'linear' }, duration: 500 } ] } ] } };`

可以通过在band axes上配置trimPadding实现，配置项详见：https://www.visactor.io/vchart/option/barChart-axes-band#trimPadding
![image](https://github.com/VisActor/VChart/assets/40675330/15ab70ae-d6a9-4116-8e55-3ce5454718aa)

**Comment by way-jm** [comment]
从你的截图来看两边还是有空白？这个没有办法彻底去除吗？顶边的那种

**Comment by way-jm** [comment]
<img width="259" alt="image" src="https://github.com/VisActor/VChart/assets/18083432/cdd31120-9c0e-49ba-8317-477272f2b9d4"> 这是[ant pro](https://preview.pro.ant.design/dashboard/analysis) 示例页面的效果，我希望达成这样的

**Comment by skie1997** [comment]
> 从你的截图来看两边还是有空白？这个没有办法彻底去除吗？顶边的那种

看截图左右两边的空白有可能是图表padding引起的，可以设置下图表padding: 0看下效果。  

顶部空白可以通过设置轴范围来解决，当前的空白是轴根据数据范围自动配置的。

**Comment by skie1997** [comment]
@way-jm 如果修改不能满足需求可以加下我们的微信群或者飞书群，我们可以拉群看下具体case后解答。
微信群:  
![image](https://github.com/VisActor/VChart/assets/40675330/ed9edb89-0c49-484b-883f-87466fe18867)

飞书群:  
![飞书20240122-110415](https://github.com/VisActor/VChart/assets/40675330/36cb1a83-98de-47bf-9688-bb88f991008d)
