### ISSUE TITLE
taro-vchart 怎么配置按需引入图标

### ISSUE THREAD

**Issue by hanyingming** [VisActor/VChart#2018]

**Comment by xiaoluoHe** [comment]
1.10.x 起， taro-vchart 支持按需加载，参考文档 [Load on demand](https://visactor.bytedance.net/vchart/guide/tutorial_docs/Load_on_Demand)
![image](https://github.com/VisActor/VChart/assets/11360419/c8321362-c6b2-46f2-876c-d663e137a3fd)
