### ISSUE TITLE
When I call updateData, the selection status of the legends gets reset.

### ISSUE THREAD

**Issue by kotepillar** [VisActor/VChart#2034]
For example, if I have the following chart legends: "Option 1", "Option 2", and "Option 3", when I click on the legends for "Option 2" and "Option 3", the chart will only display the graph corresponding to "Option 1". If I call updateData at this point, the graphs for "Option 2" and "Option 3" will reappear (and the corresponding legends will reset to their default state).

Here is the key code where I am using React and vchart:
```
vchartRef.current.updateData(
          'id',
          fakeData, 
        )
```

**Comment by xile611** [comment]
fixed in 1.11.0
