### ISSUE TITLE
[Bug] :@visactor/react-vchart打包类型错误

### ISSUE THREAD

**Issue by LRboyz** [VisActor/VChart#2039]
### Version

^1.8.7

### Link to Minimal Reproduction

no

### Steps to Reproduce

1.pnpm build 2.报错

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/48092353/dad4a5f6-c91d-48c8-9290-c1f4b0c19ec2)

### Expected Behavior

build Success！

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

修复类型错误❌

**Comment by xile611** [comment]
可能是typescript 版本问题
https://stackoverflow.com/questions/72947650/type-error-expected-when-running-yarn-build
如果提供复现环境，可以reopen或者新建一个issue
