### ISSUE TITLE
[Bug] Drag outside the chart area and release the mouse. The select frame has been stuck

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#205]
### Version

1.0.0

### Link to Minimal Reproduction

na

### Steps to Reproduce

1. mouse down in chart area
2. move to out side of chart area
3. release mouse button

### Current Behavior

the select frame has been stuck
![20230714161427_rec_](https://github.com/VisActor/VChart/assets/8744196/06bbd103-00a9-4387-b07c-2d8bbdc3ee30)

### Expected Behavior

the select frame has been fixed when mouse out
![20230714161501_rec_-convert](https://github.com/VisActor/VChart/assets/8744196/32501aaf-fa77-4fb2-b654-83f14bb2071c)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by skie1997** [comment]
it will be sloved when the [vrender-component MR](https://github.com/VisActor/VRender/pull/278) has merged and package version has been updated in vchart
![20230809105236_rec_](https://github.com/VisActor/VChart/assets/40675330/b4c722f2-ee6d-4160-b281-e2a89d039c5b)

**Comment by kkxxkk2019** [comment]
`@visactor/vrender-components` had been released, just upgrade your dependencies, make sure `@visactor/vrender-components`'s version is `0.13.10`
