### ISSUE TITLE
[Bug] bar chart with only one data item behaves incorrectly on y axis range when y axis is set ‘ zero : false’

### ISSUE THREAD

**Issue by Kate199824** [VisActor/VChart#2069]
### Version

1.6.1

### Link to Minimal Reproduction

null

### Steps to Reproduce

const spec = {
  type: 'bar',
  data: [
    {
      id: 'barData',
      values: [
        { month: 'Monday', sales: 22 },
      ]
    }
  ],
  xField: 'month',
  yField: 'sales',
  axes: [
    {
        orient: "left",
        zero: false,
    }
]
};

### Current Behavior

<img width="1330" alt="image" src="https://github.com/VisActor/VChart/assets/29827036/4274cce3-b469-4214-83e2-8e1f357310d7">

### Expected Behavior

<img width="1539" alt="image" src="https://github.com/VisActor/VChart/assets/29827036/d8ab25f0-df7a-42c6-a09d-68491c773300">

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
因为算出来的最小值刚好也是0，如果想要指定最小值，可以设置 min
