### ISSUE TITLE
[Demo] 提供 next.js 项目中使用 VChart 的示例，并且在生产环境中测试正常

### ISSUE THREAD

**Issue by zamhown** [VisActor/VChart#2071]
用户在 nextjs 生产环境中无法使用 VChart，出现报错
（客户端渲染错误，但是在开发环境中是一切正常的，只要哪一个页面使用了这个图表组件就会报错）

用户使用的是 next13 的 page 路由版本，应该都是客户端渲染，打包方法就是正常的 next build

![img_v3_0277_be1f0640-31ab-4a26-9203-46c8e7bb8b4g](https://github.com/VisActor/VChart/assets/15249097/3b7cf6d2-1d6c-456e-a69a-f79b3fdc0372)
![img_v3_0277_6422c4c0-f9e4-4822-83a2-3317b30254ag](https://github.com/VisActor/VChart/assets/15249097/1aad45c3-3b80-430f-9bf2-444773080bc6)

**Comment by xile611** [comment]
@zamhown 让用户提供一下最小复现的方法吧

**Comment by zamhown** [comment]
https://github.com/LRboyz/vchart-demo

**Comment by Crayon-ShinChan** [comment]
Hi, I have a open source project using Next.js and VChart. https://github.com/Crayon-ShinChan/runiu

Hope this can help as reference
