### ISSUE TITLE
[Bug] Sequence Chart does not display the last bar.

### ISSUE THREAD

**Issue by kotepillar** [VisActor/VChart#2115]
### Version

1.8.9

### Link to Minimal Reproduction

https://jsfiddle.net/kotepillar/jdqv6zyb/

### Steps to Reproduce

Just view the VChart rendering result

### Current Behavior

<img width="653" alt="image" src="https://github.com/VisActor/VChart/assets/31957644/067fed96-17f0-4af8-b8d0-f79aeceb0a86">

### Expected Behavior

<img width="545" alt="image" src="https://github.com/VisActor/VChart/assets/31957644/01429605-62e4-409e-9f92-c65b1204c6c2">

### Any additional comments?

Is there a problem with my configuration?

**Comment by skie1997** [comment]
> ### Version
> 1.8.9
> 
> ### Link to Minimal Reproduction
> https://jsfiddle.net/kotepillar/jdqv6zyb/
> 
> ### Steps to Reproduce
> Just view the VChart rendering result
> 
> ### Current Behavior
> <img alt="image" width="653" src="https://private-user-images.githubusercontent.com/31957644/298860549-067fed96-17f0-4af8-b8d0-f79aeceb0a86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDE4MzUsIm5iZiI6MTcwNjAwMTUzNSwicGF0aCI6Ii8zMTk1NzY0NC8yOTg4NjA1NDktMDY3ZmVkOTYtMTdmMC00YWY4LWI4ZDAtZjc5YWVjZWIwYTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNTIwOGM4MDEyYjVkOGJhMGE2YThmMmUxYzNlMjhkYTY2M2VjMTc0MWJmMmNmODk5OGJlZTlmMDYwZDk4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4nZw2x8L0XzkaLUGbc-LrBf2zHSEs8tDyGyRyM4rgPY">
> ### Expected Behavior
> <img alt="image" width="545" src="https://private-user-images.githubusercontent.com/31957644/298860247-01429605-62e4-409e-9f92-c65b1204c6c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDE4MzUsIm5iZiI6MTcwNjAwMTUzNSwicGF0aCI6Ii8zMTk1NzY0NC8yOTg4NjAyNDctMDE0Mjk2MDUtNjJlNC00MDllLTlmOTItYzY1YjEyMDRjNmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZTM2ZTZkNmU5NDVjMTA4NWIwNWRkMDkwODUzNzg3NzBmM2IyZDEyMTViMTkwNjA4ZTQ5NzlmMDA2MGJhZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.brABFFxm095vq7eVdpUDrDhIU0inZyjcwlOSnKshYFs">
> ### Environment
> _No response_
> 
> ### Any additional comments?
> Is there a problem with my configuration?
thank you for your feedback.  
region index error and bar has no layout space leads to the problem, i have fixed it with this mr: https://github.com/VisActor/VChart/pull/2118.  
it will be display correctly in the next version.
