### ISSUE TITLE
[Bug] sortDataByAxis 在双轴图时，轴的domain在第一个系列数据更新时还没有获取完成

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#2130]
### Version

1.8.8

### Link to Minimal Reproduction

null

### Steps to Reproduce

const spec = {
  "type": "common",
  "data": [
    {
      "values": [
        {
          "x": 1706059200,
          "y": 194,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706059500,
          "y": 183,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706059800,
          "y": 141,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706060100,
          "y": 146,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706060400,
          "y": 154,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706060700,
          "y": 169,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706061000,
          "y": 147,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706061300,
          "y": 171,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706061600,
          "y": 187,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706061900,
          "y": 168,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706062200,
          "y": 161,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706062500,
          "y": 158,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706062800,
          "y": 160,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706063100,
          "y": 176,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706063400,
          "y": 155,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706063700,
          "y": 158,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706064000,
          "y": 161,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706064300,
          "y": 167,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706064600,
          "y": 154,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706064900,
          "y": 171,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706065200,
          "y": 155,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706065500,
          "y": 197,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706065800,
          "y": 154,
          "dimension": "申诉量绝对值"
        },
        {
          "x": 1706066100,
          "y": 172,
          "dimension": "申诉量绝对值"
        }
      ],
      "id": "axisLeft"
    },
    {
      "values": [
        {
          "x": 1706052000,
          "y": 74,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706052300,
          "y": 61,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706052600,
          "y": 72,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706052900,
          "y": 85,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706053200,
          "y": 75,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706053500,
          "y": 88,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706053800,
          "y": 70,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706054100,
          "y": 72,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706054400,
          "y": 89,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706054700,
          "y": 64,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706055000,
          "y": 72,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706055300,
          "y": 95,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706055600,
          "y": 105,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706055900,
          "y": 89,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706056200,
          "y": 92,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706056500,
          "y": 100,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706056800,
          "y": 109,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706057100,
          "y": 93,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706057400,
          "y": 111,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706057700,
          "y": 134,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706058000,
          "y": 133,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706058300,
          "y": 172,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706058600,
          "y": 184,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706058900,
          "y": 172,
          "dimension": "申诉量近1个分区"
        },
        {
          "x": 1706059200,
          "y": 2,
          "dimension": "申诉量近1个分区"
        }
      ],
      "id": "axisRight"
    }
  ],
  "padding": {
    "top": 0,
    "bottom": 0,
    "left": 0,
    "right": 0
  },
  "series": [
    {
      "type": "line",
      "point": {
        "visible": false
      },
      "style": {
        "curveType": "monotone"
      },
      "xField": "x",
      "yField": [
        "y",
        "dimension"
      ],
      "seriesField": "dimension",
      "dataIndex": 0,
      sortDataByAxis: true
    },
    {

      "type": "line",
      "point": {
        "visible": false
      },
      "style": {
        "curveType": "monotone"
      },
      "xField": "x",
      "yField": [
        "y",
        "dimension"
      ],
      "seriesField": "dimension",
      "dataIndex": 1,
      sortDataByAxis: true
    }
  ],
  "tooltip": {
    "visible": true,
    "dimension": {
      "title": {}
    }
  },
  "legends": {
    "visible": true,
    "orient": "top",
    "position": "start",
    "padding": {
      "top": 0,
      "bottom": 12,
      "left": 0,
      "right": 0
    },
    "item": {
      "label": {
        "style": {
          "fill": "#1C1F23"
        }
      },
      "shape": {
        "style": {
          "symbolType": "rect"
        }
      }
    }
  },
  "axes": [
    {
      "id": "axisBottom",
      "orient": "bottom",
      "label": {
        "style": {
          "fontSize": 12,
          "fill": "#1C1F2399"
        }
      }
    },
    {
      "id": "axisLeft",
      "orient": "left",
      "seriesIndex": [
        0
      ],
      "label": {
        "style": {
          "fontSize": 12,
          "dx": 10,
          "lineHeight": 16,
          "fill": "#1C1F2399"
        }
      },
      "visible": true
    },
    {
      "id": "axisRight",
      "orient": "right",
      "gird": {
        "visible": false
      },
      "nice": false,
      "zero": false,
      "sync": {
        "axisId": "axisLeft",
        "tickAlign": true
      },
      "seriesIndex": [
        1
      ],
      "label": {
        "style": {
          "fontSize": 12,
          "dx": 10,
          "lineHeight": 16,
          "fill": "#1C1F2399"
        }
      },
      "visible": true
    }
  ]
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/15776277/f882d35a-6463-40a3-abc8-b3cd8f59ab03)

### Expected Behavior

![image](https://github.com/VisActor/VChart/assets/15776277/a155f157-b3c0-41e0-97e5-a5b2fe2af300)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
还有一个在双轴图中，`sortDataByAxis` 没有生效的问题，spec如下：

```js
const spec = {
  type: 'common',
  seriesField: 'color',
  data: [
    {
      id: 'id0',
      values: [
        { x: '周一', type: '早餐', y: 15 },
        { x: '周一', type: '午餐', y: 25 },
        { x: '周二', type: '早餐', y: 12 },
        { x: '周二', type: '午餐', y: 30 },
        { x: '周三', type: '午餐', y: 24 },
        { x: '周三', type: '早餐', y: 15 },
        { x: '周四', type: '早餐', y: 10 },
        { x: '周四', type: '午餐', y: 25 },
        { x: '周五', type: '早餐', y: 13 },
        { x: '周五', type: '午餐', y: 20 },
        { x: '周六', type: '早餐', y: 10 },
        { x: '周六', type: '午餐', y: 22 },
        { x: '周日', type: '早餐', y: 12 },
        { x: '周日', type: '午餐', y: 19 }
      ],
       fields: {
        'x': {
          type: 'ordinal',
           sortIndex: 0
        },
        'type': {
           type: 'ordinal',
           sortIndex: 1
        }
      }
    },
    {
      id: 'id1',
      values: [
        { x: '周一', type: '饮料', y: 22 },
        { x: '周二', type: '饮料', y: 43 },
         { x: '周五', type: '饮料', y: 10 },
        { x: '周三', type: '饮料', y: 33 },
        { x: '周四', type: '饮料', y: 22 },
        { x: '周六', type: '饮料', y: 30 },
        { x: '周日', type: '饮料', y: 50 }
      ]
    }
  ],
  series: [
    {
      type: 'bar',
      dataIndex: 0,
      label: { visible: true },
      seriesField: 'type',
      dataIndex: 0,
      xField: 'x',
      yField: 'y',
      stack: true
    },
    {
      type: 'line',
      dataIndex: 1,
      label: { visible: true },
      seriesField: 'type',
      xField: 'x',
      yField: 'y',
      stack: false,
      sortDataByAxis: true
    }
  ],
  axes: [{ orient: 'left' }, { orient: 'bottom', label: { visible: true }, type: 'band' }],
  legends: {
    visible: true,
    orient: 'bottom'
  }
};
```
