### ISSUE TITLE
使用taro编译的微信小程序,  @visactor/taro-vchart 包太大了, 期待有解决办法

### ISSUE THREAD

**Issue by schrodingere57** [VisActor/VChart#2157]
![22222](https://github.com/VisActor/VChart/assets/137301152/e51d0194-a377-4d9a-b00d-90c16e0f71f0)

**Comment by FTD-ZF** [comment]
同问

**Comment by benson0801** [comment]
解决了吗？

**Comment by xiaoluoHe** [comment]
> 解决了吗？

目前还没有，这段时间还没有腾出精力处理。

后续的话，我们会考虑在 taro-vchart 中支持按需加载来减轻包体积的问题。顺利的话，大约年后我们会开始着手开始这个优化。

对于整包体积来说，优化会是一个持续且收效缓慢的过程，我们后续会考虑将一些非常用图表，从主包中移出去，作为单独的图表包提供。

各位如果有想法和时间，也欢迎一起共建 🌹

**Comment by FTD-ZF** [comment]
目前 使用 taro-react-echarts，可以自行选择图表资源进行下载，整体项目打包后的大小增加了550KB，暂时在接受范围内

**Comment by schrodingere57** [comment]
同上，目前使用taro编译的小程序用 taro-react-echarts， 自行选择图表资源进行下载,也可以用原生混合的方式使用echarts先用着先

**Comment by benson0801** [comment]
> 目前 使用 taro-react-echarts，可以自行选择图表资源进行下载，整体项目打包后的大小增加了550KB，暂时在接受范围内

好的，目前已用taro-f2-react解决了，感谢

**Comment by schrodingere57** [comment]
在taro编译的小程序中使用图表：                                                                                                                                                         
 1、可以去taro的物料市场看一下，像上述的taro-react-echarts、taro-f2-reac等；                        
 2、使用原生混合开发：https://ovyvo.github.io/yanblog.github.io/2021/10/18/blog/、https://ovyvo.github.io/yanblog.github.io/2021/10/19/blog4/、https://taro-docs.jd.com/docs/hybrid、                                                             3、使用webview组件跳转到H5,H5承载的内容就是图表

**Comment by xiaoluoHe** [comment]
1.10.x 起， taro-vchart 支持按需加载，参考文档 [Load on demand](https://visactor.bytedance.net/vchart/guide/tutorial_docs/Load_on_Demand)
另外，我们也在规划站点自定义打包功能  @purpose233 
![image](https://github.com/VisActor/VChart/assets/11360419/fc29a6d2-f4b8-43e6-bede-8717b8440c32)
