### ISSUE TITLE
[doc] 微信小程序文档添加 按需打包指引

### ISSUE THREAD

**Issue by xuanhun** [VisActor/VChart#2192]
### Version

1.9.0

### Link to Minimal Reproduction

https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/mini-app/wx

### Steps to Reproduce

https://www.visactor.io/vchart/guide/tutorial_docs/Progressive_Render?version=1.9.0

### Current Behavior

没有关于如何进行按需打包的说明

### Expected Behavior

添加按需打包的说明
![image](https://github.com/VisActor/VChart/assets/2384516/5b1f8a61-829b-48c0-8c0d-f612da24d4d5)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by L1f3-15-a-kn1f3** [comment]
+1

**Comment by xile611** [comment]
> +1

taro-vchart 1.12.0 已经默认支持按需加载，可以考虑使用taro-vchart 吗

**Comment by xile611** [comment]
taro-vchart 按需加载相关文档： https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/taro

**Comment by wuhongdan** [comment]
> taro-vchart 按需加载相关文档： https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/taro

这个文档一点都不清晰呀，有没有完整的按需加载代码示例呀？
