### ISSUE TITLE
[Bug] vchart and vrender type error when build

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#2207]
### Version

1.8.9

### Link to Minimal Reproduction

null

### Steps to Reproduce

use vite and run npm run build:dev
here is the tsconfig.json:
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
        "strictNullChecks": false,
        "noEmitOnError": false,
    "jsx": "react"
  },
  "include": ["./src"]
}

### Current Behavior

![img_v3_027m_e0bd15eb-bac8-4953-9291-8fd1ee0c9a7g](https://github.com/VisActor/VChart/assets/20367445/b0ed5cde-a0f1-44bf-a99c-a8a569df5983)
![img_v3_027m_409abbaf-f336-498b-8894-c72bceb9191g](https://github.com/VisActor/VChart/assets/20367445/a26c1da5-a807-4513-a66b-512670f9689e)

### Expected Behavior

build successfully with no type error.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
vchart 及底层库采用的 tsconfig 没有当前项目严格，导致一些编译报错。
可以配置 `skipLibCheck: true` 跳过 lib type check
