### ISSUE TITLE
轴标签内容格式化后折线有偏移的效果

### ISSUE THREAD

**Issue by nianba23** [VisActor/VChart#2214]
```
spec.axes[0].label.formatMethod = (val, datum) => {
    return `¥${val.toFixed(0)}`;
},
```

<img width="363" alt="image" src="https://github.com/VisActor/VChart/assets/39176194/0f3c28b1-9b92-4485-9e48-2663c88b3216">

**Comment by xile611** [comment]
@nianba23 提交bug的时候，请给一下完整的spec，方便大家复现问题呢，感谢你的配置🙏

**Comment by xile611** [comment]
@nianba23 鉴于之前提交的bug都没法复现，希望能够提供最小复现demo，不然没法排查问题
谢谢你的配合
你可以重新开一个新的issue，提供最小复现demo 的项目，能够让我们导入到飞书小程序直接联调

**Comment by nianba23** [comment]
@xile611  偏移指的是会出现比较明显的过渡效果，完整代码关联此 issue: https://github.com/VisActor/VChart/issues/2206

**Comment by nianba23** [comment]
希望updateSpec时这个偏移的过渡效果不要这么明显
