### ISSUE TITLE
[Bug] MarkPoint will not be released after updateSpec

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#223]
### Version

latest

### Link to Minimal Reproduction

none

### Steps to Reproduce

1. config a markpoint in chart spec
2. render chart
3. remove markpoint in spec
4. updateSpec

### Current Behavior

markPoint will still show in chart after calling updateSpec

### Expected Behavior

1. release markPoint
2. check if markPoint/markLine/markArea has the same problem

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by skie1997** [comment]
fixed in https://github.com/VisActor/VChart/pull/213

**Comment by skie1997** [comment]
fixed in https://github.com/VisActor/VChart/pull/213
