### ISSUE TITLE
[Bug] react-vchart render error after toggling direction

### ISSUE THREAD

**Issue by purpose233** [VisActor/VChart#2241]
### Version

1.9.3

### Link to Minimal Reproduction

null

### Steps to Reproduce

https://webide.bytedance.net/s/form.watch-oerwq6a4?file=/src/App.tsx

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/14228496/7794bd0e-cee7-48e7-b00c-532d0a3dec13)

### Expected Behavior

![image](https://github.com/VisActor/VChart/assets/14228496/3ccd3ecf-cb25-4579-88d4-5e702e598fcc)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
试了下，不是react-vchart 的bug，vchart updateSpec() 后，有问题
