### ISSUE TITLE
[Bug] ResizeObserver兼容性问题

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#2281]
### Version

latest

### Link to Minimal Reproduction

-

### Steps to Reproduce

用户浏览器环境：
User Agent：Mozilla/5.0 (X11; Linux aarch64; rv:68.0) Gecko/20100101 Firefox/68.0
VChart报错：
![image](https://github.com/VisActor/VChart/assets/25134429/3063c7fb-dfb0-4648-84e4-f1bc7545c7b8)
![image](https://github.com/VisActor/VChart/assets/25134429/cfd7249f-e9be-4583-a856-3219833a86a4)

查询兼容性：
![M6vFU2mVYE](https://github.com/VisActor/VChart/assets/25134429/f5c49ce9-8df6-4514-9a2a-14966c2d072a)

Firefox在69.0版本完整支持ResizeObserver，用户使用的是68版本，应该是报错的原因

### Current Behavior

没有兼容低版本浏览器

### Expected Behavior

兼容低版本浏览器

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
该浏览器版本比较落后，vchart不默认引入 polyfill
让用户根据产品需求，提示用户升级浏览器 或者 引入polyfill

**Comment by Rui-Sun** [comment]
![img_v3_028g_11c08a0b-aef8-4633-8d86-b79a0dc9e0eg](https://github.com/VisActor/VChart/assets/25134429/29081387-336c-4eee-8fe5-423e23c11a6a)
增加resizeObserve的判断，没有resizeObserve的话就不创建observe，避免旧版本浏览器报错
