### ISSUE TITLE
[Bug] 双图表 hover 联动效果不理想

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#2311]
### Version

latest

### Link to Minimal Reproduction

-

### Steps to Reproduce

import "./style.css";
import { default as VChart } from "@visactor/vchart";

const data = {
  values: [
    { type: "0", country: "Africa", value: 4229 },
    { type: "0", country: "EU", value: 4376 },
    { type: "1", country: "Africa", value: 3932 },
    { type: "1", country: "EU", value: 3987 },
    { type: "2", country: "Africa", value: 5221 },
    { type: "2", country: "EU", value: 3574 },
    { type: "3", country: "Africa", value: 9256 },
    { type: "3", country: "EU", value: 4376 },
    { type: "4", country: "Africa", value: 3308 },
    { type: "4", country: "EU", value: 4572 },
    { type: "5", country: "Africa", value: 5432 },
    { type: "5", country: "EU", value: 3417 },
  ],
};

const spec1 = {
  type: "line",
  data,
  title: {
    visible: true,
    text: "Stacked area chart of cosmetic products sales",
  },
  stack: true,
  xField: "type",
  yField: "value",
  seriesField: "country",
  legends: [{ visible: true, position: "middle", orient: "bottom" }],
};

const spec2 = {
  type: "line",
  data,
  title: {
    visible: true,
    text: "Stacked area chart of cosmetic products sales",
  },
  stack: true,
  xField: "type",
  yField: "value",
  seriesField: "country",
  legends: [{ visible: true, position: "middle", orient: "bottom" }],
};

function throttle(fn, delay) {
  return (args) => {
    if (fn.id) return;

    fn.id = setTimeout(() => {
      fn.call(this, args);
      clearTimeout(fn.id);
      fn.id = null;
    }, delay);
  };
}

const vchart1 = new VChart(spec1, { dom: "container1" });
vchart1.renderAsync();

const vchart2 = new VChart(spec2, { dom: "container2" });
vchart2.renderAsync();

vchart1.on("dimensionHover", (params) => {
  if (!params.dimensionInfo[0]) {
    return;
  }
  const { value } = params.dimensionInfo[0];
  vchart2.setDimensionIndex(value, {
    tooltip: true,
  });
});

vchart2.on("dimensionHover", (params) => {
  if (!params.dimensionInfo[0]) {
    return;
  }
  const { value } = params.dimensionInfo[0];
  vchart1.setDimensionIndex(value, {
    tooltip: true,
  });
});

### Current Behavior

https://github.com/VisActor/VChart/assets/25134429/a0db1dea-593e-48fa-b859-ca5767dc8bf1

### Expected Behavior

流畅联动

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by zamhown** [comment]
之前为了避免多图表场景多 tooltip 同时存在的情况，全局默认只保留一个 tooltip，可以通过以下方法关闭：
```
VChart.globalConfig.uniqueTooltip = false;
```

后面考虑把默认值改成 false？
