### ISSUE TITLE
[Bug] 当图形在入场动画阶段时，调整容器大小，图元位置未更新

### ISSUE THREAD

**Issue by webiamcome** [VisActor/VChart#2390]
### Version

1.10.0&1.9.6&...

### Link to Minimal Reproduction

https://visactor.io/vchart/demo/storytelling/bar-oneByOne-group?version=1.9.6

### Steps to Reproduce

1、切换版本，在入场动画过程中，点击全屏按钮，即可复现
![image](https://github.com/VisActor/VChart/assets/20121525/389c6925-8207-4df5-a1d6-7212c2be2332)

![image](https://github.com/VisActor/VChart/assets/20121525/899ee8f0-aaa4-4546-a217-d1f7369e6129)

### Current Behavior

1、切换版本，在入场动画过程中，点击全屏按钮，即可复现
![image](https://github.com/VisActor/VChart/assets/20121525/6e00b308-59aa-47ff-9a57-8947c1c9947f)

![image](https://github.com/VisActor/VChart/assets/20121525/899ee8f0-aaa4-4546-a217-d1f7369e6129)

### Expected Behavior

在入场动画阶段，调整容器大小，图表正常适配

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by webiamcome** [comment]
1.10.0 会出现图元消失的效果。
复现步骤还是在入场动画时，改变容器大小
![image](https://github.com/VisActor/VChart/assets/20121525/2b55a152-a931-441b-b962-93b433594c79)

**Comment by webiamcome** [comment]
> @webiamcome 1.9.7 和 1.10.0 应该已经修复了这个问题，你刷新一下浏览器缓存，1.10.0出问题应该是有缓存

1.10.0 会出现图元消失的效果。
复现步骤还是在入场动画时，改变容器大小
![image](https://github.com/VisActor/VChart/assets/20121525/9a1a95d8-846d-4c28-b094-a66f6b22e765)

**Comment by xile611** [comment]
> https://visactor.io/vchart/demo/storytelling/bar-oneByOne-group?version=1.9.6

复现了，我们排查一下看看那

**Comment by purpose233** [comment]
https://github.com/VisActor/VGrammar/pull/417
