### ISSUE TITLE
我想可视化数据的min/max/sum/bin，是否只能使用visactor-dataset，如何在react里引用dataset呢

### ISSUE THREAD

**Issue by heyi11** [VisActor/VChart#2413]
data: {
          values: data.values,
          transforms:[
            {
            type: 'statistics',
            option: {
              fields: [yField],
              operations: 'average',
              as:'avg',
              groupby:[xField]
           
          }}],}我想计算average，直接在spec里配置transform并不好使，是否一定需要dataview.transform呢？react框架怎么使用dataset呢

**Comment by xile611** [comment]
@heyi11 可以自己处理好数据，传入到spec中，不一定要使用 dataview.transform

**Comment by heyi11** [comment]
> @heyi11可以自己处理好数据，整理到spec中，不一定要使用dataview.transform

那vchart有什么能算min/max的接口吗？不想再二次处理了:(，我看Vgrammar有类似的功能，vgrammar和vchart能混用吗

**Comment by xile611** [comment]
> > @heyi11可以自己处理好数据，整理到spec中，不一定要使用dataview.transform
> 
> 那vchart有什么能算min/max的接口吗？不想再二次处理了:(，我看Vgrammar有类似的功能，vgrammar和vchart能混用吗

不知道你具体要实现什么功能，希望能够完整描述你的问题和场景，这样能够更加高效

**Comment by heyi11** [comment]
> > > @heyi11可以自己处理好数据，整理到spec中，不一定要使用dataview.transform
> > 
> > 
> > 那vchart有什么能算min/max的接口吗？不想再二次处理了:(，我看Vgrammar有类似的功能，vgrammar和vchart能混用吗
> 
> 不知道你具体要实现什么功能，希望能够完整描述你的问题和场景，这样能够更加高效


/**
 * 至此，dataViewMerge 数据处理已经完成了。
 * 最终数据的内容如下
  [
    { year: '1990', group: '18-34', value: 16.9 },
    { year: '1990', group: '35-49', value: 12.2 },
    { year: '1991', group: '18-34', value: 17 },
    { year: '1991', group: '35-49', value: 17.8 },
    { year: '1993', group: '18-34', value: 26.5 },
    { year: '1993', group: '35-49', value: 23.8 },
    { year: '1990', group: '50-64', value: 10.2 },
    { year: '1990', group: '65+', value: 5.2 },
    { year: '1991', group: '50-64', value: 10 },
    { year: '1991', group: '65+', value: 4.8 },
    { year: '1993', group: '50-64', value: 16.8 },
    { year: '1993', group: '65+', value: 6.6 }
  ]
*/

// 创建平均值数据 令它引用 dataViewMerge
const dataViewAvg = new DataView(dataSet, { name: 'dataViewAvg' });
dataViewAvg.parse([dataViewMerge], { type: 'dataview' });
// 内置的 copy transform。从依赖的 dataView 上浅拷贝数据，只会重新创建数据数组，数据对象不变。
dataViewAvg.transform({ type: 'copyDataView' });
// 此时 dataViewAvg 与 dataViewMerge 中的数据内容相同
// 内置的 statistics transform 可以生成统计数据
dataViewAvg.transform({
  type: 'statistics'
  option: {
    fields: ['value'],
    operations: ['average'],
    as: ['avg'],
    groupBy: 'year'
  }
});
/**
 * 至此，dataViewAvg 数据处理已经完成了
 * 最终数据的内容如下
  [
    { year: '1990', group: '18-34', value: 11.125 },
    { year: '1991', group: '18-34', value: 12.4 },
    { year: '1993', group: '18-34', value: 18.425 },
  ]
export interface IStatisticsOptions {
    fields: string[];
    operations: Array<'count' | 'max' | 'min' | 'mean' | 'average' | 'median' | 'mode' | 'product' | 'standardDeviation' | 'sum' | 'sumSimple' | 'variance'>;
    as?: string[];
    groupBy?: string;
}
const statisticsTransform = (data: string, option: IStatisticsOptions) => {
  /** ...*/
};
// 先对 transform 进行注册
dataSet.registerTransform('statistics', statisticsTransform);
// 使用
dataView.transform({
  type: 'statistics'
  option: {
    fields: ['year'],
    operations: ['average'],
    as: ['avg'],
    groupBy: 'group'
  }
});
*/可以看这段示例代码，我想实现的就是这样的功能，但是实际上我看这段代码需要输入字符串，然后用parser去解析，我的输入就是vchart最常见的json格式，并且我使用的是react，因此不知道怎么样导入vchart-dataset，也不知道能不能直接在spec里配置使用，以下是我的尝试的代码
onst spec = {
        type: 'bar3d',
        data: {
          values: data.values,
          transforms:[
            {
              type: 'statistics',
              options: {
                fields: yField,
                operations: 'average',
                as:'avg',
                groupby:xField
              }
            }
          ],
...
}

**Comment by xile611** [comment]
@heyi11 github 答复是支持markdown的，格式都乱掉了 。。。。

**Comment by heyi11** [comment]
> @heyi11 github 答复是支持markdown的，格式都乱掉了 。。。。

抱歉抱歉，我还不太熟练:(，这样子表达有清晰一点吗:)

## 我的需求：对数据进行统计，得到一份平均值/最大值/最小值....数据
### 数据格式：json
### 开发生态：react

![微信截图_20240320115618](https://github.com/VisActor/VChart/assets/65163361/a129af8a-f2b2-4f69-b9dd-2be7d6c60de6)

### 我的困惑：可以看这段示例代码，就是我想实现的功能。但是实际上我看这段代码需要输入字符串，然后用parser去解析，而我的输入就是vchart最常见的json格式，并且我使用的是react。因此不知道怎么样导入vchart-dataset，也不知道能不能直接在spec里配置使用。

### 我的尝试：

 
![2](https://github.com/VisActor/VChart/assets/65163361/a6ba2ae4-06c0-4f00-89c1-89ae3396cd9e)

**Comment by xile611** [comment]
@heyi11 `@visactor/vdataset` 是一个单独的包: https://www.npmjs.com/package/@visactor/vdataset
可以npm引用这个包

**Comment by xile611** [comment]
```js
const values = [
        { month: 'Monday', sales: 22 },
        { month: 'Tuesday', sales: 13 },
        { month: 'Wednesday', sales: 25 },
        { month: 'Thursday', sales: 29 },
        { month: 'Friday', sales: 38 }
      ];

const spec = {
  type: 'bar',
  data: [
    {
      id: 'barData',
      values
    },
    {
      id: 'avg',
      values,
      transform: [{
        type: 'statistics',
        option: {
          fields: ['sales'],
          operations: ['average'],
          as: ['avg']
        }
      }]
    }
  ],
  xField: 'month',
  yField: 'sales'
};
```

或者你也可以按照上面的方法，创建两个数据

**Comment by heyi11** [comment]
@xile611 

感谢您的回复，我尝试了一下
```js
const values = [
        { month: 'Monday', sales: 22 },
        { month: 'Tuesday', sales: 13 },
        { month: 'Wednesday', sales: 25 },
        { month: 'Thursday', sales: 29 },
        { month: 'Friday', sales: 38 },
        { month: 'Monday', sales: 42 },
        { month: 'Tuesday', sales: 43 },
        { month: 'Wednesday', sales: 45 },
        { month: 'Thursday', sales: 49 },
        { month: 'Friday', sales: 48 }
      ];

const spec = {
  
  data: [
    {
      id: 'barData',
      values
    },
    {
      id: 'avg',
      values,
      transform: [{
        type: 'statistics',
        option: {
          fields: ['sales'],
          operations: ['average'],
          as: ['avg'],
          groupby:['month']
        }
      }]
    }
  ],
  type: 'bar',
  dataIndex:1,
  xField: 'month',
  yField: 'sales'
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

```
![3](https://github.com/VisActor/VChart/assets/65163361/ce3bba6c-13e9-443f-9eb6-16fe02233ef2)

但他并没有得到我想要的 （22+42）/2这种average，而是简单的把两个monday的数据都列上去了，所以我的疑问是

1. transform: [{type: 'statistics', 这个方式是生效的吗？
2.如果我想使用dataset里的parser，可以传入json吗，我看目前的文档只能传入csv

**Comment by xile611** [comment]
@heyi11 确认了一下代码逻辑，这块确实还不完善，不支持在spec中的使用
可以考虑直接引用 `@visactor/vdataset` 包，或者自己处理这块数据逻辑

**Comment by heyi11** [comment]
> @heyi11确认逻辑代码逻辑，这块确实不够完善，不支持在spec中的使用 可以考虑直接引用`@visactor/vdataset`包，或者自己处理这块数据逻辑


谢谢！已经使用@visactor/vdataset包解决了，您真的很耐心，感激！希望vchart能完善spec的数值分析功能~

**Comment by xile611** [comment]
> > @heyi11确认逻辑代码逻辑，这块确实不够完善，不支持在spec中的使用 可以考虑直接引用`@visactor/vdataset`包，或者自己处理这块数据逻辑
> 
> 谢谢！已经使用@visactor/vdataset包解决了，您真的很耐心，感激！希望vchart能完善spec的数值分析功能~

OK，我们会重新梳理一下这块的功能
