### ISSUE TITLE
如何获取3d chart的canvas元素？

### ISSUE THREAD

**Issue by tacit0428** [VisActor/VChart#2416]
<img width="470" alt="image" src="https://github.com/VisActor/VChart/assets/26201291/e50cb9c5-aa71-4638-b732-a05073dc159e">

我在使用react-vchart，发现渲染后的chart的dom元素是一个div包着一个canvas，我想在chart组件渲染后获取这个canvas，但是在componentdidiupdate或componentdidmount中通过document.getElementsByClassName('chartcanvas-0')[0]?.childNodes[0]获取为undefined，但可以通过document.getElementsByClassName('chartcanvas-0')[0]获取外层div。不知道怎么才能获取这个canvas

**Comment by xile611** [comment]
> <img alt="image" width="470" src="https://private-user-images.githubusercontent.com/26201291/313934315-e50cb9c5-aa71-4638-b732-a05073dc159e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzA2NzcsIm5iZiI6MTcxMDgzMDM3NywicGF0aCI6Ii8yNjIwMTI5MS8zMTM5MzQzMTUtZTUwY2I5YzUtYWE3MS00NjM4LWI3MzItYTA1MDczZGMxNTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNGVkYjY1NmU2Nzk2MjZkZDBjMDZhYzdhOWZkZmQxODBkZmU0NjhlMmNjMmFmODQ5NmEwYTJkOTAxOGNiOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0k8v69K8dBo8vs59DgVxHDoyAFOy4Iu6fRsLJWp1UHU">
> 我在使用react-vchart，发现渲染后的chart的dom元素是一个div包着一个canvas，我想在chart组件渲染后获取这个canvas，但是在componentdidiupdate或componentdidmount中通过document.getElementsByClassName('chartcanvas-0')[0]?.childNodes[0]获取为undefined，但可以通过document.getElementsByClassName('chartcanvas-0')[0]获取外层div。不知道怎么才能获取这个canvas

@tacit0428 为什么要获取canvas ？不推荐获取canvas
