### ISSUE TITLE
bar3d，排序错误

### ISSUE THREAD

**Issue by heyi11** [VisActor/VChart#2422]
fields: {
            [sortXField]: {
              sortIndex: 1,
              sortReverse: sortXBoolean
            },
            [sortYField]: {
              sortIndex: 1,
              sortReverse: sortYBoolean
            }
          }
        }，如图，我使用sortReverse对3d柱状图进行排序，发现它并不是完全按照大小排序，有问题
![1](https://github.com/VisActor/VChart/assets/65163361/4c353ef8-1217-453c-81b2-92d70483a1f0)
![2](https://github.com/VisActor/VChart/assets/65163361/2b19ba1c-d0d7-4927-9c60-ad033937ae14)

**Comment by xile611** [comment]
@heyi11  请提供一下能够复现问题的在线示例？减小我们排查问题的时间成本

**Comment by heyi11** [comment]
> @heyi11 请提供一下能够复现问题的在线示例？ 减少我们排查问题的时间成本
麻烦了，应该是我这边堆叠的数据，他没法直接排序，已经解决了，谢谢！
