### ISSUE TITLE
饼形图的图例第二列的标题怎么设置啊?

### ISSUE THREAD

**Issue by Zardw** [VisActor/VChart#2425]
如图, 这个标题怎么设置, 看了半天文档, 还是不知道怎么弄, 求解,谢谢!!

![image](https://github.com/VisActor/VChart/assets/117419340/7e7c50ce-0cde-4f63-8eb7-2d4d7487dd15)

**Comment by xile611** [comment]
@Zardw 暂时不支持

**Comment by Zardw** [comment]
那他们是咋弄的, P上去的吗

**Comment by xile611** [comment]
> @xile611 那他们是咋弄的, P上去的吗

@Zardw 可能是通过react  或者 dom 定位实现的

**Comment by Zardw** [comment]
飞书工作台小组件里面的, 你们的图形都在Canvas里面, 操作不了吧

**Comment by xile611** [comment]
> 飞书工作台小组件里面的, 你们的图形都在Canvas里面, 操作不了吧

用dom定位上去的吧
