### ISSUE TITLE
[Bug] 在 stage 上监听事件，在事件中同步更新vchartSpec，会有报错

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#2429]
### Version

1.10.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

const spec = {
  type: 'bar',
  data: {
    values: [
      { type: 'Nail polish', country: 'Africa', value: 4229 },
      { type: 'Nail polish', country: 'EU', value: 4376 },
      { type: 'Nail polish', country: 'China', value: 3054 },
      { type: 'Nail polish', country: 'USA', value: 12814 },
      { type: 'Eyebrow pencil', country: 'Africa', value: 3932 },
      { type: 'Eyebrow pencil', country: 'EU', value: 3987 },
      { type: 'Eyebrow pencil', country: 'China', value: 5067 },
      { type: 'Eyebrow pencil', country: 'USA', value: 13012 },
      { type: 'Rouge', country: 'Africa', value: 5221 },
      { type: 'Rouge', country: 'EU', value: 3574 },
      { type: 'Rouge', country: 'China', value: 7004 },
      { type: 'Rouge', country: 'USA', value: 11624 },
      { type: 'Lipstick', country: 'Africa', value: 9256 },
      { type: 'Lipstick', country: 'EU', value: 4376 },
      { type: 'Lipstick', country: 'China', value: 9054 },
      { type: 'Lipstick', country: 'USA', value: 8814 },
      { type: 'Eyeshadows', country: 'Africa', value: 3308 },
      { type: 'Eyeshadows', country: 'EU', value: 4572 },
      { type: 'Eyeshadows', country: 'China', value: 12043 },
      { type: 'Eyeshadows', country: 'USA', value: 12998 }
    ]
  },
  xField: ['type', 'country'],
  yField: 'value',
  seriesField: 'country',
  animation: false,
  axes: [
    {
      orient: 'left',
    },
    {
      orient: 'bottom',
      paddingInner: [0.5,0],
      paddingOuter: [0.5,0],
    }
  ]
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });

vchart.renderSync();

// vchart.on('pointerup',()=>{
//   console.log('pointerup1')
// })

vchart.getStage().on('pointerup',()=>{
  vchart.updateSpecSync(
    {
  type: 'bar',
  data: {
    values: [
      { type: 'Nail polish', country: 'Africa', value: 4229 },
      { type: 'Nail polish', country: 'EU', value: 4376 },
      { type: 'Nail polish', country: 'China', value: 3054 },
      { type: 'Nail polish', country: 'USA', value: 12814 },
      { type: 'Eyebrow pencil', country: 'Africa', value: 3932 },
      { type: 'Eyebrow pencil', country: 'EU', value: 3987 },
      { type: 'Eyebrow pencil', country: 'China', value: 5067 },
      { type: 'Eyebrow pencil', country: 'USA', value: 13012 },
      { type: 'Rouge', country: 'Africa', value: 5221 },
      { type: 'Rouge', country: 'EU', value: 3574 },
      { type: 'Rouge', country: 'China', value: 7004 },
      { type: 'Rouge', country: 'USA', value: 11624 },
      { type: 'Lipstick', country: 'Africa', value: 9256 },
      { type: 'Lipstick', country: 'EU', value: 4376 },
      { type: 'Lipstick', country: 'China', value: 9054 },
      { type: 'Lipstick', country: 'USA', value: 8814 },
      { type: 'Eyeshadows', country: 'Africa', value: 3308 },
      { type: 'Eyeshadows', country: 'EU', value: 4572 },
      { type: 'Eyeshadows', country: 'China', value: 12043 },
      { type: 'Eyeshadows', country: 'USA', value: 12998 }
    ]
  },
  xField: ['type', 'country'],
  yField: 'value',
  seriesField: 'country',
  animation: false,
  axes: [
        {
          orient: 'left',
        },
        {
          orient: 'bottom',
          paddingInner: [Math.random() * 0.1 + 0.4,0],
          paddingOuter: [0.5,0],
        }
      ]
    }
  )
})

// vchart.on('pointerup',()=>{
//   console.log('pointerup2')
// })

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/15776277/a3b49c86-6d1c-41a8-a66b-eda80c0b741d)

### Expected Behavior

不报错

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
Fixed in v1.10.3
