### ISSUE TITLE
[Bug] 柱状图下axes设置为time后渲染异常

### ISSUE THREAD

**Issue by fzxbl** [VisActor/VChart#2447]
### Version

1.10.0

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/eloquent-wilson-l6992p?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu2kxi7w00073p6m150s5x4d%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu2kxi7v00033p6mrih54ljx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu2kxi7v00043p6mljhjze81%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu2kxi7w00063p6m2yec2qqb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu2kxi7v00033p6mrih54ljx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2kxi7v00023p6mz87fla9f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clu2kxi7v00033p6mrih54ljx%2522%252C%2522activeTabId%2522%253A%2522clu2kxi7v00023p6mz87fla9f%2522%257D%252C%2522clu2kxi7w00063p6m2yec2qqb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2kxi7v00053p6mxcg564ac%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu2kxi7w00063p6m2yec2qqb%2522%252C%2522activeTabId%2522%253A%2522clu2kxi7v00053p6mxcg564ac%2522%257D%252C%2522clu2kxi7v00043p6mljhjze81%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu2kxi7v00043p6mljhjze81%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
```
const spec = {
  type: 'bar',
  data: [
    {
      id: 'barData',
      values: [
        {
          month: 1711062314,
          sales: 8,
        },
        {
          month: 1711062374,
          sales: 16,
        },
        {
          month: 1711062434,
          sales: 24,
        },
        {
          month: 1711062494,
          sales: 19,
        },
        {
          month: 1711062554,
          sales: 23,
        },
        {
          month: 1711062614,
          sales: 44,
        },
        {
          month: 1711062674,
          sales: 84,
        },
        {
          month: 1711062734,
          sales: 60,
        },
        {
          month: 1711062794,
          sales: 46,
        },
        {
          month: 1711062854,
          sales: 27,
        },
      ]
    }
  ],
  xField: 'month',
  yField: 'sales',
  axes:[
    {
      type: "time",
      orient: "bottom",
      layers: [
        {
          tickStep: 300,
          timeFormat: "%H:%M",
        },
        {
          tickStep: 86400,
          timeFormat: "%m/%d",
        },
      ],
    },
  ],
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// 只为了方便控制台调试用，不要拷贝
window['vchart'] = vchart;

```

### Steps to Reproduce

当axes设置orient:bottom后柱状图显示不正常，移除orient后，layers不生效

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/31810871/d0f3cf9f-0267-4cda-a16b-aa64b8df0254)

### Expected Behavior

时间轴和柱状图均显示正确
<img width="1103" alt="image" src="https://github.com/VisActor/VChart/assets/31810871/aed193a7-2bdc-4bf5-9579-6e7804104d8f">

### Environment

```markdown
- OS: macOS
- Browser: Edge
- Framework: react + nextJs
```

**Comment by skie1997** [comment]
> ### Version
> 1.10.0
> 
> ### Link to Minimal Reproduction
> https://codesandbox.io/p/sandbox/eloquent-wilson-l6992p?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu2kxi7w00073p6m150s5x4d%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu2kxi7v00033p6mrih54ljx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu2kxi7v00043p6mljhjze81%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu2kxi7w00063p6m2yec2qqb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu2kxi7v00033p6mrih54ljx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2kxi7v00023p6mz87fla9f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clu2kxi7v00033p6mrih54ljx%2522%252C%2522activeTabId%2522%253A%2522clu2kxi7v00023p6mz87fla9f%2522%257D%252C%2522clu2kxi7w00063p6m2yec2qqb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2kxi7v00053p6mxcg564ac%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu2kxi7w00063p6m2yec2qqb%2522%252C%2522activeTabId%2522%253A%2522clu2kxi7v00053p6mxcg564ac%2522%257D%252C%2522clu2kxi7v00043p6mljhjze81%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu2kxi7v00043p6mljhjze81%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
> 
> ```
> const spec = {
>   type: 'bar',
>   data: [
>     {
>       id: 'barData',
>       values: [
>         {
>           month: 1711062314,
>           sales: 8,
>         },
>         {
>           month: 1711062374,
>           sales: 16,
>         },
>         {
>           month: 1711062434,
>           sales: 24,
>         },
>         {
>           month: 1711062494,
>           sales: 19,
>         },
>         {
>           month: 1711062554,
>           sales: 23,
>         },
>         {
>           month: 1711062614,
>           sales: 44,
>         },
>         {
>           month: 1711062674,
>           sales: 84,
>         },
>         {
>           month: 1711062734,
>           sales: 60,
>         },
>         {
>           month: 1711062794,
>           sales: 46,
>         },
>         {
>           month: 1711062854,
>           sales: 27,
>         },
>       ]
>     }
>   ],
>   xField: 'month',
>   yField: 'sales',
>   axes:[
>     {
>       type: "time",
>       orient: "bottom",
>       layers: [
>         {
>           tickStep: 300,
>           timeFormat: "%H:%M",
>         },
>         {
>           tickStep: 86400,
>           timeFormat: "%m/%d",
>         },
>       ],
>     },
>   ],
> };
> 
> const vchart = new VChart(spec, { dom: CONTAINER_ID });
> vchart.renderSync();
> 
> // 只为了方便控制台调试用，不要拷贝
> window['vchart'] = vchart;
> ```
> 
> ### Steps to Reproduce
> 当axes设置orient:bottom后柱状图显示不正常，移除orient后，layers不生效
> 
> ### Current Behavior
> ![image](https://private-user-images.githubusercontent.com/31810871/315995424-d0f3cf9f-0267-4cda-a16b-aa64b8df0254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzU3MzksIm5iZiI6MTcxMTMzNTQzOSwicGF0aCI6Ii8zMTgxMDg3MS8zMTU5OTU0MjQtZDBmM2NmOWYtMDI2Ny00Y2RhLWExNmItYWE2NGI4ZGYwMjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAyNTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NTBiYjgyODhlZTZiMmY2NGIxNjNiNDFjN2RmZTVkNDEzYzJlYzU2YzZhM2VjY2RhODhmMWU0MjE3MDlmY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U2N8Uolq6Ixe3Kfy16RYdlzgNgSntmI58Qb5anbozEY)
> 
> ### Expected Behavior
> 时间轴和柱状图均显示正确 <img alt="image" width="1103" src="https://private-user-images.githubusercontent.com/31810871/316032279-aed193a7-2bdc-4bf5-9579-6e7804104d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzU3MzksIm5iZiI6MTcxMTMzNTQzOSwicGF0aCI6Ii8zMTgxMDg3MS8zMTYwMzIyNzktYWVkMTkzYTctMmJkYy00YmY1LTk1NzktNmU3ODA0MTA0ZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAyNTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMWZkMjIyMTE5YWM2NjNhN2MyNjk5ZjA1NDVjMGM4NGNmYjYzY2MzNjk0OTVhNjRlNjczMDI3NGNmNzc0YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RVPDfaa6Xu3xvlgGsfoxtP5mmBgzafMrFYWI4tjnWKY">
> 
> ### Environment
> ```
> - OS: macOS
> - Browser: Edge
> - Framework: react + nextJs
> ```
> 
> ### Any additional comments?
> _No response_
时间轴layer不生效的问题我来排查下。

时间轴的用法问题如下：
时间轴为线性轴，如果需要在柱状图上生效，需要同时配置xField和x2Field，即需要同时定位柱子的左边界和右边界。
具体可以这样配置，需要注意的是：
1. 图表类型为histogram，因为histogram支持xField和x2Field。
2. 数据需要增加一个字段用于映射x2Field。
3. time轴需要指定min和max，否则时间范围不精确
![image](https://github.com/VisActor/VChart/assets/40675330/a60f205f-b311-4f3b-91f4-1acaa6bbfe16)

```ts
const spec = {
  type: 'histogram',
  data: [
    {
      id: 'barData',
      values: [
        {
          month_start: 1711062314,
          month_end: 1711062314 + 10,
          sales: 8,
        },
        {
          month_start: 1711062374,
          month_end: 1711062374 + 10,
          sales: 16,
        },
        {
          month_start: 1711062434,
          month_end: 1711062434+ 10,
          sales: 24,
        },
        // {
        //   month: 1711062494,
        //   sales: 19,
        // },
        // {
        //   month: 1711062554,
        //   sales: 23,
        // },
        // {
        //   month: 1711062614,
        //   sales: 44,
        // },
        // {
        //   month: 1711062674,
        //   sales: 84,
        // },
        // {
        //   month: 1711062734,
        //   sales: 60,
        // },
        // {
        //   month: 1711062794,
        //   sales: 46,
        // },
        // {
        //   month: 1711062854,
        //   sales: 27,
        // },
      ]
    }
  ],
  xField: 'month_start',
  x2Field: 'month_end',
  yField: 'sales',
  axes:[
    {
      type: "time",
      orient: "bottom",
      range: {
        min: 1711062314,
        max: 1711062434 + 10
      },
      layers: [
        {
          tickStep: 300,
          timeFormat: "%H:%M",
        },
        {
          tickStep: 86400,
          timeFormat: "%m/%d",
        },
      ],
    },
  ]
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

**Comment by fzxbl** [comment]
@skie1997 貌似时间轴并没有按照layers的格式来将时间戳转换成易读的文本，可以继续指导下吗

**Comment by skie1997** [comment]
> @skie1997 貌似时间轴并没有按照layers的格式来将时间戳转换成易读的文本，可以继续指导下吗?而且这种方式下datazoom也会有问题，时序数据正常来说应该用柱状图就可以了，用histogram有些trick

1.声明为柱状图是更合乎逻辑的，但是柱状图不支持配置xField和x2Field，所以我推荐使用histogram。 但histogram不支持time axes，所以上述配置方法并不能满足需求
2. 声明为common类型，并声明bar series可以解决问题，具体配置如下：
```ts

const spec = {
  type: 'common',
  data: [
    {
      id: 'barData',
      values: [
        {
          month_start: 1711062314,
          month_end: 1711062314 + 10,
          sales: 8,
        },
        {
          month_start: 1711062374,
          month_end: 1711062374 + 10,
          sales: 16,
        },
        {
          month_start: 1711062434,
          month_end: 1711062434+ 10,
          sales: 24,
        },
        // {
        //   month: 1711062494,
        //   sales: 19,
        // },
        // {
        //   month: 1711062554,
        //   sales: 23,
        // },
        // {
        //   month: 1711062614,
        //   sales: 44,
        // },
        // {
        //   month: 1711062674,
        //   sales: 84,
        // },
        // {
        //   month: 1711062734,
        //   sales: 60,
        // },
        // {
        //   month: 1711062794,
        //   sales: 46,
        // },
        // {
        //   month: 1711062854,
        //   sales: 27,
        // },
      ]
    }
  ],
  series: [{
    type: 'bar',
    xField: 'month_start',
    x2Field: 'month_end',
    yField: 'sales',
  }],
  axes:[
    {
      type: 'linear',
      orient: 'left'
    },
    {
      type: "time",
      orient: "bottom",
      range: {
        min: 1711062314 - 10,
        max: 1711062434 + 10
      },
      layers: [
        {
          tickStep: 30,
          timeFormat: "%H:%M",
        },
        {
          tickStep: 30,
          timeFormat: "%m/%d",
        },
      ],
    },
  ],
  dataZoom: [{
    orient: 'bottom',
    filterMode: 'axis'
  }]
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

```
![20240325223506_rec_](https://github.com/VisActor/VChart/assets/40675330/88980465-383f-4b7c-b969-5444068ca9b8)
