### ISSUE TITLE
[Bug] 仪表盘图指针fadeIn动画失效

### ISSUE THREAD

**Issue by neuqzxy** [VisActor/VChart#2458]
### Version

1.8.0

### Link to Minimal Reproduction

1.8.0

### Steps to Reproduce

const spec = {
    "type": "gauge",
    "seriesField": "type",
    "gauge": {
        "type": "circularProgress",
        "progress": {
            "style": {} 
        },
        "track": {
            "style": {}
        },
        "animationAppear": {
            "track": 400,
            "preset": "fadeIn",
            "progress": {
                "duration": 2000
            }
        }
    },
    "pointer": {
        "width": 0.5,
        "height": 0.5,
        "style": {
            "path": "M-0.020059 -0.978425 C-0.018029 -0.9888053 -0.013378 -1 0 -1 C0.01342 -1 0.01812 -0.989146 0.0201 -0.978425 C0.02161 -0.9702819 0.0692 -0.459505 0.09486 -0.184807 C0.10298 -0.097849 0.1089 -0.034548 0.11047 -0.018339 C0.11698 0.04908 0.07373 0.11111 0.00002 0.11111 C-0.07369 0.11111 -0.117184 0.04991 -0.110423 -0.018339 C-0.103662 -0.086591 -0.022089 -0.9680447 -0.020059 -0.978425Z",
            "fill": "#5A595E"
        }
    },
    "pin": {
        "style": {
            "path": "M1 0 C1 0.55228 0.55228 1 0 1 C-0.552285 1 -1 0.55228 -1 0 C-1 -0.552285 -0.552285 -1 0 -1 C0.55228 -1 1 -0.552285 1 0Z",
            "fill": "red"
        }
    },
    "pinBackground": {
        "width": 0.08,
        "height": 0.08,
        "style": {
            "path": "M1 0 C1 0.55228 0.55228 1 0 1 C-0.552285 1 -1 0.55228 -1 0 C-1 -0.552285 -0.552285 -1 0 -1 C0.55228 -1 1 -0.552285 1 0Z",
            "fill": "#ddd"
        }
    },
    "axes": [
        {
            "type": "linear",
            "orient": "angle",
            "label": {
                "style": {}
            },
            "grid": {
                "visible": false
            }
        }
    ],
    "data": {
        "id": "id0",
        "values": [
            {
                "type": "运动时长",
                "value": "0.795"
            }
        ]
    },
    "background": "transparent",
    "valueField": "value",
    "animationAppear": {
        "pointer": {
            "duration": 2000
        }
    },
    "outerRadius": 0.8,
    "innerRadius": 0.5,
    "startAngle": -225,
    "endAngle": 45,
    "width": 600,
    "height": 450
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

指针不执行fadeIn动画
1.7.x正常，1.8.0到现在的版本均有问题

### Expected Behavior

指针执行fadeIn动画

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
在最外层 animationAppear 里，配置一下 preset: 'fadeIn'
