### ISSUE TITLE
[Bug] 没有导出mark注册函数

### ISSUE THREAD

**Issue by xile611** [VisActor/VChart#2468]
### Version

1.10.2

### Link to Minimal Reproduction

no need

### Steps to Reproduce

no need

### Current Behavior

`registerTextMark` 等未导出

### Expected Behavior

1. 导出所有的mark
2. 必选组件，默认注册
<img width="1021" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/d0b33bd2-ff4d-457c-8e9b-86e55f8f2cbd">

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
如果使用了未注册的mark或者组件，能够在开发模式下提示用户，调用对应的注册函数

**Comment by Gavinchen92** [comment]
没有默认导出registerWordCloudShapeChart
