### ISSUE TITLE
[Feature] vue3 use ts feature how to import the *.d.ts file?

### ISSUE THREAD

**Issue by pengsamkee** [VisActor/VChart#2477]
### What problem does this feature solve?

when i import component from vchart, the vscode warn some error，because missing the *.d.ts file.
i try import the *.d.ts from node_module/@visactor/vchart/esm，dev environment is running well，but build environment appear some error，the chart do not appear.

### What does the proposed API look like?

may be you can offer the *.d.ts file

**Comment by pengsamkee** [comment]
![image](https://github.com/VisActor/VChart/assets/6622267/768b6f49-ac01-40e6-ae1e-f51fe08d5442)
build environment happen this error

**Comment by xile611** [comment]
> ![image](https://private-user-images.githubusercontent.com/6622267/317092474-768b6f49-ac01-40e6-ae1e-f51fe08d5442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjYyNTIsIm5iZiI6MTcxMTUyNTk1MiwicGF0aCI6Ii82NjIyMjY3LzMxNzA5MjQ3NC03NjhiNmY0OS1hYzAxLTQwZTYtYWUxZS1mNTFmZTA4ZDU0NDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDc1MjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJmOTkwYmYxMWZjYWVhZjJhODc3ZDQzN2NmMjdjYTljNDU3MjBiYzBiNjAyODhkNTViZGU2ZDg5NTNlOTZjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nW0l1tH2bhf8SDp7axPL3mRNhtQ-eW8ILqFZ_Qzo-pw) build environment happen this error

can you share a online  to reproduce your issue?

**Comment by pengsamkee** [comment]
> > ![image](https://private-user-images.githubusercontent.com/6622267/317092474-768b6f49-ac01-40e6-ae1e-f51fe08d5442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjYyNTIsIm5iZiI6MTcxMTUyNTk1MiwicGF0aCI6Ii82NjIyMjY3LzMxNzA5MjQ3NC03NjhiNmY0OS1hYzAxLTQwZTYtYWUxZS1mNTFmZTA4ZDU0NDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDc1MjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJmOTkwYmYxMWZjYWVhZjJhODc3ZDQzN2NmMjdjYTljNDU3MjBiYzBiNjAyODhkNTViZGU2ZDg5NTNlOTZjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nW0l1tH2bhf8SDp7axPL3mRNhtQ-eW8ILqFZ_Qzo-pw) build environment happen this error
> 
> can you share a online to reproduce your issue?

maybe other libs or config affects vchart, it's difficult to find out which reasons, but anyway thank you very much!

**Comment by pengsamkee** [comment]
when i run the command in my vue3 project “npm install @visactor/vchart”，under the version in package.json dependencies node is "@visactor/vchart": "^1.2.3"，dev environment running well，prod environment happen error. when i change the version to "~1.2.3"，all thing is well.
