### ISSUE TITLE
[Feature] 瀑布图 totalLabel 增强

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#2480]
### What problem does this feature solve?

1. 瀑布图的 totalLabel 、stackLabel 不merge spec；能力对齐；可以同时生效；后续2.x 考虑去掉stackLabel 
2. totalLabel 增强
瀑布图支持特殊属性：
valueType: 'change' | 'absolute', 
position: 'withChange' | 'middle' | 'max' | 'min'

### What does the proposed API look like?

none

**Comment by kkxxkk2019** [comment]
position: 'withChange' 这个特性感觉应该属于通用属性，在正常的堆叠图中，如果数值总值为负，也会有这个需求

<img width="1099" alt="image" src="https://github.com/VisActor/VChart/assets/135952300/3e63f305-0ffb-4461-b336-6b958253ae7a">

**Comment by xile611** [comment]
> position: 'withChange' 这个特性感觉应该属于通用属性，在正常的堆叠图中，如果数值总值为负，也会有这个需求
> 
> <img alt="image" width="1099" src="https://private-user-images.githubusercontent.com/135952300/317171886-3e63f305-0ffb-4461-b336-6b958253ae7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjYxMzQsIm5iZiI6MTcxMTUyNTgzNCwicGF0aCI6Ii8xMzU5NTIzMDAvMzE3MTcxODg2LTNlNjNmMzA1LTBmZmItNDQ2MS1iMzM2LTZiOTU4MjUzYWU3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNzUwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODlmZTQ4ZDQ2MWVlODRhZDNmZGExYjcxM2ExODRmOTM1MzAxMjQ4MDU5YmNkNGJlYjEyNzVkYjBlODMyMTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V78UQRbNkxpUJ57SHTDXPMEqVX7jkG40ATUSFTQiGEQ">

 确实，另外如果堆积图有正数和负数的时候，分别暂时正数的累计值、负数的累计值也是一种常见需求吧

CC @xiaoluoHe
