### ISSUE TITLE
[Bug] vtable 里面嵌入图标的时候，直接使用vchart的spec会导致hover后图表消失

### ISSUE THREAD

**Issue by deno-source** [VisActor/VChart#2486]
### Version

1.10.2

### Link to Minimal Reproduction

无

### Steps to Reproduce

 columns的配置：
  {
        field: "areaChart",
        title: "multiple vchart type",
        width: "320",
        cellType: "chart",
        chartModule: "vchart",
        chartSpec(args) {
          return  {
            type: 'pie',
            data: [
              {
                id: 'id0',
                values: [
                  { type: 'oxygen', value: '46.60' },
                  { type: 'silicon', value: '27.72' },
                  { type: 'aluminum', value: '8.13' },
                  { type: 'iron', value: '5' },
                  { type: 'calcium', value: '3.63' },
                  { type: 'sodium', value: '2.83' },
                  { type: 'potassium', value: '2.59' },
                  { type: 'others', value: '3.5' }
                ]
              }
            ],
            outerRadius: 0.8,
            valueField: 'value',
            categoryField: 'type',
            title: {
              visible: true,
              text: 'Statistics of Surface Element Content'
            },
            legends: {
              visible: true,
              orient: 'left'
            },
            label: {
              visible: true
            },
            tooltip: {
              mark: {
                content: [
                  {
                    key: datum => datum['type'],
                    value: datum => datum['value'] + '%'
                  }
                ]
              }
            }
          }
        },
      },

![image](https://github.com/VisActor/VChart/assets/21171308/6a8ce771-2374-498f-9a12-6a157190eed1)
hover
![image](https://github.com/VisActor/VChart/assets/21171308/00d1bd6c-c1ea-43cb-861b-7d019e62d8e1)

### Current Behavior

应该正常展示图表

### Expected Behavior

应该正常展示图表

### Environment

```markdown
- OS:windows
- Browser:chrome 124.0.6356.6
- Framework:react nextjs
```

### Any additional comments?

无

**Comment by xiaoluoHe** [comment]
chartSpec 的数据value不能配 ，要来源于records

```ts
chartSpec(args) {
      return {
        type: "pie",
        data: [
          {
            id: "data",
          },
        ],
        outerRadius: 0.8,
        valueField: "y",
        categoryField: "type",
        title: {
          visible: true,
          text: "Statistics of Surface Element Content",
        },
      };
    },
```
