### ISSUE TITLE
Does "sortDataByAxis" allow for both ascending and descending sorting?

### ISSUE THREAD

**Issue by Crayon-ShinChan** [VisActor/VChart#2496]
The [documentation](https://visactor.io/vchart/option/lineChart#sortDataByAxis) indicates that we have the ability to sort the data based on a specific axis:

```
lineChart.sortDataByAxis
boolean
This field determines whether the data is sorted by axis. By specifying if the data should be arranged in axis order, you can ensure the correct order when the data sequence is uncertain. To maintain the original data order, set this field to false.
```

Based on my interpretation, the sorting is done by the X-axis rather than the Y-axis. When I set it to "true" it arranges my data on the X-axis in descending order. Is it possible to sort it in ascending order using sortDataByAxis? Or do we have to manually arrange the data before implementing it?

**Comment by xuefei1313** [comment]
The effect of this configuration is to sort the series data according to the order of the axis data. It is used to deal with the drawing problem caused by the different order of the data of multiple series on the x-axis. So it takes effect after the axis data is generated.

If you expect the data to be sorted according to its y value, the currently supported method is to configure the sortIndex of the corresponding dimension on the data.
```
const spec = {
  type: 'line',
  data: {
    fields: {
      value: {
        // When sortIndex is set to a number, the data will be sorted according to this dimension
        // if multiple dimensions of the data have sortIndex set. It will be sorted one by one according to the value of sortIndex of the dimension.
        sortIndex: 0,
        // sortReverse: true,
      }
    },
    values: [
      {
        time: '2:00',
        value: 8
      },
      {
        time: '4:00',
        value: 9
      },
      {
        time: '6:00',
        value: 11
      },
      {
        time: '8:00',
        value: 14
      },
      {
        time: '10:00',
        value: 16
      },
      {
        time: '12:00',
        value: 17
      },
      {
        time: '14:00',
        value: 17
      },
      {
        time: '16:00',
        value: 16
      },
      {
        time: '18:00',
        value: 15
      }
    ]
  },
  xField: 'time',
  yField: 'value'
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

**Comment by Crayon-ShinChan** [comment]
> The effect of this configuration is to sort the series data according to the order of the axis data. It is used to deal with the drawing problem caused by the different order of the data of multiple series on the x-axis. So it takes effect after the axis data is generated.
> 
> If you expect the data to be sorted according to its y value, the currently supported method is to configure the sortIndex of the corresponding dimension on the data.
> 
> ```
> const spec = {
>   type: 'line',
>   data: {
>     fields: {
>       value: {
>         // When sortIndex is set to a number, the data will be sorted according to this dimension
>         // if multiple dimensions of the data have sortIndex set. It will be sorted one by one according to the value of sortIndex of the dimension.
>         sortIndex: 0,
>         // sortReverse: true,
>       }
>     },
>     values: [
>       {
>         time: '2:00',
>         value: 8
>       },
>       {
>         time: '4:00',
>         value: 9
>       },
>       {
>         time: '6:00',
>         value: 11
>       },
>       {
>         time: '8:00',
>         value: 14
>       },
>       {
>         time: '10:00',
>         value: 16
>       },
>       {
>         time: '12:00',
>         value: 17
>       },
>       {
>         time: '14:00',
>         value: 17
>       },
>       {
>         time: '16:00',
>         value: 16
>       },
>       {
>         time: '18:00',
>         value: 15
>       }
>     ]
>   },
>   xField: 'time',
>   yField: 'value'
> };
> 
> const vchart = new VChart(spec, { dom: CONTAINER_ID });
> vchart.renderSync();
> 
> // Just for the convenience of console debugging, DO NOT COPY!
> window['vchart'] = vchart;
> ```

Hi, thank you for your response. I now have a dataset with date strings like "2024-03-26" on the X-axis. I would like to sort this date X-axis (not Y-axis, unfortunately) in ascending order, however, when I set `lineChart.sortDataByAxis = true`, it is sorting it in descending order. Is there a way to sort it in ascending order without preprocessing the original data order?

**Comment by xuefei1313** [comment]
There is currently no built-in sorting capability for non-standard date strings, but if you can get all the x-axis data in advance, you can configure it through fields of data.
```
const spec = {
  type: 'line',
  data: {
    fields: {
      // value: { },
      time: {
        domain: ['2024-03-26', '2024-03-27', '2024-03-28'],
        sortIndex: 0,
      }
    },
    values: [
      {
        time: '2024-03-28',
        value: 8
      },
      {
        time: '2024-03-27',
        value: 9
      },
      {
        time: '2024-03-26',
        value: 11
      }
    ]
  },
  xField: 'time',
  yField: 'value'
};

```
