### ISSUE TITLE
[Enhancement] 优化轴值域的 min max 策略

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#2498]
## 问题
现在对于线性轴值域的 min max 配置策略，是无论用户配置的 min 和 max 是多少，都直接以用户配置的为主，如果用户配置的范围与真实的数据范围不同，如 max 小于真实数据的最大值，就以 max 为准，这样会造成截断图形，如下图：

<img width="653" alt="image" src="https://github.com/VisActor/VChart/assets/135952300/028b284e-dfda-4c02-b7e4-8fd7f8b6ed95">

顶部柱子被截断
<img width="655" alt="image" src="https://github.com/VisActor/VChart/assets/135952300/06481611-599d-43f2-a8f3-1bc21f357e5f">

## 期望的解决方案

提供一种策略，无论用户配置了多少 min 和 max，以真实的数据方位为准，即 max 不得小于真实数据的最大值，min 不得大于真实数据的最大值。

**Comment by xile611** [comment]
补充一些需求：

* 支持类目轴和回调。在类目轴中，也可以设置为类目的序数（如类目轴 data: ['类A', '类B', '类C'] 中，序数 2 表示 '类C'。也可以设置为负数，如 -3）。
* 当设置成 function 形式时，可以根据计算得出的数据最大最小值设定坐标轴的最小值。如：
```
min: function (value) {
    return value.min - 20;
}
```
