### ISSUE TITLE
What is the best practice to import Datum type

### ISSUE THREAD

**Issue by Crayon-ShinChan** [VisActor/VChart#2507]
I am currently using TypeScript with `@visactor/react-vchart` When working with ESLint, it asks me to specify the type of `Datum`, but I am unable to import the Datum type from `@visactor/react-vchart`. Could you please advise on the best practice for specifying types in the following scenario?
```ts
 tooltip: {
  mark: {
    visible: true,
    content: [
      {
        key: (datum: Datum) => `${datum["typeClean"]} (issued)`,
        value: (datum: Datum) => datum["issued"],
      },
    ],
  },
},
 ```

**Comment by Crayon-ShinChan** [comment]
I installed `@visactor/vchart` and found type `Datum` is in `@visactor/vchart`, not in `@visactor/react-vchart`.
And then I changed my code to:
```ts
tooltip: {
  dimension: {
    content: [
      {
        key: (datum: Datum | undefined) =>
          datum ? `${datum.typeClean} (issued)` : "",
        value: (datum: Datum | undefined) =>
          datum ? `${datum.issued}` : "",
      },
    ],
  },
},
```

**Comment by xile611** [comment]
@Crayon-ShinChan  you can import `Datum` from `@visactor/vchart`; or just use `any`, because `Datum` is just `any` in `vchart`
