### ISSUE TITLE
[Bug] `visible: false` not working for commonChart-series-line.visible

### ISSUE THREAD

**Issue by Crayon-ShinChan** [VisActor/VChart#2510]
### Version

1.10.2

### Link to Minimal Reproduction

https://www.visactor.io/vchart/demo/combination/dual-axis?keyword=commonChart

### Steps to Reproduce

1. go to the reproduction url
2. add `visible: false,` to
```js
    {
      type: 'line',
      id: 'line',
      visible: false,
      dataIndex: 1,
      label: { visible: true },
      seriesField: 'type',
      xField: 'x',
      yField: 'y',
      stack: false
    }
```
3. the line chart will be still there

### Current Behavior

The line chart will be still there even if we set `commonChart-series-line.visible` to be `false`
![CleanShot 2024-03-30 at 15 17 22@2x](https://github.com/VisActor/VChart/assets/38809606/abdc5215-119d-4de5-ae96-7e34d573f9e2)
And in another piece of code (the code I'm working on for my own project), I got
![CleanShot 2024-03-30 at 15 21 39@2x](https://github.com/VisActor/VChart/assets/38809606/53124f9e-23a9-47dc-862b-bfdddd02e255)

### Expected Behavior

According to the [doc](https://www.visactor.io/vchart/option/commonChart-series-line#visible), `commonChart-series-line.visible` can control the visibility of the corresponding chart.
```
commonChart-series-line.visible
boolean
Whether to display chart elements.
```
Therefore, the following code should make the line chart disappear
```js
    {
      type: 'line',
      id: 'line',
      visible: false,
      dataIndex: 1,
      label: { visible: true },
      seriesField: 'type',
      xField: 'x',
      yField: 'y',
      stack: false
    }
```

Please correct me if I misunderstand the document

### Environment

```markdown
- OS: macOS 14.2.1 (23C71)
- Browser: Arc Version 1.35.0 (47750)
- Framework: React
```

**Comment by xile611** [comment]
@Crayon-ShinChan the doc is missleading.

the right specification is 

```
{
      type: 'line',
      id: 'line',
      line: {
        visible: false
      },
      dataIndex: 1,
      label: { visible: true },
      seriesField: 'type',
      xField: 'x',
      yField: 'y',
      stack: false
    }
```

**Comment by Crayon-ShinChan** [comment]
> @Crayon-ShinChan the doc is missleading.
> 
> the right specification is
> 
> ```
> {
>       type: 'line',
>       id: 'line',
>       line: {
>         visible: false
>       },
>       dataIndex: 1,
>       label: { visible: true },
>       seriesField: 'type',
>       xField: 'x',
>       yField: 'y',
>       stack: false
>     }
> ```

Hello, thank you for the response. After the code, the line disappeared, but the points and dots are still there. Based on my understanding, `{line: {visible: false}}` only hides the line. Is there a specific way to hide the entire series?
