### ISSUE TITLE
[Bug] histogramChart crosshair

### ISSUE THREAD

**Issue by skie1997** [VisActor/VChart#254]
### Version

1.1.0-beta2

### Link to Minimal Reproduction

null

### Steps to Reproduce

https://www.visactor.io/vchart/demo/histogram-chart/histogram-different-bin

### Current Behavior

最后一根柱子的crosshair区域不对

### Expected Behavior

最后一根柱子的crosshair区域应该显示正确

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
This was caused by the fieldX2 does not participate in data statistics, resulting in incorrect scale domain of the x-axis.
