### ISSUE TITLE
[Bug] vchart进度图当value＞1且max＞时渲染起始点计算错误

### ISSUE THREAD

**Issue by a1419735487** [VisActor/VChart#2541]
### Version

1.10.4

### Link to Minimal Reproduction

-1

### Steps to Reproduce

![image](https://github.com/VisActor/VChart/assets/72694814/ffda9124-72e6-4a74-9400-f08f66b28873)

### Current Behavior

const spec = {
  type: 'linearProgress',
  data: [
    {
      id: 'id0',
      values: [
        {
          type: 'Tradition Industries',
          value: 2,
          goal: 0.7,
          text: '79.5%'
        }
      ]
    }
  ],
  direction: 'horizontal',
  xField: 'value',
  yField: 'type',
  seriesField: 'type',
  height: 150,
  cornerRadius: 20,
  bandWidth: 30,
  axes: [
    {
      orient: 'bottom',
      label: { visible: true, inside: true },
      type: 'linear',
      grid: {
        visible: false
      },
      min: 0,
      max: 3,
    }
  ],
};

### Expected Behavior

0-1之间应该也要被渲染，例如
![image](https://github.com/VisActor/VChart/assets/72694814/454f17d6-2f57-4e0d-a384-61d3f49e78de)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
进度图数据需要在 0-1 之间。
这个效果你可以用柱状图做吧
