### ISSUE TITLE
[Feature] markPoint 如何便捷的设置最大最小值？且能和 datazoom 组件联动

### ISSUE THREAD

**Issue by webiamcome** [VisActor/VChart#2546]
### What problem does this feature solve?

markPoint 通过配置可以自动计算聚合方式，例如：可视区域数据的最大最小值。而且需要支持 datazoom 缩放数据时，最大最小值能自动计算

需求讨论地址：https://github.com/orgs/VisActor/discussions/2369

### What does the proposed API look like?

none

**Comment by webiamcome** [comment]
这个问题有大佬看吗？期望5.1 前修复

**Comment by skie1997** [comment]
> 这个问题有大佬看吗？期望5.1 前修复

1. markPoint用回调的方式配置，这样可以拿到上下文，并动态更新

**Comment by webiamcome** [comment]
> > 这个问题有大佬看吗？期望5.1 前修复
> 
> markPoint用回调的方式配置，这样可以拿到上下文，并动态更新 这边写了一个demo，可以实现同学的需求： ![20240425173959_rec_](https://private-user-images.githubusercontent.com/40675330/325555680-88a22ff1-d738-4454-bf5f-085fc6c75aff.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjMwMTMsIm5iZiI6MTcxNTA2MjcxMywicGF0aCI6Ii80MDY3NTMzMC8zMjU1NTU2ODAtODhhMjJmZjEtZDczOC00NDU0LWJmNWYtMDg1ZmM2Yzc1YWZmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA2MTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTY2Y2Q0ZmUyNDJmZjM5OTlhNmI1ZWQ2ZTU2ZjE3NWNmODQzYWNlMGMxNzk3MWRjYmMzMzY5YzBmYWQxZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zkLpwTCEutmPBBPdHTVoIwAHAREKiED-ul-V5qypMtY) [ ![20240425173959_rec_](https://private-user-images.githubusercontent.com/40675330/325555680-88a22ff1-d738-4454-bf5f-085fc6c75aff.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjMwMTMsIm5iZiI6MTcxNTA2MjcxMywicGF0aCI6Ii80MDY3NTMzMC8zMjU1NTU2ODAtODhhMjJmZjEtZDczOC00NDU0LWJmNWYtMDg1ZmM2Yzc1YWZmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA2MTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTY2Y2Q0ZmUyNDJmZjM5OTlhNmI1ZWQ2ZTU2ZjE3NWNmODQzYWNlMGMxNzk3MWRjYmMzMzY5YzBmYWQxZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zkLpwTCEutmPBBPdHTVoIwAHAREKiED-ul-V5qypMtY) ](https://private-user-images.githubusercontent.com/40675330/325555680-88a22ff1-d738-4454-bf5f-085fc6c75aff.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjMwMTMsIm5iZiI6MTcxNTA2MjcxMywicGF0aCI6Ii80MDY3NTMzMC8zMjU1NTU2ODAtODhhMjJmZjEtZDczOC00NDU0LWJmNWYtMDg1ZmM2Yzc1YWZmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA2MTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTY2Y2Q0ZmUyNDJmZjM5OTlhNmI1ZWQ2ZTU2ZjE3NWNmODQzYWNlMGMxNzk3MWRjYmMzMzY5YzBmYWQxZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zkLpwTCEutmPBBPdHTVoIwAHAREKiED-ul-V5qypMtY) [ ](https://private-user-images.githubusercontent.com/40675330/325555680-88a22ff1-d738-4454-bf5f-085fc6c75aff.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjMwMTMsIm5iZiI6MTcxNTA2MjcxMywicGF0aCI6Ii80MDY3NTMzMC8zMjU1NTU2ODAtODhhMjJmZjEtZDczOC00NDU0LWJmNWYtMDg1ZmM2Yzc1YWZmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA2MTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTY2Y2Q0ZmUyNDJmZjM5OTlhNmI1ZWQ2ZTU2ZjE3NWNmODQzYWNlMGMxNzk3MWRjYmMzMzY5YzBmYWQxZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zkLpwTCEutmPBBPdHTVoIwAHAREKiED-ul-V5qypMtY)
> 
> ```ts
>   const findMinOrMaxDatum = (data, field) => {
>     let min = Infinity;
>     let max = -Infinity;
>     let minIndex = 0;
>     let maxIndex = 0;
>     data.forEach((d, i) => {
>       if (d[field] > max) {
>         maxIndex = i;
>         max = d[field];
>       } else if (d[field] < min) {
>         minIndex = i;
>         min = d[field];
>       }
>     });
>     return {
>       minDatum: data[minIndex],
>       maxDatum: data[maxIndex]
>     }
>   }
> 
>   const spec = {
>     type: 'bar',
>     data: [
>       {
>         id: 'barData',
>         values: [
>           {
>             name: 'Apple',
>             value: 214480
>           },
>           {
>             name: 'Google',
>             value: 155506
>           },
>           {
>             name: 'Amazon',
>             value: 100764
>           },
>           {
>             name: 'Microsoft',
>             value: 92715
>           },
>           {
>             name: 'Coca-Cola',
>             value: 66341
>           },
>           {
>             name: 'Samsung',
>             value: 59890
>           },
>           {
>             name: 'Toyota',
>             value: 53404
>           },
>           {
>             name: 'Mercedes-Benz',
>             value: 48601
>           },
>           {
>             name: 'Facebook',
>             value: 45168
>           },
>           {
>             name: "McDonald's",
>             value: 43417
>           },
>           {
>             name: 'Intel',
>             value: 43293
>           },
>           {
>             name: 'IBM',
>             value: 42972
>           },
>           {
>             name: 'BMW',
>             value: 41006
>           },
>           {
>             name: 'Disney',
>             value: 29874
>           },
>           {
>             name: 'Cisco',
>             value: 34575
>           },
>           {
>             name: 'GE',
>             value: 12757
>           },
>           {
>             name: 'Nike',
>             value: 30120
>           },
>           {
>             name: 'Louis Vuitton',
>             value: 28152
>           },
>           {
>             name: 'Oracle',
>             value: 26133
>           },
>           {
>             name: 'Honda',
>             value: 33682
>           }
>         ]
>       }
>     ],
>     xField: 'name',
>     yField: 'value',
>     axes: [
>       {
>         orient: 'bottom',
>         visible: false
>       }
>     ],
>     label: {
>       visible: true
>     },
>     dataZoom: [
>       {
>         orient: 'bottom',
>         backgroundChart: {
>           area: {
>             style: {
>               lineWidth: 1,
>               fill: '#D1DBEE'
>             }
>           },
>           line: {
>             style: {
>               stroke: '#D1DBEE',
>               lineWidth: 1
>             }
>           }
>         },
>         selectedBackgroundChart: {
>           area: {
>             style: {
>               lineWidth: 1,
>               fill: '#fbb934'
>             }
>           },
>           line: {
>             style: {
>               stroke: '#fbb934',
>               lineWidth: 1
>             }
>           }
>         }
>       }
>     ],
>     markPoint: [
>       {
>         coordinate: {
>           name: (relativeSeriesData,
>             startRelativeSeriesData,
>             endRelativeSeriesData,
>             relativeSeries,
>             startSeries,
>             endSeries) => {
>             const domain: any[] = relativeSeries._scaleX.domain()
>             console.log(relativeSeries._scaleX.domain())
>             const { minDatum, maxDatum } = findMinOrMaxDatum(
>               relativeSeriesData.filter(d => domain.indexOf(d['name']) >= 0), 'value')
> 
>             return minDatum?.['name']
>           },
>           value: (relativeSeriesData,
>             startRelativeSeriesData,
>             endRelativeSeriesData,
>             relativeSeries,
>             startSeries,
>             endSeries) => {
>             const domain = relativeSeries._scaleX.domain()
>             const { minDatum, maxDatum } = findMinOrMaxDatum(
>               relativeSeriesData.filter(d => domain.indexOf(d['name']) >= 0), 'value')
>             return minDatum?.['value']
>           }
>         },
>         itemContent: {
>           offsetY: -100,
>           type: 'text',
>           text: {
>             formatMethod: (...p) => p[0][0].y[0]
>           }
>         }
>       },
>       {
>         coordinate: {
>           name: (relativeSeriesData,
>             startRelativeSeriesData,
>             endRelativeSeriesData,
>             relativeSeries,
>             startSeries,
>             endSeries) => {
>             const domain = relativeSeries._scaleX.domain()
>             console.log(relativeSeries._scaleX.domain())
>             const { minDatum, maxDatum } = findMinOrMaxDatum(
>               relativeSeriesData.filter(d => domain.indexOf(d['name']) >= 0), 'value')
>             return maxDatum?.['name']
>           },
>           value: (relativeSeriesData,
>             startRelativeSeriesData,
>             endRelativeSeriesData,
>             relativeSeries,
>             startSeries,
>             endSeries) => {
>             const domain = relativeSeries._scaleX.domain()
>             const { minDatum, maxDatum } = findMinOrMaxDatum(
>               relativeSeriesData.filter(d => domain.indexOf(d['name']) >= 0), 'value')
>             return maxDatum?.['value']
>           }
>         },
>         itemContent: {
>           offsetY: -100,
>           type: 'text',
>           text: {
>             formatMethod: (...p) => p[0][0].y[0]
>           }
>         }
>       }
>     ]
>   };
> ```

您好，麻烦帮忙看看分组柱状图，markPoint 不显示。代码如下：
上面您答复的代码我复制到官网 demo 中，图形显示不出来了。。。

```javascript
const spec = {
  type: 'bar',
  data: [
    {
      id: 'barData',
      values: [
        { type: 'Autocracies', year: '1930', value: 129 },
        { type: 'Autocracies', year: '1940', value: 133 },
        { type: 'Autocracies', year: '1950', value: 130 },
        { type: 'Autocracies', year: '1960', value: 126 },
        { type: 'Autocracies', year: '1970', value: 117 },
        { type: 'Autocracies', year: '1980', value: 114 },
        { type: 'Autocracies', year: '1990', value: 111 },
        { type: 'Autocracies', year: '2000', value: 89 },
        { type: 'Autocracies', year: '2010', value: 80 },
        { type: 'Autocracies', year: '2018', value: 80 },
        { type: 'Democracies', year: '1930', value: 22 },
        { type: 'Democracies', year: '1940', value: 13 },
        { type: 'Democracies', year: '1950', value: 25 },
        { type: 'Democracies', year: '1960', value: 29 },
        { type: 'Democracies', year: '1970', value: 38 },
        { type: 'Democracies', year: '1980', value: 41 },
        { type: 'Democracies', year: '1990', value: 57 },
        { type: 'Democracies', year: '2000', value: 87 },
        { type: 'Democracies', year: '2010', value: 98 },
        { type: 'Democracies', year: '2018', value: 99 }
      ]
    }
  ],
  xField: ['year', 'type'], // 多加了一个 type 字段，markPoint 就不显示了
  yField: 'value',
  seriesField: 'type',
  legends: {
    visible: true,
    orient: 'top',
    position: 'start'
  },
  markPoint: [
    {
      coordinate: {
        year: "2018",
        value: 99
      },
      itemContent: {
        // offsetY: -100,
        // offsetX: -200,
        type: 'richText',
        autoRotate: false,
        confine: true,
        position: 'insideBottom',
        richText: {
          style: {
            width: 100,
            height: 50,
            dx: 110,
            dy: 10,
            textConfig: [
              {
                text: '2016\n',
                fontWeight: 'bold',
                fontSize: 13,
                fill: '#E8346D',
                fontFamily: 'Times New Roman'
              },
              {
                text: 'population was 899447',
                fontSize: 10,
                fill: '#E8346D',
                fontFamily: 'Times New Roman'
              }
            ]
          }
        }
      },
      itemLine: {
        type: 'type-do',
        startSymbol: {
          size: 100,
          style: {
            stroke: '#E8346D'
          }
        },
        line: {
          style: {
            stroke: '#E8346D'
          }
        }
      }
    }
  ]
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```
