### ISSUE TITLE
[Bug] label displays beyond canvas

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#2557]
### Version

@visactor/vchart :  "1.10.3"

### Link to Minimal Reproduction

null

### Steps to Reproduce

use this spec in the text
[label-clip.txt](https://github.com/VisActor/VChart/files/14998210/label-clip.txt)

### Current Behavior

![img_v3_02a0_2e877442-2530-43c3-b56c-d8441a4d57bg](https://github.com/VisActor/VChart/assets/40026218/93963f88-edf2-4f85-9dab-6d8dfe906468)

### Expected Behavior

The label is displayed in the canvas

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
标签算法已更新
