### ISSUE TITLE
[Bug] 选中取消图例会选中页面上一些文字

### ISSUE THREAD

**Issue by zzzhangy** [VisActor/VChart#2560]
### Version

v1.10.4

### Link to Minimal Reproduction

 legends: [                 {                     visible: true,                     position: 'end',                     orient: 'top',                     item: { shape: { style: { symbolType: 'roundLine' } } }                 }             ],

### Steps to Reproduce

![image](https://github.com/VisActor/VChart/assets/116279784/4da394d5-1574-4ffa-83c0-f72861161dc6)

### Current Behavior

循环选中取消同一图例会选中页面上的文字

### Expected Behavior

循环选中取消同一图例会选中页面上的文字

### Environment

```markdown
- OS:
- Browser:
- Framework:Chrome 96.0.4664.55
react@18.2.0
```

### Any additional comments?

循环选中取消同一图例会选中页面上的文字

**Comment by xile611** [comment]
@zzzhangy 是不是你们页面实现的问题？
能给一下复现的场景吗？

**Comment by xile611** [comment]
@zzzhangy 我先关闭了，如果能给出复现示例，可以新开一个issue，或者重新打开这个issue
