### ISSUE TITLE
[Bug] Pie indicator does not display in grid layout

### ISSUE THREAD

**Issue by purpose233** [VisActor/VChart#2564]
### Version

1.10.4

### Link to Minimal Reproduction

null

### Steps to Reproduce

https://visactor.io/vchart/demo/layout/grid-layout

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/14228496/cc0aacb9-d666-46ce-a049-eac882e17eb2)

### Expected Behavior

![image](https://github.com/VisActor/VChart/assets/14228496/a2d34e6e-aa0e-494c-9c6e-b97ba2fdc4fc)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
The indicator configuration is placed outside of the series and is associated with a specific region through the regionId.

We will correct the demo
