### ISSUE TITLE
[Feature] Wish word cloud support text as cloud shape

### ISSUE THREAD

**Issue by xuanhun** [VisActor/VChart#259]
### What problem does this feature solve?

Wish word cloud support text as cloud shape，like this：

<img src = https://github.com/VisActor/VChart/assets/2384516/85f08c08-3286-43c3-974c-06207b88fd80 ></img>

### What does the proposed API look like?

add a  "shapeType" field to wordCloudChart.wordCloudShapeConfig,

type="text"|"url"|"svg"|"base64"|"shapeName“，

const spec = {
  type: 'wordCloud',
  maskShape: '玄',
  wordCloudShapeConfig:{
    shapeType:"text"
  },
....
}

**Comment by xile611** [comment]
supported in 1.12.0
