### ISSUE TITLE
为什么使用demo页面，输入不同的prompt，但是生成的图表没有变化？

### ISSUE THREAD

**Issue by Muyi030** [VisActor/VChart#2628]
### Version

/

### Link to Minimal Reproduction

/

### Steps to Reproduce

demo页面使用

### Current Behavior

demo页面，输入不同的prompt，但是生成的图表没有变化

### Expected Behavior

demo页面，输入不同的prompt，能根据输入的不同prompt产生不同的图表结果

### Environment

```markdown
demo页面：http://localhost:3020/vchart/VMind
```

**Comment by da730** [comment]
看下控制台有没有报错，可能是LLM没有配置好，触发了兜底逻辑

**Comment by da730** [comment]
> ### Version
> /
> 
> ### Link to Minimal Reproduction
> /
> 
> ### Steps to Reproduce
> demo页面使用
> 
> ### Current Behavior
> demo页面，输入不同的prompt，但是生成的图表没有变化
> 
> ### Expected Behavior
> demo页面，输入不同的prompt，能根据输入的不同prompt产生不同的图表结果
> 
> ### Environment
> ```
> demo页面：http://localhost:3020/vchart/VMind
> ```
> 
> ### Any additional comments?
> _No response_

官网已经上线了专门的playground：https://www.visactor.io/vmind/playground ，可以在这里体验
