### ISSUE TITLE
[Bug] react-vchart BarChart cannot work while set direction="horizontal"

### ISSUE THREAD

**Issue by hunter-xue** [VisActor/VChart#2634]
### Version

1.10.5

### Link to Minimal Reproduction

https://github.com/VisActor/VChart/tree/main/packages/react-vchart

### Steps to Reproduce

    return (
        <div>
            <BarChart ref={chartRef} data={[{ id: 'chat_bar', values: barData }]}>
                <Bar
                    seriesField="category"
                    xField="count"
                    yField="dept"
                    direction="horizontal"
                    stack={true}
                    percent={true}
                />
                <Axis orient="bottom" />
                <Legend visible={true} position="start" orient="top" padding={{ bottom: 12 }} />
            </BarChart>
        </div>
    );

### Current Behavior

horizontal does NOT work, but vetical working well. 

### Expected Behavior

horizontal working well. 

### Environment

```markdown
- OS:MacOS
- Browser: Edge
- Framework: Vite and Yarn 2
```

**Comment by xile611** [comment]
@hunter-xue 

` direction="horizontal"` 是图表级别的配置，要如下配置：
```
<BarChart  direction="horizontal">
...
```
