### ISSUE TITLE
请问theme和backgroundcolor可以做响应式开发吗

### ISSUE THREAD

**Issue by heyi11** [VisActor/VChart#2636]
` background: [config.background],`

我想动态的改变背景的颜色，但是似乎不能做到，这是和渲染方式有关吗

**Comment by xuefei1313** [comment]
你是直接使用的vchart还是react-vchart呢？

**Comment by xuefei1313** [comment]
> ` background: [config.background],`
> 
> 我想动态的改变背景的颜色，但是似乎不能做到，这是和渲染方式有关吗

你是使用了响应式插件吗？还是直接使用的vchart或者vchart-react呢？

**Comment by heyi11** [comment]
> > ` background: [config.background],`
> > 我想动态改变背景的颜色，但是似乎无法实现，这和渲染方式有关吗？
> 
> 你是使用了响应式插件吗？还是直接使用的vchart或者react-vchart呢？

是直接使用的react-vchart

**Comment by xiaoluoHe** [comment]
> 是直接使用的react-vchart
你好，请提供一下代码示例，以便复现问题和寻找解决方案
