### ISSUE TITLE
[Bug] 微信小程序图表没显示，使用的包@visactor/taro-vchart，onChartInit 和 onChartReady 回调都触发了

### ISSUE THREAD

**Issue by chenyong0923** [VisActor/VChart#2640]
### Version

@visactor/taro-vchart@1.10.5

### Link to Minimal Reproduction

无

### Steps to Reproduce

```
import { VChart } from '@visactor/taro-vchart';
const Demo = () => {
 const barSpec = {
    type: 'bar',
    data: [
      {
        id: 'barData',
        values: [
          { type: 'Autocracies', year: '1930', value: 129 },
          { type: 'Autocracies', year: '1940', value: 133 },
          { type: 'Autocracies', year: '1950', value: 130 },
          { type: 'Autocracies', year: '1960', value: 126 },
          { type: 'Autocracies', year: '1970', value: 117 },
          { type: 'Autocracies', year: '1980', value: 114 },
          { type: 'Autocracies', year: '1990', value: 111 },
          { type: 'Autocracies', year: '2000', value: 89 },
          { type: 'Autocracies', year: '2010', value: 80 },
          { type: 'Autocracies', year: '2018', value: 80 },
          { type: 'Democracies', year: '1930', value: 22 },
          { type: 'Democracies', year: '1940', value: 13 },
          { type: 'Democracies', year: '1950', value: 25 },
          { type: 'Democracies', year: '1960', value: 29 },
          { type: 'Democracies', year: '1970', value: 38 },
          { type: 'Democracies', year: '1980', value: 41 },
          { type: 'Democracies', year: '1990', value: 57 },
          { type: 'Democracies', year: '2000', value: 87 },
          { type: 'Democracies', year: '2010', value: 98 },
          { type: 'Democracies', year: '2018', value: 99 },
        ],
      },
    ],
    xField: ['year', 'type'],
    yField: 'value',
    seriesField: 'type',
    legends: {
      visible: true,
      orient: 'top',
      position: 'start',
    },
  };

 return (
      <VChart
          style={{ width: '300px', height: '400px' }}
          spec={barSpec}
          canvasId="work-time-chart"
          onChartInit={(chart) => {
            console.log('onChartInit');
          }}
          onChartReady={(chart) => {
            console.log('onChartReady');
          }}
          onChartUpdate={(chart) => {
            console.log('onChartUpdate');
          }}
        />
 )
}

export default Demo
```

### Current Behavior

<img width="1191" alt="L1VzZXJzL3FpYW55dS9MaWJyYXJ5L0NvbnRhaW5lcnMvNVpTTDJDSlUyVC5jb20uZGluZ3RhbGsubWFjL0RhdGEvTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0RpbmdUYWxrTWFjLzY4NjI4NjM1OF92Mi9JbWFnZUZpbGVzLzE3MTUxMzk1NDYwOThfNUMwQzZBQ0QtNERFOC00RDMyLUFBREQtMjQ0NjU3ODc5ODIzLnBuZw==" src="https://github.com/VisActor/VChart/assets/119842780/269e8ad0-9252-43cb-b978-cd7f8ea32327">

图表没显示

### Expected Behavior

图表正常渲染出来

### Environment

```markdown
- OS:
- Browser:
- Framework:
Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1 wechatdevtools/1.06.2306281 MicroMessenger/8.0.5 Language/zh_CN webview/
```

**Comment by chenyong0923** [comment]
Taro版本3.6.28

**Comment by neuqzxy** [comment]
我这边启动了一个新项目没有复现出来，基于taro版本3.6.28，VChart版本@visactor/taro-vchart，可能需要提供一个可复现环境 @chenyong0923

**Comment by chenyong0923** [comment]
重新装了下依赖，可以了

**Comment by chenyun7924** [comment]
我现在的项目也出现这个问题 无法显示
"dependencies": {
		"@babel/runtime": "^7.7.7",
		"@nutui/nutui-react-taro": "^2.7.8",
		"@taroify/core": "^0.1.1-alpha.11",
		"@tarojs/components": "3.6.28",
		"@tarojs/helper": "3.6.28",
		"@tarojs/plugin-framework-react": "3.6.28",
		"@tarojs/plugin-html": "3.6.28",
		"@tarojs/plugin-inject": "^4.0.9",
		"@tarojs/plugin-mock": "^0.0.9",
		"@tarojs/plugin-platform-alipay": "3.6.28",
		"@tarojs/plugin-platform-h5": "3.6.28",
		"@tarojs/plugin-platform-jd": "3.6.28",
		"@tarojs/plugin-platform-qq": "3.6.28",
		"@tarojs/plugin-platform-swan": "3.6.28",
		"@tarojs/plugin-platform-tt": "3.6.28",
		"@tarojs/plugin-platform-weapp": "3.6.28",
		"@tarojs/react": "3.6.28",
		"@tarojs/runtime": "3.6.28",
		"@tarojs/shared": "3.6.28",
		"@tarojs/taro": "3.6.28",
		"@visactor/taro-vchart": "^1.13.5",
		"antd": "^5.23.1",
		"babel-plugin-import": "^1.13.8",
		"babel-preset-taro": "3.6.28",
		"install": "^0.13.0",
		"js-md5": "^0.8.3",
		"mobx": "^6.11.0",
		"mobx-persist-store": "^1.1.3",
		"mobx-react": "^9.1.0",
		"npm": "^11.1.0",
		"react": "^18.0.0",
		"react-dom": "^18.0.0",
		"shelljs": "^0.8.5",
		"taro-iconfont-cli": "^3.3.0"
	},
	"devDependencies": {
		"@babel/core": "^7.8.0",
		"@babel/plugin-proposal-class-properties": "^7.18.6",
		"@babel/plugin-transform-class-properties": "^7.25.9",
		"@babel/preset-react": "^7.26.3",
		"@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
		"@tarojs/cli": "3.6.28",
		"@tarojs/webpack5-runner": "3.6.28",
		"@types/react": "^18.0.0",
		"@types/webpack-env": "^1.13.6",
		"@typescript-eslint/eslint-plugin": "^5.20.0",
		"@typescript-eslint/parser": "^5.20.0",
		"babel-preset-taro": "3.6.28",
		"eslint": "^8.12.0",
		"eslint-config-taro": "3.6.28",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-react-hooks": "^4.2.0",
		"postcss": "^8.4.18",
		"react-refresh": "^0.11.0",
		"stylelint": "^14.4.0",
		"typescript": "^4.1.0",
		"webpack": "5.94.0"
	}
能帮忙看下吗

**Comment by chenyun7924** [comment]
> 我这边启动了一个新项目没有复现出来，基于taro版本3.6.28，VChart版本@visactor/taro-vchart，可能需要提供一个可复现环境 [@chenyong0923](https://github.com/chenyong0923) 麻烦看下
