### ISSUE TITLE
[Feature] vchart地图支持geoJson乱码时解码功能

### ISSUE THREAD

**Issue by zzsssssss** [VisActor/VChart#2694]
### What problem does this feature solve?

当geoJson乱码时，地图正常渲染

### What does the proposed API look like?

当geoJson乱码时，地图正常渲染

**Comment by zzsssssss** [comment]
[621000.json](https://github.com/VisActor/VChart/files/15334726/621000.json)

**Comment by xile611** [comment]
@zzsssssss 这个不属于标准的geoJson，所以vchart暂时不方便处理
