### ISSUE TITLE
如何在相机坐标系中确定图表的原点的位置

### ISSUE THREAD

**Issue by heyi11** [VisActor/VChart#2698]
如题，我想请问一下，我怎么能确定图表原点坐标呢（排除掉padding、legends，纯粹的图表的原点）？因为我想控制这个图表在画面上沿着某一个轨迹运动并且控制它的旋转，需要一个精确的图表的原点坐标，否则就会有很大误差。

**Comment by heyi11** [comment]
能否修改图表的6d（x，y，z，alpha，beta，gamma）位姿

**Comment by neuqzxy** [comment]
![image](https://github.com/VisActor/VChart/assets/26994055/95ebcde3-a450-486c-a395-c4db53e379dd)
@heyi11 猜测你想获得这个红点位置，可以通过右侧API获取

**Comment by xuanhun** [comment]
期待分享你的demo，好奇是个啥效果

**Comment by heyi11** [comment]
> ![image](https://private-user-images.githubusercontent.com/26994055/331455735-95ebcde3-a450-486c-a395-c4db53e379dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjA0NTUsIm5iZiI6MTcxNTkyMDE1NSwicGF0aCI6Ii8yNjk5NDA1NS8zMzE0NTU3MzUtOTVlYmNkZTMtYTQ1MC00ODZjLWEzOTUtYzRkYjUzZTM3OWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA0MjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhN2I3MmE2MzgxYzA5MDZjOGVmMjg4MGI3YThkYmZlYjE0NjlkODNlNmQwYjYyM2FkZWYyYjhjNzQ5ZjViM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c2-CAYY_IfFyyGQy-DDemtiLELrct5oHvG1T74zXlGE) @heyi11 猜测你想获得这个红点位置，可以通过右侧API获取

get！那我有办法自由控制这个坐标吗？ 因为我想通过修改他的6d pose（x，y，z，alpha，beta，gamma）

**Comment by neuqzxy** [comment]
> > ![image](https://private-user-images.githubusercontent.com/26994055/331455735-95ebcde3-a450-486c-a395-c4db53e379dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjA0NTUsIm5iZiI6MTcxNTkyMDE1NSwicGF0aCI6Ii8yNjk5NDA1NS8zMzE0NTU3MzUtOTVlYmNkZTMtYTQ1MC00ODZjLWEzOTUtYzRkYjUzZTM3OWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA0MjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhN2I3MmE2MzgxYzA5MDZjOGVmMjg4MGI3YThkYmZlYjE0NjlkODNlNmQwYjYyM2FkZWYyYjhjNzQ5ZjViM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c2-CAYY_IfFyyGQy-DDemtiLELrct5oHvG1T74zXlGE) @heyi11 猜测你想获得这个红点位置，可以通过右侧API获取
> 
> get！那我有办法自由控制这个坐标吗？ 因为我想通过修改他的6d pose（x，y，z，alpha，beta，gamma）

控制坐标就是移动VChart的位置，正常情况下VChart是在dom容器中的，修改dom位置即可，你可以获得锚点位置，那么执行dom的3d transform感觉就可以

**Comment by heyi11** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/26994055/331455735-95ebcde3-a450-486c-a395-c4db53e379dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjA0NTUsIm5iZiI6MTcxNTkyMDE1NSwicGF0aCI6Ii8yNjk5NDA1NS8zMzE0NTU3MzUtOTVlYmNkZTMtYTQ1MC00ODZjLWEzOTUtYzRkYjUzZTM3OWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA0MjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhN2I3MmE2MzgxYzA5MDZjOGVmMjg4MGI3YThkYmZlYjE0NjlkODNlNmQwYjYyM2FkZWYyYjhjNzQ5ZjViM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c2-CAYY_IfFyyGQy-DDemtiLELrct5oHvG1T74zXlGE) @heyi11 猜测你想获得这个红点位置，可以通过右侧API获取
> > 
> > 
> > get！那我有办法自由控制这个坐标吗？ 因为我想通过修改他的6d pose（x，y，z，alpha，beta，gamma）
> 
> 控制坐标就是移动VChart的位置，正常情况下VChart是在dom容器中的，修改dom位置即可，你可以获得锚点位置，那么执行dom的3d transform感觉就可以 @heyi11

1. 也就是说，我没法直接通过配置项改变对吗？那我可以通过这个options3d控制旋转角吗，alpha、beta、gamma他们的旋转中心是什么，是通过center配置吗
` const options = {
        options3d: {
            enable: true,
            enableView3dTransform: true,
            alpha: 0,
            beta: 0,
            fieldRatio: 15,
            fieldDepth: 500,
            center: { x: 500, y: 520 }
        }
    }`
2. 这个旋转角可以使用响应式修改吗？
