### ISSUE TITLE
[Bug] react-vchart spec.height 设置为undefined不生效

### ISSUE THREAD

**Issue by neuqzxy** [VisActor/VChart#2708]
### Version

1.11.0

### Link to Minimal Reproduction

1.11.0

### Steps to Reproduce

<VChart
        spec={spec}
        className={'testchart'}
        onDimensionClick={() => {
          console.log('abc');
          setABC(!abc);
        }}
      />
      <button onClick={() => setSpec({...spec, height: undefined})}>click</button>

### Current Behavior

设置height为undefined不生效

### Expected Behavior

生效

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
![vqskB91hsJ](https://github.com/VisActor/VChart/assets/6111424/219ece56-f76a-45c0-9242-36256063d37b)

现在的行为是，如果更新的时候，没有`height`，会去拿老的`height`
如果一定要强制更新height，建议新建图表
