### ISSUE TITLE
[Bug] taro按需引入时报错TypeError: Cannot read property 'transformSpec' of null

### ISSUE THREAD

**Issue by HongxuanG** [VisActor/VChart#2720]
### Version

1.11.0

### Link to Minimal Reproduction

1

### Steps to Reproduce

![image](https://github.com/VisActor/VChart/assets/64389111/6f53a729-d866-4334-892f-1745ad96b58d)

![image](https://github.com/VisActor/VChart/assets/64389111/d99c3f7c-e06f-4402-82e6-a8bd54376f40)
![image](https://github.com/VisActor/VChart/assets/64389111/ba1d4210-bdca-461b-b530-960de797fbb0)
![image](https://github.com/VisActor/VChart/assets/64389111/4ae03d92-ca3f-4ee2-9015-e8e6a6363c3c)

### Current Behavior

根据文档操作后报错

### Expected Behavior

不报错，词云显示出来

### Environment

```markdown
- OS:window 11 
- Browser:小程序
- Framework:Taro 3.6.17
```

**Comment by HongxuanG** [comment]
![image](https://github.com/VisActor/VChart/assets/64389111/a6728433-7849-45a7-b51c-16fb7d871ccc)

**Comment by xile611** [comment]
@HongxuanG 参考这个文档： https://visactor.com/vchart/guide/tutorial_docs/Load_on_Demand
需要注册一下图表

**Comment by HongxuanG** [comment]
> @HongxuanG 参考这个文档： https://visactor.com/vchart/guide/tutorial_docs/Load_on_Demand 需要注册一下图表

已经参考了，就是这么写的
![image](https://github.com/VisActor/VChart/assets/64389111/3ffcb98b-2aa0-42be-ac08-5c842d3ccdcf)

**Comment by xiaoluoHe** [comment]
@HongxuanG 代码里注册的是系列，你注册一下图表：
![image](https://github.com/VisActor/VChart/assets/11360419/2d7005ce-24ee-408a-ba40-35b88c21827c)
注册系列通常用于组合图中按需使用：
![image](https://github.com/VisActor/VChart/assets/11360419/4f3991af-4536-4b3e-bec7-13c32b556017)

**Comment by HongxuanG** [comment]
> @HongxuanG 代码里注册的是系列，你注册一下图表： ![image](https://private-user-images.githubusercontent.com/11360419/333015648-2d7005ce-24ee-408a-ba40-35b88c21827c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzYxOTEsIm5iZiI6MTcxNjUzNTg5MSwicGF0aCI6Ii8xMTM2MDQxOS8zMzMwMTU2NDgtMmQ3MDA1Y2UtMjRlZS00MDhhLWJhNDAtMzViODhjMjE4MjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MzEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NDA1ODA2MGFiNmM5MzVjODY4NGJhYWY3NDFhNTdlYmJkMWYyMTEzMjg1ODA0ZDIzM2ZlMDI3NzhjNGEyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.da-JUegTSsooxM1ZjBpvpI-5EX_y4TNMp4AHZYoLoUM) 注册系列通常用于组合图中按需使用： ![image](https://private-user-images.githubusercontent.com/11360419/333015861-4f3991af-4536-4b3e-bec7-13c32b556017.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzYxOTEsIm5iZiI6MTcxNjUzNTg5MSwicGF0aCI6Ii8xMTM2MDQxOS8zMzMwMTU4NjEtNGYzOTkxYWYtNDUzNi00YjNlLWJlYzctMTNjMzJiNTU2MDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MzEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MTEyNWY4ODljM2Q1NDQ2NmFkZTY0NGI5OTBkYzZmNzY2MDRhYzhiZjQyYTBmNWYyYWIwN2I2YTBjODY5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IeU5sW6clHgpr5ZlsBwqzAMaDlfnJ7XfXmH-5rpmtRA)

我用到的并非组合图，而是单单一个词云图

**Comment by xiaoluoHe** [comment]
@HongxuanG 是的，所以不要注册系列，直接注册图表就可以。
```ts
VChart.useRegisters([
  registerWordCloudChart, // 词云
  registerWordCloudShapeChart // 形状词云
])

```

**Comment by HongxuanG** [comment]
> @HongxuanG 是的，所以不要注册系列，直接注册图表就可以。
> 
> ```ts
> VChart.useRegisters([
>   registerWordCloudChart, // 词云
>   registerWordCloudShapeChart // 形状词云
> ])
> ```

🤣感谢感谢，文档好像没相关的描述，我自己看源码看到有这个`registerWordCloudChart`方法就试了一下，成功了
