### ISSUE TITLE
飞书小程序console.log() 不输出。

### ISSUE THREAD

**Issue by meshangqingchen** [VisActor/VChart#2750]
<img width="783" alt="image" src="https://github.com/VisActor/VChart/assets/15076491/4f8b7300-7c9f-4a54-920d-717f4105308e">

<img width="819" alt="image" src="https://github.com/VisActor/VChart/assets/15076491/d2f82853-0a26-4d70-b5ec-33b99b807786">

这样updateSpec之后 spec上的函数生效了。但是log不输出

**Comment by xile611** [comment]
@meshangqingchen 可能是飞书小组件不支持console.log方法吧

**Comment by xile611** [comment]
可以试一下 formatMethod: (a) => {retrun `${a}---`; }
修改一下内容，看看是否能生效，如果生效了，那就是飞书小组件拦截了或者重写了 `console.log` 方法
