### ISSUE TITLE
[Bug] sankey demo in tutorials is not drawn 

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#2765]
### Version

1.11.1

### Link to Minimal Reproduction

https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Types/Sankey?version=1.11.0

### Steps to Reproduce

see 
![image](https://github.com/VisActor/VChart/assets/11360419/dcd7c729-07e6-40a5-a22c-23ecf9636f59)

### Current Behavior

chart is not drawn

### Expected Behavior

draw chart correctly

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
fixed in 1.11.3
