### ISSUE TITLE
[Feature] pie label line support `smooth` line

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#277]
### What problem does this feature solve?

![image](https://github.com/VisActor/VChart/assets/11360419/7dae29bb-6d91-4906-834f-e13538a825e3)

### What does the proposed API look like?

```json
{
    "label": {
        "labelLine": {
           "smooth": true
        }
    }
}
```

**Comment by kkxxkk2019** [comment]
will support in 1.4.0
