### ISSUE TITLE
[Docs] Preview image can't be loaded

### ISSUE THREAD

**Issue by Crayon-ShinChan** [VisActor/VChart#2817]
I found the preview image relevant to my PR #2760 was not loaded. 

To fix, should I change the relative path from `cover: ../../../../public/vchart/preview/bar-customized-label-en_1.11.1.png` to `cover: /vchart/preview/bar-customized-label-en_1.11.1.png`?

**Comment by Crayon-ShinChan** [comment]
I can create a new PR to fix this if my suggestion above is correct.

**Comment by xiaoluoHe** [comment]
Yes, relative paths should not be used. The writing style starting with `/vchart` is correct.

**Comment by Crayon-ShinChan** [comment]
> Yes, relative paths should not be used. The writing style starting with `/vchart` is correct.

Alright, Let me handle it

> Yes, relative paths should not be used. The writing style starting with `/vchart` is correct.

Alright, I'll handle this
