### ISSUE TITLE
[Feature] 希望桑基图（sankey）支持滚动条以及缩略轴

### ISSUE THREAD

**Issue by ErleYb** [VisActor/VChart#2838]
### What problem does this feature solve?

在桑基图中也实现滚动条的功能
1.滚动条：跟现有的滚动条相似的功能，设置显示比例时（0~0.4）能支持显示左侧40%部分的画布，横向或纵向拖动时，能查看剩余部分
样式以及API 参考：https://visactor.com/vchart/demo/scrollbar/basic-scrollbar-bar-chart
![image](https://github.com/VisActor/VChart/assets/154569783/6b9a27b5-c38a-40c9-a1dd-bc2e364d2ca2)
2.缩略轴：跟现有的缩略轴类似的功能，设置start，end支持默认显示缩放比例，拖动或拉伸缩略轴时，能看到剩余部分的画布。
样式以及API 参考：https://visactor.com/vchart/demo/data-zoom/data-zoom-lock?keyword=dataZoom
![image](https://github.com/VisActor/VChart/assets/154569783/77560ca1-a9ab-469f-8533-7cc16d8e3a1c)

### What does the proposed API look like?

1.滚动条：
样式以及API 参考：https://visactor.com/vchart/demo/scrollbar/basic-scrollbar-bar-chart
2.缩放轴：
样式以及API 参考：https://visactor.com/vchart/demo/data-zoom/data-zoom-lock?keyword=dataZoom

**Comment by LofiSu** [comment]
你好请问这个issue有人做了吗，没有的话可以给我做吗

**Comment by xile611** [comment]
\

**Comment by xile611** [comment]
@LofiSu 这个问题可能相对而言比较复杂，你可以在 dev/1.12.0熟悉一下代码，看看有没有思路

**Comment by xuanhun** [comment]
@LofiSu 已经assign 给你了， 可以在issue 下面 或者开发者交流群讨论具体实现方案，

**Comment by xile611** [comment]
fixed in 1.13.0
https://www.visactor.io/vchart/demo/sankey-chart/sankey-with-scrollbar
