### ISSUE TITLE
[Bug] remix+vite 背景下，dev 模式下 tooltip 正常显示，build 后 tooltip 不显示 

### ISSUE THREAD

**Issue by liuxinqiong** [VisActor/VChart#2873]
### Version

1.11.5

### Link to Minimal Reproduction

https://stackblitz.com/edit/remix-run-remix-9yqcbj

### Steps to Reproduce

1. in dev mode, tooltip shown when mouse over
2. run `npm run build` script
3. run `npm start` script
4. tooltip didn't show when mouse over

### Current Behavior

in build mode, tooltip didn't show when mouse over

### Expected Behavior

tooltip should show in both dev and build mode.

### Environment

```markdown
- OS: macos and windows
- Browser: chrome 126.0.6478.127
- Framework: react@18
```

**Comment by xile611** [comment]
@liuxinqiong react-vchart做了默认的按需加载，减小包体积，tooltip没有默认加载，需要手动的引用一下 tooltip
![799f441d-da06-409f-98cb-85c2d87542ec](https://github.com/VisActor/VChart/assets/6111424/28c07196-5ccc-445d-a5ef-17255010c0a5)

**Comment by xile611** [comment]
dev环境因为不会做tree-shaking，所以能正常展示

**Comment by liuxinqiong** [comment]
感谢回复，也许可以在文档某处说明一下这个情况？不然出现了会有些懵逼，会浪费不少找错时间。开发路径上直接拷贝一个示例改一改，不会想到这里还需要手动声明。

**Comment by xile611** [comment]
> 感谢回复，也许可以在文档某处说明一下这个情况？不然出现了会有些懵逼，会浪费不少找错时间。开发路径上直接拷贝一个示例改一改，不会想到这里还需要手动声明。

@liuxinqiong 欢迎参与文档的贡献，文档发现怎么写，都会有人不明白
