### ISSUE TITLE
[Feature] Bar Chart 希望加入 stack gap， Tooltip 在 Theme 配置中希望支持 transitionDuration，Theme 配置中希望加入全局 animation

### ISSUE THREAD

**Issue by iNorthSea** [VisActor/VChart#2886]
### What problem does this feature solve?

semiDV 配置项梳理中，发现的功能点，希望支持

### What does the proposed API look like?

Bar Chart 配置中，希望加入 stack gap 设置
Theme 配置中，希望加入 Tooltip 的跟随动效过渡 transitionDuration 支持
Theme 配置中，希望加入全局 animation

**Comment by xile611** [comment]
fixed in 1.11.9
