### ISSUE TITLE
[Feature] 【WordCloud】

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#2891]
### What problem does this feature solve?

- [x] 支持文字词云
- [ ] 无论是内置的 maskShape 还是自定义，期望都能够提供根据单词数量绘制和自动填充的配置，如下图，可以参考 https://design.weiciyun.com/

| | |
|--------|--------|
| ![image](https://github.com/VisActor/VChart/assets/135952300/5704ff3d-890f-4d6d-9f84-8b5a6482e307) | ![image](https://github.com/VisActor/VChart/assets/135952300/57ac7fc1-8bbf-48d9-b947-b4a2601f8707) | 

- [x] colorMode: 'linear' 配置始终返回  colorList[0]，并且缺少 demo 【可能是还没有支持】
![image](https://github.com/VisActor/VChart/assets/135952300/0c1031ca-e2e8-4f02-b466-2bc8c19f1280)

- [ ] 支持 maskShape 的遮罩层配置，实现如下功能：(有一个遮罩的图形背景)
<img width="1037" alt="image" src="https://github.com/VisActor/VChart/assets/135952300/c0c8eb9c-7914-4bcd-809e-422ccb266a96">

### What does the proposed API look like?

NA

**Comment by xile611** [comment]
@kkxxkk2019 
现在分三种主要的算法：
* 普通词云 grid算法，支持自动填充，配置如下：
```
 wordCloudConfig: {
    layoutMode: 'shape',
    zoomToFit: {
      repeat: true
    }
  },
```
* 形状词云，默认支持填充，如果要关闭自动填充词，需要如下配置：
```
wordCloudShapeConfig: {
    fillingTimes: 0 // 默认值是4，也就是所有的词会尝试填充4次
  },
```

**Comment by xile611** [comment]
遮罩层如果上传的是图片，会存在糊的问题

**Comment by xile611** [comment]
1.12.0已支持
