### ISSUE TITLE
[Feature] 希望主题可以修改 legend 分页器页码颜色

### ISSUE THREAD

**Issue by webiamcome** [VisActor/VChart#2901]
### What problem does this feature solve?

暗色模式主题会导致 legend 分页器页码看不清楚，效果如下图：
![image](https://github.com/VisActor/VChart/assets/20121525/c2cb3d84-718d-4e6c-a907-d1fd5723abc9)
![image](https://github.com/VisActor/VChart/assets/20121525/b2c37d52-271a-4cc9-b5d2-205a8156c22b)

### What does the proposed API look like?

none

**Comment by xiaoluoHe** [comment]
1.11.6 版本已修复：https://github.com/VisActor/VChart/pull/2825
主题新增 3 个图例相关的颜色 token 
![image](https://github.com/VisActor/VChart/assets/11360419/e209e347-63d2-4a68-b961-0d3e296a5937)
