### ISSUE TITLE
Inner Offset without Tooltip

### ISSUE THREAD

**Issue by jonyeokj** [VisActor/VChart#2923]
### What problem does this feature solve?

Right now, when I put inner offset on my time axis to make my graph look smaller and shift my labels inwards, i.e
`innerOffset: {
   left: 20,
   right: 20,
},`
I can still hover on the tooltip on the outer area of the graph and I get unexpected data, according to the y-axis of the graph. I would like an option to toggle this off or another alternative to inner Offset.

### What does the proposed API look like?

No change to API

**Comment by xile611** [comment]
@jonyeokj can you share the whole spec of your case?
