### ISSUE TITLE
[Bug] container-box类名冲突

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#2924]
### Version

latest

### Link to Minimal Reproduction

-

### Steps to Reproduce

tooltip中有一个div的类名是container-box，这个类名太普遍了，会有其他库使用，导致样式错乱

### Current Behavior

-

### Expected Behavior

希望将相关类名加上前缀，避免误用外部样式导致渲染错误

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
@Rui-Sun 可以让用户暂时规避一下，考虑在 1.12.0 版本增加prefix来规避冲突问题

**Comment by xile611** [comment]
fixed in https://github.com/VisActor/VChart/pull/3321

**Comment by xile611** [comment]
fixed in 1.13.1
