### ISSUE TITLE
[Bug] 韦恩图渲染失败、控制台报错

### ISSUE THREAD

**Issue by xsy-kucha** [VisActor/VChart#2936]
### Version

1.11.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

使用示例（https://www.visactor.io/vchart/demo/venn-chart/venn-chart?keyword=vennChart ）中的spec在自己的代码中渲染
![image](https://github.com/VisActor/VChart/assets/75476633/2f1ba2af-816c-4e0d-811e-10827f0f0627)
控制台会有下面的报错，图表并没有渲染出来
![image](https://github.com/VisActor/VChart/assets/75476633/ff3da731-5030-4013-9825-ecc7efc78c1b)

### Current Behavior

none

### Expected Behavior

none

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
@xsy-kucha 需要做一下图表注册
![51dd5542-f020-424b-806f-101cc97074c6](https://github.com/user-attachments/assets/81c58637-8629-4650-9cae-e4c2bd55e3aa)
