### ISSUE TITLE
[Feature]It is expected that when the pie chart labels need to be abbreviated, they can automatically wrap to the next line.

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#2952]
### What problem does this feature solve?

![img_v3_02cr_46ec36f5-5f59-4568-88c1-55a18d0e7b5g](https://github.com/user-attachments/assets/3146e0af-0f6d-4217-bc81-dce7de9a8909)

As shown in the above picture, it is difficult to handle without automatic line wrapping. Even if rich text is used, it is difficult for users to grasp the timing of line wrapping.

### What does the proposed API look like?

no

**Comment by xiaoluoHe** [comment]
supported richtext in label, see demo: https://visactor.io/vchart/demo/pie-chart/richtext-autowrap
![image](https://github.com/user-attachments/assets/3aae3893-e6fa-4f80-a216-70e942fbb198)
