### ISSUE TITLE
[Feature] support custom shape type of markline

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#2959]
### What problem does this feature solve?

![image](https://github.com/user-attachments/assets/e88399f3-8424-4e5f-a14b-f2406d51ed28)
To create this effect

### What does the proposed API look like?

no

**Comment by xile611** [comment]
1. `markLine.label.labelBackground` 新增配置 `customShape`回调函数，同

```
(datum: any, attrs: any, path: ICustomPath2D) => {
  const width = attrs.width;
  const deltaY = attrs.y1 - attrs.y;

  path.moveTo(0, deltaY);
  path.quadraticCurveTo(0.45 * width, 0.67 * deltaY, 0.5 * width, 0);
  path.quadraticCurveTo(0.55 * width, 0.67 * deltaY, width, deltaY);
  path.lineTo(0, deltaY);
  path.closePath();
  return path;
};
```

参考图表： https://visactor.com/vchart/demo/custom/custom-shape

在vrender-components中，通过 pathProxy 机制实现自定义渲染图形，

```
this.graphicItem.pathProxy = (attrs: Partial<IGraphicAttribute>) => {
      return setCustomizedShape(this.data, attrs, new CustomPath2D());
    };
```
