### ISSUE TITLE
【按需加载】taro-vchart 如何实现按需加载

### ISSUE THREAD

**Issue by tangguo13** [VisActor/VChart#2967]
我正在使用taro开发微信小程序 如何实现按需加载呢 

我看了按需加载的相关文档，但是不太明白。我是安装taro-vchart 还是安装 vchart 

我试着对着react-vchart 部分进行修改还是会报错 请问可以给出一个大概的步骤吗 谢谢啦

**Comment by xile611** [comment]
参考这个教程：https://visactor.io/vchart/guide/tutorial_docs/Load_on_Demand
具体遇到什么问题，需要描述清楚，不然也没法帮助到你 @tangguo13

**Comment by tangguo13** [comment]
![6c471b4e461a8a39ef741760954cc47](https://github.com/user-attachments/assets/7fbcf39d-0b5a-4a16-8c1b-7454ae8a12c9)
![82e50f200a79f7de7620e140485c25b](https://github.com/user-attachments/assets/1571c244-2b41-4bbc-b3b2-d3d7ee25b4dd)
![image](https://github.com/user-attachments/assets/38d772ad-0ec9-4273-a323-b5c5de2b6c9c)

如上图所示 我用了文档的方法好像包的体积变大了 是我用的方法有问题吗  控制台还有报错信息

**Comment by tangguo13** [comment]
补充一下 版本信息 "@visactor/taro-vchart": "^1.11.8",
![image](https://github.com/user-attachments/assets/7f73438e-9765-4de7-9012-e75bde4711fd)

**Comment by xile611** [comment]
@tangguo13 方便创建最小复现的demo吗？
另外你说的体积变大是相较于什么而言的？

**Comment by tangguo13** [comment]
好的 非常抱歉 我提供一个最小化的git仓库 git clone https://gitee.com/tangguo13/v-chart-demo.git 谢谢

**Comment by xiaoluoHe** [comment]
@tangguo13 按需之后包体积变大，有点不符合逻辑。可以查看下，是否在 develop 环境下，没有进行 minify；
可以在 production 环境编译测试下。

**Comment by tangguo13** [comment]
我编译了 生产包体积还是相当大 一个分包体积都超过4M了

**Comment by xile611** [comment]
taro-vchart 1.12.0版本新增语义化标签，默认支持按需加载，
具体参考文档：https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/taro
