### ISSUE TITLE
[Bug] 安装最新版本的库 按照官网示例直接报错

### ISSUE THREAD

**Issue by tangguo13** [VisActor/VChart#2971]
### Version

1.11.8

### Link to Minimal Reproduction

no

### Steps to Reproduce

第一步：npm install @visactor/taro-vchart

第二步：
import VChart from '@visactor/taro-vchart';
import React, { useState } from "react";
import { View } from '@tarojs/components';

// 定义 props 接口
interface Props {
  dataSource: any;
}

const BarChart: React.FC<Props> = (_props) => {
   // 1. 准备图表配置项与数据
   const [spec, setSpec] = useState({
    data: [
      {
        id: 'data1',
        values: [
          {
            value: 335,
            name: '直接访问'
          },
          {
            value: 310,
            name: '邮件营销'
          },
          {
            value: 274,
            name: '联盟广告'
          },
          {
            value: 235,
            name: '视频广告'
          },
          {
            value: 400,
            name: '搜索引擎'
          }
        ]
      }
    ],
    type: 'pie',
    outerRadius: 0.6,
    innerRadius: 0.5,
    categoryField: 'name',
    valueField: 'value',
    legends: {
      visible: true
    }
  });

  // 向Chart组件, 传递参数.
  return (
    <View
      style={{
        border: '1px solid #eeeeee',
        width: '90vw'
      }}
    >
      <VChart
        type="weapp"
        spec={spec}
        canvasId="pie"
        style={{ height: '35vh', width: '100%' }}
        onChartInit={() => {
          console.log('init pie');
        } }
        onChartReady={() => {
          console.log('ready pie');
        } }
        onChartUpdate={() => {
          console.log('update pie');
        } } />
    </View>
  );
};

export default BarChart

### Current Behavior

我想通过官网的demo实现对应的图表 结果控制台报错了 
![image](https://github.com/user-attachments/assets/c7f4f061-bc1a-4a71-b9c5-fe7a7e4fdb21)

### Expected Behavior

希望能直接实现官网上显示的效果

### Environment

```markdown
-微信开发工具
```

**Comment by tangguo13** [comment]
好的 谢谢 我创建了一个分支 2971可以复现这个问题 git clone https://gitee.com/tangguo13/v-chart-demo.git

**Comment by xiaoluoHe** [comment]
版本先降级到 1.11.1 试一下，我们再排查下

**Comment by wuhongdan** [comment]
> 1. 版本先降级到 1.11.1 试一下，我们再排查下
> 2. VChartSimple 组件需要传自定义加载的 VChart
> 
>  <VChartSimple
>         type={Taro.getEnv() as any}
>         style={{ width: "100%", height: "150px" }}
>         spec={spec}
>         canvasId="bar-chart"
>        // 这个遗漏了
>         chartConstructor={VChart}
>         onChartReady={() => {
>           console.log("onChartReady");
>         }}
>  />
你好 你这边代码中chartConstructor={VChart}的VChart是怎么引入的？我尝试了好几种引入方法都会报错
