### ISSUE TITLE
[Bug] updateDataSync接口 重复调用在viewbox很小的时候 渲染元素未清除

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VChart#2986]
### Version

develop

### Link to Minimal Reproduction

none

### Steps to Reproduce

1

### Current Behavior

![image](https://github.com/user-attachments/assets/79780d7e-2dcc-4a98-b518-a45b0d5e0aef)

### Expected Behavior

1

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
fixed in 1.11.10
