### ISSUE TITLE
[Bug] legend.item.maxWidth has the same effect with legend.item.width

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#300]
### Version

1.1.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

const spec ={
    "type": "bar",
    "xField": [
        "230727153136073",
        "10001"
    ],
    "yField": [
        "10002"
    ],
    "direction": "vertical",
    "seriesField": "20001",
    "data": [
        {
            "id": "data",
            "values": [
                {
                    "10001": "销售额",
                    "10002": "5734340.8279953",
                    "10003": "230727153136032",
                    "20001": "销售额",
                    "230727153136032": "5734340.8279953",
                    "230727153136073": "家具"
                },
                {
                    "10001": "数量",
                    "10002": "8491",
                    "10003": "230727171340017",
                    "20001": "数量",
                    "230727153136073": "家具",
                    "230727171340017": "8491"
                },
                {
                    "10001": "销售额",
                    "10002": "4865589.799788475",
                    "10003": "230727153136032",
                    "20001": "销售额",
                    "230727153136032": "4865589.799788475",
                    "230727153136073": "办公用品"
                },
                {
                    "10001": "数量",
                    "10002": "21401",
                    "10003": "230727171340017",
                    "20001": "数量",
                    "230727153136073": "办公用品",
                    "230727171340017": "21401"
                },
                {
                    "10001": "销售额",
                    "10002": "5469023.505149841",
                    "10003": "230727153136032",
                    "20001": "销售额",
                    "230727153136032": "5469023.505149841",
                    "230727153136073": "技术"
                },
                {
                    "10001": "数量",
                    "10002": "7642",
                    "10003": "230727171340017",
                    "20001": "数量",
                    "230727153136073": "技术",
                    "230727171340017": "7642"
                }
            ],
            "transform": [
                {
                    "type": "fields",
                    "options": {
                        "fields": {
                            "10001": {
                                "alias": "指标名称 "
                            },
                            "10002": {
                                "alias": "指标值 "
                            },
                            "20001": {
                                "alias": "图例项 ",
                                "domain": [
                                    "销售额",
                                    "数量"
                                ]
                            },
                            "230727153136032": {
                                "alias": "销售额"
                            },
                            "230727153136073": {
                                "alias": "类别",
                                "domain": [
                                    "办公用品",
                                    "技术",
                                    "家具"
                                ]
                            },
                            "230727171340017": {
                                "alias": "数量"
                            }
                        }
                    }
                }
            ]
        }
    ],
    "axes": [
        {
            "type": "band",
            "tick": {
                "visible": false
            },
            "grid": {
                "visible": false,
                "style": {
                    "stroke": "#DADCDD",
                    "lineWidth": 1,
                    "lineDash": [
                        4,
                        2
                    ]
                }
            },
            "orient": "bottom",
            "visible": true,
            "domainLine": {
                "visible": true,
                "style": {
                    "lineWidth": 1,
                    "stroke": "#989999"
                }
            },
            "title": {
                "visible": false,
                "text": "类别",
                "style": {
                    "fontSize": 12,
                    "fill": "#363839",
                    "fontWeight": "normal"
                }
            },
            "label": {
                "visible": true,
                "style": {
                    "fontSize": 12,
                    "fill": "#6F6F6F",
                    "angle": 0,
                    "fontWeight": "normal"
                },
                "minGap": 4,
                "flush": true
            },
            "hover": true,
            "background": {
                "visible": true,
                "state": {
                    "hover": {
                        "fillOpacity": 0.08,
                        "fill": "#141414"
                    }
                }
            },
            "paddingInner": 0.15,
            "paddingOuter": 0.075
        },
        {
            "type": "linear",
            "tick": {
                "visible": false,
                "style": {
                    "stroke": "rgba(255, 255, 255, 0)"
                }
            },
            "niceType": "accurateFirst",
            "grid": {
                "visible": true,
                "style": {
                    "stroke": "#DADCDD",
                    "lineWidth": 1,
                    "lineDash": [
                        4,
                        2
                    ]
                }
            },
            "orient": "left",
            "visible": true,
            "domainLine": {
                "visible": true,
                "style": {
                    "lineWidth": 1,
                    "stroke": "rgba(255, 255, 255, 0)"
                }
            },
            "title": {
                "visible": false,
                "text": "销售额",
                "style": {
                    "fontSize": 12,
                    "fill": "#363839",
                    "fontWeight": "normal"
                }
            },
            "label": {
                "visible": true,
                "style": {
                    "fontSize": 12,
                    "fill": "#6F6F6F",
                    "angle": 0,
                    "fontWeight": "normal"
                }
            },
            "hover": true,
            "background": {
                "visible": true,
                "state": {
                    "hover": {
                        "fillOpacity": 0.08,
                        "fill": "#141414"
                    }
                }
            },
            "zero": true,
            "nice": true
        }
    ],
    "color": {
        "field": "20001",
        "type": "ordinal",
        "range": [
            "#2E62F1",
            "#4DC36A"
        ],
        "specified": {}
    },
    "legends": [
        {
            "type": "discrete",
            "orient": "right",
            "position": "start",
            "layoutType": "normal-inline",
            "visible": true,
            "hover": false,
            "maxCol": 1,
            "title": {
                "textStyle": {
                    "fontSize": 12,
                    "fill": "#6F6F6F"
                }
            },
            "item": {
            maxWidth:1000,

                "spaceRow": 0,
                "spaceCol": 0,
                "padding": {
                    "top": 4,
                    "bottom": 4,
                    "left": 4,
                    "right": 22
                },
                "background": {
                    "style": {
                        "fillOpacity": 0.001
                    }
                },
                "label": {
                    "style": {
                        "fontSize": 12,
                        "fill": "#6F6F6F"
                    }
                },
                "shape": {
                    "style": {
                        "symbolType": "square"
                    }
                }
            },
            "pager": {
                "textStyle": {},
                "handler": {
                    "style": {},
                    "state": {
                        "disable": {}
                    }
                }
            },
            "padding": {
                "top": 0,
                "bottom": 0,
                "left": 16,
                "right": 0
            }
        }
    ],
    "label": {
        "visible": false,
        "overlap": {
            "hideOnHit": true,
            "clampForce": true
        },
        "style": {
            "fontSize": 12,
            "fontWeight": "normal",
            "fill": null,
            "strokeOpacity": 1
        },
        "position": "inside",
        "smartInvert": {
            "brightColor": "#fff",
            "darkColor": "#363839",
            "brightStroke": null,
            "brightStrokeWidth": 2,
            "darkStroke": "rgba(255, 255, 255, 0.8)",
            "darkStrokeWidth": 2
        }
    },
    "hover": {
        "enable": true
    },
    "select": {
        "enable": true
    },
    "bar": {
        "state": {
            "hover": {
                "cursor": "pointer",
                "fillOpacity": 0.8,
                "stroke": "#58595B",
                "lineWidth": 1,
                "zIndex": 500
            },
            "selected": {
                "cursor": "pointer",
                "fillOpacity": 1,
                "stroke": "#58595B",
                "lineWidth": 1
            },
            "selected_reverse": {
                "fillOpacity": 0.3,
                "strokeWidth": 0.3
            }
        },
        "clipByLayout": true
    },
    "background": "rgba(255, 255, 255, 0)",
    "animation": false,
    "brush": {
        "inBrush": {
            "colorAlpha": 1
        },
        "outOfBrush": {
            "colorAlpha": 0.2
        }
    },
    "hash": "f6e7590f3bd7e1a0ea495db0964a0191"
}
const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/20367445/64dc780b-855d-4ee2-93ea-30479f071e26)

### Expected Behavior

As it is written in the spec doc:
![image](https://github.com/VisActor/VChart/assets/20367445/47c04fa2-36d6-4c66-b036-93b0f8bfc64b)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
maxWidth 指的图例项可以占据的最大宽度，如果超出则会将文本自动省略，如果图例项本身的宽度小于最大宽度，那就按照图例项自身的宽度展示。

**Comment by kkxxkk2019** [comment]
Fixed in https://github.com/VisActor/VRender/pull/227

**Comment by kkxxkk2019** [comment]
重新暗转下依赖，在 '@visactor/vrender-components': 0.13.7 版本解决了
