### ISSUE TITLE
[Feature] label of scatterPlot support 'inside' position.

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#301]
### What problem does this feature solve?

scatterChart.label.position need to support 'inside' option to make the label show inside the point and do not influenced by the label.overlap.hideOnHit config.
just like this:
![image](https://github.com/VisActor/VChart/assets/20367445/4d7d3833-7a7f-42e2-ac5e-dce0d3e4d4ac)

### What does the proposed API look like?

{
label:{
position:'inside'
}
}

**Comment by xiaoluoHe** [comment]
you can config like this:
```js
{
    label: {
    visible: true,
    position: 'center',
  },
}
```

**Comment by da730** [comment]
> 

It works. Please update the spec doc.
