### ISSUE TITLE
图表一直显示在上面

### ISSUE THREAD

**Issue by rankaifeng** [VisActor/VChart#3013]
![image](https://github.com/user-attachments/assets/4c2f6b9a-0547-4f10-ab6c-5a7bf145ad84)
在有弹出层的情况下 图表一直在上面

**Comment by xile611** [comment]
@rankaifeng 确认一下dom节点 zIndex

**Comment by rankaifeng** [comment]
我已经把ddd这层的zIndex设置成最大了 但这个图标始终在最上面

**Comment by xile611** [comment]
> 我已经把ddd这层的zIndex设置成最大了 但这个图标始终在最上面

多排查几层
或者你看看能不能复现问题，这样我们排查不了

**Comment by rankaifeng** [comment]
![image](https://github.com/user-attachments/assets/8025b5b3-1cf6-4c94-8b16-0a2211bb30fe)
大佬 奇怪 突然又报这个错

**Comment by xile611** [comment]
版本号确认一下，要用最新的1.11.10版本
按照我们的issue 规范提供bug信息哦，不然沟通成本很高的

**Comment by rankaifeng** [comment]
好的 我已经重新提交了

**Comment by xile611** [comment]
duplicated with #3015
