### ISSUE TITLE
[Feature] Tooltip的content value配置能否在回调中支持HTML格式返回值

### ISSUE THREAD

**Issue by KingGanZeng** [VisActor/VChart#3021]
### What problem does this feature solve?

我们正在从echarts迁移到vchart，但在tooltip的配置上，vchart在配置回调之后只能解析为string。
<img width="300" alt="image" src="https://github.com/user-attachments/assets/c4b5d75e-6554-4ec8-a242-461713eec572">

### What does the proposed API look like?

echarts可以支持以HTML格式进行渲染
<img width="300" alt="image" src="https://github.com/user-attachments/assets/9cc84bc8-2a6b-4467-a73d-a11ec62d151e">
这是对应的echarts配置：[tooltip html](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=MYewdgzgLgBA7iOMC8MDaBaADAOgIwA0MATEdjgCxGkxUx4424UC6A3AFAcgAOUAluBQwA3hxgwAHgEFJ_CAC5R4iTCgBPHgFMlAcmABDKFoDmIAE7rdBFRIAmRg0rS6AsuGsxdAFQCuWz10AdS07QO8AC19AgDFzfkCAZSMk3zBdFhUAXxsJdVl5JTFVNU0dLwA3AwAbf11s3JgILXitRXRbZRKJMAMAW3LdQABUwDpVQFyM6077R2c8AFYsagBmRZJiOmI8AA4iPCW53YoAdmoANiwWRpKNbT1q_jAAzqyVS5UoEBBqgR4izogIoglFBzP4rjAAGYWPpGYzmJQACh4BnM_QgAEoUAA-LrdUCQWAiGAw8wAaxaRGarQgADl-loiFVagyYA4oAYAJJgOxaSQwLLCZGovoQTjdGD46DwRAANRq_mECDgaDZnO5vPYUwl4ClSoAwl8LIrZfKtDAcVgYAB-LwmcxaLTpGB6e1hTha-1QXzmMAwAAGABIRCTyeYskGqfw2nSBllAFj_AB4IMiwFig0K0Tgmf4sgmAPTJgyphGAeudACvWicLvug6mqWmQACJQNULAog_rDWG2AAjAzAUl2kBpOwKADEWgME4nbAbaZESrlzJgACp6FgsFkAKT5qtY9F-sWqF4SF5ZNhAA)

我不确定vchart是否支持这个能力，但至少在配置文档中是没有的。希望能尽快支持！

**Comment by xuanhun** [comment]
迁移到VChart 的原因是什么？ @KingGanZeng

**Comment by KingGanZeng** [comment]
我们的场景是一个大数据量的表格渲染，原来是element+echarts的方式，经常会出现卡死，目前看到VisActor有canvas表格+图表的渲染方式，所以在做技术迁移

**Comment by skie1997** [comment]
@KingGanZeng 
可以这样实现：
1. 创建自定义tooltip 容器
2. 在showTooltip中拿到回调信息确定tooltip内容和位置
```ts
const spec = {
  type: 'rose',
  data: [
    {
      id: 'id0',
      values: data,
      fields: dataFields
    }
  ],
  padding: {
    top: 30
  },
  radius: 0.8,
  innerRadius: 0,
  categoryField: 'month',
  valueField: 'value',
  seriesField: 'type',
  stack: true,
  rose: {
    style: {
      stroke: 'white',
      lineWidth: 1
    }
  },
  legends: {
    visible: true,
    orient: 'top',
    interactive: true
  },
  axes: [
    {
      orient: 'radius',
      visible: true,
      tick: { tickCount: 3 },
      grid: { visible: true, style: { lineDash: [0] } },
      max: 150
    },
    {
      orient: 'angle',
      visible: true,
      domainLine: { visible: true, smooth: false },
      grid: { visible: true, smooth: false },
      label: {
        visible: true,
        style: {
          fill: '#000'
        }
      }
    }
  ]
};

  const cs = new VChart(spec, {
    dom: CONTAINER_ID
  });

function initTooltip() {
  const createElement = (parentEl, tag, classList, style, id) => {
    const element = document.createElement(tag);
    if (classList) {
      element.classList.add(...classList);
    }
    if (style) {
      Object.keys(style).forEach(key => {
        element.style[key] = style[key];
      });
    }
    if (id) {
      element.id = id;
    }
    parentEl.appendChild(element);
    
    return element;
  };

  const customTooltip = createElement(
    document.getElementById(CONTAINER_ID),
    'div',
    [],
    {
      position: 'absolute',
      boxSizing: 'border-box',
      width: '200px',
      height: '100px',
      background:'white',
      //backdropFilter: 'blur(2px)',
      // borderRadius: '50%',
      boxShadow: 'rgba(0, 0, 0, 0.1) 0px 4px 12px 0px',
      visibility: 'hidden',
      pointerEvents: 'none',
      transform: 'translate(-50%, -50%)',
      top: 0,
      left: 0
    },
    'tooltip'
  );
}

initTooltip();
cs.setTooltipHandler({
  showTooltip: (activeType, tooltipData, params) => {
    const tooltip = document.getElementById('tooltip');
    tooltip.style.left = params.event.x + 'px';
    tooltip.style.top = params.event.y + 'px';
    if (params.changePositionOnly) {
      return;
    }
    tooltip.style.visibility = 'visible';
  },
  hideTooltip: () => {
    const tooltip = document.getElementById('tooltip');
    tooltip.style.visibility = 'hidden';
  },
  release: () => {
    // tooltipChart.release();
    const tooltip = document.getElementById('tooltip');
    tooltip.remove();
  }
});
cs.renderAsync()
```

![20240731155205_rec_](https://github.com/user-attachments/assets/89896e89-9056-4a06-a459-6d1e0fe7a217)

**Comment by KingGanZeng** [comment]
这种方案的成本会比较大，其实期望的效果是一个HTML或富文本格式的渲染，我理解如果是像custom tooltip demo展示那样的复杂交互才需要这样去维护的。
另外如果是通过VTable来内嵌VChart渲染的话，我没办法拿到里面每一个chart的实例，所以这种方案可能会有些局限性。

**Comment by xile611** [comment]
https://www.visactor.io/vchart/option/barChart#tooltip.updateElement

@KingGanZeng 试试这个自定义方式吧

**Comment by ZhangTomLiang** [comment]
<img width="410" alt="image" src="https://github.com/user-attachments/assets/8a0a68b8-7da4-432e-94b0-69cfa5b29d60">

可以试试这个
  tooltip: {
        parentElement: document.getElementById(instanceId.value),
        dimension: {
          updateContent: (prev: any) => {
            Object.entries(prev[0].datum.text_appear)
              .sort((a, b) => b[1] - a[1])
              .forEach(([key, value]) => {
                prev.push({
                  key: key,
                  value: `${value}次`
                })
              })

            prev.shift()
          }
        },
        style: {
          valueLabel: {
            multiLine: false,
            textAlign: 'left'
          },
          maxContentHeight: 600
        }
      },
