### ISSUE TITLE
[Feature] 希望可以支持图表坐标分布不均匀 例如坐标范围0-5 坐标分布：0-3 3-3.5 3.5-4 4-4.5 4.5-5

### ISSUE THREAD

**Issue by kingshuoxu** [VisActor/VChart#3022]
### What problem does this feature solve?

解决了某些情况下希望坐标轴分布不均匀 例如：
![image](https://github.com/user-attachments/assets/76b84bc7-5dbd-447e-aa2c-6755d7151df1)

### What does the proposed API look like?

axes.xxx 支持传入一个数组，数组数量是坐标轴数量，数组中的item可以为坐标对应的value（或者其他）

**Comment by skie1997** [comment]
需求较为定制化，不符合轴的绘制原则，暂不考虑实现
