### ISSUE TITLE
柱状图怎么实现不同颜色的柱子

### ISSUE THREAD

**Issue by echo713** [VisActor/VChart#3038]
柱状图怎么实现不同颜色的柱子  就一个坐标系

**Comment by xiaoluoHe** [comment]
vchart 会根据 `seriesField` 对数据进行分组，映射到不同颜色。可以参考下官网的 demo:
- 通过 `color` 配置：https://visactor.com/vchart/demo/bar-chart/group-bar-with-padding
- 通过 `bar.style.fill` 配置：https://visactor.com/vchart/demo/bar-chart/bi-direction-bar

如果不能满足你的需求，还请补充更详细的信息。
