### ISSUE TITLE
[Feature] smartInvert does not support specified color of dark and bright.

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#305]
### What problem does this feature solve?

smartInvert must support specified color of dark and light. Labels will show the specified bright color when the mark is dark, and the dark color when the mark is bright.

### What does the proposed API look like?

smartInvert:{
darkColor:'#FFFFFF',
brightColor:'#000000'
}

**Comment by pairone** [comment]
增加smartInvert时fillStrategy和 strokeStrategy的四种策略：series（baseMark色），invertSeries（执行智能反色），similarSeries（智能反色的补色），null（不执行智能反色，保持fill设置的颜色）


label: {
    fill: '#fff'
    stroke: '#000'
    smartInvert: {
        fillStrategy: 'series' | 'invertSeries' | 'similarSeries' | null
        strokeStrategy: 'series' | 'invertSeries' | 'similarSeries' | null
        brightColor: '#fff'
        darkColor: '#000'
    }
}

**Comment by pairone** [comment]
/**
   * fillStrategy四种策略：
   * - base（baseMark色），
   * - invertBase（执行智能反色），
   * - similarBase（智能反色的补色），
   * - null（不执行智能反色，保持stroke设置的颜色）
   * @default 'invertSeries'
   */
  fillStrategy?: 'base' | 'invertBase' | 'similarBase' | 'null';
  /**
   * strokeStrategy的四种策略:
   * - base（baseMark色），
   * - invertBase（执行智能反色），
   * - similarBase（智能反色的补色），
   * - null（不执行智能反色，保持fill设置的颜色）
   * @default 'series'
   */
  strokeStrategy?: 'base' | 'invertBase' | 'similarBase' | 'null';
