### ISSUE TITLE
[Bug] react-vchart 图表使用的类型和官网例子不一致

### ISSUE THREAD

**Issue by knoxnoe** [VisActor/VChart#3065]
### Version

1.11.11

### Steps to Reproduce

[codesandbox](https://codesandbox.io/p/devbox/vchart-tooltip-vjt39h?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzkpc2qa00073b6jbhrni6cm%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzkpc2q900023b6j21sw5rwd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzkpc2q900043b6jlvpfs2ne%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzkpc2qa00063b6j7yrdw6eo%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzkpc2q900023b6j21sw5rwd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzkpc2q900013b6jri6sg0zm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzkq4w5900023b6pdekykmk5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.css%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzlb3frx00023b6j8qghofto%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzkpc2q900023b6j21sw5rwd%2522%252C%2522activeTabId%2522%253A%2522clzlb3frx00023b6j8qghofto%2522%257D%252C%2522clzkpc2qa00063b6j7yrdw6eo%2522%253A%257B%2522id%2522%253A%2522clzkpc2qa00063b6j7yrdw6eo%2522%252C%2522activeTabId%2522%253A%2522clzkpcl6j000n3b6j2c2xyqtp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzkpc2q900053b6jbqbqdwro%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzkpcl6j000n3b6j2c2xyqtp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzkpc2q900043b6jlvpfs2ne%2522%253A%257B%2522id%2522%253A%2522clzkpc2q900043b6jlvpfs2ne%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzkpc2q900033b6jm8xsfugm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clzkpc2q900033b6jm8xsfugm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Current Behavior

![image](https://github.com/user-attachments/assets/8e348ee1-59fa-408d-912d-28c20a3b5893)

### Expected Behavior

https://www.visactor.io/vchart/demo-react/component/ring
![image](https://github.com/user-attachments/assets/35513d48-216e-4939-aa28-6f6f8221b144)

**Comment by xile611** [comment]
@knoxnoe codesandbox 没有发布

**Comment by knoxnoe** [comment]
> @knoxnoe codesandbox 没有发布

抱歉才看到，我看已经 fixed 🎉
