### ISSUE TITLE
当数据为0时 期望显示图表

### ISSUE THREAD

**Issue by rankaifeng** [VisActor/VChart#3066]
![image](https://github.com/user-attachments/assets/900e1daf-82ad-49e9-9a59-ccd9d2a18b45)

**Comment by xile611** [comment]
@rankaifeng 数据全为0，需要展示成什么类型呢？
1.12.0已经实现了相关功能

**Comment by rankaifeng** [comment]
如果全为0 期望展示这样
![image](https://github.com/user-attachments/assets/cf7820ca-3061-4bf6-bca3-95d489aa7e8c)

**Comment by xile611** [comment]
@rankaifeng 1.12.0 可以支持该功能
可以试用不稳定版本： [1.12.0-alpha.10](https://www.npmjs.com/package/@visactor/vchart/v/1.12.0-alpha.10)

**Comment by xile611** [comment]
相关PR： https://github.com/VisActor/VChart/pull/2893/files

**Comment by rankaifeng** [comment]
好的 感谢！
