### ISSUE TITLE
引入库过后 微信开发工具提示体积过大编译不通过

### ISSUE THREAD

**Issue by rankaifeng** [VisActor/VChart#3072]
如果单个文件里面引入了
![image](https://github.com/user-attachments/assets/111ee657-fd5d-40c3-8489-9810ca25dae4)
在微信开发工具里面编译不通过 请问一下有什么解决方法吗
![image](https://github.com/user-attachments/assets/59c404a5-e0b3-4b54-8d13-67dcbb3290fc)

**Comment by xile611** [comment]
@rankaifeng 可以试一下vchart 1.12.0的alpha版本
引入 <LineChart /> 类似
相关PR : https://github.com/VisActor/VChart/pull/3016

**Comment by rankaifeng** [comment]
![1723184180232](https://github.com/user-attachments/assets/5467d838-bbf7-41c3-ab51-6c6e0513bda2)
![1723184180237](https://github.com/user-attachments/assets/d251d6e3-077d-42ea-83b5-fa5ca1b39b53)
我今天上午就是用了alpha这个版本 然后报错  现在又改回来了 但是编译又不通过了

**Comment by xile611** [comment]
@rankaifeng 你是用的什么图表类型，如果是线图就引用LineChart ,其他的类似

**Comment by rankaifeng** [comment]
我用的是饼图

**Comment by xile611** [comment]
> 我用的是饼图

 `import { PieChart } from '@visactor/taro-vchart'

**Comment by rankaifeng** [comment]
@visactor/taro-vchart这个版本还是用v1.11.11这个版本吗
![image](https://github.com/user-attachments/assets/c65f3a4f-7429-449b-9e5d-3aa668c38dc3)
![image](https://github.com/user-attachments/assets/7b7cb876-6189-41ff-a6f7-f9ffa16c3377)
![image](https://github.com/user-attachments/assets/bdf806f9-8584-4641-aacd-9d0a9957aebd)

**Comment by rankaifeng** [comment]
可以了
我是这样引的
![image](https://github.com/user-attachments/assets/ab2b6792-3147-4ff6-8a4b-2ad82e5e9efd)
但微信开发工具还是提示超大小了
![image](https://github.com/user-attachments/assets/df27521c-3732-4dee-b315-be602e696182)

**Comment by xile611** [comment]
@rankaifeng 
使用1.12.0 的alpha版本，然后
```
import { PieChart } from '@visactor/taro-vchart'
```

你上面的用法，还是引用全包

**Comment by rankaifeng** [comment]
我用了1.12.0 的alpha版本 页面图表会闪现一下 然后就不见了
我还是改回了之前的版本 
我在微信开发工具把这个勾上就不报大小上限了
![image](https://github.com/user-attachments/assets/37ba8a2f-237c-4afb-9b8e-b2b012f174a3)

**Comment by xile611** [comment]
@rankaifeng 可以使用一下 1.12.0-alpha.11 版本，看看还不会有闪现的问题

**Comment by rankaifeng** [comment]
还是有闪现问题

**Comment by rankaifeng** [comment]
结果我把预览分包体积在开放工具里面设置了4M 预览编译是没问题 但是如果上传就还是提示超出限制了

**Comment by xile611** [comment]
@rankaifeng 使用按需加载的语义化标签，包体积怎么样

**Comment by rankaifeng** [comment]
我只要引入了 我的分包大小都是4M多

**Comment by xile611** [comment]
> 我只要引入了 我的分包大小都是4M多

那不对，tree-shaking 没有生效

**Comment by rankaifeng** [comment]
webpack

**Comment by xile611** [comment]
> webpack

webpack 4 还是webpack5，有没有打开tree-shaking?

**Comment by rankaifeng** [comment]
webpack5 应该是没有打开tree-shaking

**Comment by xile611** [comment]
> webpack5 应该是没有打开tree-shaking

那你打开tree-shaking 啊...

**Comment by rankaifeng** [comment]
ok 已经好了

**Comment by xile611** [comment]
> ok 已经好了

闪现问题？

**Comment by rankaifeng** [comment]
闪现问题还是存在，因为项目要验收 所以我就自己用canvas写了一个饼图 你们可以看看那个闪现的问题

**Comment by xile611** [comment]
@rankaifeng 可以试一下 1.12.0-alpha.12 版本，闪现的问题已经修复了

**Comment by xile611** [comment]
1.12.0已发布，可以尝试一下新的 1.12.0版本
