### ISSUE TITLE
[Bug] name of markLine.startSymbol.symbolType do not match the displayed shape.

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#308]
### Version

1.1.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

![image](https://github.com/VisActor/VChart/assets/20367445/754b51e1-9d3f-4485-aa6b-d9e707773156)

### Current Behavior

'triangleUp'
'triangleDown'
'triangleRight'
'triangleLeft'
will not match the displayed shape.

### Expected Behavior

orientation of the shape match their names.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by skie1997** [comment]
it can be resloved when set `markLine.startSymbol.autoRotate: false`
![image](https://github.com/VisActor/VChart/assets/40675330/9936a58e-ca28-4d78-8218-78277779ebe0)

**Comment by kkxxkk2019** [comment]
@da730 upgrade your dependencies, make sure `@visactor/vrender-components` is at `0.13.10`
