### ISSUE TITLE
[Bug] updateSpec issue in common chart

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#3082]
### Version

~1.11.9

### Link to Minimal Reproduction

null

### Steps to Reproduce

1. use common chart with multiple dataset
2. only use data id in series.data and make data.values undefined
3. call updateSpec using the same spec as parameter
```
const spec= {
type:'common',
data:[
{
id: 'dataset1',
values:[{
...some data values
}]
}
],
series:{
data:{
id: 'dataset1' //only set data id, don't assign values
}
}
}
```

### Current Behavior

This is a bug in updateDataViewInData:
![image](https://github.com/user-attachments/assets/2a351eeb-f5e1-4d05-9479-e57a9e810b48)

![image](https://github.com/user-attachments/assets/acfc5525-25ba-4a3b-9312-ea4082cda218)
![image](https://github.com/user-attachments/assets/d39a1b69-b58c-4ee1-b0ce-12408df771b3)
data.values is undefind and caused an error in addVChartProperty in dataview
![image](https://github.com/user-attachments/assets/55e5b0d4-123e-425f-b3f8-f7761ea35d64)

### Expected Behavior

update the chart normally

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
@da730 报错的问题，下个版本(1.12.1)修复

不过不太建议上面的用法，可以在系列中直接通过 `dataId` 进行配置

参考文档： https://www.visactor.io/vchart/option/commonChart-series-line#dataId
