### ISSUE TITLE
[Bug] Element render order is wrong

### ISSUE THREAD

**Issue by 666haiwen** [VisActor/VChart#3103]
### Version

1.11.12

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/dazzling-bhaskara-d49dh8?file=%2Fsrc%2Findex.ts%3A2%2C27

### Steps to Reproduce

1. Create line view with two series line
2. sorted legend and x-axis
3. set the first series in legend missing the first few data points on the x-axis

### Current Behavior

![img_v3_02dt_3b7e2ddb-c087-4f90-a42c-333884fb71bg](https://github.com/user-attachments/assets/6a3d7e3b-f802-4c21-87bf-56f509ef81e2)
The second half of the point is green, but the line is red

### Expected Behavior

Hope the second half of the line is green also because "Africa" is behind "EU" in legend

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
配置了 `sortDataByAxis` 导致的问题
