### ISSUE TITLE
[Docs] use richtext to implement two-line label of donut chart

### ISSUE THREAD

**Issue by xile611** [VisActor/VChart#3107]
![image](https://github.com/user-attachments/assets/048b1985-7b92-49c2-98f4-45c681ee77a0)

**Comment by xiaoluo997** [comment]
This demo, I'm going to do, just configure the rich text using `formatMethod` in the `label configuration`

**Comment by xiaoluo997** [comment]
大佬，这个还需要做吗，这两天才把代码跑起来，发现已经有`formatMethod` 相关的demo了。 
![pie-richtext-twoLine-label_1 12 1 png](https://github.com/user-attachments/assets/41555d91-ffc7-4605-a8a1-5f47d7933b07)

**Comment by xile611** [comment]
related demo: https://www.visactor.io/vchart/demo/pie-chart/richtext-autowrap
