### ISSUE TITLE
1.12.0版本报错

### ISSUE THREAD

**Issue by rankaifeng** [VisActor/VChart#3110]
这就是1.12.0版本报的错
![image](https://github.com/user-attachments/assets/f3b36516-ed53-4cfb-ac7b-ec81e32845db)

**Comment by xile611** [comment]
@rankaifeng 
<img width="501" alt="image" src="https://github.com/user-attachments/assets/075ddb3a-7773-42ee-ada7-858c00f3c0b5">

<img width="413" alt="image" src="https://github.com/user-attachments/assets/b8bbe506-f45a-4f12-9580-de2bae5de44c">


项目中写死了引用路径吗？

**Comment by rankaifeng** [comment]
写死了引用路径是什么意思？
![image](https://github.com/user-attachments/assets/e24e0d43-1d93-4c28-b4fa-252fac210622)

**Comment by xile611** [comment]
> 写死了引用路径是什么意思？ ![image](https://private-user-images.githubusercontent.com/16712359/359696282-e24e0d43-1d93-4c28-b4fa-252fac210622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDQwOTYsIm5iZiI6MTcyNDIwMzc5NiwicGF0aCI6Ii8xNjcxMjM1OS8zNTk2OTYyODItZTI0ZTBkNDMtMWQ5My00YzI4LWI0ZmEtMjUyZmFjMjEwNjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAxMjk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNGE0MTI4ZGIxZjhmYjRkOGQ5MjM4ZGQ4ZDViOTBhMTM0ZDBkOWQyMWVmYzk5YTYwZTc1OTYxODFiNTM1MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ghQ2FxN5qps3EMDQJZ7wLGmh2evAKS7GckQ722uI8s4)

应该是你项目的问题，我本地测试都是OK的
如果排查不到问题，可以上传一个项目复现问题

提issue的时候最好按照我们的规范提交问题，提高沟通效率
