### ISSUE TITLE
[Feature] Axis labels support automatic line breaks and automatic truncation

### ISSUE THREAD

**Issue by xile611** [VisActor/VChart#3135]
### What problem does this feature solve?

![image](https://github.com/user-attachments/assets/5685cec6-6b2e-4f8b-8b62-daac9a36a06e)

### What does the proposed API look like?

text style:

```
{
  maxLineCount?: number;
  maxLineWidth?: number;
}
```

**Comment by xiaoluoHe** [comment]
supported in v1.12.5
