### ISSUE TITLE
[Bug] memory issue with memoize

### ISSUE THREAD

**Issue by neuqzxy** [VisActor/VChart#3141]
### Version

1.12.1

### Link to Minimal Reproduction

1.12.1

### Steps to Reproduce

all chart

### Current Behavior

内存未回收，有些result被保存到memoize的闭包内

### Expected Behavior

内存回收

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
fixed in v1.12.2
