### ISSUE TITLE
[Bug] transform to sort doesn't work

### ISSUE THREAD

**Issue by Crayon-ShinChan** [VisActor/VChart#3144]
### Version

1.12.1

### Link to Minimal Reproduction

use demo site

### Steps to Reproduce

Use this code
```js
const spec = {
  type: 'line',
  data: {
    values: [
      {
        time: '2:00',
        value: 8
      },
      {
        time: '4:00',
        value: 9
      },
      {
        time: '6:00',
        value: 11
      },
      {
        time: '8:00',
        value: 14
      },
      {
        time: '10:00',
        value: 16
      },
      {
        time: '12:00',
        value: 17
      },
      {
        time: '14:00',
        value: 17
      },
      {
        time: '99:00',
        value: 16
      },
      {
        time: '18:00',
        value: 15
      }
    ],
    transforms: [
      {
        type: "fields",
        options: {
          fields: {
            time: {
              type: "ordinal",
              sortIndex: 1,
            },
          },
        },
      },
    ]
  },
  xField: 'time',
  yField: 'value'
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

### Current Behavior

time = `99:00` is at the second last position of x axis.
![CleanShot 2024-08-27 at 20 02 52@2x](https://github.com/user-attachments/assets/07431396-6b48-4654-b8d0-9ed33ee77fd9)

### Expected Behavior

time = `99:00` should at the last position of x axis because it's the largest one

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
@Crayon-ShinChan 因为设置了字段类型为 `ordinal` ，这里并不会将string类型转换为数值进行排序，现在只有数值类型的，支持正确的排期

**Comment by Crayon-ShinChan** [comment]
@xile611 我参考的这个文档：
![CleanShot 2024-08-29 at 11 18 04@2x](https://github.com/user-attachments/assets/a934b211-ff42-47bd-b713-80872199a939)

这个文档是不是 outdated 了呀，我可以帮忙修一下。因为我看上面写的就是 排序 ordinal，而且 transforms 成了 transform

**Comment by xile611** [comment]
@Crayon-ShinChan 应该是文档表达有误，你看数据结果可以发现，ordinal 字段的排序是按照值出现的顺序进行了一个排序
例子中， date 字段对应的值是， '1-2', '1-3', '1-4', '1-2', '1-3', '1-4'，最终排序后是 '1-2','1-2', '1-3', '1-3', '1-4', '1-4'
这种使用于文档中的那种场景，存在分组字段的情况下，对维度值进行一个顺序排序，对有分组的线图比较有用

但是这种情况，不会对字符串进行解析

**Comment by xile611** [comment]
@Crayon-ShinChan 非常欢迎贡献文档和bugfix
