### ISSUE TITLE
[Bug] The fontFamily property in ITheme does not work for Safari

### ISSUE THREAD

**Issue by Crayon-ShinChan** [VisActor/VChart#3145]
### Version

1.12.1 & 1.11.3

### Link to Minimal Reproduction

https://github.com/Crayon-ShinChan/runiu

### Steps to Reproduce

1. clone the [repo](https://github.com/Crayon-ShinChan/runiu) and follow the instruction in README.md (or you can visit [https://runiu.vercel.app](https://runiu.vercel.app) directly)
2. test the font in web and mobile devices (For me, MacOS Chrome & iPhone Safari & MacOS Safari)
3. Check if the font is Gabarito

### Current Behavior

MacOS Chrome works good:
![CleanShot 2024-08-28 at 00 21 07@2x](https://github.com/user-attachments/assets/1cfdc9c1-4b1a-4ec6-a7e9-da79f2475d99)

iPhone Safari (or MacOS Safari), Gabarito font works for all places except VCharts. **This means there is Gabarito in Safari**
<img src="https://github.com/user-attachments/assets/b5e5617b-5967-4ac9-8615-450d723da5ee" width="300">

### Expected Behavior

iPhone Safari, font of VCharts should be Gabarito

### Environment

```markdown
- OS: MacOS and iOS
- Browser: Chrome and Safari
- Framework: Next.js (React)
```

### Any additional comments?

The code to register theme locates in file `src/components/stats/crs-chart/index.tsx`

```tsx
useEffect(() => {
  if (typeof window !== "undefined") {
    const { ThemeManager } = require("@visactor/vchart");
    ThemeManager.registerTheme("userTheme", {
      fontFamily: "Gabarito",
    });
    ThemeManager.setCurrentTheme("userTheme");
  }
}, []);
```

If we don't register the theme but instead just set certain parts of the chart in spec using the "Gabarito" font (for example, the title using this font), the behavior remains the same.

**Comment by Crayon-ShinChan** [comment]
another reproduction: https://codesandbox.io/p/sandbox/eloquent-danny-3wqztz?workspaceId=2e62888e-1f42-46bf-8281-82af1b701470

Chrome:
![CleanShot 2024-08-28 at 22 59 33@2x](https://github.com/user-attachments/assets/d41401e4-55f2-4786-98e4-8db419791d4c)

Safari
![CleanShot 2024-08-28 at 23 01 24@2x](https://github.com/user-attachments/assets/e6fb3899-a214-4c66-aa5b-5d5f2b46c385)

**Comment by xile611** [comment]
网络字体加载的后，font-family 名称不一致导致的问题

**Comment by Crayon-ShinChan** [comment]
https://github.com/vercel/next.js/discussions/43452

Vercel will give the Gabarito font css name as __Gabarito_77a4cc

**Comment by Crayon-ShinChan** [comment]
https://github.com/vercel/next.js/pull/53608

This is the PR from Nextjs to make font name fixed

**Comment by Crayon-ShinChan** [comment]
Since the Next.js 14.3.0 hasn't been released. Here is the work around:

Define gabarito as css variable
```tsx
import { Gabarito } from "next/font/google";
const gabarito = Gabarito({ subsets: ["latin"], variable: "--font-gabarito" });
<body className={cn("min-h-screen font-sans", gabarito.variable)}>
  <Providers>
    <Toaster richColors />
    <Navbar />
    {children}
    <SpeedInsights />
    <Analytics />
  </Providers>
</body>
```

in tailwind config file
```ts
import { type Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";

export default {
  content: ["./src/**/*.tsx"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-gabarito)", ...fontFamily.sans],
      },
    },
  },
  plugins: [],
} satisfies Config;
```

Then register the theme
```tsx
  useEffect(() => {
    if (typeof window !== "undefined") {
      const font = window
        .getComputedStyle(document.body)
        .getPropertyValue("--font-gabarito")
        .trim();
      const { ThemeManager } = require("@visactor/vchart");
      ThemeManager.registerTheme("userTheme", {
        fontFamily: font,
      });
      ThemeManager.setCurrentTheme("userTheme");
    }
  }, []);
```
