### ISSUE TITLE
[Feature] Rose Chart label

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#317]
### What problem does this feature solve?

The label is necessary. 

### Current:
<img width="220" alt="image" src="https://github.com/VisActor/VChart/assets/49136199/b5b79d7f-652f-4ec3-af1b-e112f5df50c1">
 

### Expected

<img width="773" alt="image" src="https://github.com/VisActor/VChart/assets/49136199/02ccd1d4-4919-40d3-97c2-c2f8933e4605">

**Comment by pairone** [comment]
![image](https://github.com/VisActor/VChart/assets/40026218/7ccf37ce-f5a4-4073-8742-3786bcd8a2e9)

https://github.com/VisActor/VChart/pull/523
