### ISSUE TITLE
[Bug] morph动画期间触发交互会报错;

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#3174]
![Image](https://github.com/user-attachments/assets/6bdf1c83-187d-4201-8cb6-501dbcd27729)

https://visactor.com/vchart/demo/storytelling/bar-to-scatter?version=1.12.2

**Comment by xile611** [comment]
fixed in vrender: https://github.com/VisActor/VRender/pull/1422

**Comment by xile611** [comment]
fixed in v1.12.4
