### ISSUE TITLE
[Bug] Tooltips页面内文案有误

### ISSUE THREAD

**Issue by jaydeezhang** [VisActor/VChart#3176]
### Version

1.0.0

### Link to Minimal Reproduction

https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Tooltip

### Steps to Reproduce

-

### Current Behavior

Tooltip 提示信息是我们在使用 VChart 图表时，用以显示在图表不同元素上的附加信息，通过鼠标悬停操作展示出来。本教程主要讲解提示信心组件的相关概念以及组成，关于组件更加详细的配置及示例，详见[配置项文档]
![image](https://github.com/user-attachments/assets/17da6749-d408-4ec8-b07b-6a2f3054d2a6)

### Expected Behavior

提示信心组件 -> 提示信息组件

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

-

**Comment by xiaoluoHe** [comment]
@jaydeezhang 方便的话，可以提个 issue 改一下，欢迎参与贡献～
