### ISSUE TITLE
翻遍了文档都没发现这个东西在哪里隐藏或者修改

### ISSUE THREAD

**Issue by H-Sven** [VisActor/VChart#3179]
<img width="829" alt="image" src="https://github.com/user-attachments/assets/779288fc-0c11-4767-972c-3d377e5c6fe4">

整个文档看了一遍了

**Comment by skie1997** [comment]
> <img alt="image" width="829" src="https://private-user-images.githubusercontent.com/26042365/364454545-779288fc-0c11-4767-972c-3d377e5c6fe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTQzODQsIm5iZiI6MTcyNTg1NDA4NCwicGF0aCI6Ii8yNjA0MjM2NS8zNjQ0NTQ1NDUtNzc5Mjg4ZmMtMGMxMS00NzY3LTk3MmMtM2QzNzdlNWM2ZmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAzNTQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0OTNiNTkxMjcwMDAxOWVmZTE4YjdlNGI0MzM0YWEwYmVjZjMyZTZlYzVhNjVkMjc3ODA2N2I4N2I0MjVjZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zC8-lWZ-t76-f6aUrFBN8nX5jC1PTMVy_hTPc06lMrU">
> 整个文档看了一遍了

是交互后产生的背景对么？属于crosshair组件，隐藏的话可以做如下配置：
```ts
crosshair: {
  xField: {
    visible: false
  }
}
```
更多配置：https://www.visactor.io/vchart/option/barChart#crosshair
