### ISSUE TITLE
[Bug] Radar chart render error when label visible

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#319]
### Version

1.1.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

const spec = {
  type: 'radar',
  data: [
    {
      id: '白金',
      values: [
        {
          key: '力量',
          value: 5
        },
        {
          key: '速度',
          value: 5
        },
        {
          key: '射程',
          value: 3
        },
        {
          key: '持续',
          value: 5
        },
        {
          key: '精密',
          value: 5
        },
        {
          key: '成长',
          value: 5
        }
      ]
    }
  ],
  categoryField: 'key',
  valueField: 'value',
  point: {
    visible: false // 不展示点
  },
  label: {
    visible: true,
  },
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// 只为了方便控制台调试用，不要拷贝
window['vchart'] = vchart;

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/49136199/24e66416-00e4-4702-9c06-f5ff5a3d13cc)
--

### Expected Behavior

render correctly

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
label relies on basic mark, try:
```js
{
  point: {   style:{ size: 0 } },
  label: { visible: true }
}
```

**Comment by youngwinds** [comment]
if user want to hide the points, I think the most common way is to set `visible:false`.

Data driven the label mark, rather the point driven the label mark. So, label should be independent of points.

@xiaoluoHe Is there a plan to resolve the dependency between labels and points ? @

**Comment by xiaoluoHe** [comment]
> 

You're right, it's necessary to take this point into consideration. We will consider this in the follow-up plan.
