### ISSUE TITLE
[Feature] LinearProgress chart need text content

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#320]
### What problem does this feature solve?

More text content. 

1. The major indicator name title
2. The major indicator value with  custom style
3. The secondary description text 
4. all the text need Tooltip

### Expected

![image](https://github.com/VisActor/VChart/assets/49136199/737a8c1f-bd94-40e0-8116-aa74ab439c71)

**Comment by youngwinds** [comment]
![e6cd108c-975a-4eff-89a5-b5a292f8f97b](https://github.com/VisActor/VChart/assets/49136199/aa2f8ebc-fef2-47eb-b108-14d823b6387e)
![e6cd108c-975a-4eff-89a5-b5a292f8f97b](https://github.com/VisActor/VChart/assets/49136199/86422775-a20d-48d8-84fc-dc77c7d491ab)

**Comment by kkxxkk2019** [comment]
We can use `axes` and `extensionMark` to achieve.

1. LinearProgress: https://codesandbox.io/s/linearprogress-c3d2kl
![image](https://github.com/VisActor/VChart/assets/135952300/a0d8d96b-8147-4b12-9716-2490bee99242)

2. CircularProgress: https://codesandbox.io/s/circularprogress-9rqn7d
![image](https://github.com/VisActor/VChart/assets/135952300/c89697c4-69ff-40f9-95d3-44e8105be93b)
