### ISSUE TITLE
[Bug] 监听事件触发不生效

### ISSUE THREAD

**Issue by ZhangTomLiang** [VisActor/VChart#3221]
如何在area图标上注册事件，比如移入不同的markArea，就触发事件，不知道怎么去获取移入当前的这条markarea数据。

![image](https://github.com/user-attachments/assets/f4c87c16-f5e4-47b9-96bf-bc5a1fb0ef48)

**Comment by xile611** [comment]
@ZhangTomLiang 现在怎么监听事件的？
事件监听相关文档： https://www.visactor.io/vchart/api/API/event

`e.node.getDatum()` 试试

**Comment by ZhangTomLiang** [comment]
不行啊
 
 chart.on('click', async (e) => {
      console.log(e.node.getDatum())
    })
    
    
<img width="826" alt="image" src="https://github.com/user-attachments/assets/03f103b0-d047-4dc4-adc4-bcd3ae1be25f">

**Comment by xile611** [comment]
> 不行啊
> 
> chart.on('click', async (e) => { console.log(e.node.getDatum()) })
> 
> <img alt="image" width="826" src="https://private-user-images.githubusercontent.com/18275926/367480797-03f103b0-d047-4dc4-adc4-bcd3ae1be25f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTAxNTUsIm5iZiI6MTcyNjY0OTg1NSwicGF0aCI6Ii8xODI3NTkyNi8zNjc0ODA3OTctMDNmMTAzYjAtZDA0Ny00ZGM0LWFkYzQtYmNkM2FlMWJlMjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA4NTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NjliZTIxMzkwYjFkMTY0ZDFmNDc3MTQ3OWYzNTg2Zjc0MDQ5MTNiOTQ4NGU4YzQ0YTdjNmUyNDA2NGY5NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T0D9HVjHVgm3eR7d8z9xjOpYZk1J1PRfwkSIr87X4rE">

加一下判断


```
chart.on('click', (e) => {
const element = e?.item;

if (element && element.mark.markType === 'area') {
  console.log(element.getDatum())
}
})
```

**Comment by xile611** [comment]
@ZhangTomLiang 使用上述方法测试一下，如果还是有问题，可以新开issue
