### ISSUE TITLE
[Bug] 'type' is missing in 'PointerMarkSpec'

### ISSUE THREAD

**Issue by mengxi-ream** [VisActor/VChart#3227]
### Version

1.12.4

### Link to Minimal Reproduction

documentation site

### Steps to Reproduce

Many gauge charts in the documentation website with pointer spec (`PointerMarkSpec`) don't specify the type of pointer, but I noticed that `PointerMarkSpec` requires `type`. 

For example, the following spec will get the error: `Property 'type' is missing in type '{ style: { fill: string; }; }' but required in type 'PointerMarkSpec'.`

```tsx
const spec: IGaugeChartSpec = {
  type: 'gauge',
  data: [
    {
      id: 'id0',
      values: [
        {
          type: '目标A',
          value: 0.7
        }
      ]
    }
  ],
  radiusField: 'type',
  categoryField: 'type',
  valueField: 'value',
  outerRadius: 0.8,
  innerRadius: 0.75,
  startAngle: -240,
  endAngle: 60,
  gauge: {
    type: 'circularProgress',
    cornerRadius: 20,
    progress: {
      style: {
        fill: '#1664ff'
      }
    },
    track: {
      style: {
        fill: '#000'
      }
    }
  },
  pointer: {
    style: {
      fill: '#333'
    }
  }
};
```

I'd like to inquire about our preferences regarding the type parameter. Should we implement it as type = 'path' | 'rect' with a default value such as 'path', or do we want to require users to explicitly specify the type?

### Current Behavior

users have to specify the type as TypeScript asks them to do so

### Expected Behavior

Should we implement it as type = 'path' | 'rect' with a default value such as 'path', or do we want to require users to explicitly specify the type?

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by skie1997** [comment]
> ### Version
> 1.12.4
> 
> ### Link to Minimal Reproduction
> documentation site
> 
> ### Steps to Reproduce
> Many gauge charts in the documentation website with pointer spec (`PointerMarkSpec`) don't specify the type of pointer, but I noticed that `PointerMarkSpec` requires `type`.
> 
> For example, the following spec will get the error: `Property 'type' is missing in type '{ style: { fill: string; }; }' but required in type 'PointerMarkSpec'.`
> 
> ```tsx
> const spec: IGaugeChartSpec = {
>   type: 'gauge',
>   data: [
>     {
>       id: 'id0',
>       values: [
>         {
>           type: '目标A',
>           value: 0.7
>         }
>       ]
>     }
>   ],
>   radiusField: 'type',
>   categoryField: 'type',
>   valueField: 'value',
>   outerRadius: 0.8,
>   innerRadius: 0.75,
>   startAngle: -240,
>   endAngle: 60,
>   gauge: {
>     type: 'circularProgress',
>     cornerRadius: 20,
>     progress: {
>       style: {
>         fill: '#1664ff'
>       }
>     },
>     track: {
>       style: {
>         fill: '#000'
>       }
>     }
>   },
>   pointer: {
>     style: {
>       fill: '#333'
>     }
>   }
> };
> ```
> 
> I'd like to inquire about our preferences regarding the type parameter. Should we implement it as type = 'path' | 'rect' with a default value such as 'path', or do we want to require users to explicitly specify the type?
> 
> ### Current Behavior
> users have to specify the type as TypeScript asks them to do so
> 
> ### Expected Behavior
> Should we implement it as type = 'path' | 'rect' with a default value such as 'path', or do we want to require users to explicitly specify the type?
> 
> ### Environment
> ```
> - OS:
> - Browser:
> - Framework:
> ```
> 
> ### Any additional comments?
> _No response_

Thank you for raising this issue, default `PointerMarkSpec.type` is `'path'`, i think `PointerMarkSpec.type` should not be required. It will be a small change in this file `packages/vchart/src/series/gauge/interface.ts`, if you are interested to contribute our project, you can submit a pull request.

**Comment by mengxi-ream** [comment]
> > ### Version
> > 1.12.4
> > ### Link to Minimal Reproduction
> > documentation site
> > ### Steps to Reproduce
> > Many gauge charts in the documentation website with pointer spec (`PointerMarkSpec`) don't specify the type of pointer, but I noticed that `PointerMarkSpec` requires `type`.
> > For example, the following spec will get the error: `Property 'type' is missing in type '{ style: { fill: string; }; }' but required in type 'PointerMarkSpec'.`
> > ```tsx
> > const spec: IGaugeChartSpec = {
> >   type: 'gauge',
> >   data: [
> >     {
> >       id: 'id0',
> >       values: [
> >         {
> >           type: '目标A',
> >           value: 0.7
> >         }
> >       ]
> >     }
> >   ],
> >   radiusField: 'type',
> >   categoryField: 'type',
> >   valueField: 'value',
> >   outerRadius: 0.8,
> >   innerRadius: 0.75,
> >   startAngle: -240,
> >   endAngle: 60,
> >   gauge: {
> >     type: 'circularProgress',
> >     cornerRadius: 20,
> >     progress: {
> >       style: {
> >         fill: '#1664ff'
> >       }
> >     },
> >     track: {
> >       style: {
> >         fill: '#000'
> >       }
> >     }
> >   },
> >   pointer: {
> >     style: {
> >       fill: '#333'
> >     }
> >   }
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'd like to inquire about our preferences regarding the type parameter. Should we implement it as type = 'path' | 'rect' with a default value such as 'path', or do we want to require users to explicitly specify the type?
> > ### Current Behavior
> > users have to specify the type as TypeScript asks them to do so
> > ### Expected Behavior
> > Should we implement it as type = 'path' | 'rect' with a default value such as 'path', or do we want to require users to explicitly specify the type?
> > ### Environment
> > ```
> > - OS:
> > - Browser:
> > - Framework:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Any additional comments?
> > _No response_
> 
> Thank you for raising this issue, default `PointerMarkSpec.type` is `'path'`, i think `PointerMarkSpec.type` should not be required. It will be a small change in this file `packages/vchart/src/series/gauge/interface.ts`, if you are interested to contribute our project, we very much welcome your pull request.

Thank you for the confirmation. The PR has been created.
