### ISSUE TITLE
[Bug] Pie chart label angle is not working.

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#323]
### Version

1.1.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

const spec = {
  type: 'pie',
  data: [
    {
      id: 'id0',
      values: [
        { type: 'oxygen', value: '46.60' },
        { type: 'silicon', value: '27.72' },
        { type: 'aluminum', value: '8.13' },
        { type: 'iron', value: '5' },
        { type: 'calcium', value: '3.63' },
        { type: 'sodium', value: '2.83' },
        { type: 'potassium', value: '2.59' },
        { type: 'others', value: '3.5' }
      ]
    }
  ],
  outerRadius: 0.8,
  valueField: 'value',
  categoryField: 'type',
  title: {
    visible: true,
    text: 'Statistics of Surface Element Content'
  },
  legends: {
    visible: true,
    orient: 'left'
  },
  label: {
    visible: true,
    position: "inside",
    style: {
      fill: "#fff",
      angle: 0,
    } 
  },
  tooltip: {
    mark: {
      content: [
        {
          key: datum => datum['type'],
          value: datum => datum['value'] + '%'
        }
      ]
    }
  }
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

<img width="1079" alt="image" src="https://github.com/VisActor/VChart/assets/49136199/d3a9ebbc-795b-4beb-85f9-94fe0bdecf41">

### Expected Behavior

angle render correctly

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pairone** [comment]
![image](https://github.com/VisActor/VChart/assets/40026218/289c903e-f859-499d-a0e4-7b6f649d3a5e)
