### ISSUE TITLE
[Bug] radiusField causes the gauge pointer to disappear

### ISSUE THREAD

**Issue by mengxi-ream** [VisActor/VChart#3233]
### Version

1.12.4

### Link to Minimal Reproduction

doc website

### Steps to Reproduce

```
const spec: IGaugeChartSpec = {
  type: 'gauge',
  data: [
    {
      id: 'pointer',
      values: [
        {
          type: 'A',
          value: 0.6
        }
      ]
    },
    {
      id: 'segment',
      values: [
        {
          type: 'Level 1',
          color: '#07A35A',
          value: 0.4
        },
        {
          type: 'Level 2',
          color: '#FFC528',
          value: 0.6
        },
        {
          type: 'Level 3',
          color: '#E33232',
          value: 0.8
        }
      ]
    }
  ],
  gauge: {
    type: 'gauge',
    dataIndex: 1,
    categoryField: 'type',
    valueField: 'value',
    seriesField: 'type',
    segment: {
      style: {
        cornerRadius: 10,
        fill: datum => datum['color']
      }
    }
  },
  pointer: {
    style: {
      fill: '#666666'
    }
  },
  radiusField: "type",
  categoryField: 'type',
  valueField: 'value',
  outerRadius: 0.9,
  innerRadius: 0.6,
  startAngle: -180,
  endAngle: 0,
  centerY: '100%',
  layoutRadius: 'auto',
  axes: [
    {
      type: 'linear',
      orient: 'angle',
      inside: true,
      grid: { visible: false }
    }
  ],
};
```

### Current Behavior

gauge pointer disappeared

### Expected Behavior

gauge pointer should not disappear

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by skie1997** [comment]
> ### Version
> 1.12.4
> 
> ### Link to Minimal Reproduction
> doc website
> 
> ### Steps to Reproduce
> ```
> const spec: IGaugeChartSpec = {
>   type: 'gauge',
>   data: [
>     {
>       id: 'pointer',
>       values: [
>         {
>           type: 'A',
>           value: 0.6
>         }
>       ]
>     },
>     {
>       id: 'segment',
>       values: [
>         {
>           type: 'Level 1',
>           color: '#07A35A',
>           value: 0.4
>         },
>         {
>           type: 'Level 2',
>           color: '#FFC528',
>           value: 0.6
>         },
>         {
>           type: 'Level 3',
>           color: '#E33232',
>           value: 0.8
>         }
>       ]
>     }
>   ],
>   gauge: {
>     type: 'gauge',
>     dataIndex: 1,
>     categoryField: 'type',
>     valueField: 'value',
>     seriesField: 'type',
>     segment: {
>       style: {
>         cornerRadius: 10,
>         fill: datum => datum['color']
>       }
>     }
>   },
>   pointer: {
>     style: {
>       fill: '#666666'
>     }
>   },
>   radiusField: "type",
>   categoryField: 'type',
>   valueField: 'value',
>   outerRadius: 0.9,
>   innerRadius: 0.6,
>   startAngle: -180,
>   endAngle: 0,
>   centerY: '100%',
>   layoutRadius: 'auto',
>   axes: [
>     {
>       type: 'linear',
>       orient: 'angle',
>       inside: true,
>       grid: { visible: false }
>     }
>   ],
> };
> ```
> 
> ### Current Behavior
> gauge pointer disappeared
> 
> ### Expected Behavior
> gauge pointer should not disappear
> 
> ### Environment
> ```
> - OS:
> - Browser:
> - Framework:
> ```
> 
> ### Any additional comments?
> _No response_

what kind of effect do you want to achieve? i think it is not the right way to set radiusField in gauge chart
