### ISSUE TITLE
[Bug] Pie chart can't see label when inside

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#324]
### Version

1.1.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

const spec = {
  type: 'pie',
  data: [
    {
      id: 'id0',
      values: [
        { type: 'oxygen', value: '46.60' },
        { type: 'silicon', value: '27.72' },
        { type: 'aluminum', value: '8.13' },
        { type: 'iron', value: '5' },
        { type: 'calcium', value: '3.63' },
        { type: 'sodium', value: '2.83' },
        { type: 'potassium', value: '2.59' },
        { type: 'others', value: '3.5' }
      ]
    }
  ],
  outerRadius: 0.8,
  valueField: 'value',
  categoryField: 'type',
  title: {
    visible: true,
    text: 'Statistics of Surface Element Content'
  },
  legends: {
    visible: true,
    orient: 'left'
  },
  label: {
    visible: true,
    position: "inside",

  },
  tooltip: {
    mark: {
      content: [
        {
          key: datum => datum['type'],
          value: datum => datum['value'] + '%'
        }
      ]
    }
  }
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

<img width="1218" alt="image" src="https://github.com/VisActor/VChart/assets/49136199/82f1ec6d-5fef-495d-94f1-e05f897a6102">

### Expected Behavior

render correctly

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
目前没有针对内部的 label 做特殊的处理，之所以看不见是因为 label 默认同 mark 同色了，导致看不见

**Comment by pairone** [comment]
默认应用智能反色，inside label可始终可见
![image](https://github.com/VisActor/VChart/assets/40026218/a1f92226-4bf8-48bc-a5f4-32a96d739455)
