### ISSUE TITLE
在windows下，当页面上有多个图表时，经常发生画质变糊的情况，请问是怎么回事呢？

### ISSUE THREAD

**Issue by zLsPitaya** [VisActor/VChart#3244]
如题，可以看到，标题和图标（React Dom）是正常显示的，关于画布的内容就变得很模糊，

![image](https://github.com/user-attachments/assets/4a12c910-3dd8-4899-8888-9f8981522de4)

系统信息如下：
![image](https://github.com/user-attachments/assets/9912d29c-6fc0-463c-b85f-c400cec99184)

VChart 版本：1.12.1

**Comment by xile611** [comment]
> 如题，可以看到，标题和图标（React Dom）是正常显示的，关于画布的内容就变得很模糊，
> 
> ![image](https://private-user-images.githubusercontent.com/18525473/368497095-4a12c910-3dd8-4899-8888-9f8981522de4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTMzNDQsIm5iZiI6MTcyNjY1MzA0NCwicGF0aCI6Ii8xODUyNTQ3My8zNjg0OTcwOTUtNGExMmM5MTAtM2RkOC00ODk5LTg4ODgtOWY4OTgxNTIyZGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA5NTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OTQ2NGZkMzY5Mzk5ZTBiYzBmMWY1OWY0YWFkNDNmYTEzNDQyYjEzMGY0MDJjYmU3NGZhZWZkY2NlZGRkNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UJeql5Bpof48pVf6HtCHjv8vidz3bfhvN3LqfAjiQgA)
> 
> 系统信息如下： ![image](https://private-user-images.githubusercontent.com/18525473/368497823-9912d29c-6fc0-463c-b85f-c400cec99184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTMzNDQsIm5iZiI6MTcyNjY1MzA0NCwicGF0aCI6Ii8xODUyNTQ3My8zNjg0OTc4MjMtOTkxMmQyOWMtNmZjMC00NjNjLWI4NWYtYzQwMGNlYzk5MTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA5NTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1M2M2ZmUyMjBhY2MwNzY3NzAyYzVkYjQwYWZhZTM4NDFjY2VkZDY3ZjBjMjg4MTZmMDE4ZDg4NzJhYWVjMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ygJh1maiZC-l890viRJWBx4eao_6v4iYn9JOqx8FKio)
> 
> VChart 版本：1.12.1

有没有最小复现环境？或者你需要排查一下本地有没有修改 dpr 相关的配置

**Comment by zLsPitaya** [comment]
这个问题比较麻烦的就是没法复现，是在用户的设备上出现的，Mac上是没出现过的，用户的配置是在4K的显示器上配置了 150% 的缩放和 1920*1200 的默认分辨率，通过控制台输出，用户的 devicePixelRatio 为 1.75，用户没有自己修改过，应该就是默认的，据用户描述：刚开始会是正常的，搁置一段时间过后就会变糊。
![image](https://github.com/user-attachments/assets/88b9d5be-3f7b-4877-827a-0c55b7ae64a9)
![image](https://github.com/user-attachments/assets/c4098fc0-53aa-4962-abd4-1a7b2e64c62f)

**Comment by zLsPitaya** [comment]
感谢

**Comment by neuqzxy** [comment]
@zLsPitaya 这些case可以控制台看到canvas的位置信息和宽高信息吗？

**Comment by neuqzxy** [comment]
@zLsPitaya 我们还需要一些信息，能否帮忙和用户确认以下三个问题？
1. 是否有后缩放的操作，就是先打开浏览器，然后再设置了150%的缩放。
2. 或者有没有从一个底分辨率窗口拖动到高分辨率窗口的操作
3. 刷新之后，能不能恢复正常清晰度

**Comment by zLsPitaya** [comment]
> @zLsPitaya 我们还需要一些信息，能否帮忙和用户确认以下三个问题？
> 
> 1. 是否有后缩放的操作，就是先打开浏览器，然后再设置了150%的缩放。
> 2. 或者有没有从一个底分辨率窗口拖动到高分辨率窗口的操作
> 3. 刷新之后，能不能恢复正常清晰度


1. 没有更改缩放
2. 有的，从4k扩展屏挪到笔记本电脑的显示屏
3. 刷新后能恢复

**Comment by zLsPitaya** [comment]
@neuqzxy  不会立刻变糊，据用户描述：先在 4K 显示器上显示，然后合上笔记本盖进入睡眠，打开盖子后浏览器自动显示在笔记本自带屏幕上，然后再将浏览器拖到 4K 显示器上显示。
用户的显示器配置如下：
![image](https://github.com/user-attachments/assets/eb0ce57c-168e-4b66-a3e9-b0dbc1e0f667)
![image](https://github.com/user-attachments/assets/9b555c5a-be38-44e0-96b7-bfd679d1250e)

**Comment by neuqzxy** [comment]
@zLsPitaya 我们这边使用windows机器和4k显示器也测试了一下，没有复现出来，可能需要一些更详细的信息，如果还需要排查的话，可以加入飞书群讨论cc @xile611

**Comment by zLsPitaya** [comment]
> @zLsPitaya 我们这边使用windows机器和4k显示器也测试了一下，没有复现出来，可能需要一些更详细的信息，如果还需要排查的话，可以加入飞书群讨论cc @xile611

嗯，感谢，已加入飞书群，劳烦帮忙排查一下哈

**Comment by xile611** [comment]
@zLsPitaya 试一下最新的1.12.12版本，看看这个问题是否解决，如果没有解决可以新开issue
