### ISSUE TITLE
官网图表示例中“动画&叙事”部分，涉及动画的图表，代码未完全展示

### ISSUE THREAD

**Issue by EricHan0723** [VisActor/VChart#3248]
比如“流光动画”中的代码中有custom: VRender.StreamLight,但VRender.StreamLight并未定义

**Comment by xiaoluoHe** [comment]
使用的时候，可以从 `@visactor/vrender` 导出 StreamLight。
**注意 vrender 的版本保持与 vchart 中引入的一致**
相关代码可以参考https://github.com/VisActor/VRender/blob/61b5f63d3a7bcf7c0d5e38e00a7c93875403ff86/packages/vrender-core/src/animate/custom-animate.ts#L305

**Comment by EricHan0723** [comment]
好的感谢
