### ISSUE TITLE
[Help] 我想实现双向堆积分组柱状图，但不使用负数

### ISSUE THREAD

**Issue by dingdayu** [VisActor/VChart#3252]
![image](https://github.com/user-attachments/assets/2bea8fe2-49f5-4dc6-ac07-0ef67ca81b85)

如上图[官方示例](https://visactor.io/vchart/demo/bar-chart/bi-direction-stack-column)中的效果

但希望零轴下方仍是正数，需求的原因如下：

X轴日期，Y轴为某天数据，分布为： Total = sub Total （A + B + C  + D）+ (E + F)

思路： A，B，C，D 在 上方堆叠，E，F 在下方堆叠，totalLabel 直接显示 求和的值（subTotal 目前没有思路怎么展示，或者totalLabel 展示 subTotal，Total 用折线展示 ），ABCDEF 均为正值。

**Comment by dingdayu** [comment]
当前的效果如图：

![image](https://github.com/user-attachments/assets/bfcca19b-400c-4529-9672-42fd8a8d39eb)

**Comment by xile611** [comment]
@dingdayu 那只能通过多region图表来实现了
可以参考这个例子： https://www.visactor.io/vchart/demo/combination/col-line
将两个方向的柱子，分别放在两个 region中，两个region 共享一个x轴

**Comment by xile611** [comment]
> Hi @xile611 感谢你的指点，请问 复用 X 轴后，在 Y 轴上下方的 region 可以倒序吗？

可以的，配置一下就可以了： 
https://www.visactor.io/vchart/option/barChart-axes-linear#inverse
