### ISSUE TITLE
关于图表容器 resize 后，图表绘制出错的问题咨询

### ISSUE THREAD

**Issue by zLsPitaya** [VisActor/VChart#3255]
如题，容器的高度可调整，图表挂载的dom 是根据容器高度自适应的，当容器高度发生快速变化时，图表内容绘制出错，但是控制台没有错误抛出。
![可视化组件兼容](https://github.com/user-attachments/assets/afad1af5-843a-4cb6-af57-c7f8bb961968)

可以看到，挂在的容器 dom 高度是有的，但是canvas 内容没出来。
![image](https://github.com/user-attachments/assets/6dda4616-2b69-4bfc-b86f-5da9fcbc3511)

用户的设置信息如下：
![image](https://github.com/user-attachments/assets/7ab4a17c-82f0-4929-9355-486e6959f613)

**Comment by xile611** [comment]
@zLsPitaya spec 补充一下吧

**Comment by zLsPitaya** [comment]
@xile611 该问题仅在这一个用户的设备上出现，他用笔记本就不会复现，在上面的拓展显示屏上能稳定复现，这是对应的链接：https://codesandbox.io/p/sandbox/vchart-resize-ltp4ng?file=%2Fsrc%2Findex.ts%3A19%2C14

![F576EDC3-30C4-978F-22E1-4C52191866D4](https://github.com/user-attachments/assets/15fcf9f3-0507-40ca-926a-d124a7ef996a)

**Comment by zLsPitaya** [comment]
@xile611 我在想，是不是因为用户设备的 dpr 失去精度的原因导致的呢？我在前面手动设置 dpr 为 1.35，实际我设备是 2，也能复现这个问题。
![image](https://github.com/user-attachments/assets/b8b06cae-0e32-43ea-a612-0da66226ea13)

**Comment by xile611** [comment]
@zLsPitaya 排查到是底层在处理dpr 为1.35 的时候，更新范围计算有问题

**Comment by zLsPitaya** [comment]
@xile611 辛苦排查，感谢～

**Comment by xile611** [comment]
@zLsPitaya 1.12.9 已经修复了这个问题，可以验证一下

**Comment by zLsPitaya** [comment]
@xile611 感谢～

**Comment by xile611** [comment]
@zLsPitaya 也帮忙观察一下，升级1.12.9之后的话，之前那个部分图表变模糊的问题，会不会出现

**Comment by xile611** [comment]
fixed in 1.12.9
