### ISSUE TITLE
桑基图如何把中间节点移到尾部？

### ISSUE THREAD

**Issue by Edge00** [VisActor/VChart#3289]
如图，希望把中间节点异动到最右侧能够实现吗？
<img width="1613" alt="image" src="https://github.com/user-attachments/assets/ebd4e2f4-fba8-447b-83d9-7b3e4a53c519">

代码见：https://visactor.io/vchart/demo/sankey-chart/hierarchical-sankey

**Comment by xile611** [comment]
> https://visactor.io/vchart/demo/sankey-chart/hierarchical-sankey

暂不支持

**Comment by Edge00** [comment]
@xile611  感谢解答，还有一个问题想请教下，可以调整 node 的 y 轴位置么？比如将图中最右侧紫色 02 节点往下移 100px

**Comment by xile611** [comment]
> @xile611 感谢解答，还有一个问题想请教下，可以调整 node 的 y 轴位置么？比如将图中最右侧紫色 02 节点往下移 100px

如果是固定的数据，可以这么做，如果是动态数据，那就不建议了，这里节点的位置有一系列的计算逻辑

**Comment by Edge00** [comment]
> > @xile611 感谢解答，还有一个问题想请教下，可以调整 node 的 y 轴位置么？比如将图中最右侧紫色 02 节点往下移 100px
> 
> 如果是固定的数据，可以这么做，如果是动态数据，那就不建议了，这里节点的位置有一系列的计算逻辑

数据是动态的，那就不处理了吧，感谢！
