### ISSUE TITLE
[Bug] cursor pointer dissapear when animation rendering

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#331]
### Version

1.1.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

```
hover: {
  stroke: '#000000',
  strokeWidth: 1,
  cursor: 'pointer',
  outerRadius: Math.min(1, spec.radius + 0.05),
},
```

### Current Behavior

![20230728171205_rec_](https://github.com/VisActor/VChart/assets/49136199/2c6bfac1-fcda-429d-b5a0-6c0c2229f084)

### Expected Behavior

render correctyly

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
You can configure `cursor` in `pie.style`
