### ISSUE TITLE
[Bug] 切后台或闲置超过20分钟, 使用`updateSpec`更新数据, 后再调用`renderSync`重新渲染, 数据未更新

### ISSUE THREAD

**Issue by darkfiredarkhalo** [VisActor/VChart#3312]
### Version

1.12.6

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/festive-grothendieck-d9lmxw?file=%2Findex.html%3A8%2C15

### Steps to Reproduce

1. 首次正常渲染出图表后切后台或闲置(勿刷新页面)
2. 大于20分钟后使用`updateSpec`更新数据

### Current Behavior

数据未更新, 查看页面结构, 发现有两个canvas
![image](https://github.com/user-attachments/assets/c7f17e1e-e1b2-4639-87cb-6b78dcec3548)
第二个canvas的数据是正常的, 不过这个canvas在可见区域外

### Expected Behavior

长时间闲置或切后台后能正常更新数据

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Framework: vue3
```

**Comment by darkfiredarkhalo** [comment]
目前暂时使用如下方法解决了:
每次更新数据后检查图表容器下的canvas数量, 大于一个就将最后一个提到第一位

**Comment by xile611** [comment]
@darkfiredarkhalo 首次渲染完成后，没有任何操作，会多出一个canvas吗？

**Comment by xile611** [comment]
> 目前暂时使用如下方法解决了: 每次更新数据后检查图表容器下的canvas数量, 大于一个就将最后一个提到第一位

问题没法复现... 如果不能提供更多复现方式，只能暂时关闭了
