### ISSUE TITLE
[Bug] 多图表位置接近的时候鼠标快速移动，crosshair不隐藏

### ISSUE THREAD

**Issue by neuqzxy** [VisActor/VChart#3335]
### Version

1.12.6

### Link to Minimal Reproduction

1.12.6

### Steps to Reproduce

放多个图表，拼一下，然后鼠标快速移动

### Current Behavior

有时候crosshair不消失

### Expected Behavior

crosshair消失

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
duplicated with #2726
