### ISSUE TITLE
[Bug] Error when use markLine in Sankey. "Cannot read properties of undefined (reading 'getScale')"

### ISSUE THREAD

**Issue by lutian197** [VisActor/VChart#3336]
### Version

1.12.8

### Link to Minimal Reproduction

you can reproduce on the any sankey examples of official website

### Steps to Reproduce

const spec = {
...
  markLine: [{ x: 0, y: 0, x1: 500, y1: 0 }]
}

### Current Behavior

![Snipaste_2024-10-24_16-08-56](https://github.com/user-attachments/assets/09ebdeca-4faf-479b-afd2-26ab593096b8)

### Expected Behavior

--

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
@lutian197 `markLine` can't be used in sankey chart, can you show your case ? what kind of markLine you want to add to the sankey chart?

**Comment by lutian197** [comment]
> @lutian197 `markLine` can't be used in sankey chart, can you show your case ? what kind of markLine you want to add to the sankey chart?

I find customMark can draw lines. But there is a new problem. I use function to set line position, and this error "'vchart' is not defined" occurred .

mounted() {
  const spec = {
    ...
    customMark: {
      style: {
        y1:  () => {
          return vchart.getChart().getCanvasRect()?.height;
        }
      }
    }
  };
  const vchart = new VChart(spec, { dom: 'sankeyChart' });
  vchart.renderSync();
}

**Comment by lutian197** [comment]
@xile611 
I find customMark can draw lines. But there is a new problem. I use function to set line position, and this error "'vchart' is not defined" occurred .

mounted() {
const spec = {
...
customMark: {
style: {
y1: () => {
return vchart.getChart().getCanvasRect()?.height;
}
}
}
};
const vchart = new VChart(spec, { dom: 'sankeyChart' });
vchart.renderSync();
}

**Comment by xile611** [comment]
> @xile611 I find customMark can draw lines. But there is a new problem. I use function to set line position, and this error "'vchart' is not defined" occurred .
> 
> mounted() { const spec = { ... customMark: { style: { y1: () => { return vchart.getChart().getCanvasRect()?.height; } } } }; const vchart = new VChart(spec, { dom: 'sankeyChart' }); vchart.renderSync(); }

@lutian197 you can get chart in the parameters of `y1: ()`

**Comment by lutian197** [comment]
@xile611 
I tried. There is nothing in the y1: ()
![image](https://github.com/user-attachments/assets/ea9df475-d4d6-47b6-88ae-4d357444f703)
![image](https://github.com/user-attachments/assets/0949ea46-6335-49a1-816c-889a5e096d3d)

**Comment by xile611** [comment]
@lutian197 
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/8ddea96f-7bbb-4827-bd60-e1305957fecc">

you can get the `chart` from the second parameter
the first parameter is refer to the `datum` , then your data is empty now

**Comment by lutian197** [comment]
@xile611 
Got it!  Thank you so much.
