### ISSUE TITLE
[Feature] datazoom support waterfall chart

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#334]

**Comment by skie1997** [comment]
瀑布图中datazoom不生效的原因和现象大概是这样：
`dataZoom.filterMode: 'filter'`: 瀑布图系列不支持数据筛选，这导致datazoom在做数据筛选时不生效；
`dataZoom.filterMode: 'axis'`: datazoom不筛选数据而直接控制轴映射时，首尾两端的图元不能及时恢复（比如下面的情况，datazoom即使拖动到最右端，总计图元也无法出现）。原因是首尾两端的这个值可能是后加的，没有参与坐标轴数据映射

待瀑布图内部修复
