### ISSUE TITLE
[Bug] legend is empty after scrool

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#3344]
### Version

1.2.9

### Link to Minimal Reproduction

bug server case id: 671a368dc21c5900b31822f4

### Steps to Reproduce

bug server case id: 671a368dc21c5900b31822f4

### Current Behavior

bug server case id: 671a368dc21c5900b31822f4

### Expected Behavior

bug server case id: 671a368dc21c5900b31822f4
![Uploading image.png…]()

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by skie1997** [comment]
问题原因：
图例最后一项内容的空白占位导致分页
![20241029145601_rec_](https://github.com/user-attachments/assets/37697f19-7441-431d-91db-c4cb1fddfc79)

预计修复方法：
如果图例分页时，next页仅有1个item 且 该item横跨两页，则增加container height，确保该item在当前页布局成功，不触发分页
