### ISSUE TITLE
桑基图如何自定义节点位置呢？How to custom sankey node's position?

### ISSUE THREAD

**Issue by lutian197** [VisActor/VChart#3346]
垂直桑基图 左侧节点靠左边，右边节点靠右边，需要改变节点水平位置。这种情况怎么实现呢？

**Comment by xile611** [comment]
@lutian197 具体什么效果，可以看看吗？

**Comment by xile611** [comment]
@lutian197 如果没有更新，这个issue暂时关闭了，后续提issue请按照我们的规范填写内容～ 感谢理解
