### ISSUE TITLE
[Bug] totalLabel overlap don't work when has datazoom

### ISSUE THREAD

**Issue by xile611** [VisActor/VChart#3363]
### Version

1.12.9

### Link to Minimal Reproduction

no need

### Steps to Reproduce

[a.txt](https://github.com/user-attachments/files/17553546/a.txt)

### Current Behavior

<img width="890" alt="image" src="https://github.com/user-attachments/assets/31d86f5a-7a17-4806-88ca-233728b1fb2d">

### Expected Behavior

 拖动datazoom 标签防重叠能够生效

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
配置 overlap 后，实际已生效
