### ISSUE TITLE
[Bug] Remove the cornerRadius from bar.style，barchart's rounded corner style isn't updated.

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#3372]
### Version

@visactor/vchart :  "1.12.2"

### Link to Minimal Reproduction

null

### Steps to Reproduce

[updateSpec问题.txt](https://github.com/user-attachments/files/17572898/updateSpec.txt)

bar.style 去除cornerRadius，柱状图圆角样式未更新为无圆角

### Current Behavior

https://github.com/user-attachments/assets/5aa0800c-ca27-4026-ac46-7a723d283ecb

### Expected Behavior

柱状图更新为无圆角样式

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
问题定位：`updateSpec` 中 的 subSeries，并没有设置 `cornerRadius: 0`

**Comment by youngwinds** [comment]
> 问题定位：`updateSpec` 中 的 subSeries，并没有设置 `cornerRadius: 0`

Get
