### ISSUE TITLE
How to custom sankey node's position?

### ISSUE THREAD

**Issue by lutian197** [VisActor/VChart#3399]
![f0a9f2f2996ef255f6e0d510eb4d0af](https://github.com/user-attachments/assets/efc6d664-94e4-42a8-ba5d-ded62b64680e)
如图，桑基图垂直时，如何让每行第一个节点靠左垂直对齐，每行最后一个节点在右侧某个位置垂直对齐？
是不是要设置node.style.x和link.style.x呢？

**Comment by xile611** [comment]
@lutian197 
https://github.com/VisActor/VChart/issues/3400
这两个想表达同一个问题吗？
最终想要实现什么效果？get不到

可以试一下配置  `crossNodeAlign`：  https://www.visactor.io/vchart/option/sankeyChart#crossNodeAlign

**Comment by lutian197** [comment]
@xile611 
crossNodeAlign可以实现垂直左对齐，https://github.com/VisActor/VChart/issues/3400 也是想达到效果的另一个问题。

普通的桑基图是这样：
![image](https://github.com/user-attachments/assets/c18316ad-686d-4072-ad31-2a2c17295a0e)

通过设置节点和边的位置后，是这样的：
![image](https://github.com/user-attachments/assets/350c0ae7-7be8-4c04-855e-5aa08aab7327)

我想实现的效果和上图很接近，相当于是个区域人流方向图，第一行是入口节点，第二行开始，最后都有个出口节点，要放在固定的位置，其余节点不能超过这条leave线。

目前离我想要的效果还有些距离，我固定了每个节点的宽度为100，节点宽度不能随数据大小变化，然后边的两头不能占满节点宽度，节点会有一节多余出来。也许节点宽度我能根据数据计算出来，再去定位，但是这个边的两头该怎么处理呢？
想实现这种效果是不是有更好的方案呢？

我的代码如下：
`
const nodes = [
  { name: 'Entrance', id: '0_247' },
  { name: 'Block1', id: '1_175' },
  { name: 'Block2', id: '1_176' },
  { name: 'Block2', id: '2_176' },
  { name: 'Exit', id: '1_-1' },
  { name: 'Exit', id: '2_-1' }
];
const links = [
  { source: '0_247', target: '1_176', value: 3 },
  { source: '0_247', target: '1_175', value: 1 },
  { source: '0_247', target: '1_-1', value: 2 },
  { source: '1_176', target: '2_-1', value: 3 },
  { source: '1_175', target: '2_176', value: 1 }
];
const leaveNodes = nodes.filter(node => node.id.includes('-1')).map(node => node.id);
const spec = {
    type: 'sankey',
    data: [
      {
        id: 'sankey',
        values: [
          {
            nodes: nodes,
            links: links,
          },
        ],
      },
    ],
    height: 720,
    padding: { left: 0, right: 0, top: 48, bottom: 48 },
    categoryField: 'name',
    valueField: 'value',
    direction: 'vertical',
    nodeAlign: 'left',
    nodeGap: 16,
    nodeWidth: 24,
    minNodeHeight: 10,
    nodeHeight: 100,
    crossNodeAlign: 'start',
    nodeKey: datum => datum.id,
    label: {
      visible: true,
      style: {
        fontSize: 14,
        fill: '#333333',
        dy: 10,
      },
    },

    node: {
      style: {
        x: (data, chart) => { // 这里可以直接设置x
          if (leaveNodes.includes(data.key)) {
            return chart.vchart._currentSize.width * 0.68;
          } else {
            return data.x0;
          }
        },
        width: (data, chart) => {
          return 100; // 这里和nodeHeight都要设置
        },
      },
    },

    link: {
      style: {
        x1: (data, chart) => { // 边x0，x1是指左上角
          if (leaveNodes.includes(data.target)) {
            return chart.vchart._currentSize.width * 0.68 + data.thickness / 2;
          } else {
            return data.x1;
          }
        },
      },
    },
    customMark: [
      {
        type: 'rule',
        width: 5,
        layoutType: 'absolute',
        style: {
          stroke: '#B2B2B2',
          lineDash: [2, 3],
          x: 0,
          y: 0,
          x1: 0,
          y1: (datum, { chart }) => {
            return chart.getCanvasRect()?.height;
          },
        },
      },
      {
        type: 'text',
        style: {
          text: 'Enter',
          fontSize: 16,
          fill: '#333333',
          x: 20,
          y: 20,
        },
      },
      {
        type: 'rule',
        width: 5,
        layoutType: 'absolute',
        style: {
          stroke: '#B2B2B2',
          lineDash: [2, 3],
          x: (datum, { chart }) => {
            return chart.getCanvasRect()?.width * 0.68;
          },
          y: 0,
          x1: (datum, { chart }) => {
            return chart.getCanvasRect()?.width * 0.68;
          },
          y1: (datum, { chart }) => {
            return chart.getCanvasRect()?.height;
          },
        },
      },
      {
        type: 'text',
        style: {
          text: 'Leave',
          fontSize: 16,
          fill: '#333333',
          x: (datum, { chart }) => {
            return chart.getCanvasRect()?.width * 0.68;
          },
          y: 20,
          dx: 20,
        },
      },
    ],
  };
`

**Comment by xile611** [comment]
@lutian197 非常自定义的布局，感觉已经超出桑基图的范围了，这种还是建议自定义布局实现吧

**Comment by lutian197** [comment]
@xile611 
好的。
想问下如何自定义边的四个点的位置呢？现在有的边不能撑满节点宽度。

**Comment by xile611** [comment]
> const nodes = [ { name: 'Entrance', id: '0_247' }, { name: 'Block1', id: '1_175' }, { name: 'Block2', id: '1_176' }, { name: 'Block2', id: '2_176' }, { name: 'Exit', id: '1_-1' }, { name: 'Exit', id: '2_-1' } ];

哦，这个不支持自定义点的位置，这都是根据算法算出来的。。。
