### ISSUE TITLE
[Bug] 组合图打包后运行出错

### ISSUE THREAD

**Issue by superzou2021** [VisActor/VChart#3412]
### Version

1.12.10

### Link to Minimal Reproduction

https://www.visactor.io/vchart/demo/combination/dual-axis

### Steps to Reproduce

1.将https://www.visactor.io/vchart/demo/combination/dual-axis地址的示例代码copy到vue3+vite新构建的项目中，npm run dev运行正常，执行npm run build将项目打包到dist目录下，并放置到服务器上，访问项目，控制台提示如下：
index-B0sh4bS7.js:22 Uncaught TypeError: this.contributions.forEach is not a function
    at ca.init (index-B0sh4bS7.js:22:174554)
    at new ca (index-B0sh4bS7.js:22:174521)
  尝试的vchart版本有：1.0.0；1.9.0；1.12.10。说明从1.0.0开始，此问题一直存在，但是在开发环境中无此问题。服务器环境为：winserver2022-iis或linux-Tomcat。vite版本5.4.10，vue版本3.5.12

### Current Behavior

本地运行正常显示图表，部署到服务器后未能创建图表的canvas元素

### Expected Behavior

图表显示，并且无报错信息

### Environment

```markdown
- OS:Windows 11 专业版
- Browser:Chrome  130.0.6723.117（正式版本） （64 位）
- Framework:vue3:3.5.12
```

**Comment by xile611** [comment]
@superzou2021 应该是打包的时候做了tree-shaking 把一些组件给去掉了

各种引用方法的区别见文档： https://www.visactor.io/vchart/guide/tutorial_docs/Basic/How_to_Import_VChart
按需加载文档： https://www.visactor.io/vchart/guide/tutorial_docs/Load_on_Demand

如果暂时不考虑按需加载的问题，可以把引用方式改成 
```
import { default as VChart } from '@visactor/vchart';
```

这样是已经做了默认模块加载的，不会被tree-shaking

**Comment by superzou2021** [comment]
OK，确实是tree-shaking导致的报错
