### ISSUE TITLE
[Feature] sankey support `maxNodeHeight`

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#3439]
### What problem does this feature solve?

1. 桑基图支持节点最大高度配置 `maxNodeHeight`
2. 支持配置子节点起始层数（或子节点所在层跟随父节点） 
![image](https://github.com/user-attachments/assets/e298fa6f-da70-47ea-b364-51aa554a6230)
![image](https://github.com/user-attachments/assets/6c46c691-8134-4cd4-a73f-26de481d9298)

### What does the proposed API look like?

1. `maxNodeHeight`
2. `nodeLayer`: `auto` | `upstream`

**Comment by xile611** [comment]
supported in 1.12.14
