### ISSUE TITLE
[Bug] SankeyChart resize Error

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#344]
### Version

1.1.0

### Link to Minimal Reproduction

https://visactor.bytedance.net/vchart/demo/sankey-chart/basic-sankey

### Steps to Reproduce

1. enter full screen

2. close full screen

3. In Addition, resize the chart, legends will disappear.

links and legends update error.

### Current Behavior

![20230731170057_rec_](https://github.com/VisActor/VChart/assets/49136199/5f268bff-0c29-45bf-afc4-e574bb761a28)

![20230731180419_rec_](https://github.com/VisActor/VChart/assets/49136199/23c88488-05f6-4c51-a4a2-c027187aab60)

### Expected Behavior

update correctly

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pairone** [comment]
After accessing vgrammar 0.5.2 version, this problem has been solved.

Related to this MR of fixing glyph state: https://github.com/VisActor/VGrammar/pull/92/files

**Comment by kkxxkk2019** [comment]
@youngwinds 升级到 1.1.3 就可以嘞，我先关了哈
