### ISSUE TITLE
[Bug] bar chart with datazoom displays incorrectly while bar width is set to small value

### ISSUE THREAD

**Issue by purpose233** [VisActor/VChart#3446]
### Version

1.12.11

### Link to Minimal Reproduction

null

### Steps to Reproduce

See Link

### Current Behavior

柱子设置了 barWidth 为 1，但是在 datazoom 操作过程中中似乎没有依据 barWidth 计算柱子隐藏，导致柱子在画布左右两侧吸附。

### Expected Behavior

用户需求：保证柱子和标签在 datazoom 操作过程中隐藏显示的逻辑一致。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
@purpose233 补充一下spec 吧，没有链接呢

**Comment by skie1997** [comment]
问题原因：label被强制限制在画布内
解决方案：label.overlap.clampForce: false 即可
![20241124165434_rec_](https://github.com/user-attachments/assets/23c92887-8a90-471c-8eee-c4f52b9b05f6)

**Comment by skie1997** [comment]
https://github.com/VisActor/VChart/pull/3468
