### ISSUE TITLE
[Bug] Sankey Chart emphasis not working 

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#347]
### Version

1.1.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

```

const spec = {
  "type": "sankey",
  "data": [
    {
      "values": [
        {
          "nodes": [
            {
              "230731153454018": "小型企业",
              "color": "小型企业",
              "group": "230731153454018",
              "key": "230731153454018-小型企业",
              "name": "小型企业",
              "type": "node",
              "value": 2891088.6421899796
            },
            {
              "230731153454018": "消费者",
              "color": "消费者",
              "group": "230731153454018",
              "key": "230731153454018-消费者",
              "name": "消费者",
              "type": "node",
              "value": 8025072.194172859
            },
            {
              "230731153454018": "公司",
              "color": "公司",
              "group": "230731153454018",
              "key": "230731153454018-公司",
              "name": "公司",
              "type": "node",
              "value": 5152793.296570778
            },
            {
              "230731153454015": "办公用品",
              "color": "办公用品",
              "group": "230731153454015",
              "key": "230731153454015-办公用品",
              "name": "办公用品",
              "type": "node",
              "value": 4865589.799788475
            },
            {
              "230731153454015": "技术",
              "color": "技术",
              "group": "230731153454015",
              "key": "230731153454015-技术",
              "name": "技术",
              "type": "node",
              "value": 5469023.505149841
            },
            {
              "230731153454015": "家具",
              "color": "家具",
              "group": "230731153454015",
              "key": "230731153454015-家具",
              "name": "家具",
              "type": "node",
              "value": 5734340.8279953
            },
            {
              "230731174522020": "小型企业",
              "color": "小型企业",
              "group": "230731174522020",
              "key": "230731174522020-小型企业",
              "name": "小型企业",
              "type": "node",
              "value": 2891088.6421899796
            },
            {
              "230731174522020": "消费者",
              "color": "消费者",
              "group": "230731174522020",
              "key": "230731174522020-消费者",
              "name": "消费者",
              "type": "node",
              "value": 8025072.194172859
            },
            {
              "230731174522020": "公司",
              "color": "公司",
              "group": "230731174522020",
              "key": "230731174522020-公司",
              "name": "公司",
              "type": "node",
              "value": 5152793.296570778
            }
          ],
          "links": [
            {
              "from": "230731153454018-小型企业",
              "key": "1",
              "to": "230731153454015-办公用品",
              "value": 837464.545838356,
              "source": 0,
              "target": 3
            },
            {
              "from": "230731153454015-办公用品",
              "key": "1",
              "to": "230731174522020-小型企业",
              "value": 837464.545838356,
              "source": 3,
              "target": 6
            },
            {
              "from": "230731153454018-消费者",
              "key": "2",
              "to": "230731153454015-办公用品",
              "value": 2543529.3300714493,
              "source": 1,
              "target": 3
            },
            {
              "from": "230731153454015-办公用品",
              "key": "2",
              "to": "230731174522020-消费者",
              "value": 2543529.3300714493,
              "source": 3,
              "target": 7
            },
            {
              "from": "230731153454018-消费者",
              "key": "3",
              "to": "230731153454015-技术",
              "value": 2692828.4352111816,
              "source": 1,
              "target": 4
            },
            {
              "from": "230731153454015-技术",
              "key": "3",
              "to": "230731174522020-消费者",
              "value": 2692828.4352111816,
              "source": 4,
              "target": 7
            },
            {
              "from": "230731153454018-公司",
              "key": "4",
              "to": "230731153454015-办公用品",
              "value": 1484595.9238786697,
              "source": 2,
              "target": 3
            },
            {
              "from": "230731153454015-办公用品",
              "key": "4",
              "to": "230731174522020-公司",
              "value": 1484595.9238786697,
              "source": 3,
              "target": 8
            },
            {
              "from": "230731153454018-消费者",
              "key": "5",
              "to": "230731153454015-家具",
              "value": 2788714.4288902283,
              "source": 1,
              "target": 5
            },
            {
              "from": "230731153454015-家具",
              "key": "5",
              "to": "230731174522020-消费者",
              "value": 2788714.4288902283,
              "source": 5,
              "target": 7
            },
            {
              "from": "230731153454018-小型企业",
              "key": "6",
              "to": "230731153454015-家具",
              "value": 1042003.6409912109,
              "source": 0,
              "target": 5
            },
            {
              "from": "230731153454015-家具",
              "key": "6",
              "to": "230731174522020-小型企业",
              "value": 1042003.6409912109,
              "source": 5,
              "target": 6
            },
            {
              "from": "230731153454018-公司",
              "key": "7",
              "to": "230731153454015-技术",
              "value": 1764574.614578247,
              "source": 2,
              "target": 4
            },
            {
              "from": "230731153454015-技术",
              "key": "7",
              "to": "230731174522020-公司",
              "value": 1764574.614578247,
              "source": 4,
              "target": 8
            },
            {
              "from": "230731153454018-公司",
              "key": "8",
              "to": "230731153454015-家具",
              "value": 1903622.758113861,
              "source": 2,
              "target": 5
            },
            {
              "from": "230731153454015-家具",
              "key": "8",
              "to": "230731174522020-公司",
              "value": 1903622.758113861,
              "source": 5,
              "target": 8
            },
            {
              "from": "230731153454018-小型企业",
              "key": "9",
              "to": "230731153454015-技术",
              "value": 1011620.4553604126,
              "source": 0,
              "target": 4
            },
            {
              "from": "230731153454015-技术",
              "key": "9",
              "to": "230731174522020-小型企业",
              "value": 1011620.4553604126,
              "source": 4,
              "target": 6
            }
          ]
        }
      ]
    }
  ],
  "children": [],
  "shape": "diagonal",
  "colorFull": true,
  "nodeGap": 5,
  "nodeWidth": 10,
  "nodeAlign": "justify",
  "iterations": 0,
  "categoryField": "key",
  "valueField": "value",
  "sourceField": "source",
  "targetField": "target",
  "legends": [
    {
      "type": "discrete",
      "item": {
        "label": {
          "style": {
            "fontSize": 12,
            "fill": "#6F6F6F"
          }
        },
        "spaceRow": 0,
        "spaceCol": 0,
        "padding": {
          "top": 4,
          "bottom": 4,
          "left": 4,
          "right": 22
        },
        "background": {
          "style": {
            "fillOpacity": 0.001
          }
        },
        "shape": {
          "style": {
            "symbolType": "square"
          }
        }
      },
      "orient": "bottom",
      "position": "middle",
      "layoutType": "normal",
      "visible": true,
      "hover": false,
      "maxRow": 2,
      "title": {
        "textStyle": {
          "fontSize": 12,
          "fill": "#6F6F6F"
        }
      },
      "pager": {
        "textStyle": {},
        "handler": {
          "style": {},
          "state": {
            "disable": {}
          }
        }
      },
      "padding": {
        "top": 16,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  ],
  "background": "rgba(255, 255, 255, 0)",
  "hover": {
    "enable": true
  },
  "select": {
    "enable": true
  },
  "emphasis": {
    "enable": true,
    "effect": "adjacency"
  },
  "link": {
    "state": {
      "hover": {
        "cursor": "pointer",
        "fillOpacity": 0.8,
        "stroke": "#58595B",
        "lineWidth": 0,
        "zIndex": 500
      },
      "selected": {
        "cursor": "pointer",
        "fillOpacity": 1,
        "stroke": "#58595B",
        "lineWidth": 1
      }
    }
  },
  "node": {
    "state": {
      "hover": {
        "cursor": "pointer",
        "fillOpacity": 0.8,
        "stroke": "#58595B",
        "lineWidth": 1,
        "zIndex": 500
      },
      "selected": {
        "cursor": "pointer",
        "fillOpacity": 1,
        "stroke": "#58595B",
        "lineWidth": 1
      }
    }
  },
  "hash": "30e8b102df05193926fab9c918c4c597"
}

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// 只为了方便控制台调试用，不要拷贝
window['vchart'] = vchart;

```

### Current Behavior

![20230731185939_rec_](https://github.com/VisActor/VChart/assets/49136199/25fa71dc-0118-4586-a516-51dbaf1c2011)

### Expected Behavior

interaction active

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pairone** [comment]
需要配置一下blur，也就是未选中的显示状态，这样才能凸显出emphasis

**Comment by pairone** [comment]
例如，设置blur: {
        fillOpacity: 0.05
      }


https://github.com/VisActor/VChart/assets/40026218/b5aced50-31d0-458d-93e4-463aedc96bd4

**Comment by pairone** [comment]
@youngwinds

**Comment by pairone** [comment]
const spec = {
  "type": "sankey",
  "data": [
    {
      "values": [
        {
          "nodes": [
            {
              "230731153454018": "小型企业",
              "color": "小型企业",
              "group": "230731153454018",
              "key": "230731153454018-小型企业",
              "name": "小型企业",
              "type": "node",
              "value": 2891088.6421899796
            },
            {
              "230731153454018": "消费者",
              "color": "消费者",
              "group": "230731153454018",
              "key": "230731153454018-消费者",
              "name": "消费者",
              "type": "node",
              "value": 8025072.194172859
            },
            {
              "230731153454018": "公司",
              "color": "公司",
              "group": "230731153454018",
              "key": "230731153454018-公司",
              "name": "公司",
              "type": "node",
              "value": 5152793.296570778
            },
            {
              "230731153454015": "办公用品",
              "color": "办公用品",
              "group": "230731153454015",
              "key": "230731153454015-办公用品",
              "name": "办公用品",
              "type": "node",
              "value": 4865589.799788475
            },
            {
              "230731153454015": "技术",
              "color": "技术",
              "group": "230731153454015",
              "key": "230731153454015-技术",
              "name": "技术",
              "type": "node",
              "value": 5469023.505149841
            },
            {
              "230731153454015": "家具",
              "color": "家具",
              "group": "230731153454015",
              "key": "230731153454015-家具",
              "name": "家具",
              "type": "node",
              "value": 5734340.8279953
            },
            {
              "230731174522020": "小型企业",
              "color": "小型企业",
              "group": "230731174522020",
              "key": "230731174522020-小型企业",
              "name": "小型企业",
              "type": "node",
              "value": 2891088.6421899796
            },
            {
              "230731174522020": "消费者",
              "color": "消费者",
              "group": "230731174522020",
              "key": "230731174522020-消费者",
              "name": "消费者",
              "type": "node",
              "value": 8025072.194172859
            },
            {
              "230731174522020": "公司",
              "color": "公司",
              "group": "230731174522020",
              "key": "230731174522020-公司",
              "name": "公司",
              "type": "node",
              "value": 5152793.296570778
            }
          ],
          "links": [
            {
              "from": "230731153454018-小型企业",
              "key": "1",
              "to": "230731153454015-办公用品",
              "value": 837464.545838356,
              "source": 0,
              "target": 3
            },
            {
              "from": "230731153454015-办公用品",
              "key": "1",
              "to": "230731174522020-小型企业",
              "value": 837464.545838356,
              "source": 3,
              "target": 6
            },
            {
              "from": "230731153454018-消费者",
              "key": "2",
              "to": "230731153454015-办公用品",
              "value": 2543529.3300714493,
              "source": 1,
              "target": 3
            },
            {
              "from": "230731153454015-办公用品",
              "key": "2",
              "to": "230731174522020-消费者",
              "value": 2543529.3300714493,
              "source": 3,
              "target": 7
            },
            {
              "from": "230731153454018-消费者",
              "key": "3",
              "to": "230731153454015-技术",
              "value": 2692828.4352111816,
              "source": 1,
              "target": 4
            },
            {
              "from": "230731153454015-技术",
              "key": "3",
              "to": "230731174522020-消费者",
              "value": 2692828.4352111816,
              "source": 4,
              "target": 7
            },
            {
              "from": "230731153454018-公司",
              "key": "4",
              "to": "230731153454015-办公用品",
              "value": 1484595.9238786697,
              "source": 2,
              "target": 3
            },
            {
              "from": "230731153454015-办公用品",
              "key": "4",
              "to": "230731174522020-公司",
              "value": 1484595.9238786697,
              "source": 3,
              "target": 8
            },
            {
              "from": "230731153454018-消费者",
              "key": "5",
              "to": "230731153454015-家具",
              "value": 2788714.4288902283,
              "source": 1,
              "target": 5
            },
            {
              "from": "230731153454015-家具",
              "key": "5",
              "to": "230731174522020-消费者",
              "value": 2788714.4288902283,
              "source": 5,
              "target": 7
            },
            {
              "from": "230731153454018-小型企业",
              "key": "6",
              "to": "230731153454015-家具",
              "value": 1042003.6409912109,
              "source": 0,
              "target": 5
            },
            {
              "from": "230731153454015-家具",
              "key": "6",
              "to": "230731174522020-小型企业",
              "value": 1042003.6409912109,
              "source": 5,
              "target": 6
            },
            {
              "from": "230731153454018-公司",
              "key": "7",
              "to": "230731153454015-技术",
              "value": 1764574.614578247,
              "source": 2,
              "target": 4
            },
            {
              "from": "230731153454015-技术",
              "key": "7",
              "to": "230731174522020-公司",
              "value": 1764574.614578247,
              "source": 4,
              "target": 8
            },
            {
              "from": "230731153454018-公司",
              "key": "8",
              "to": "230731153454015-家具",
              "value": 1903622.758113861,
              "source": 2,
              "target": 5
            },
            {
              "from": "230731153454015-家具",
              "key": "8",
              "to": "230731174522020-公司",
              "value": 1903622.758113861,
              "source": 5,
              "target": 8
            },
            {
              "from": "230731153454018-小型企业",
              "key": "9",
              "to": "230731153454015-技术",
              "value": 1011620.4553604126,
              "source": 0,
              "target": 4
            },
            {
              "from": "230731153454015-技术",
              "key": "9",
              "to": "230731174522020-小型企业",
              "value": 1011620.4553604126,
              "source": 4,
              "target": 6
            }
          ]
        }
      ]
    }
  ],
  "children": [],
  "shape": "diagonal",
  "colorFull": true,
  "nodeGap": 5,
  "nodeWidth": 10,
  "nodeAlign": "justify",
  "iterations": 0,
  "categoryField": "key",
  "valueField": "value",
  "sourceField": "source",
  "targetField": "target",
  "legends": [
    {
      "type": "discrete",
      "item": {
        "label": {
          "style": {
            "fontSize": 12,
            "fill": "#6F6F6F"
          }
        },
        "spaceRow": 0,
        "spaceCol": 0,
        "padding": {
          "top": 4,
          "bottom": 4,
          "left": 4,
          "right": 22
        },
        "background": {
          "style": {
            "fillOpacity": 0.001
          }
        },
        "shape": {
          "style": {
            "symbolType": "square"
          }
        }
      },
      "orient": "bottom",
      "position": "middle",
      "layoutType": "normal",
      "visible": true,
      "hover": false,
      "maxRow": 2,
      "title": {
        "textStyle": {
          "fontSize": 12,
          "fill": "#6F6F6F"
        }
      },
      "pager": {
        "textStyle": {},
        "handler": {
          "style": {},
          "state": {
            "disable": {}
          }
        }
      },
      "padding": {
        "top": 16,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  ],
  "background": "rgba(255, 255, 255, 0)",
  "hover": {
    "enable": true
  },
  "select": {
    "enable": true
  },
  "emphasis": {
    "enable": true,
    "effect": "adjacency"
  },
  "link": {
    "state": {
      "hover": {
        "cursor": "pointer",
        "fillOpacity": 0.8,
        "stroke": "#58595B",
        "lineWidth": 0,
        "zIndex": 500
      },
      "selected": {
        "cursor": "pointer",
        "fillOpacity": 1,
        "stroke": "#58595B",
        "lineWidth": 1,
      },
      blur: {
        fillOpacity: 0.05
      }
    }
  },
  "node": {
    "state": {
      "hover": {
        "cursor": "pointer",
        "fillOpacity": 0.8,
        "stroke": "#58595B",
        "lineWidth": 1,
        "zIndex": 500
      },
      "selected": {
        "cursor": "pointer",
        "fillOpacity": 1,
        "stroke": "#58595B",
        "lineWidth": 1,
      },
      blur: {
        fillOpacity: 0.05
      }
    }
  },
  "hash": "30e8b102df05193926fab9c918c4c597"
}

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
