### ISSUE TITLE
[Bug] chart state after updateSpec is incorrect

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#3470]
### Version

@visactor/vchart :  "1.12.2"

### Link to Minimal Reproduction

null

### Steps to Reproduce

[state_spec.txt](https://github.com/user-attachments/files/17931153/state_spec.txt)

### Current Behavior

https://github.com/user-attachments/assets/a329b345-00ce-4d4a-9664-22cc8c38e09d

### Expected Behavior

updateSpec后，没有选中状态，所有图元都高亮

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
可以在更新前调用 `clearAllStates()` 解决这个问题
