### ISSUE TITLE
[Bug] 曲线展示有时候会有不准确的情况

### ISSUE THREAD

**Issue by KekeORSJ** [VisActor/VChart#3472]
### Version

1.12.11

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/the-template-of-visactor-vchart-vl84ww

### Steps to Reproduce

配置信息：
 type: 'line',
  color: ['#0A4CDE', '#F689EB', '#FAC858', '#EE6666', '#73C0DE', '#3CA272', '#FC8452', '#9A60B4', '#ea7ccc'],
  height: 175,
  padding: {
    top: 5,
    right: 0,
    bottom: 12,
    left: 0,
  },
  hover: {
    enable: false,
  },
  select: {
    enable: true,
  },
  // markLine: {
  //   visible: false, // 标注组件是什么
  // },
  axes: [
    {
      orient: 'left',
      label: {visible: false}, // 左边坐标不显示
      grid: {
        style: {lineDash: [4, 4]},
      },
    },
    {
      orient: 'bottom',
      sampling: false,
      label: {
        flush: true,
        lastVisible: true,
        style: {
          fontSize: 9,
          fill: '#999999',
        },
      },
      tick: {
        tickCount: 12,
      },
    },
  ],
  stack: true,
  xField: 'categories', // 坐标
  yField: 'value', // 值
  seriesField: 'name', // 分组
  line: {
    style: {
      curveType: 'monotone',
      lineDash: data => (data.last ? [5, 5] : [0]),
    },
  },
  point: {
    style: {
      opacity: 0,
    },
    state: {
      selected: {
        opacity: 1,
        size: 10,
        lineWidth: 2,
        stroke: {
          scale: 'color',
          field: 'name',
        },
        fill: 'white',
      },
    },
  },
  legends: [
    {
      visible: true,
      position: 'end',
      orient: 'top',
      item: {shape: {style: {symbolType: 'rect'}}},
    },
  ],
  crosshair: {
    trigger: 'click',
    xField: {
      visible: true,
      line: {
        type: 'line',
      },
      label: {
        visible: false,
      },
    },
    yField: {
      visible: false,
    },
  },
  tooltip: {
    // hideTimer: 1000, // 隐藏
    renderMode: 'canvas', // 渲染为canvas
    trigger: 'click', // tooltip 触发方式
    // triggerOff: 'none', // tooltip常驻
    dimension: {
      positionMode: 'pointer',
      shapeType: 'rect',
      title: {
        visible: false,
      },
    },
  },
未组装前的数据：

### Current Behavior

![Uploading bug1.jpg…]()
![bug3](https://github.com/user-attachments/assets/7e34d5c9-65f9-4c4d-8297-4234bde2c19b)
如图: 实际点的数据和曲线所表示的数据不一致

### Expected Behavior

数字应该和曲线是相互匹配的

### Environment

```markdown
- OS:PC
- Browser:Chrome 版本 131.0.6778.86（正式版本） 浏览器-手机模式
- Framework:vue@3
```

### Any additional comments?

no

**Comment by KekeORSJ** [comment]
查到原因了，在配置用使用   stack: true  堆叠，那么数据有可能重叠；

**Comment by xile611** [comment]
> 叠，那么数据有可能重叠；
那看你需求，如果不需要堆叠，就关掉
