### ISSUE TITLE
使用 taro-vchart 体积过大

### ISSUE THREAD

**Issue by HealingW** [VisActor/VChart#3475]
使用 taro cli 初始化的新项目,"webpack": "5.78.0"
![image](https://github.com/user-attachments/assets/d1bbdc90-fdd6-483c-90fc-e9fd92829957)
不引入 vchart 包分析大小是1 MB
![image](https://github.com/user-attachments/assets/70a480cc-acaf-4822-aaf7-55eacc69a433)
使用 import {LineChart} from "@visactor/taro-vchart"; 包体积 6.24MB
![image](https://github.com/user-attachments/assets/6f790717-b926-44f4-a3c2-1bb06478b93d)
使用 import {VChart} from "@visactor/taro-vchart"; 包体积 3.38
![image](https://github.com/user-attachments/assets/2905b8af-af25-4e96-8d6c-167221df1343)
看了相关 issues 和文档，按照文档中说明使用按需加载的话1.12.x 版本之后是使用 语义化标签，但是这样做了包体积反而比使用直接使用 <Vchar/> 体积更大
相关 issues 中提到可能是没开启 Tree Shaking，看了 taro 文档说是默认开启，使用NODE_ENV=production taro build --type weapp --watch命令运行之后的包体积也是无法通过预览
是我使用的姿势不对吗，感谢解答 🙏

**Comment by xile611** [comment]
@HealingW 可以对比一下 `import VChart from "@visactor/taro-vchart";` 的大小，这个才是全量引用

**Comment by HealingW** [comment]
与 import {VChart} from "@visactor/taro-vchart"; 的效果一样，是 3.38MB

**Comment by xile611** [comment]
> 与 import {VChart} from "@visactor/taro-vchart"; 的效果一样，是 3.38MB

感觉你这个大包有问题，

`使用 import {LineChart} from "@visactor/taro-vchart"; 包体积 6.24MB`
这个是只引用LineChart 
竟然比全量引用的体积更大

**Comment by xile611** [comment]
@HealingW 可以再试试 `VChartSimple` ，如果打包体积还是一样的话，那tree-shaking 肯定是有问题的
这个组件是不加载任何图表，只是加载核心代码

**Comment by HealingW** [comment]
只引入，不使用组件不会增加包体积。
页面 import {BarChart} from "@visactor/taro-vchart";
使用 BarChart 组件大约会增加 1.3MB 包体积是正常的吗

**Comment by xile611** [comment]
> 只引入，不使用组件不会增加包体积。 页面 import {BarChart} from "@visactor/taro-vchart"; 使用 BarChart 组件打包后大约会增加 1.4MB 包体积是正常的吗

如果 import {VChart} from "@visactor/taro-vchart"; 增加 3.38MB 
那这个数据应该是正常的

**Comment by xile611** [comment]
因为图表库不同图表类型，但是公共的内容还是挺多的，所以现在单个图表的体积做不到那么小，后续会持续优化

**Comment by HealingW** [comment]
好的，谢谢。
