### ISSUE TITLE
[Documentation] 在文档中通过点击事件获取当前的值只有柱状图，折线图怎么精确获取当前值？

### ISSUE THREAD

**Issue by kuangyuliang** [VisActor/VChart#3488]
### Documentation Title or Section

FAQ89：当使用堆叠柱状图时，如何在点击事件中获取与被点击柱子同维度的所有数据？
```
vchart.on('click', { markName: 'bar', level: 'mark' }, (e) => {
  const datum = e.datum; // 获取被点击的柱子的信息
  const chartSpec = e.chart?.getSpec(); // 如果你无法获取当前的 spec，可以通过该方式获取原始 spec
  const xDimensionValue = datum[chartSpec.xField];
  const chartData = e.chart.chartData.getSeriesData().latestData; // 如果可以拿到原始数据，也可以直接拿原始数据
  const filterData = chartData.filter(chartDatum => chartDatum[chartSpec.xField] === xDimensionValue);

  console.log(filterData);
});
```

### Issue Description or Suggestion

折线图的单个或者多个数据获取都没有例子，我不知道怎么获取数据，麻烦提供个例子说明下，谢谢！

**Comment by xile611** [comment]
@kuangyuliang 如果是想获取点击的维度数据，可以监听`dimensionClick` 事件

```
vchart.on('dimensionClick',  (e) => {
  console.log(e);
});
```

<img width="598" alt="image" src="https://github.com/user-attachments/assets/9e2c6a46-fc57-48b8-9f3c-064a5b806973" />

如果要限制在点击到线上，可以如下判断

```
vchart.on('dimensionClick',  (e) => {
  if (e.model && e.model.type === 'line') {
    
  }
});
```

点击到柱子上也类似

**Comment by hmj-0v0** [comment]
> dimensionClick

请问有适配移动端的方法吗？试了下这个方法在移动端上貌似不会触发的样子

**Comment by hmj-0v0** [comment]
> @kuangyuliang 如果是想获取点击的维度数据，可以监听`dimensionClick` 事件
> 
> ```
> vchart.on('dimensionClick',  (e) => {
>   console.log(e);
> });
> ```
> 
> <img alt="image" width="598" src="https://private-user-images.githubusercontent.com/6111424/396327129-9e2c6a46-fc57-48b8-9f3c-064a5b806973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTcxMDEsIm5iZiI6MTczNDUxNjgwMSwicGF0aCI6Ii82MTExNDI0LzM5NjMyNzEyOS05ZTJjNmE0Ni1mYzU3LTQ4YjgtOWYzYy0wNjRhNWI4MDY5NzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMTAxMzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2FmOWIyMDlhN2VhM2NmNDBiMGQyYzhlODQzZjQ1NjA2MTkxNTAyZjM5YmNhNDhiNzg2ZmRiMTQyY2RmNGUxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vUoESKWkXw8RK4iAOhpi5-dFJtChHqaCNPTR4JR5tkg">
> 如果要限制在点击到线上，可以如下判断
> 
> ```
> vchart.on('dimensionClick',  (e) => {
>   if (e.model && e.model.type === 'line') {
>     
>   }
> });
> ```
> 
> 点击到柱子上也类似

请问有适配移动端的方法吗？试了下这个方法在移动端上貌似不会触发的样子
