### ISSUE TITLE
[Bug] tooltipRender in react-vchart cannot support enterable

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VChart#3522]
### Version

1.13.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

![img_v3_02hd_e708ba0d-ef5e-426b-a571-353057fc30bg](https://github.com/user-attachments/assets/4d09156f-1248-4b36-b67d-8cc93d1ea485)

![img_v3_02hd_dd4e0961-df32-4dcc-91f9-343fa0d526bg](https://github.com/user-attachments/assets/d46c3392-1a53-4f97-9cc7-381bf8036c30)

### Current Behavior

Cannot support enterable

### Expected Behavior

support enterable

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
fixed in 1.13.1

when open `enterable`, it recommended to add `transitionDuration: 0` to tooltip
