### ISSUE TITLE
[Bug] 在鸿蒙arkts中, 饼状图绘制大小异常

### ISSUE THREAD

**Issue by damengbuxing** [VisActor/VChart#3554]
### Version

1.12.15

### Link to Minimal Reproduction

-

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/22eb36b0-ad51-4bd3-87fc-e9c7a6d6bc34)
![image](https://github.com/user-attachments/assets/a8a25d41-f812-458b-8f78-87dc644c6f5d)

### Current Behavior

![image](https://github.com/user-attachments/assets/3d808a4b-056e-405c-8e2f-5bc73bfa9e38)

### Expected Behavior

期望可以占满整个容器

### Environment

```markdown
- OS: macOS Monterey 
- Browser:
- Framework: HarmonyOS
```

**Comment by xile611** [comment]
@damengbuxing 试试增加配置 `padding: 0`，vchart默认主题中，padding 默认值是 20px

**Comment by damengbuxing** [comment]
加上确实好了,  不过文档中好像并没有说默认值是30. 还有些小建议, 
1. w h spec 参数带上private会有警告;
2. 希望能为 spec 参数提供具体类型, 因为在使用Record时属性没有提示, 而且每个对象都要 as ESObject 很麻烦, ESObject 也会有警告.

**Comment by xile611** [comment]
类型定义的问题， @neuqzxy  看看

**Comment by xile611** [comment]
> 加上确实好了, 不过文档中好像并没有说默认值是30. 还有些小建议,
> 
> 1. w h spec 参数带上private会有警告;
> 2. 希望能为 spec 参数提供具体类型, 因为在使用Record时属性没有提示, 而且每个对象都要 as ESObject 很麻烦, ESObject 也会有警告.

这个是默认主题里面配置，如果不用这个主题就没有，有点不好描述。。。。

**Comment by xile611** [comment]
类型定义问题， 暂时无法短期解决，这个issue先关闭
