### ISSUE TITLE
[Bug] axes label with background does not display completely

### ISSUE THREAD

**Issue by purpose233** [VisActor/VChart#3559]
### Version

1.12.6

### Link to Minimal Reproduction

null

### Steps to Reproduce

数据包含隐私信息。

spec 中轴标签已经配置 flush，但是标签内容仍然被截断。

### Current Behavior

![image](https://github.com/user-attachments/assets/05789077-3d83-4c81-bda6-b47170afefd2)

### Expected Behavior

轴标签完整显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
类似问题，建议设置图表 padding，或轴内偏移`innerOffset`；


具体修改方式见 vrender pr: https://github.com/VisActor/VRender/pull/1615
修改后影响 autohLimit 效果，综合评估暂不合入。

![image](https://github.com/user-attachments/assets/508da06a-128d-49b4-bd5b-188774628952)
