### ISSUE TITLE
[Bug] incorrect heatmap label position while dragging datazoom

### ISSUE THREAD

**Issue by purpose233** [VisActor/VChart#3561]
### Version

1.12.6

### Link to Minimal Reproduction

null

### Steps to Reproduce

数据包含隐私信息。

spec 中标签已经配置 position 为 inside，但是在 datazoom 拖拽过程中，标签位置出现跳变。

### Current Behavior

![20241212202358_rec_](https://github.com/user-attachments/assets/c150b586-8c1c-4ad1-a3dd-d6b870a9ce56)

### Expected Behavior

标签位置不变化。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
设置 `label.overlap.strategy: []` ，重叠后无任何策略即可
