### ISSUE TITLE
possible to use in plain html?

### ISSUE THREAD

**Issue by quantrpeter** [VisActor/VChart#3567]
Hi

   I got

```
Uncaught TypeError: VChart is not a constructor
```

```
<html>

<head>
    <meta charset="utf-8" />
	<script src="https://cdn.jsdelivr.net/npm/@visactor/vchart/build/index.min.js"></script>
  </head>

<body>
	<!-- Prepare a DOM with size (width and height) for vchart, or you can specify it in the spec configuration -->
	<div id="chart" style="width: 600px;height:400px;"></div>
</body>
<script>
	const spec = {
		data: [
			{
				id: 'barData',
				values: [
					{ month: 'Monday', sales: 22 },
					{ month: 'Tuesday', sales: 13 },
					{ month: 'Wednesday', sales: 25 },
					{ month: 'Thursday', sales: 29 },
					{ month: 'Friday', sales: 38 }
				]
			}
		],
		type: 'bar',
		xField: 'month',
		yField: 'sales'
	};

	// Create a vchart instance
	/**
	 * Note: When using the CDN approach for importing, pay attention to the way VChart is referenced:
	 * const vchart = new VChart.default(spec, { dom: 'chart' });
	 */
	const vchart = new VChart(spec, { dom: 'chart' });
	// Draw the chart
	vchart.renderSync();
</script>

</html>
```

**Comment by xile611** [comment]
> Hi
> 
> I got
> 
> ```
> Uncaught TypeError: VChart is not a constructor
> ```
> 
> ```
> <html>
> 
> <head>
>     <meta charset="utf-8" />
> 	<script src="https://cdn.jsdelivr.net/npm/@visactor/vchart/build/index.min.js"></script>
>   </head>
> 
> <body>
> 	
> 	<div id="chart" style="width: 600px;height:400px;"></div>
> </body>
> <script>
> 	const spec = {
> 		data: [
> 			{
> 				id: 'barData',
> 				values: [
> 					{ month: 'Monday', sales: 22 },
> 					{ month: 'Tuesday', sales: 13 },
> 					{ month: 'Wednesday', sales: 25 },
> 					{ month: 'Thursday', sales: 29 },
> 					{ month: 'Friday', sales: 38 }
> 				]
> 			}
> 		],
> 		type: 'bar',
> 		xField: 'month',
> 		yField: 'sales'
> 	};
> 
> 	// Create a vchart instance
> 	/**
> 	 * Note: When using the CDN approach for importing, pay attention to the way VChart is referenced:
> 	 * const vchart = new VChart.default(spec, { dom: 'chart' });
> 	 */
> 	const vchart = new VChart(spec, { dom: 'chart' });
> 	// Draw the chart
> 	vchart.renderSync();
> </script>
> 
> </html>
> ```

@quantrpeter replace `new VChart` with `new VChart.default`
