### ISSUE TITLE
[Bug] react-vchart图表连续两次更新数据，导致数据没更新上

### ISSUE THREAD

**Issue by neuqzxy** [VisActor/VChart#3576]
### Version

1.13.0

### Link to Minimal Reproduction

1.13.0

### Steps to Reproduce

连续两次更新数据，最后一次数据没更新上

### Current Behavior

连续两次更新数据，最后一次数据没更新上

### Expected Behavior

连续两次更新数据，最后一次数据要更新上

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by neuqzxy** [comment]
群里@xugenshi

**Comment by xile611** [comment]
没有复现，应该是上层封装的问题
