### ISSUE TITLE
[Bug] Tooltip cannot be confined within the mounted DOM node

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#3590]
### Version

1.13.1

### Link to Minimal Reproduction

none

### Steps to Reproduce

- 问题1: dom tooltip 有时候没有被正确约束在挂载 dom 宽高内, [demo](https://visactor.com/vchart/demo/bar-chart/group-stack-column) 可复现
<img width="986" alt="image" src="https://github.com/user-attachments/assets/d070d685-c097-4c29-9b6f-4baf7b4f7a04" />

- 问题2: react 下使用自定义tooltip组件，无法约束在dom宽高内，见下 spec； 

- 问题2: dom tooltip 配置 confine: true，tooltip 消失； 

- 问题3: 1.13.0 后，tooltip demo不正确
https://visactor.com/vchart/demo/tooltip/enterable-tooltip?version=1.13.0
<img width="786" alt="image" src="https://github.com/user-attachments/assets/ae398d57-3f58-4a49-9c9b-d45df0fbf9a2" />

问题2 代码:
```js
const lineData = generateData([{ key: 'type', values: ['A', 'B', 'C'] }], 20);

function App() {
  const chartRef = useRef(null);
  return (
    <div className="App">
      <LineChart ref={chartRef} data={[{ id: 'id0', values: lineData }]}>
        <Line xField="x" yField="y" seriesField="type" />
        <Tooltip
          parentElement="root"
          mark={{ visible: false }}
          dimension={{ hasShape: true, content: [] }}
          triggerOff="none"
        >
          <TestTooltip />
        </Tooltip>
      </LineChart>
    </div>
  );
}

const TestTooltip = ({ actualTooltip }: ITooltipRenderProps) => (
  <div>
    <div style={{ color: 'red', padding: 5 }}>🏀 {actualTooltip.title.value}</div>
    <div style={{ color: 'red', padding: 5 }}>🏀 {actualTooltip.title.value}</div>
    <div style={{ color: 'red', padding: 5 }}>🏀 {actualTooltip.title.value}</div>
    <div style={{ color: 'red', padding: 5 }}>🏀 {actualTooltip.title.value}</div>
  </div>
);

```

### Current Behavior

none

### Expected Behavior

none

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
fixed in 1.13.2
