### ISSUE TITLE
[Bug] set `tickStep` to time axes will cause the page to crash

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#3591]
### Version

1.13.1

### Link to Minimal Reproduction

https://www.visactor.io/vchart/demo/label/label-formatter

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/a9f2e4fd-e3c3-452a-b374-b4cdc9f55bb0)

### Current Behavior

页面崩溃

### Expected Behavior

图表正常绘制

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
@xiaoluoHe tickStep: 2 应该代表了 2ms，tick太多了
