### ISSUE TITLE
[Feature] add an option to axis.label.style.textAlign to make all the labels align in the center of the whole axis component

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#380]
### What problem does this feature solve?

While label.style.textAlign support 'center' currently, the baseline of the text is not in the middle of the whole axis component:
![img_v2_7dd56c77-39f5-401a-9df4-8b4fa9d4deeg](https://github.com/VisActor/VChart/assets/20367445/899f5571-0608-44de-ad44-1651c6df0fef)
We need a new option to make the baseline of the align in the middle of the axis (0.5*width of the axis):
![img_v2_e2371cdc-605a-45d0-a4a2-4dcfc4bc8e3g](https://github.com/VisActor/VChart/assets/20367445/1c76fb34-2c24-49f9-bad2-d5390e1e54e4)

### What does the proposed API look like?

label.style.textAlign='axisCenter'

**Comment by kkxxkk2019** [comment]
@visactor/vchart@1.3.0-beta.3 support it
