### ISSUE TITLE
[Feature] axis supports to show the tick of maximum value

### ISSUE THREAD

**Issue by zamhown** [VisActor/VChart#393]
![Image](https://user-images.githubusercontent.com/15249097/258029265-7f8a9097-951f-475c-9ff7-42e14d835736.png)

两种思路
- 基于显示最大值 tick 的约束重新设计采样算法以达到均分
- tick 步长计算后可以支持自动扩展一个步长，达到最大值 tick 必现的效果？

**Comment by kkxxkk2019** [comment]
已经解决，升级到 latest 版本就可以了
