### ISSUE TITLE
[Feature]  Provide an API for retrieving the width and height of a region in extension mark callback

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#414]
### What problem does this feature solve?

线高度，这里用 valueToY(0) ，实际上，当数据存在负数时，高度会不正确。
![image](https://github.com/VisActor/VChart/assets/11360419/a121c877-a252-47a3-a2f2-09e7aabb25ff)

### What does the proposed API look like?

```js
const  {width, height} = ctx.regionSize();
```

**Comment by kkxxkk2019** [comment]
已经在上下文提供了 getRegion() 方法
