### ISSUE TITLE
[Bug] axis layout error when chart height is small

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#416]
### Version

1.1.0-beta.10

### Link to Minimal Reproduction

none

### Steps to Reproduce

1. small chart height

### Current Behavior

![e180fb9d-19f9-4f69-8f96-15c8eb76642d](https://github.com/VisActor/VChart/assets/25134429/a766d020-cd0b-4dd0-8cb9-639c20bf1f3b)
![7871c759-4286-4a6a-88c4-cb5a67544628](https://github.com/VisActor/VChart/assets/25134429/331a2c5d-555d-47c7-92b8-ae41e7d271a5)
![c0b92c77-dc78-4548-9dac-107c6f6141cc](https://github.com/VisActor/VChart/assets/25134429/2bb6acae-3e31-458f-a5ef-8c44f3ec8daf)

### Expected Behavior

correct axis layout

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
It mainly caused by the title hadn't ellipsis correctly(https://github.com/VisActor/VChart/issues/417), and the issue had been fixed. After 1.2.0 has been released, you can upgrade and validate it.
