### ISSUE TITLE
[Bug] tooltip will not show when brush is set in spec

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#419]
### Version

1.1.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

const spec ={
    "type": "bar",
    "xField": [
        "230804000453014",
        "10001"
    ],
    "yField": [
        "10002"
    ],
    "direction": "vertical",
    "seriesField": "20001",
    "data": [
        {
            "id": "data",
            "values": [
                {
                    "10001": "销售额",
                    "10002": "3504050.1277780533",
                    "10003": "230804000453017",
                    "20001": "销售额",
                    "230804000453014": "二级",
                    "230804000453017": "3504050.1277780533"
                },
                {
                    "10001": "销售额",
                    "10002": "2407324.292157173",
                    "10003": "230804000453017",
                    "20001": "销售额",
                    "230804000453014": "一级",
                    "230804000453017": "2407324.292157173"
                },
                {
                    "10001": "销售额",
                    "10002": "835469.698682785",
                    "10003": "230804000453017",
                    "20001": "销售额",
                    "230804000453014": "当日",
                    "230804000453017": "835469.698682785"
                },
                {
                    "10001": "销售额",
                    "10002": "9377948.706583977",
                    "10003": "230804000453017",
                    "20001": "销售额",
                    "230804000453014": "标准级",
                    "230804000453017": "9377948.706583977"
                }
            ],
            "fields": {
                "10001": {
                    "alias": "指标名称 "
                },
                "10002": {
                    "alias": "指标值 "
                },
                "20001": {
                    "alias": "图例项 ",
                    "domain": [
                        "销售额"
                    ]
                },
                "230804000453014": {
                    "alias": "邮寄方式",
                    "domain": [
                        "标准级",
                        "当日",
                        "二级",
                        "一级"
                    ]
                },
                "230804000453017": {
                    "alias": "销售额"
                }
            }
        }
    ],
    "axes": [
        {
            "type": "band",
            "tick": {
                "visible": false
            },
            "grid": {
                "visible": false,
                "style": {
                    "stroke": "#DADCDD",
                    "lineWidth": 1,
                    "lineDash": [
                        4,
                        2
                    ]
                }
            },
            "orient": "bottom",
            "visible": true,
            "domainLine": {
                "visible": true,
                "style": {
                    "lineWidth": 1,
                    "stroke": "#989999"
                }
            },
            "title": {
                "visible": false,
                "text": "邮寄方式",
                "style": {
                    "fontSize": 12,
                    "fill": "#363839",
                    "fontWeight": "normal"
                }
            },
            "label": {
                "visible": true,
                "style": {
                    "fontSize": 12,
                    "fill": "#6F6F6F",
                    "angle": 0,
                    "fontWeight": "normal"
                },
                "minGap": 4,
                "flush": true
            },
            "hover": true,
            "background": {
                "visible": true,
                "state": {
                    "hover": {
                        "fillOpacity": 0.08,
                        "fill": "#141414"
                    }
                }
            },
            "paddingInner": 0.15,
            "paddingOuter": 0.075
        },
        {
            "type": "linear",
            "tick": {
                "visible": false,
                "style": {
                    "stroke": "rgba(255, 255, 255, 0)"
                }
            },
            "niceType": "accurateFirst",
            "grid": {
                "visible": true,
                "style": {
                    "stroke": "#DADCDD",
                    "lineWidth": 1,
                    "lineDash": [
                        4,
                        2
                    ]
                }
            },
            "orient": "left",
            "visible": true,
            "domainLine": {
                "visible": true,
                "style": {
                    "lineWidth": 1,
                    "stroke": "rgba(255, 255, 255, 0)"
                }
            },
            "title": {
                "visible": false,
                "text": "销售额",
                "style": {
                    "fontSize": 12,
                    "fill": "#363839",
                    "fontWeight": "normal"
                }
            },
            "label": {
                "visible": true,
                "style": {
                    "fontSize": 12,
                    "fill": "#6F6F6F",
                    "angle": 0,
                    "fontWeight": "normal"
                }
            },
            "hover": true,
            "background": {
                "visible": true,
                "state": {
                    "hover": {
                        "fillOpacity": 0.08,
                        "fill": "#141414"
                    }
                }
            },
            "zero": true,
            "nice": true
        }
    ],
    "color": {
        "field": "20001",
        "type": "ordinal",
        "range": [
            "#2E62F1"
        ],
        "specified": {}
    },
    // "legends": [
    //     {
    //         "type": "discrete",
    //         "id": "legend",
    //         "orient": "right",
    //         "position": "start",
    //         "layoutType": "normal",
    //         "visible": true,
    //         "hover": false,
    //         "maxCol": 1,
    //         "title": {
    //             "textStyle": {
    //                 "fontSize": 12,
    //                 "fill": "#6F6F6F"
    //             }
    //         },
    //         "item": {
    //             "spaceRow": 0,
    //             "spaceCol": 0,
    //             "padding": {
    //                 "top": 4,
    //                 "bottom": 4,
    //                 "left": 4,
    //                 "right": 22
    //             },
    //             "background": {
    //                 "style": {
    //                     "fillOpacity": 0.001
    //                 }
    //             },
    //             "label": {
    //                 "style": {
    //                     "fontSize": 12,
    //                     "fill": "#6F6F6F"
    //                 }
    //             },
    //             "shape": {
    //                 "style": {
    //                     "symbolType": "square"
    //                 }
    //             }
    //         },
    //         "pager": {
    //             "textStyle": {},
    //             "handler": {
    //                 "style": {},
    //                 "state": {
    //                     "disable": {}
    //                 }
    //             }
    //         },
    //         "padding": {
    //             "top": 0,
    //             "bottom": 0,
    //             "left": 16,
    //             "right": 0
    //         }
    //     }
    // ],
    "label": {
        "visible": false,
        "overlap": {
            "hideOnHit": true,
            "clampForce": true
        },
        "style": {
            "fontSize": 12,
            "fontWeight": "normal",
            "fill": null,
            "strokeOpacity": 1
        },
        "position": "inside",
        "smartInvert": {
            "brightColor": "#fff",
            "darkColor": "#363839",
            "brightStroke": null,
            "brightStrokeWidth": 2,
            "darkStroke": "rgba(255, 255, 255, 0.8)",
            "darkStrokeWidth": 2
        }
    },
    "hover": {
        "enable": true
    },
    "select": {
        "enable": true
    },
    "bar": {
        "state": {
            "hover": {
                "cursor": "pointer",
                "fillOpacity": 0.8,
                "stroke": "#58595B",
                "lineWidth": 1,
                "zIndex": 500
            },
            "selected": {
                "cursor": "pointer",
                "fillOpacity": 1,
                "stroke": "#58595B",
                "lineWidth": 1
            },
            "selected_reverse": {
                "fillOpacity": 0.3,
                "strokeWidth": 0.3
            }
        },
        "clipByLayout": true
    },
    "background": "rgba(255, 255, 255, 0)",
    "animation": false,
    "brush": {
        "inBrush": {
            "colorAlpha": 1
        },
        "outOfBrush": {
            "colorAlpha": 0.2
        }
    },
    "hash": "5a826a60eedcf82001c71c4d4475e116"
}

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

tooltip will not show. But when you remove the "brush" config in spec, it will work correctly.

### Expected Behavior

tooltip will show correctly when brush is set in spec

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by skie1997** [comment]
it has been sloved with vrender upgrade
