### ISSUE TITLE
[Feature] mark tooltip supports setting based on mark type

### ISSUE THREAD

**Issue by zamhown** [VisActor/VChart#42]
### What problem does this feature solve?

Users hope to more conveniently configure different tooltip content for different mark types.
![img_v2_aa555535-e619-440e-97ee-750f0f37b20g](https://github.com/VisActor/VChart/assets/15249097/019efc6e-2207-4a44-a8ad-f7e1bdcec495)

### What does the proposed API look like?

There are 2 ways to implement:
1. add `tooltip` api to mark spec, like this:
  ```ts
  // series spec
  {
    funnel: {
      style: { ... },
      state: { ... },
      tooltip: { ... } // ITooltipPattern
    },
    transform: {
      style: { ... },
      state: { ... },
      tooltip: { ... } // ITooltipPattern
    },
  }
  ```
  `ITooltipPattern` declaration:
  ```ts
  interface ITooltipPattern {
    visible?: boolean;
    title?: IToolTipLinePattern;
    content?: IToolTipLinePattern[];
    position?: TooltipPosition;
    hasShape?: boolean;
    shapeType?: ShapeType | TooltipContentCallback;
    shapeColor?: string | TooltipContentCallback;
    shapeHollow?: boolean;
    updateTitle?: (prev: IToolTipLineActual | undefined, data: TooltipData) => IToolTipLineActual | undefined;
    updateContent?: (prev: IToolTipLineActual[] | undefined, data: TooltipData) => IToolTipLineActual[] | undefined;
    updatePosition?: (prev: ITooltipPositionActual | undefined, data: TooltipData) => ITooltipPositionActual | undefined;

    // new api, same to the property in ITooltipSpec
    style?: Omit<ITooltipTheme, 'maxWidth' | 'minWidth' | 'offset'>;
  }
  ```
  This method is very intuitive but difficult to implement.

2. `ITooltipPattern.visible`, `ITooltipPattern.title` and `ITooltipPattern.content` support custom callback:
  ```ts
  interface ITooltipPattern {
    visible?: boolean | ((data: TooltipData, mark: IMark) => boolean);
    title?: IToolTipLinePattern | ((data: TooltipData, mark: IMark) => IToolTipLinePattern);
    content?: IToolTipLinePattern[] | ((data: TooltipData, mark: IMark) => IToolTipLinePattern[]);
  }
  ```
  This method is less flexible and scalable.

**Comment by kkxxkk2019** [comment]
I prefer the second option as it is more flexible, and we already have `tooltip.mark`, it is better to centralize the configuration in one place.

**Comment by xiaoluoHe** [comment]
I prefer to the callback as well. 
In addition,  I think `element` is a better argument than `mark` :

`(data: TooltipData, element: IElement) => IToolTipLinePattern[])`
or
`(data: TooltipData, element: IElement, params: { mark: IMark, event: xxx}) => IToolTipLinePattern[])`
