### ISSUE TITLE
[Bug] axis labels display error

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#454]
### Version

1.1.0-beta.10

### Link to Minimal Reproduction

https://codesandbox.io/s/axis-labels-display-error-kcqsvq?file=/src/index.ts

### Steps to Reproduce

none

### Current Behavior

1. left axis label's textAlign and textBaseLine are wrong when axis label space is 0
![image](https://github.com/VisActor/VChart/assets/25134429/6ef271f8-26e5-44c7-8eb4-97ee9b5dc9f8)

2. left axis can not move autolly to avoid intersecting with the axis line
![image](https://github.com/VisActor/VChart/assets/25134429/219109cf-ca3a-4a0e-acaa-fe42e48ecd31)

### Expected Behavior

1. left axis label layout correctly when axis label space is 0
2. left axis label auto layout when axis label config has angle

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
It had been fixed in https://github.com/VisActor/VRender/pull/268, and it will released in @vchart/visactor@1.2.1 which we will upgrader vrender version to v0.14.x

**Comment by kkxxkk2019** [comment]
@visactor/vchart@1.3.0-beta.3 solve it
