### ISSUE TITLE
[Bug] axis label position difference on Safari

### ISSUE THREAD

**Issue by zamhown** [VisActor/VChart#470]
Safari：

![Image](https://github.com/VisActor/VChart/assets/15249097/e7fcfe46-0ba5-4cd6-81c9-65c07f251293)
![image](https://github.com/VisActor/VChart/assets/15249097/b8887b23-8b6a-4f31-b734-798705700cbc)

Chrome：

![Image](https://github.com/VisActor/VChart/assets/15249097/06552570-3963-4c46-a414-91074453fd09)
![image](https://github.com/VisActor/VChart/assets/15249097/100c9ffc-d6d6-458e-b66b-c0e463209f0b)

**Comment by zamhown** [comment]
Reason: Safari's canvas text rendering is slightly lower than the Chrome baseline.

Safari：
![img_v2_264b3d40-875f-451f-9230-ce7b9a7ef60g](https://github.com/VisActor/VChart/assets/15249097/c04bc932-8c12-4b77-9b61-b77e47b76bee)

Chrome:
![img_v2_315c5db9-43a6-4eac-9534-d24629122f8g](https://github.com/VisActor/VChart/assets/15249097/c281c031-5de6-4c82-a6c2-0769612e503f)

There are some similar issues, and the rendering effects of Chrome and Firefox are also different:

https://stackoverflow.com/questions/39379392/placing-text-on-html5-canvas-inconsistent-across-browsers
https://stackoverflow.com/questions/35407614/html5-canvas-textbaseline-top-looks-different-in-firefox-and-chrome

What needs to be done now is to add a buffer to the VRender text measure method to make it compatible with various browsers.

**Comment by kkxxkk2019** [comment]
fixed: https://github.com/VisActor/VRender/issues/294
