### ISSUE TITLE
[Bug] use updateDataSync chart domain error when axis set visible false  

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VChart#488]
### Version

1.1.0-beta.10

### Link to Minimal Reproduction

none 

### Steps to Reproduce

```
axes: [
          { orient: 'left', visible: false, label: { visible: true } },
          { orient: 'bottom', visible: false }
        ],
```

### Current Behavior

domain use first data domain, not render right
![image](https://github.com/VisActor/VChart/assets/3468473/3abbaf51-1828-42c4-a8b4-eb346997e8f4)

### Expected Behavior

![image](https://github.com/VisActor/VChart/assets/3468473/928807de-5642-4848-90ce-f682791722d8)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
change into #489
