### ISSUE TITLE
[Bug] time scale line chart cause page crush when certain data is passed in

### ISSUE THREAD

**Issue by neuqzxy** [VisActor/VChart#528]
### Version

1.2.0

### Link to Minimal Reproduction

const wrongSpec = {   type: 'line',   xField: 'time',   yField: 'price',   data: [     {       values: [          {           price: 2384.8,           // time: '1691942400000',           time: '1692028800000',           // manufacturer: 'FOXCONN',           // __VCHART_DEFAULT_DATA_INDEX: 0,           // __VCHART_DEFAULT_DATA_KEY: '1691942400000_FOXCONN_0',           // VGRAMMAR_DATA_ID_KEY_42: 0,           // VGRAMMAR_DATA_ID_KEY_68: 0,         }     },   ],    axes: [     {       orient: 'bottom',       type: 'time',       layers: [         {           timeFormat: '%Y%m%d',           tickStep: 86400,         },       ],     },   ], };

### Steps to Reproduce

the spec is listed below:
const wrongSpec = {
  type: 'line',
  xField: 'time',
  yField: 'price',
  data: [
    {
      values: [

        {
          price: 2384.8,
          // time: '1691942400000',
          time: '1692028800000',
          // manufacturer: 'FOXCONN',
          // __VCHART_DEFAULT_DATA_INDEX: 0,
          // __VCHART_DEFAULT_DATA_KEY: '1691942400000_FOXCONN_0',
          // VGRAMMAR_DATA_ID_KEY_42: 0,
          // VGRAMMAR_DATA_ID_KEY_68: 0,
        }
]
    },
  ],

  axes: [
    {
      orient: 'bottom',
      type: 'time',
      layers: [
        {
          timeFormat: '%Y%m%d',
          tickStep: 86400,
        },
      ],
    },
  ],
};

### Current Behavior

page was block

### Expected Behavior

page run as usual

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
排查了下：是 niceDomain 这个逻辑造成的，用户的数据只有一个值造成 domain 的 min max 相同，走到了 https://github.com/VisActor/VChart/blob/db7cf449723edafaeecdc781c1c8d122cf4ed87a/packages/vchart/src/component/axis/mixin/linear-axis-mixin.ts#L130 这个逻辑中，domain 被优化未[0, 5000000000000]，然后用户的 tickStep 配置为 86400，这样就导致了 ticks 数量非常巨大，5000000000000 / 86400 = 57870370.37037037，导致程序卡死。

解决方案：只针对 type === 'linear' 的 scale 轴做 niceDomain 处理
