### ISSUE TITLE
[Feature] Sankey diagram interaction

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#529]

**Comment by pairone** [comment]
Realize partial highlighting effect based on data

**Comment by xiaoluoHe** [comment]
Hope to provide the ability to customize interactions.

之前我们提供了 3 种内置交互：
1. 高亮单个节点
2. 高亮上下游节点
3. 高亮整条路径

现在可能会有新的交互需求，例如：高亮上下游中最大值的节点；所以期望能有一种自定义交互的方式

**Comment by pairone** [comment]
Partial highlighting effect
![img_v2_1ea0af4b-e44b-4be0-9d98-c8a1f92a08bg](https://github.com/VisActor/VChart/assets/40026218/ae86199e-ef52-45d0-b2c3-0172585b3279)

**Comment by xuanhun** [comment]
>

> Hope to provide the ability to customize interactions.
> 
> 之前我们提供了 3 种内置交互：
> 
> 1. 高亮单个节点
> 2. 高亮上下游节点
> 3. 高亮整条路径
> 
> 现在可能会有新的交互需求，例如：高亮上下游中最大值的节点；所以期望能有一种自定义交互的方式

It is best to use English or a combination of Chinese and English.  @xiaoluoHe
