### ISSUE TITLE
[Bug] label disappear in pie chart

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#553]
### Version

latest

### Link to Minimal Reproduction

https://codesandbox.io/s/label-disappear-v253w6?file=/src/index.ts

### Steps to Reproduce

none

### Current Behavior

bottom label disappear
![image](https://github.com/VisActor/VChart/assets/25134429/9d0ec3d3-dc52-4a78-a77e-63ee7d52a45c)
add config `coverEnable: true,` label  appear

![image](https://github.com/VisActor/VChart/assets/25134429/1ef5f5bc-60f6-4238-afbe-2c4f7126a187)

### Expected Behavior

label  appear when `coverEnable: false,`

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
默认的布局逻辑是这样的，默认是会计算两个半圆弧来布局标签，cover enable 开启之后就全都按照整圆弧来布局，所以是这样的效果.

The default layout logic is like this. By default, two semi-arcs are calculated to lay out the labels. After the cover enable is turned on, they are all laid out according to the full arc, so this is the effect.

**Comment by kkxxkk2019** [comment]
It will be fixed in 1.3.0, @pairone please add this case to bugserver
