### ISSUE TITLE
[Feature] Add segment progress chart demo

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#555]
### What problem does this feature solve?

Add segment progress chart demo in VChart website, such like:
![img_v2_14dca9c9-de61-4e47-9e51-6f5194b2bb1g](https://github.com/VisActor/VChart/assets/25134429/494219d4-0fd9-482e-98a1-fb32be7f7a0e)

### What does the proposed API look like?

none

**Comment by xuanhun** [comment]
> https://codesandbox.io/s/segment-linear-progress-3v4w5q
> 
> ![image](https://user-images.githubusercontent.com/135952300/261027955-289dd236-3a0a-4f53-917a-f352c62a1c2e.png)
This should be added to website.

**Comment by kkxxkk2019** [comment]
> > https://codesandbox.io/s/segment-linear-progress-3v4w5q
> > ![image](https://user-images.githubusercontent.com/135952300/261027955-289dd236-3a0a-4f53-917a-f352c62a1c2e.png)
> > This should be added to website.

on the way
