### ISSUE TITLE
[Bug] word cloud demo in the website can't render

### ISSUE THREAD

**Issue by xuanhun** [VisActor/VChart#561]
### Version

1.2.0

### Link to Minimal Reproduction

https://www.visactor.io/vchart/demo/word-cloud-chart/word-cloud-shape-rotate

### Steps to Reproduce

1. open the url https://www.visactor.io/vchart/demo/word-cloud-chart/word-cloud-shape-rotate
![image](https://github.com/VisActor/VChart/assets/2384516/2aec2b19-68b6-4d57-8703-91bd618a3fbc)

### Current Behavior

It can't  be rendered

### Expected Behavior

It should  be rendered 

### Environment

```markdown
- OS: Mac os
- Browser: Chrome 115.0.5790.170
- Framework:
```

**Comment by skie1997** [comment]
related to https://github.com/VisActor/VGrammar/pull/150
it will be sloved after vgrammar upgrade
