### ISSUE TITLE
[Bug] formatMethod does not work on label, outerLabel and transformLabel in funnel chart

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#571]
### Version

1.1.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

const spec = {
  type: 'funnel',
  maxSize: '75%',
  minSize: '10%',
  isTransform: true,
  shape: 'rect',
  color: {
    type: 'ordinal',
    range: ['#00328E', '#0048AA', '#005FC5', '#2778E2', '#4E91FF', '#70ABFF', '#8FC7FF', '#AEE2FF']
  },
  funnel: {
    style: {
      cornerRadius: 4,
      stroke: 'white',
      lineWidth: 2
    },
    state: {
      hover: {
        stroke: '#4e83fd',
        lineWidth: 1
      }
    }
  },
//       tooltip:{
// // mark:{visible:false},
// dimension:{visible:false}
//     },
  transform: {
interactive:false,
    style: {
      stroke: 'white',
      lineWidth: 2,
    },
    state: {
      hover: {
        stroke: '#4e83fd',
        lineWidth: 1
      }
    }
  },
  label: {
    formatMethod:v=>v+'123',
    visible: true,
    smartInvert:{
    },
    style: {
      lineHeight: 16,
      limit: Infinity,
      text: datum => [`${datum.name}`, `${datum.value}`],
      fill:undefined,
    }
  },
  outerLabel: {
    formatMethod:v=>v+'123',
    visible: true,
    position: 'top',
    alignLabel: false,
    style: {
      text: datum => {
        return `${datum.percent * 100}%`;
      }
    },
    line: {
      style: {
        lineDash: [2, 2]
      }
    }
  },
  transformLabel: {
    formatMethod:v=>v+'123',
    visible: true,
    style: {
      fill: undefined,
    }
  },
  data: [
    {
      name: 'funnel',
      values: [
        {
          value: 100,
          name: 'Resume Screening',
          percent: 1
        },
        {
          value: 80,
          name: 'Resume Evaluation',
          percent: 0.8
        },
        {
          value: 50,
          name: 'Evaluation Passed',
          percent: 0.5
        },
        {
          value: 30,
          name: 'Interview',
          percent: 0.3
        },
        {
          value: 10,
          name: 'Final Pass',
          percent: 0.1
        }
      ]
    }
  ],
  categoryField: 'name',
  valueField: 'value',
  funnelOrient:'left'
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

<img width="1308" alt="image" src="https://github.com/VisActor/VChart/assets/20367445/d027403d-8001-432d-831b-da2936ee52ff">

### Expected Behavior

formatMethod should work correctly just like other charts.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
related case:
 646745e9cb5fa8011f4e03e3
 646745e9cb5fa8011f4e03f1
