### ISSUE TITLE
[Bug] smartInvert does not work on funnel chart

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#573]
### Version

1.1.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

const spec = {
    "type": "funnel",
    "shape": "rect",
    "categoryField": "230818142327043",
    "valueField": "230818142327046",
    "funnelOrient": "top",
    "data": [
        {
            "id": "data",
            "values": [
                {
                    "230818142327043": "西北",
                    "230818142327046": "815039.5979347229"
                },
                {
                    "230818142327043": "中南",
                    "230818142327046": "4137415.0951108932"
                },
                {
                    "230818142327043": "东北1",
                    "230818142327046": "2681567.4745378494"
                },
                {
                    "230818142327043": "西南",
                    "230818142327046": "1303124.5089645386"
                },
                {
                    "230818142327043": "华东",
                    "230818142327046": "4684506.442247391"
                },
                {
                    "230818142327043": "华北",
                    "230818142327046": "2447301.0141382217"
                }
            ],
            "fields": {
                "230818142327043": {
                    "alias": "地区"
                },
                "230818142327046": {
                    "alias": "销售额"
                }
            }
        }
    ],
    "isTransform": true,
    "transformLabel": {
        "visible": true,
        "style": {
            "fontSize": 14
        }
    },
    "transform": {
        "interactive": false
    },
    "seriesField": "230818142327043",
    "color": {
        "field": "230818142327043",
        "type": "ordinal",
        "range": [
            "#009db5",
            "#f2b823",
            "#eb7006",
            "#1f5273",
            "#3da241",
            "#77bfc8"
        ],
        "specified": {}
    },
    "legends": [
        {
            "type": "discrete",
            "id": "legend",
            "orient": "right",
            "position": "start",
            "layoutType": "normal",
            "visible": true,
            "hover": false,
            "maxCol": 2,
            "title": {
                "textStyle": {
                    "fontSize": 12,
                    "fill": "#6F6F6F"
                }
            },
            "item": {
                "spaceRow": 0,
                "spaceCol": 0,
                "padding": {
                    "top": 4,
                    "bottom": 4,
                    "left": 4,
                    "right": 22
                },
                "background": {
                    "style": {
                        "fillOpacity": 0.001
                    }
                },
                "label": {
                    "style": {
                        "fontSize": 12,
                        "fill": "#6F6F6F"
                    }
                },
                "shape": {
                    "style": {
                        "symbolType": "square"
                    }
                }
            },
            "pager": {
                "textStyle": {},
                "handler": {
                    "style": {},
                    "state": {
                        "disable": {}
                    }
                }
            },
            "padding": {
                "top": 0,
                "bottom": 0,
                "left": 16,
                "right": 0
            }
        }
    ],
    "label": {
        "visible": true,
        "overlap": {
            "hideOnHit": true,
            "clampForce": true
        },
        "style": {
            "fontSize": 14,
            "fill": null,
            "strokeOpacity": 1
        },
        "smartInvert": true
    },
    "outerLabel": {
        "visible": true,
        "style": {
            "fontSize": 14,
            "fill": "#9ca0b1"
        },
        "line": {
            "style": {
                "stroke": "#9ca0b1"
            }
        }
    },
    "tooltip": {
        "handler": {}
    },
    "background": "rgba(255, 255, 255, 0)",
    "funnel": {
        "style": {
            "lineWidth": 1
        }
    },
    "animation": false,
    "hash": "711306cb9f3a08ef9c1ea96a0dd386e3"
}

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

<img width="736" alt="image" src="https://github.com/VisActor/VChart/assets/20367445/021b9269-b754-42de-ae6f-0d16624c7b1b">

### Expected Behavior

It should work just like what it is on bar chart:
<img width="686" alt="image" src="https://github.com/VisActor/VChart/assets/20367445/1fa99869-d47b-4c54-b865-bace944b58ee">

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
related case: 64fada2ee8a02e06c62a0792
