### ISSUE TITLE
[Feature] gauge chart indicator offsexY support Radius.

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#587]
### What problem does this feature solve?

The position of the indicator can't adapt to the height and width, because radius is radian, but the offsetY is pixel.

So we need a relative unit to define the offsetY rather than the pixel.

1. width: 1100, height:780.
<img width="1037" alt="image" src="https://github.com/VisActor/VChart/assets/49136199/98e05872-68a3-4965-82cc-dd3feefe97b8">

2. width: 550, height: 390
<img width="573" alt="image" src="https://github.com/VisActor/VChart/assets/49136199/f07b02e6-6517-4337-8ad2-78a84b6aa7ad">

```
const spec = {
  // width: 575,
  // height: 370,

  width: 550,
  height: 390,
  type: 'gauge',
  categoryField: 'name',
  valueField: 'progress',
  startAngle: -225,
  endAngle: 45,
  outerRadius: 0.8,
  innerRadius: 0.5,
  indicator: {
    visible: true,
    fixed: true,
    trigger: 'hover',
    offsetY: 150,
    title: {
      visible: true,
      field: 'name',
      style: {
        fontSize: 20,
        fill: 'red'
      }
    },
    content: {
      visible: true,
      field: 'current'
    }
  },
  color: {
    type: 'ordinal',
    range: ['#009db5'],
    specified: {}
  },
  min: 10000000,
  max: 20000000,
  roundCap: false,
  data: [
    {
      id: 'data',
      values: [
        {
          current: 16068954.132933617,
          name: '超级长的销售额超级长的销售额超级长的销售额超级长的销售额超级长的销售额超级长的销售额超级长的销售额超级长的销售额',
          emptyName: '',
          percent: '75.86%',
          progress: 0.6068954132933617
        }
      ]
    }
  ]
};

```

### What does the proposed API look like?

offsetY: 0.1

**Comment by pairone** [comment]
/**
   * 指标卡 y 方向偏移
   * 支持两种格式：像素值、百分比
   * @default 0
   */
  offsetY?: number | IPercent;
 
百分比的偏移量使用string类型，例如‘10%’
