### ISSUE TITLE
[Bug] interaction event bug collection

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#623]
### Version

1.3.0-beta.6

### Link to Minimal Reproduction

n/a

### Steps to Reproduce

1. how to query all type of chart mark (glyph)
2. EventParams type error：attribute does not exist on type 'INode'
![image](https://github.com/VisActor/VChart/assets/8744196/15f3ec6a-d3d1-41f6-a434-645b6df97197)
3. query: { type: 'markline' } not work, and no markline data export
4. pointerover event not work

### Current Behavior

contact me

### Expected Behavior

n/a

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
> 1. how to query all type of chart mark (glyph)

这个算是个 bug 吧，会在 1.3.0 里修复，修复之后直接配置 `level: mark` 就可以了，如果不配置 `type` 则默认监听所有 mark 的事件

```ts
  cs.on('pointerdown', { level: 'mark' }, e => {
    console.log('pointerdown', e.mark);
  });
```

> 2. EventParams type error：attribute does not exist on type 'INode'

1.3.0 里修复，但是因为无法确定拾取的的图形是哪一种类型，所以有可能 node.attribute.xx 还是会报错....，建议 any 下

```ts
 cs.on('pointerdown', { level: 'mark' }, e => {
    console.log('pointerdown', (e.node as IGraphic<any>)?.attribute.text);
  });
```

> 3. query: { type: 'markline' } not work, and no markline data export

这个是因为目前 markLine 默认是关闭交互的，所以如果想要监听，需要开启对应的 mark 组件的 `interactive` 属性（`interactive: true`），就可以监听了：

```ts
  cs.on('pointerdown', { level: 'model', type: 'markLine' }, e => {
    console.log('markLine pointerdown', (e.node as IGraphic<ITextGraphicAttribute>)?.attribute.text);
  });
```

> 4. pointerover event not work

可以生效

**Comment by kkxxkk2019** [comment]
> 1. how to query all type of chart mark (glyph)

这个算是个 bug 吧，会在 1.3.0 里修复，修复之后直接配置 `level: mark` 就可以了，如果不配置 `type` 则默认监听所有 mark 的事件

```ts
  cs.on('pointerdown', { level: 'mark' }, e => {
    console.log('pointerdown', e.mark);
  });
```

> 2. EventParams type error：attribute does not exist on type 'INode'

1.3.0 里修复，但是因为无法确定拾取的的图形是哪一种类型，所以有可能 node.attribute.xx 还是会报错....，建议 any 下

```ts
 cs.on('pointerdown', { level: 'mark' }, e => {
    console.log('pointerdown', (e.node as IGraphic<any>)?.attribute.text);
  });
```

> 3. query: { type: 'markline' } not work, and no markline data export

这个是因为目前 markLine 默认是关闭交互的，所以如果想要监听，需要开启对应的 mark 组件的 `interactive` 属性（`interactive: true`），就可以监听了：

```ts
  cs.on('pointerdown', { level: 'model', type: 'markLine' }, e => {
    console.log('markLine pointerdown', (e.node as IGraphic<ITextGraphicAttribute>)?.attribute.text);
  });
```

> 4. pointerover event not work

可以生效
