### ISSUE TITLE
[Bug] position of the label is not correct when set to 'inside'

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#626]
### Version

1.3.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

const spec = {
    "type": "bar",
    "xField": [
        "230822145933017",
        "10001"
    ],
    "yField": [
        "10002"
    ],
    "direction": "vertical",
    "seriesField": "20001",
    "data": [
        {
            "id": "data",
            "values": [
                {
                    "10001": "行 ID",
                    "10002": "13157091",
                    "10003": "230822145933086",
                    "20001": "行 ID",
                    "230822145933017": "中南",
                    "230822145933086": "13157091"
                },
                {
                    "10001": "利润",
                    "10002": "670885.3138181865",
                    "10003": "230822153117042",
                    "20001": "利润",
                    "230822145933017": "中南",
                    "230822153117042": "670885.3138181865"
                },
                {
                    "10001": "行 ID",
                    "10002": "8296805",
                    "10003": "230822145933086",
                    "20001": "行 ID",
                    "230822145933017": "东北1",
                    "230822145933086": "8296805"
                },
                {
                    "10001": "利润",
                    "10002": "242191.509221375",
                    "10003": "230822153117042",
                    "20001": "利润",
                    "230822145933017": "东北1",
                    "230822153117042": "242191.509221375"
                },
                {
                    "10001": "行 ID",
                    "10002": "14550225",
                    "10003": "230822145933086",
                    "20001": "行 ID",
                    "230822145933017": "华东",
                    "230822145933086": "14550225"
                },
                {
                    "10001": "利润",
                    "10002": "607218.6830426604",
                    "10003": "230822153117042",
                    "20001": "利润",
                    "230822145933017": "华东",
                    "230822153117042": "607218.6830426604"
                },
                {
                    "10001": "行 ID",
                    "10002": "6939587",
                    "10003": "230822145933086",
                    "20001": "行 ID",
                    "230822145933017": "华北",
                    "230822145933086": "6939587"
                },
                {
                    "10001": "利润",
                    "10002": "431053.2174924314",
                    "10003": "230822153117042",
                    "20001": "利润",
                    "230822145933017": "华北",
                    "230822153117042": "431053.2174924314"
                }
            ],
            "fields": {
                "10001": {
                    "alias": "指标名称 "
                },
                "10002": {
                    "alias": "指标值 "
                },
                "20001": {
                    "alias": "图例项 ",
                    "domain": [
                        "行 ID",
                        "利润"
                    ],
                    "lockStatisticsByDomain": true
                },
                "230822145933017": {
                    "alias": "地区",
                    "domain": [
                        "东北1",
                        "华北",
                        "华东",
                        "中南"
                    ],
                    "lockStatisticsByDomain": true,
                    "sortIndex": 0
                },
                "230822145933086": {
                    "alias": "行 ID"
                },
                "230822153117042": {
                    "alias": "利润"
                }
            }
        }
    ],
    "percent": true,
    "axes": [
        {
            "type": "band",
            "tick": {
                "visible": false
            },
            "grid": {
                "visible": true,
                "style": {
                    "stroke": "#fbb7bb",
                    "lineWidth": 5,
                    "lineDash": [
                        5,
                        5
                    ]
                }
            },
            "orient": "bottom",
            "visible": true,
            "domainLine": {
                "visible": true,
                "style": {
                    "lineWidth": 1,
                    "stroke": "#f5222d"
                }
            },
            "title": {
                "visible": true,
                "text": "嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷",
                "style": {
                    "fontSize": 16,
                    "fill": "#f7555d",
                    "fontWeight": "normal"
                }
            },
            "sampling": false,
            "label": {
                "visible": true,
                "style": {
                    "fontSize": 48,
                    "fill": "#6F6F6F",
                    "angle": 45,
                    "fontWeight": "normal"
                },
                "autoHide": true,
                "autoHideMethod": "greedy",
                "flush": false
            },
            "hover": true,
            "background": {
                "visible": false,
                "state": {
                    "hover": {
                        "fillOpacity": 0.08,
                        "fill": "#141414"
                    }
                }
            },
            "paddingInner": 0.15,
            "paddingOuter": 0.075
        },
        {
            "type": "linear",
            "tick": {
                "visible": false,
                "style": {
                    "stroke": "#81c87c"
                }
            },
            "niceType": "accurateFirst",
            "grid": {
                "visible": true,
                "style": {
                    "stroke": "#fbb7bb",
                    "lineWidth": 5,
                    "lineDash": [
                        5,
                        5
                    ]
                }
            },
            "orient": "left",
            "visible": true,
            "domainLine": {
                "visible": true,
                "style": {
                    "lineWidth": 1,
                    "stroke": "#81c87c"
                }
            },
            "title": {
                "visible": true,
                "text": "嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷",
                "style": {
                    "fontSize": 12,
                    "fill": "#363839",
                    "fontWeight": "normal"
                }
            },
            "sampling": false,
            "label": {
                "visible": true,
                "style": {
                    "fontSize": 12,
                    "fill": "#6F6F6F",
                    "angle": 0,
                    "fontWeight": "normal"
                },
                "autoHide": true,
                "autoHideMethod": "greedy"
            },
            "hover": true,
            "background": {
                "visible": true,
                "state": {
                    "hover": {
                        "fillOpacity": 0.08,
                        "fill": "#141414"
                    }
                }
            },
            "zero": true,
            "nice": true
        }
    ],
    "color": {
        "field": "20001",
        "type": "ordinal",
        "range": [
            "#207BFE",
            "#00CFFF"
        ],
        "specified": {},
        "domain": [
            "行 ID",
            "利润"
        ]
    },
    "legends": [
        {
            "type": "discrete",
            "id": "legend",
            "orient": "left",
            "position": "middle",
            "layoutType": "normal",
            "visible": true,
            "hover": false,
            "maxCol": 1,
            "title": {
                "textStyle": {
                    "fontSize": 12,
                    "fill": "#6F6F6F"
                }
            },
            "item": {
                "spaceRow": 0,
                "spaceCol": 0,
                "padding": {
                    "top": 4,
                    "bottom": 4,
                    "left": 4,
                    "right": 22
                },
                "background": {
                    "style": {
                        "fillOpacity": 0.001
                    }
                },
                "label": {
                    "style": {
                        "fontSize": 12,
                        "fill": "#6F6F6F"
                    }
                },
                "shape": {
                    "style": {
                        "symbolType": "square"
                    }
                }
            },
            "pager": {
                "textStyle": {},
                "handler": {
                    "style": {},
                    "state": {
                        "disable": {}
                    }
                }
            },
            "padding": {
                "top": 0,
                "bottom": 0,
                "left": 0,
                "right": 16
            }
        }
    ],
    "label": {
        "visible": true,
        "overlap": {
            "hideOnHit": true,
            "clampForce": true
        },
        "style": {
            "fontSize": 12,
            "fontWeight": "normal",
            "fill": null,
            "strokeOpacity": 1
        },
        
        "position": "inside",
        "smartInvert": {
            "brightColor": "#fff",
            "darkColor": "#363839",
            "brightStroke": null,
            "brightStrokeWidth": 2,
            "darkStroke": "rgba(255, 255, 255, 0.8)",
            "darkStrokeWidth": 2
        }
    },
    "tooltip": {
        "handler": {}
    },
    "hover": {
        "enable": true
    },
    "select": {
        "enable": true
    },
    "bar": {
        "state": {
            "hover": {
                "cursor": "pointer",
                "fillOpacity": 0.8,
                "stroke": "#58595B",
                "lineWidth": 1,
                "zIndex": 500
            },
            "selected": {
                "cursor": "pointer",
                "fillOpacity": 1,
                "stroke": "#58595B",
                "lineWidth": 1
            },
            "selected_reverse": {
                "fillOpacity": 0.3,
                "strokeWidth": 0.3
            }
        },
        "clipByLayout": true
    },
    "background": "rgba(255, 255, 255, 0)",
    "animation": false,
    "hash": "64b09fc8cfd8c8d57e607452cea64759"
}

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior
position of the label is set to inside, but some of the label appear in the wrong place:
![image](https://github.com/VisActor/VChart/assets/20367445/48a735fd-e3d9-417f-98d8-7676e5f7bac5)

### Expected Behavior

all the labels appear in the right place.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
@da730 应该是因为如果放到 inside 位置，会发生重叠。所以被放到了 inside-top 的位置

**Comment by da730** [comment]
> 

为什么不直接消失呢？已经开启了hideOnHit

**Comment by xiaoluoHe** [comment]
有默认的躲避策略，可以设置
```js
overlap:{
  strategy:[]
}
```

**Comment by da730** [comment]
> 有默认的躲避策略，可以设置
> 
> ```js
> overlap:{
>   strategy:[]
> }
> ```

It works!
