### ISSUE TITLE
[Feature] Tooltip of axis title should be along with the mouse position and can  be displayed in new lines.

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#627]
### What problem does this feature solve?

when the axis has a very long title, a tooltip will be shown when you hover on the text. However, if the text is too long, it still can not be fully displayed, and will appear in a fixed position: 
![image](https://github.com/VisActor/VChart/assets/20367445/191e9463-306e-4bff-a9b9-d8d5d9047189)
We hope the tooltip content can be displayed in new lines so the text can be fully displayed, and the position of the tooltip can follow the mouse:
![image](https://github.com/VisActor/VChart/assets/20367445/bbc8fced-d69d-4426-aec3-b2a8a54b1809)

### What does the proposed API look like?

Built-in support, no need to expose in spec

**Comment by neuqzxy** [comment]
supported in vrender v13.x and vchart 1.2.x

**Comment by kkxxkk2019** [comment]
Already supported in 1.3.0 version.
