### ISSUE TITLE
[Bug] tooltip在vue3 + TS使用中发生偏移

### ISSUE THREAD

**Issue by mwr0707** [VisActor/VChart#640]
### Version

1.2.2

### Link to Minimal Reproduction

无

### Steps to Reproduce

```
<template>
  <div id="container" style="height: 500px;width: 900px; border: 1px solid #bf1313"></div>
</template>

<script src="./vchart-test.ts"></script>
```

```
import {defineComponent, onMounted} from 'vue'
import VChart from '@visactor/vchart';

const spec = {
  type: 'bar',
  data: [
    {
      id: 'barData',
      values: [
        { month: 'Monday', sales: 22 },
        { month: 'Tuesday', sales: 13 },
        { month: 'Wednesday', sales: 25 },
        { month: 'Thursday', sales: 29 },
        { month: 'Friday', sales: 38 }
      ]
    }
  ],
  xField: 'month',
  yField: 'sales'
};
export default defineComponent({
    setup() {
        onMounted(() => {

          const vchart = new VChart(spec, { dom: document.getElementById("container")});
          vchart.renderAsync();
        })
    }
})
```

### Current Behavior

编写一个在vue3+ts的简单示例，实现一个简单的柱状图
tooltip位置并没有在图中央

### Expected Behavior

tooltip应该显示正常位置

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by zamhown** [comment]
Hello bro, I did not reproduce this error. I followed your reproduction steps to create a codesandbox demo, and the position of the tooltip follows the mouse normally. Can you take a screenshot of your environment or try to reproduce it in this demo?

https://codesandbox.io/s/vchart-vue-yqg37f

![image](https://github.com/VisActor/VChart/assets/15249097/4cf695c9-b0d0-4a4d-bf37-e5fa715a63c5)

---

你好，我没有复现这个错误，我按照复现步骤做了一个 codesandbox demo，tooltip 的位置是正常跟随鼠标的，可否在你的环境截屏一下，或者尝试在这个 demo 里复现？

**Comment by mwr0707** [comment]
https://codesandbox.io/p/sandbox/pedantic-rain-5qk9gw

**Comment by mwr0707** [comment]
这个demo可以复现问题

**Comment by mwr0707** [comment]
display: flex 属性会影响tooltip的显示位置
```
body {
  display: flex;
}
```

**Comment by zamhown** [comment]
If you cannot change the CSS on the body, you can try configuring `tooltip.parentElement` in the spec to change the tooltip mount container. I have updated the example in this demo: https://codesandbox.io/s/vchart-vue-yqg37f?file=/src/App.vue
---
如果不能更改 body 上的css，你可以尝试在 spec 中配置 tooltip.parentElement 来更改 tooltip 挂载容器。示例我更新在了这个demo：https://codesandbox.io/s/vchart-vue-yqg37f?file=/src/App.vue

**Comment by zamhown** [comment]
In the future, we will evaluate which is better as the default container for tooltip: the body or the chart container.
