### ISSUE TITLE
[Bug] line chart label position error in inside mode

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#645]
position inside mode
Current:
<img width="1423" alt="image" src="https://github.com/VisActor/VChart/assets/49136199/4053da7c-fe14-461c-9e87-7fa38e087612">
Expected:
<img width="657" alt="image" src="https://github.com/VisActor/VChart/assets/49136199/e1a31780-2e3b-40a3-87f0-d2492299c3b2">

**Comment by da730** [comment]
1.  label.position of symbol mask doesn't have 'inside' option
2. must set label.overlap. avoidBaseMark=false
