### ISSUE TITLE
[Feature] axes-linear.sync need to support domain sync of the two axes.

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#650]
### What problem does this feature solve?

axes-linear.sync目前仅支持两个轴0 值对齐和tick对齐，需要支持在两个轴都没有指定min max的情况下，最大最小值对齐：
![image](https://github.com/VisActor/VChart/assets/20367445/f955413c-8741-493f-8e52-496101f33d01)

### What does the proposed API look like?

axes-linear.sync:{
axisId:'xxx',
domainSync:true,
}

**Comment by xuefei1313** [comment]
could support by set axis.seriesId with same seriesList
