### ISSUE TITLE
[Feature] markline should support click event API

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#653]
### What problem does this feature solve?

markline should support click event API

### What does the proposed API look like?

vchart.on('pointerdown', { level: 'model', type: 'markline' }, () => {});
or vchart.on('marklineClick',{ }, () => {});

**Comment by kkxxkk2019** [comment]
标注组件默认关闭了交互，打开就可以了，另外 `type: 'markLine'` 不是 `type: 'markline'`
