### ISSUE TITLE
[Bug] LinearProgress  linear color render error

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#655]
The linearColor render error in progress chart
---
Current: 

![Image](https://user-images.githubusercontent.com/49136199/262898205-975f5ca6-8d1c-450c-881a-d0fad0181069.png)

Expected: 

![Image](https://user-images.githubusercontent.com/49136199/262898327-c1b29505-3096-4256-9edc-19fa7403fda5.png)

```ts
{
    "type": "linearProgress",
    "direction": "horizontal",
    "yField": "name",
    "xField": "progress",
    "cornerRadius": 15,
    "bandWidth": 15,
    "track": {
        "style": {
            "fill": "#ececec"
        }
    },
    "categoryField": "name",
    "roundCap": false,
    "data": [
        {
            "id": "data",
            "values": [
                {
                    "current": 2147538.9271282256,
                    "name": "利润",
                    "emptyName": "",
                    "percent": "14.32%",
                    "progress": 0.14316926180854836,
                    "detail": "",
                    "goalProgress": 1
                }
            ]
        }
    ],
    "axes": [
        {
            "orient": "right",
            "type": "band",
            "domainLine": {
                "visible": false
            },
            "tick": {
                "visible": false
            },
            "label": {
                "style": {
                    "visible": true,
                    "fontSize": 30,
                    "fill": "#161616",
                    "fontWeight": 400
                }
            },
            "maxWidth": "60%"
        }
    ],
    "progress": {
        "style": {
            "fill": {
                "gradient": "linear",
                "x0": 0,
                "y0": 0.5,
                "x1": 1,
                "y1": 0.5,
                "stops": [
                    {
                        "offset": 0,
                        "color": "#ebcb6c"
                    },
                    {
                        "offset": 1,
                        "color": "#cc3d41"
                    }
                ]
            }
        }
    },
    "extensionMark": [
        {
            "type": "text",
            "dataId": "data",
            "style": {
                "text": "利润",
                "textAlign": "start",
                "textBaseline": "bottom",
                "fontSize": 16,
                "fill": "#666666",
                "fontWeight": 500,
                "dy": 0
            }
        },
        {
            "type": "text",
            "dataId": "data",
            "visible": false,
            "style": {
                "text": "",
                "fontWeight": 500,
                "fontSize": 16,
                "fill": "#666666",
                "textAlign": "start",
                "textBaseline": "top",
                "dy": 0
            }
        },
        {
            "type": "rule",
            "dataId": "data",
            "visible": true,
            "style": {
                "stroke": "red",
                "lineWidth": 1
            }
        }
    ],
    "background": "rgba(255, 255, 255, 0)",
    "animation": false,
    "tooltip": {
        "handler": {}
    },
    "hash": "7564fe7acdba10e6d89dcb89273dae77"
}
```

**Comment by pairone** [comment]
The start and end points of the gradient need to be configured. 
For the progress bar in the horizontal direction, since the entire length is translated to the left, the starting point of the linear horizontal direction is 1-value, and the end point is 1
![image](https://github.com/VisActor/VChart/assets/40026218/446c8fc1-7d0d-44e2-81fd-fed8cad1a74b)

spec:
const spec = {
    "type": "linearProgress",
    "direction": "horizontal",
    "yField": "name",
    "xField": "progress",
    "cornerRadius": 15,
    "bandWidth": 15,
    "track": {
        "style": {
            "fill": "#ececec"
        }
    },
    "categoryField": "name",
    "roundCap": false,
    "data": [
        {
            "id": "data",
            "values": [
                {
                    "current": 2147538.9271282256,
                    "name": "利润",
                    "emptyName": "",
                    "percent": "14.32%",
                    "progress": 0.1432,
                    "detail": "",
                    "goalProgress": 1
                }
            ]
        }
    ],
    "axes": [
        {
            "orient": "right",
            "type": "band",
            "domainLine": {
                "visible": false
            },
            "tick": {
                "visible": false
            },
            "label": {
                "style": {
                    "visible": true,
                    "fontSize": 30,
                    "fill": "#161616",
                    "fontWeight": 400
                }
            },
            "maxWidth": "60%"
        }
    ],
    "progress": {
        "style": {
            "fill": {
                "gradient": "linear",
                "x0": 0.8568,
                "y0": 0.5,
                "x1": 1,
                "y1": 0.5,
                "stops": [
                    {
                        "offset": 0,
                        "color": "#ebcb6c"
                    },
                    {
                        "offset": 1,
                        "color": "#cc3d41"
                    }
                ]
            }
        }
    },
    "extensionMark": [
        {
            "type": "text",
            "dataId": "data",
            "style": {
                "text": "利润",
                "textAlign": "start",
                "textBaseline": "bottom",
                "fontSize": 16,
                "fill": "#666666",
                "fontWeight": 500,
                "dy": 0
            }
        },
        {
            "type": "text",
            "dataId": "data",
            "visible": false,
            "style": {
                "text": "",
                "fontWeight": 500,
                "fontSize": 16,
                "fill": "#666666",
                "textAlign": "start",
                "textBaseline": "top",
                "dy": 0
            }
        },
        {
            "type": "rule",
            "dataId": "data",
            "visible": true,
            "style": {
                "stroke": "red",
                "lineWidth": 1
            }
        }
    ],
    "background": "rgba(255, 255, 255, 0)",
    "animation": false,
    "tooltip": {
        "handler": {}
    },
    "hash": "7564fe7acdba10e6d89dcb89273dae77"
}
