### ISSUE TITLE
[Bug] "Label position config" cann't be found in the option docs

### ISSUE THREAD

**Issue by xuanhun** [VisActor/VChart#673]
### Version

1.2.0

### Link to Minimal Reproduction

https://www.visactor.io/vchart/option/roseChart#label.position

### Steps to Reproduce

open  https://www.visactor.io/vchart/option/roseChart#label.position

### Current Behavior

There's no detail config for label.position.

### Expected Behavior

Add detailed configuration for label.position.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pairone** [comment]
There is a new config will be added in version 1.3.0.

**Comment by pairone** [comment]
There is a new config will be added in version 1.3.0.
