### ISSUE TITLE
[Bug]label.positon configured as "outside" has no effect on Rose chart

### ISSUE THREAD

**Issue by xuanhun** [VisActor/VChart#674]
### Version

1.2.0

### Link to Minimal Reproduction

https://codesandbox.io/s/rose-chart-label-positon-gqq6xj?file=/package.json

### Steps to Reproduce

https://codesandbox.io/s/rose-chart-label-positon-gqq6xj?file=/package.json

### Current Behavior

![image](https://github.com/VisActor/VChart/assets/2384516/6b8ac828-d9db-4a0b-a761-65841ee2792a)

### Expected Behavior

labels should be placed on out side of the sectors

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by kkxxkk2019** [comment]
The latest version has already support.

![image](https://github.com/VisActor/VChart/assets/135952300/5a684af0-81bd-48b0-b576-3cdec2abea46)
