### ISSUE TITLE
[Bug] Event handler not work when react-vchart component is repeatedly rendered.

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#68]
### Version

@visactor/react-vchart@1.0.0-alpha.1

### Link to Minimal Reproduction

none

### Steps to Reproduce

if add a random key for the component, this problem can be avoided.

### Current Behavior

onPointerUp onClick not triggered

### Expected Behavior

event handler works if rerender. 

### Environment

```markdown
- OS: Mac
- Browser: Chrome
- Framework: React
```

**Comment by kkxxkk2019** [comment]
You can validate this issue in @visactor/vchart@1.1.0-beta.2

**Comment by xiaoluoHe** [comment]
> You can validate this issue in @visactor/vchart@1.1.0-beta.2

so this is an issue caused by vchart?

**Comment by kkxxkk2019** [comment]
> > You can validate this issue in @visactor/vchart@1.1.0-beta.2
> 
> so this is an issue caused by vchart?

already edited
