### ISSUE TITLE
[Feature] markline label auto layout nearby chart edge

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VChart#685]
### What problem does this feature solve?

![image](https://github.com/VisActor/VChart/assets/25134429/14215dc5-bddb-473f-9b84-3716caf0d64c)
markline label position is fixed, and long label will be clip when nearby chart edge.
Hope for auto layout such as:
![image](https://github.com/VisActor/VChart/assets/25134429/b0e6384c-978e-4f95-b12c-1d4d8b7cba24)

### What does the proposed API look like?

-

**Comment by kkxxkk2019** [comment]
In latest version, you can use `label.confine`
