### ISSUE TITLE
[Feature] In pie chart indicator title/content field, we want to enable ‘autoFit’ while setting a minimal text fontSize and a maximum text fontSize

### ISSUE THREAD

**Issue by Kate199824** [VisActor/VChart#691]
### What problem does this feature solve?

In pie chart indicator title/content field, we want to enable ‘autoFit’ while setting a minimal text fontSize（which means when the space is not enough even using the minimal fontSize, ‘autoLimit’ function is enabled）

### What does the proposed API look like?

null

**Comment by Kate199824** [comment]
and a maximum text fontSize

**Comment by purpose233** [comment]
Plan changes, no follow-up required.
