### ISSUE TITLE
[Feature] markLine label auto position

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#699]
### What problem does this feature solve?

when markline.autoRange=true, label of the markline will be clipped:
![image](https://github.com/VisActor/VChart/assets/20367445/d61be93b-c766-44bb-905d-3a57da4d8039)

the position of the label should be auto changed to avoid clip like this:
![image](https://github.com/VisActor/VChart/assets/20367445/b4385dc8-1af9-43c4-9338-74e31697ff3d)

It will first use the position in label.position if it can be fully displayed. 

### What does the proposed API look like?

markline:{
autoRange:true,
label:{
autoPosition:true
}

}

**Comment by kkxxkk2019** [comment]
label 上配置 confine: true 即可
