### ISSUE TITLE
[FAQ]How to customize Tooltip in dual axis chart?

### ISSUE THREAD

**Issue by liuyang661** [VisActor/VChart#708]
How to display some rich text content in the tooltip of the dual axis chart?
![image](https://github.com/VisActor/VChart/assets/143578595/f2b5502e-d4d7-4758-812c-411634f23e2d)

**Comment by xuanhun** [comment]
## 解决方案 Solution


这个问题的前提条件是双轴图，事实上对于大多数具有Tooltip自定义功能的图表组件来说，是不是双轴图对于自定义Tooltip没有影响。

接下来我以我最近在用的VisActor图表举例，逻辑是这样的：

-   确定你想要自定义的tooltip类型
-   注册对应的事件触发自定义tooltip的显示
-   自行设计tooltip的布局

在自定义事件中，你可以将tooltip渲染成任何你需要的样子。通过回调事件的参数，你可以获取到当前hover的元素具体的数据。

  
---

This question presupposes a dual-axis chart. In fact, for most chart components with tooltips customization, whether or not it's a dual-axis chart has no effect on customizing the tooltips. Next I'll use an example of a VisActor chart that I've been using recently, and the logic goes something like this:

-   Determine the type of tooltips you want to customize.
-   Register an event to trigger the display of custom tooltips.
-   Design your own layout for the tooltip

In custom events, you can render the tooltip any way you want. By callback event parameters, you can get the current hover element specific data.

## 代码示例 Code Example

```
const vchart = new VChart(spec, { dom: "container" });

vchart.setTooltipHandler({
  showTooltip: (activeType, tooltipData, params) => {
    // some code of custom tooltip
    const tooltip = document.getElementById("custom-tooltip");
    if (!tooltip) return;
    tooltip.style.visibility = "visible";
    tooltip.style.left = params.event.x + 20 + "px";
    tooltip.style.top = params.event.y + 20 + "px";
    tooltip.style.position = "absolute";
    tooltip.style.background = "white";
    tooltip.style.padding = "10px";
    tooltip.innerText = "This is Custom Tooltip";
  },
  hideTooltip: () => {
    // hide your custom tooltip
    const tooltip = document.getElementById("custom-tooltip");
    if (!tooltip) return;
    tooltip.style.visibility = "hidden";
  }
});
```

  


## 结果展示 Results

[https://codesandbox.io/s/custom-tooltip-dyvy3z](https://codesandbox.io/s/custom-tooltip-dyvy3z)

![](https://tech-proxy.bytedance.net/tos/images/1693367595028_b085a97d19b121af5bd813053907df74)

  


## 相关文档 Quote

[https://visactor.bytedance.net/vchart/guide/tutorial_docs/Chart_Concepts/Tooltip](https://visactor.bytedance.net/vchart/guide/tutorial_docs/Chart_Concepts/Tooltip)

[https://visactor.bytedance.net/vchart/demo/tooltip/custom-tooltip-handler?keyword=tooltip](https://visactor.bytedance.net/vchart/demo/tooltip/custom-tooltip-handler?keyword=tooltip)
