### ISSUE TITLE
[FAQ] How to truncate, wrap, or perform other formatting effects on axis labels in charts?  

### ISSUE THREAD

**Issue by TingLittleKang** [VisActor/VChart#710]
How to achieve line breaks or truncation effects for axis labels in bar charts similar to this example(https://www.visactor.io/vchart/demo/bar-chart/basic-bar) when the labels are very long?

**Comment by xuanhun** [comment]
## 解决方案 Solution

不同图表库的解决方案不一样，根据你给的demo，在VChart中只需要配置axes 中对应轴的`label`相关配置：

-   通过`formatMethod`返回数组，可以实现自定义换行
-   通过`style.maxLineWidth`可以实现自动截断
-   通过`style.ellipsis`可以设置省略符

the solutions vary among different chart libraries. Based on the demo you provided, in VChart, you only need to configure the label-related settings in the axes section: - By returning an array through the `formatMethod`, you can achieve custom line breaks. - By using `style.maxLineWidth`, you can achieve automatic truncation. - By setting `style.ellipsis`, you can set the ellipsis.

  
![image](https://github.com/VisActor/VChart/assets/2384516/06869af5-7b1d-4712-a17f-349b6f44fbd9)



  


## 代码示例 Code Example

代码参考 Code Example

```
const spec = {
  type: 'bar',
  data: [
    {
      id: 'barData',
      values: [
        {
          name: 'Apple https://www.apple.com/',
          value: 214480
        },
        {
          name: 'Google https://www.google.com.hk/',
          value: 155506
        },
        {
          name: 'Amazon https://www.amazon.com/',
          value: 100764
        },
        {
          name: 'Microsoft https://www.microsoft.com/',
          value: 92715
        }
      ]
    }
  ],
  direction: 'horizontal',
  xField: 'value',
  yField: 'name',
  axes: [
    {
      orient: 'bottom',
      visible: false
    },
    {
      orient: 'left',
      label: {
        formatMethod: (text, datum) => {
          return text.split(' ');
        },
        style: {
          maxLineWidth: 100,
          ellipsis: '~'
        }
      }
    }
  ],
  label: {
    visible: true
  }
};
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/axis-label-auto-limit-pnsvzl

Online demo：https://codesandbox.io/s/axis-label-auto-limit-pnsvzl

![](https://tech-proxy.bytedance.net/tos/images/1693380147169_3b93ed7b440a8bb4d367704646e7984e)
  
![image](https://github.com/VisActor/VChart/assets/2384516/5f323b97-294a-4ffa-8f65-7d7d9eb44fd4)



## 相关文档 Related Documentation

坐标轴demo：https://www.visactor.io/vchart/demo/axis/animation

坐标轴教程：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Axes

相关配置：https://www.visactor.io/vchart/option/barChart#axes-band.label.style.ellipsis

github：https://github.com/VisActor/VChart

  


Axis Demo：https://www.visactor.io/vchart/demo/axis/animation

Axis Tutorial：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Axes

Related option：https://www.visactor.io/vchart/option/barChart#axes-band.label.style.ellipsis

github：https://github.com/VisActor/VChart
