### ISSUE TITLE
[Feature] cartesian chart with zero line

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#713]
### What problem does this feature solve?

zero line can distinguish between positive and negative areas more obvious.
just like this screenshot:
![image](https://github.com/VisActor/VChart/assets/8744196/df8204c9-0f64-4607-99ec-c94159f96181)

### What does the proposed API look like?

n/a

**Comment by kkxxkk2019** [comment]
https://www.visactor.io/vchart/demo/axis/on-zero

Is this the one you need?

**Comment by ssfxz** [comment]
yap! thx
