### ISSUE TITLE
[FAQ] How to add a title and subtitle to a chart?

### ISSUE THREAD

**Issue by FlyingAndFly** [VisActor/VChart#714]
Seemly to https://visactor.io/vchart/demo/line-chart/basic-line, I want to add a title description to the chart. How can I configure it?

**Comment by xuanhun** [comment]
## 解决方案 Solution

不同图表库的解决方案不一样。根据你给的 demo，在 VChart 中，只需要配置 `title.text`（标题文本）和 `title.subtext`（副标题文本）即可。

另外，你可以通过 `title.textStyle` 和`title.subtextStyle` 配置来分别调整标题的样式。

The solutions for different chart libraries are different. According to the demo you provided, in VChart, you only need to configure title.text and title.subtext.

In addition, you can configure the style of the title and subtitle separately by using `title.textStyle` and `title.subtextStyle`.

```
title: {
    text: 'Line chart',
    subtext:
      'The line chart is a simple, two-dimensional chart with an X and Y axis, each point representing a single value.',
    textStyle: {
      fontSize: 20
    },
    subtextStyle: {
      fontStyle: 'italic'
    }
}
```

## 代码示例 Code Example

代码参考 Code Example

```
const spec = {
  type: 'line',
  data: {
    values: [
      {
        time: '2:00',
        value: 8
      },
      {
        time: '4:00',
        value: 9
      },
      {
        time: '6:00',
        value: 11
      },
      {
        time: '8:00',
        value: 14
      },
      {
        time: '10:00',
        value: 17
      },
      {
        time: '12:00',
        value: 19
      },
      {
        time: '14:00',
        value: 19
      },
      {
        time: '16:00',
        value: 17
      },
      {
        time: '18:00',
        value: 15
      }
    ]
  },
  xField: 'time',
  yField: 'value',
  title: {
    text: 'Line chart',
    subtext:
      'The line chart is a simple, two-dimensional chart with an X and Y axis, each point representing a single value.',
    textStyle: {
      fontSize: 20
    },
    subtextStyle: {
      fontStyle: 'italic'
    }
  }
};
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/title-in-line-chart-rkzvns

Online demo：https://codesandbox.io/s/title-in-line-chart-rkzvns

  
![image](https://github.com/VisActor/VChart/assets/2384516/19abc453-b3f6-48a0-9580-9261bacd4f3e)



## 相关文档 Related Documentation

更多标题 demo：https://visactor.io/vchart/demo/title/richText-title

标题教程：https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Title

相关api：https://visactor.io/vchart/option/lineChart#title.text

github：https://github.com/VisActor/VChart

  


More title demos：https://visactor.io/vchart/demo/title/richText-title

Title tutorial：https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Title

Related api：https://visactor.io/vchart/option/lineChart#title.text

github：https://github.com/VisActor/VChart
