### ISSUE TITLE
[FAQ]How to customize the position and offset of the tooltip in the chart?

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#745]
When I use VChart charts, I encounter the problem that the chart tip box is very close to the mouse pointer, so that the mouse pointer may obscure the tips on a large screen with high resolution. Is there any way to solve this problem?
![image](https://github.com/VisActor/VChart/assets/8744196/b8faaa9b-8f34-4fd0-835f-15e6fb9465dc)

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart图表已经提供了对应的功能，你只需要在图表的spec里设置tooltip.offset即可。官网上有对应的配置文档。

https://visactor.io/vchart/option/barChart#tooltip.offset

  


VChart already provides the corresponding function, you just need to set tooltip.offset in the spec of the chart. The corresponding configuration documents are available on the official website.

  


## 代码示例 Code Example

```
spec.tooltip.offset = {
    x: 40,
    y: 40,
}
```

  


## 结果展示 Results

![image](https://github.com/VisActor/VChart/assets/2384516/e507f7ed-fc0f-4989-804e-d57ae18eafe2)


  


## 相关文档 Quote

tooltip option：https://visactor.io/vchart/option/barChart#tooltip.offset

github：https://github.com/VisActor/VChart

Tooltip tutorials: https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Tooltip

Tooltip demos:https://www.visactor.io/vchart/demo/tooltip/custom-mark-tooltip
