### ISSUE TITLE
[FAQ] Can we add a horizontal line for the average value to the data?

### ISSUE THREAD

**Issue by skie1997** [VisActor/VChart#760]
When using the [VChart](https://www.visactor.io/vchart) chart library, can you achieve an effect similar to the figure below, adding a label line to the chart to represent the average value of the data?
![image](https://github.com/VisActor/VChart/assets/40675330/ef63ef15-0c2e-4e90-b2a4-a82fac88801f)

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart有着丰富的数据标注能力，对于您描绘的场景，只需要在markLine中配置`x: 'average'`即可。

VChart has rich data annotation capabilities. For the scenario you described, you only need to configure x: 'average' in markLine.

## 代码示例 Code Example

代码参考 Code Example

```
const spec = {
  type: "bar",
  data: [
    {
      id: "barData",
      values: [
        { type: "Autocracies", year: "1930", value: 129 },
        { type: "Autocracies", year: "1940", value: 133 },
        { type: "Autocracies", year: "1950", value: 130 },
        { type: "Autocracies", year: "1960", value: 126 },
        { type: "Autocracies", year: "1970", value: 117 },
        { type: "Autocracies", year: "1980", value: 114 },
        { type: "Autocracies", year: "1990", value: 111 },
        { type: "Autocracies", year: "2000", value: 89 },
        { type: "Autocracies", year: "2010", value: 80 },
        { type: "Autocracies", year: "2018", value: 80 },
        { type: "Democracies", year: "1930", value: 22 },
        { type: "Democracies", year: "1940", value: 13 },
        { type: "Democracies", year: "1950", value: 25 },
        { type: "Democracies", year: "1960", value: 29 },
        { type: "Democracies", year: "1970", value: 38 },
        { type: "Democracies", year: "1980", value: 41 },
        { type: "Democracies", year: "1990", value: 57 },
        { type: "Democracies", year: "2000", value: 87 },
        { type: "Democracies", year: "2010", value: 98 },
        { type: "Democracies", year: "2018", value: 99 }
      ]
    }
  ],
  xField: ["year", "type"],
  yField: "value",
  seriesField: "type",
  legends: {
    visible: true,
    orient: "top",
    position: "start"
  },
  markLine: [
    {
      y: "average",
      label: {
        visible: true,
        position: "insideEndTop",
        text: "Average Country",
        style: {
          fill: "#000"
        },
        labelBackground: {
          visible: false
        }
      }
    }
  ]
};
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/average-markline-wgfdkg

Online demo：https://codesandbox.io/s/average-markline-wgfdkg

  
![image](https://github.com/VisActor/VChart/assets/2384516/f241fbde-eb20-46e9-bd57-4ffcd07b0775)



## 相关文档 Related Documentation

图表标注线demo：<https://visactor.io/vchart/demo/marker/mark-line-axis>

图表标注教程：<https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/marker>

相关api：<https://visactor.io/vchart/option/barChart#markLine.y>

github：https://github.com/VisActor/VChart

  


Chart Annotation Demo：<https://visactor.io/vchart/demo/marker/mark-line-axis>

Chart Annotation Tutorials：<https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/marker>

Related api：<https://visactor.io/vchart/option/barChart#markLine.y>

github：<https://github.com/VisActor/VChart>
