### ISSUE TITLE
[FAQ] How to configure the range of the axis?

### ISSUE THREAD

**Issue by FlyingAndFly** [VisActor/VChart#772]
In my dual-axis chart, the right axis represents the percentage.  
Can this percentage range be manually configured? 
I am using vchart and have configured min and max, but it has not taken effect.   

![image](https://github.com/VisActor/VChart/assets/143593654/bb25c188-3a00-4bfe-9003-d5ec7b08bde9)

my configuration:
```ts
{
  type: 'common',
  seriesField: 'color',
  data: [
    {
      id: 'id0',
      values: [
        { x: '2021-10-22', type: 'A', y: 10 },
        { x: '2021-10-23', type: 'B', y: 22 },
      ]
    },
    {
      id: 'id1',
      values: [
        { x: '2021-10-22', type: 'TA', y: 0.5 },
        { x: '2021-10-22', type: 'TB', y: 1.1 },
        { x: '2021-10-23', type: 'TA', y: 1 },
        { x: '2021-10-23', type: 'TB', y: 1.5 },

      ]
    }
  ],
  series: [
    {
      type: 'bar',
      id: 'bar',
      dataIndex: 0,
      label: { visible: true ,position:'inside'},
      seriesField: 'type',
      xField: 'x',
      yField: 'y',
      max: 100 
    },
    {
      type: 'line',
      id: 'line',
      dataIndex: 1,
      label: { visible: true },
      seriesField: 'type',
      xField: 'x',
      yField: 'y',
      min: 0, 
      max: 2,
      stack: false
    }
  ],
  axes: [
    { orient: 'left', seriesIndex: [0] },
    { orient: 'right', seriesId: ['line'], gird: { visible: false }},
    { orient: 'bottom', label: { visible: true }, type: 'band' }
  ],
}
```

**Comment by xuanhun** [comment]
## 解决方案 Solution

轴范围的配置在 `axes` 配置项里，并不是在 `series` 上。你可以根据需要配置最小值（`min`）和最大值（`max`）, 例如：

The configuration of the axis range is in the `axes` configuration item, not in the `series`. You can configure the minimum value (min) and maximum value (max) as your need, for example:

```
  axes: [
    { orient: 'left', max: 100 },
    { orient: 'right', min:0, max:2 },
  ],
```

  


## 代码示例 Code Example

代码参考 Code Example

```
const spec = {
  type: 'common',
  seriesField: 'color',
  data: [
    {
      id: 'id0',
      values: [
        { x: '2021-10-22', type: 'A', y: 10 },
        { x: '2021-10-23', type: 'B', y: 22 },
      ]
    },
    {
      id: 'id1',
      values: [
        { x: '2021-10-22', type: 'TA', y: 0.5 },
        { x: '2021-10-22', type: 'TB', y: 1.1 },
        { x: '2021-10-23', type: 'TA', y: 1 },
        { x: '2021-10-23', type: 'TB', y: 1.6 },

      ]
    }
  ],
  series: [
    {
      type: 'bar',
      id: 'bar',
      dataIndex: 0,
      label: { visible: true ,position:'inside'},
      seriesField: 'type',
      xField: 'x',
      yField: 'y'
    },
    {
      type: 'line',
      id: 'line',
      dataIndex: 1,
      label: { visible: true },
      seriesField: 'type',
      xField: 'x',
      yField: 'y',
      stack: false
    }
  ],
  axes: [
    { orient: 'left', seriesIndex: [0], max: 100 },
    { orient: 'right', seriesId: ['line'], gird: { visible: false }, min:0, max:2 },
    { orient: 'bottom', label: { visible: true }, type: 'band' }
  ],
};
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/dual-axis-custom-range-9r93h9

Online demo：https://codesandbox.io/s/dual-axis-custom-range-9r93h9

![image](https://github.com/VisActor/VChart/assets/2384516/ccf4900d-ab1a-458b-baa2-5bcbb4617656)


  


## 相关文档 Related Documentation

更多 demo：https://visactor.io/vchart/demo/combination/dual-axis

轴教程：https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Axes

相关api：https://visactor.io/vchart/option/lineChart#axes-linear.min

github：https://github.com/VisActor/VChart

  


More demos：https://visactor.io/vchart/demo/combination/dual-axis

Axes tutorial：https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Axes

Related api：https://visactor.io/vchart/option/lineChart#axes-linear.min

github：https://github.com/VisActor/VChart
