### ISSUE TITLE
[Bug] chart label effected by updateDataSync

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VChart#773]
### Version

1.3.1

### Link to Minimal Reproduction

none 

### Steps to Reproduce

use api to updateData

```
vchart.updateDataSync('data',record1)

vchart.updateDataSync('data',record2)

```

this effect is not same with

```
vchart.updateDataSync('data',record2)

```

### Current Behavior

label show  error

### Expected Behavior

label show effect normally

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
will be fixed in vchart 1.4.0
