### ISSUE TITLE
[Feature] Datazoom handler support custom svg image

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VChart#785]
希望datazoom手柄支持 svg 图片。
（UI不能接受中间白色的三条是挖空的效果）

![Image](https://github.com/VisActor/VChart/assets/11360419/e272afd1-04ab-4e40-b05d-c3b7ccaafc7b)

**Comment by xile611** [comment]
duplicated with https://github.com/VisActor/VChart/issues/177
