### ISSUE TITLE
[FAQ] How to configure a DataZoom component in a chart that can be used on a mobile device?  

### ISSUE THREAD

**Issue by TingLittleKang** [VisActor/VChart#787]
类似 （[https://www.visactor.io/vchart/demo/line-chart/basic-line](https://www.visactor.io/vchart/demo/line-chart/basic-line)）这样的简单线图，
![image](https://github.com/VisActor/VChart/assets/143469603/90a7a02c-b056-4d10-a7d7-bc2ddd09433b)

怎么配置DataZoom组件？DataZoom组件可以在移动端设备进行交互吗？

For a simple line chart like this one (https://www.visactor.io/vchart/demo/line-chart/basic-line), how do I configure the DataZoom component? Can the DataZoom component be used for interaction on mobile devices?

**Comment by xuanhun** [comment]
## 解决方案 Solution

不同图表库的解决方案不一样，根据你给的demo，在VChart中只需要配置 **dataZoom** ，就会展示组件；为了移动端的交互更加友好，可以开启`roam: true`的配置。

![image](https://github.com/VisActor/VChart/assets/2384516/baab07d1-e1cc-4519-a60c-db5e2859d59f)


The solutions of different chart libraries vary. Based on the demo you provided, in VChart, you only need to configure **dataZoom** to display the component. To make the interaction more user-friendly for mobile devices, you can enable the configuration of **roam: true**.

## 代码示例 Code Example

代码参考 Code Example

```
const spec = {
  type: "line",
  data: {
    values: [
      {
        time: "2:00",
        value: 8
      },
      {
        time: "4:00",
        value: 9
      },
      {
        time: "6:00",
        value: 11
      },
      {
        time: "8:00",
        value: 14
      },
      {
        time: "10:00",
        value: 16
      },
      {
        time: "12:00",
        value: 17
      },
      {
        time: "14:00",
        value: 17
      },
      {
        time: "16:00",
        value: 16
      },
      {
        time: "18:00",
        value: 15
      }
    ]
  },
  xField: "time",
  yField: "value",
  dataZoom: [
    {
      orient: "bottom",
      filterMode: "filter",
      roam: true
    }
  ]
};
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/line-chart-datazoom-wzk8n7

Online demo：https://codesandbox.io/s/line-chart-datazoom-wzk8n7

![Sep-12-2023 14-17-56](https://github.com/VisActor/VChart/assets/2384516/162b72f6-cb77-4798-a254-dcca712b27b8)



  


## 相关文档 Related Documentation

DataZoom demo：https://www.visactor.io/vchart/demo/data-zoom/preview-data?keyword=dataZoom

DataZoom教程：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/DataZoom

相关配置：https://www.visactor.io/vchart/option/lineChart#dataZoom.valueField

github：https://github.com/VisActor/VChart

  


DataZoom demo：https://www.visactor.io/vchart/demo/data-zoom/preview-data?keyword=dataZoom

DataZoom Tutorial：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/DataZoom

Related option：https://www.visactor.io/vchart/option/lineChart#dataZoom.valueField

github：https://github.com/VisActor/VChart
