### ISSUE TITLE
[FAQ] How do I customize the position of the tooltip to avoid occlusion?

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#789]
### What problem does this feature solve?

When I use VChart charts, the tooltip of the chart gets truncated by the edge of the dom. I would like to know how to customize the position of the tooltip in VChart to avoid this？

### What does the proposed API look like?

n/a

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart中控制tooltip的位置有很多方式，例如实现自定义tooltip，或者指定tooltip的offset参数。

但你遇到的情况其实有简单的办法实现，通过指定Tooltip挂载的dom节点来实现。

默认情况下，tooltip会挂载在页面的body上，因此是不应该出现截断的。你的情况可能是修改了`spec.tooltip.parentElement`的配置。删除或修改该配置应该就可以了。

  


There are many ways to control the position of tooltip in VChart, such as implementing a custom tooltip, or specifying the offset parameter of tooltip. But there is actually a simple way to realize the situation you encountered, by specifying the dom node where the tooltip is mounted. By default, the tooltip is mounted on the body of the page, so it is not supposed to be truncated. In your case you may have modified the `spec.tooltip.parentElement` configuration. Removing or modifying that configuration should solve your problem.

  


## 代码示例 Code Example

```
spec.tooltip.parentElement = document.body
```

  


## 结果展示 Results



Demo: https://visactor.io/vchart/demo/line-chart/null-value-line
![image](https://github.com/VisActor/VChart/assets/2384516/4d5b457b-6cc5-4429-a4ba-da1b828e213a)

  


## 相关文档 Quote

tooltip：https://visactor.io/vchart/option/barChart#tooltip.parentElement

github：https://github.com/VisActor/VChart

Tooltip tutorials: https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Tooltip
