### ISSUE TITLE
[FAQ] 在Chart 层面监听事件，是否可以通过event 参数获取具体点击的元素类型，类似于dom 的 target 参数？

### ISSUE THREAD

**Issue by skie1997** [VisActor/VChart#810]

**Comment by xuanhun** [comment]
## 解决方案 Solution

可以实现的，VChart实例上提供了事件的注册和卸载，您可以通过

`chart.on(event: string, callback: (params: EventParams)=> void): void`

监听不同的事件类型，并通过回调函数拿到上下文信息。如果要区分您是在axis/legend/item上触发的不同事件，可以事件过滤来实现，并传入

`{ level: 'model' | 'mark', type: 'axis' }`，

其中`'model'`表示图表组成元素模型类型，`'mark'`表示图表item元素。

比如：

`vchart.on('pointerdown', { level: 'model', type: 'axis' }, (params) => {})`。

当我点击了坐标轴，便可以拿到具体的参数。

更多的事件类型及参数可以参考：<https://www.visactor.io/vchart/api/event>。
![image](https://github.com/VisActor/VChart/assets/2384516/2c366146-32ac-4dbc-96c4-76fc88c3a583)


This can be done. The VChart instance provides event registration and unregistration, you can listen to different event types via 

`chart.on(event: string, callback: (params: EventParams)=> void): void` 

and get the context information via the callback function. If you want to distinguish the different events you are triggering on axis/legend/item, you can do so by event filtering and passing 

`{ level: 'model' | 'mark', type: 'axis' }`,

where `'model'` denotes the model type of the chart's constituent elements and ` 'mark'  `denotes the chart's item elements.

For example:

`vchart.on('pointerdown', { level: 'model', type: 'axis' }, (params) => {})`. 

When I click on the axis, I can get the specific parameters.

More event types and parameters can be found at: <https://www.visactor.io/vchart/api/event>.

## 代码示例 Code Example

代码参考 Code Example

```
const spec = {
  type: 'bar',
  data: [
    {
      id: 'barData',
      values: [
        {
          State: 'WY',
          Age: 'Under 5 Years',
          Population: 25635
        },
        {
          State: 'WY',
          Age: '5 to 13 Years',
          Population: 1890
        },
        {
          State: 'WY',
          Age: '14 to 17 Years',
          Population: 9314
        },
        {
          State: 'DC',
          Age: 'Under 5 Years',
          Population: 30352
        },
        {
          State: 'DC',
          Age: '5 to 13 Years',
          Population: 20439
        },
        {
          State: 'DC',
          Age: '14 to 17 Years',
          Population: 10225
        },
        {
          State: 'VT',
          Age: 'Under 5 Years',
          Population: 38253
        },
        {
          State: 'VT',
          Age: '5 to 13 Years',
          Population: 42538
        },
        {
          State: 'VT',
          Age: '14 to 17 Years',
          Population: 15757
        },
        {
          State: 'ND',
          Age: 'Under 5 Years',
          Population: 51896
        },
        {
          State: 'ND',
          Age: '5 to 13 Years',
          Population: 67358
        },
        {
          State: 'ND',
          Age: '14 to 17 Years',
          Population: 18794
        },
        {
          State: 'AK',
          Age: 'Under 5 Years',
          Population: 72083
        },
        {
          State: 'AK',
          Age: '5 to 13 Years',
          Population: 85640
        },
        {
          State: 'AK',
          Age: '14 to 17 Years',
          Population: 22153
        }
      ]
    }
  ],
  xField: 'State',
  yField: 'Population',
  seriesField: 'Age',
  stack: true,
  legends: {
    visible: true
  },
  bar: {
    // The state style of bar
    state: {
      hover: {
        stroke: '#000',
        lineWidth: 1
      }
    }
  }
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

vchart.on('pointerdown', { level: 'model', type: 'axis' }, (params) => {
  console.log('params', params)
});

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/event-register-97tjkg

Online demo：https://codesandbox.io/s/event-register-97tjkg

  
![Sep-07-2023 13-08-32](https://github.com/VisActor/VChart/assets/2384516/a0b70881-27b7-414a-a993-bab4304f9e5b)



## 相关文档 Related Documentation

事件教程：https://www.visactor.io/vchart/guide/event

相关api：https://www.visactor.io/vchart/api/event

github：https://github.com/VisActor/VChart

  


  


Event Tutorial：https://www.visactor.io/vchart/guide/event

Related api：https://www.visactor.io/vchart/api/event

github：https://github.com/VisActor/VChart
