### ISSUE TITLE
[FAQ] How to customize the font size of words in Word Cloud Chart?

### ISSUE THREAD

**Issue by skie1997** [VisActor/VChart#811]
How to customize the text size in the word cloud, I want the text with more weight to be displayed larger. For example, in the example below, I want the largest text size to be 40px. How do I do that?

![image](https://github.com/VisActor/VChart/assets/40675330/882dae59-7737-4fe0-9163-6168fcff9fc3)

**Comment by xuanhun** [comment]
## 解决方案 Solution

你可以设置`wordCloudChart.fontSizeRange`来配置字体大小范围，它表示数据最小值和最大值分别对应的文字大小，在你给出的例子中，可以配置`wordCloudChart.fontSizeRange: [5, 40]`来达到预期效果。

You can set `wordCloudChart.fontSizeRange` to configure the font size range, which indicates the text size corresponding to the minimum and maximum values of the data respectively, in the example you gave, you can configure `wordCloudChart.fontSizeRange: [5, 40]` to achieve the desired effect.

  


## 代码示例 Code Example

代码参考 Code Example

```
const response = await fetch('https://lf9-dp-fe-cms-tos.byteorg.com/obj/bit-cloud/data-wordcloud.json');
const dataWordCloud = await response.json();
const spec = {
  type: 'wordCloud',
  nameField: 'challenge_name',
  valueField: 'sum_count',
  seriesField: 'challenge_name',
  data: {
    name: 'baseData',
    values: dataWordCloud
  },
  fontSizeRange: [5, 40],
};
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/wordcloud-chart-fontsizerange-znkv37

Online demo：https://codesandbox.io/s/wordcloud-chart-fontsizerange-znkv37

  
![image](https://github.com/VisActor/VChart/assets/2384516/7d3dba29-1892-4518-a69c-9f7396fb9d1b)



## 相关文档 Related Documentation

词云demo：https://www.visactor.io/vchart/demo/word-cloud-chart/word-cloud-basic

词云教程：https://www.visactor.io/vchart/guide/chart/word-cloud

相关api：https://www.visactor.io/vchart/option/wordCloudChart#fontSizeRange

github：https://github.com/VisActor/VChart

  


WordCloud Chart Demo：https://www.visactor.io/vchart/demo/bar-chart/stack-column

WordCloud Chart Tutorial：https://www.visactor.io/vchart/guide/chart/word-cloud

Related api：https://www.visactor.io/vchart/option/wordCloudChart#fontSizeRange

github：https://github.com/VisActor/VChart
