### ISSUE TITLE
[FAQ] The time interval of the coordinate axis scale is given (one quarter), how can I set it to display only three coordinate axis scales? Or make it adaptively uniform?

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#812]
For a line chart similar to https://www.visactor.io/vchart/demo/line-chart/multi-line,
![image](https://github.com/VisActor/VChart/assets/20367445/4bd14f07-8f5d-4950-aa67-8d422ccbae97)

if the length of the time interval for the coordinate axis is given, how should the display quantity of the coordinate axis scale be set? For example, if you want to display only three coordinate axis scales or adaptively adjust the scale quantity.

I tried to look up for the documents of some chart library, but didn't find the solution.

**Comment by xuanhun** [comment]
## 解决方案 Solution

在VChart中，共有linear、band、time、log4种坐标轴类型。对于每种坐标轴，只需要设置tick.tickCount=3，或者tick.forceTickCount=3 即可指定坐标轴刻度的数量。

In VChart, there are four types of coordinate axes: linear, band, time, and log. For each type of coordinate axis, you only need to set tick.tickCount=3 or tick.forceTickCount=3 to specify the number of axis ticks.In VChart, there are four types of coordinate axes: linear, band, time, and log. For each type of coordinate axis, you only need to set tick.tickCount=3 or tick.forceTickCount=3 to specify the number of axis ticks.

![image](https://github.com/VisActor/VChart/assets/2384516/dc9b3a64-5682-4053-bdba-2f9a3e4c24fe)

当未指定tickCount时，会采用自适应tick数量，自动寻找能够使所有轴标签都不重叠的最大tick数量

When tickCount is not specified, adaptive tick count will be used to automatically find the maximum tick count that can prevent overlapping of all axis labels.

![image](https://github.com/VisActor/VChart/assets/2384516/c33abbbd-3700-4805-8335-ac20570fae50)

## 代码示例 Code Example

代码参考 Code Example

```
const spec = {
  type: 'line',
  data: {
    values: latestData,
  },
  xField: 'country',
  yField: 'value',
  seriesField: 'name',
  axes: [
    {
      orient: 'left',
      domainLine: { visible: false },
      tick: { visible: false },
      label: {
        style: {
          fill: 'rgb(162, 162, 162)'
        }
      },
      grid: {
        style: {
          lineDash: [0],
          stroke: 'rgb(231, 231, 231)'
        }
      }
    },
    {
      orient: 'bottom',
      domainLine: { visible: true, style: { stroke: '#000' } },
      tick: {
        style: { stroke: '#000' }
        tickCount: 3,
      }
    }
  ],


};
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/line-chart-tick-count-fxh599?file=/src/index.ts

Online demo：https://codesandbox.io/s/line-chart-tick-count-fxh599?file=/src/index.ts

![image](https://github.com/VisActor/VChart/assets/2384516/7a3bd5d9-2b5d-49bc-a117-0542c879f6c7)

 

## 相关文档 Related Documentation

折线图教程：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Types/Line

相关api：https://www.visactor.io/vchart/option/lineChart#axes-linear.tick.tickCount

github：https://github.com/VisActor/VChart

  


LineChart Tutorial：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Types/Line

Related api：https://www.visactor.io/vchart/option/lineChart#axes-linear.tick.tickCount

github：https://github.com/VisActor/VChart
