### ISSUE TITLE
[FAQ] How to add tooltips to the legend of a chart?

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#815]
As shown in the following figure, the text of the legend is omitted. I want to add prompt information to them to display the complete text. How should I operate?

![image](https://github.com/VisActor/VChart/assets/135952300/2ae1a9c8-a6ad-4823-9830-00a292304ae1)

**Comment by xuanhun** [comment]
https://visactor.com/vchart/faq/92-How%20to%20add%20prompt%20information%20to%20the%20legend
