### ISSUE TITLE
[FAQ] How to customize the label text content, color, and layout of a pie chart?

### ISSUE THREAD

**Issue by TingLittleKang** [VisActor/VChart#816]
类似 （https://www.visactor.io/vchart/demo/pie-chart/basic-pie）这样的饼图，label的文字内容、颜色、布局可以按照自定义的需求调整吗？能够支持到什么粒度？应该怎么配置调整？

![image](https://github.com/VisActor/VChart/assets/143469603/abdfcc84-338c-4db8-b421-a800026231df)

Can I customize the label text, color, and layout of a pie chart similar to the one at https://www.visactor.io/vchart/demo/pie-chart/basic-pie? What level of customization is supported and how can I configure it?

**Comment by xuanhun** [comment]
## 解决方案 Solution

不同图表库对饼图的支持力度不同，对饼图label标签支持力度也不同，在VChart中：

-   label的文字内容：可以通过`label.``formatMethod`回调函数设置自定义的标签内容，[参考配置文档](https://www.visactor.io/vchart/option/pieChart#label.formatMethod)
-   label的文字颜色：可以通过`label.style`设置文字的样式，包括颜色、字体、大小等等，只要是VChart文字图形支持的属性都可以配置，[参考配置文档](https://www.visactor.io/vchart/option/pieChart#label.style.text)
-   label的布局：如果是想简单的调整标签的位置，可以通过`label.position`设置标签的位置是在内部还是外部；如果想调整布局策略，可以通过`label.layout`进行详细的调整，具体可以[参考配置文档](https://www.visactor.io/vchart/option/pieChart#label.layout.textAlign)

  


Different chart libraries have different levels of support for pie charts, and the level of support for pie chart labels also varies. In VChart: - The text content of the label: You can set custom label content through the label.formatMethod callback function. [Please refer to the configuration document](https://www.visactor.io/vchart/option/pieChart#label.formatMethod). - The text color of the label: You can set the style of the text, including color, font, size, etc., through label.style. Any attribute supported by VChart text graphics can be configured. [Please refer to the configuration document](https://www.visactor.io/vchart/option/pieChart#label.style.text). - The layout of the label: If you simply want to adjust the position of the label, you can set label.position to determine whether the label is inside or outside. If you want to adjust the layout strategy, you can use label.layout for detailed adjustments. [Please refer to the configuration document for more information](https://www.visactor.io/vchart/option/pieChart#label.layout.textAlign).

## 代码示例 Code Example

-   自定义文字内容和文字颜色
-   Custom text content and text color.

```
const spec = {
  type: 'pie',
  data: [
    {
      id: 'id0',
      values: [
        { type: 'oxygen', value: '46.60' },
        { type: 'silicon', value: '27.72' },
        { type: 'aluminum', value: '8.13' },
        { type: 'iron', value: '5' },
        { type: 'calcium', value: '3.63' },
        { type: 'sodium', value: '2.83' },
        { type: 'potassium', value: '2.59' },
        { type: 'others', value: '3.5' }
      ]
    }
  ],
  outerRadius: 0.8,
  valueField: 'value',
  categoryField: 'type',
  title: {
    visible: true,
    text: 'Statistics of Surface Element Content'
  },
  legends: {
    visible: true,
    orient: 'left'
  },
  scales: [{
    id: 'labelScale',
    type: 'linear',
    domain: [{
      dataId: 'id0',
      fields: ['value']
    }],
    range: ['red', 'green'],
  }],
  label: {
    visible: true,
    formatMethod: (text, datum) => {
      return `${datum.type}: ${datum.value}`
    },
    style: {
      fill: {
        scale: 'labelScale',
        field: 'value'
      }
    }
  },
  tooltip: {
    mark: {
      content: [
        {
          key: datum => datum['type'],
          value: datum => datum['value'] + '%'
        }
      ]
    }
  }
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

![image](https://github.com/VisActor/VChart/assets/2384516/bf362d9e-b2f1-4939-8289-b92303f5479f)

-   自定义布局，将标签设置在饼图内部
-   Custom layout, placing labels inside a pie chart.

  
![image](https://github.com/VisActor/VChart/assets/2384516/d386bc79-91d1-4729-add3-35d9ce7862b0)

![image](https://github.com/VisActor/VChart/assets/2384516/76f97de1-7f7d-478b-9d66-dc72218c62b4)

  


## 结果展示 Results

在线效果参考：https://codesandbox.io/s/pie-chart-label-53s2p9

Online demo：https://codesandbox.io/s/pie-chart-label-53s2p9

![image](https://github.com/VisActor/VChart/assets/2384516/3865d74e-dc92-4608-9108-74cf90a7df92)

## 相关文档 Related Documentation

Label文字内容配置：<https://www.visactor.io/vchart/option/pieChart#label.formatMethod>

Label 颜色配置：<https://www.visactor.io/vchart/option/pieChart#label.style.fill>

Label 布局配置：<https://www.visactor.io/vchart/option/pieChart#label.position>

饼图教程：<https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Types/Pie>

github：<https://github.com/VisActor/VChart>

  


Label content options：<https://www.visactor.io/vchart/option/pieChart#label.formatMethod>

Label color options：<https://www.visactor.io/vchart/option/pieChart#label.style.fill>

Label layout options：<https://www.visactor.io/vchart/option/pieChart#label.position>

Pie tutorials：<https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Types/Pie>

github：<https://github.com/VisActor/VChart>
