### ISSUE TITLE
[FAQ] How to implement a combination of line chart and stacked bar chart? 

### ISSUE THREAD

**Issue by TingLittleKang** [VisActor/VChart#817]
类似 （https://www.visactor.io/vchart/demo/combination/single-region?keyword=commonChart）这样的组合图，
可以实现柱图是堆积的效果吗？
![image](https://github.com/VisActor/VChart/assets/143469603/c4fe5da7-68c7-474a-a607-f084d1694695)

Can a combination chart, similar to the one at (https://www.visactor.io/vchart/demo/combination/single-region?keyword=commonChart), achieve a stacked effect for bar charts?

**Comment by xuanhun** [comment]
## **解决方案 Solution**

**不同图表库的解决方案不一样，根据你给的demo，在** **VChart** **中对** **组合图** **中的柱系列，设置** **`stack: true`**

**The solutions of different chart libraries are different. Based on the demo you provided, set** **`stack: true`** **for the bar series in** **VChart** **'s combination chart**

![image](https://github.com/VisActor/VChart/assets/2384516/7c32ade0-a128-48cf-937d-7bb9c3969128)



## **代码示例 Code Example**

**代码参考 Code Example**

```
const spec = { type: 'common', seriesField: 'color', data: [
    { id: 'id0', values: [
        { x: '周一', type: '早餐', y: 15
        },
        { x: '周一', type: '午餐', y: 25
        },
        { x: '周二', type: '早餐', y: 12
        },
        { x: '周二', type: '午餐', y: 30
        },
        { x: '周三', type: '早餐', y: 15
        },
        { x: '周三', type: '午餐', y: 24
        },
        { x: '周四', type: '早餐', y: 10
        },
        { x: '周四', type: '午餐', y: 25
        },
        { x: '周五', type: '早餐', y: 13
        },
        { x: '周五', type: '午餐', y: 20
        },
        { x: '周六', type: '早餐', y: 10
        },
        { x: '周六', type: '午餐', y: 22
        },
        { x: '周日', type: '早餐', y: 12
        },
        { x: '周日', type: '午餐', y: 19
        }
      ]
    },
    { id: 'id1', values: [
        { x: '周一', type: '饮料', y: 22
        },
        { x: '周二', type: '饮料', y: 43
        },
        { x: '周三', type: '饮料', y: 33
        },
        { x: '周四', type: '饮料', y: 22
        },
        { x: '周五', type: '饮料', y: 10
        },
        { x: '周六', type: '饮料', y: 30
        },
        { x: '周日', type: '饮料', y: 50
        }
      ]
    }
  ], series: [
    { type: 'bar', id: 'bar', dataIndex: 0, label: { visible: true
      }, seriesField: 'type', dataIndex: 0, xField: 'x', yField: 'y', stack: true
    },
    { type: 'line', id: 'line', dataIndex: 1, label: { visible: true
      }, seriesField: 'type', xField: 'x', yField: 'y', stack: false
    }
  ], axes: [
    { id: "leftYAxis", orient: "left", seriesIndex: [
        0,
        1
      ], nice: true
    },
    { id: "rightYAxis", orient: "right", seriesIndex: [
        0,
        1
      ], gird: { visible: false
      }
    },
    { orient: 'bottom', label: { visible: true
      }, type: 'band'
    }
  ], legends: { visible: true, orient: 'bottom'
  }
}; 
```

  


  


## **结果展示 Results**

**在线效果参考：** **https://codesandbox.io/s/stack-bar-chart-and-line-cz9xvj**

**Online demo：** **https://codesandbox.io/s/stack-bar-chart-and-line-cz9xvj**

![image](https://github.com/VisActor/VChart/assets/2384516/fa08f075-5fd2-4d54-92c2-694e0c1bb03d)


## **相关文档 Related Documentation**

**组合图** **教程：** **https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Types/Combination**

**组合图** **配置：** **https://www.visactor.io/vchart/option/commonChart#type**

**轴同步配置：** **https://www.visactor.io/vchart/option/commonChart#axes-linear.sync.axisId**

**github** **：** **https://github.com/VisActor/VChart**

  


  


**Common Chart Tutorial：** **https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Types/Area**

**Common Chart Option：** **https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Types/Area**

**Sync Axes Options:** **https://www.visactor.io/vchart/option/commonChart#axes-linear.sync.axisId**

**github** **：** **https://github.com/VisActor/VChart**
