### ISSUE TITLE
[FAQ] How does the Ring with Indicator Card dynamically update indicator values?

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#818]
Something like (https://www.visactor.io/vchart/demo/pie-chart/pie-indicator) for a ring with indicator cards.
![image](https://github.com/VisActor/VChart/assets/40026218/82452b8e-d825-468e-9a0d-daa375cd1247)
The value in this metrics card is now user-defined and does not support automatic changes, but it is possible to update this value after calculation. Can this number in the metrics card be changed according to the sector of the hover? How to do it?

**Comment by xuanhun** [comment]
## 解决方案 Solution

不同图表库的解决方案不一样，根据你给的demo，只需要设置交互触发类型和配置text字段内容。

-   `indicator.``trigger` 用来设置交互触发类型。可选的交互类型有hover、select、none。默认设置交互触发类型为select。根据你的需求，需要将`indicator.``trigger`设置为hover。
-   `indicator.title.style.``text`用来设置文本内容，且支持回调。可以根据需要的数据字段，在text中配置所需字段并可根据需求格式化展现形式。

![image](https://github.com/VisActor/VChart/assets/2384516/2d06fc56-67ed-400c-a3da-08715809c3d2)

The solution is different for different charting libraries. According to the demo you gave, you only need to set the interaction trigger type and configure the text field content.

-   `indicator.trigger` is used to set the interaction trigger type. The available interaction types are hover, select, none, the default interaction trigger type is select, according to your requirement, you need to set `indicator.trigger` to hover.
-   `indicator.title.style.text` is used to set the text content and supports callback. You can configure the required fields in the text according to the required data fields and format the presentation according to your needs.

  


## 代码示例 Code Example

代码参考 Code Example

```
const data = [
  { type: 'oxygen', value: '46.60', formula: 'O', texture: 'circle' },
  { type: 'silicon', value: '27.72', formula: 'Si', texture: 'horizontal-line' },
  { type: 'aluminum', value: '8.13', formula: 'Al', texture: 'vertical-line' },
  { type: 'iron', value: '5', formula: 'Fe', texture: 'rect' },
  { type: 'calcium', value: '3.63', formula: 'Ca', texture: 'grid' },
  { type: 'sodium', value: '2.83', formula: 'Na', texture: 'bias-rl' },
  { type: 'potassium', value: '2.59', formula: 'K', texture: 'diamond' },
  { type: 'others', value: '3.5', formula: 'Others', texture: 'bias-lr' }
];
const spec = {
  type: 'pie',
  data: [
    {
      id: 'id0',
      values: data
    }
  ],
  outerRadius: 0.8,
  innerRadius: 0.5,
  padAngle: 0.6,
  valueField: 'value',
  categoryField: 'type',
  pie: {
    style: {
      cornerRadius: 10,
      texture: datum => datum['texture']
    },
    state: {
      hover: {
        outerRadius: 0.85,
        stroke: '#000',
        lineWidth: 1
      },
      selected: {
        outerRadius: 0.85,
        stroke: '#000',
        lineWidth: 1
      }
    }
  },
  title: {
    visible: true,
    text: 'Statistics of Surface Element Content'
  },
  indicator: {
    visible: true,
    trigger: 'hover',
    limitRatio: 0.4,
    title: {
      visible: true,
      autoFit: true,
      style: {
        fontWeight: 'bolder',
        fontFamily: 'Times New Roman',
        fill: '#888',
        text: datum => {
          const d = datum ?? data[0];
          return d['formula'];
        }
      }
    },
    content: [
      {
        visible: true,
        style: {
          fontSize: 20,
          fill: 'orange',
          fontWeight: 'bolder',
          fontFamily: 'Times New Roman',
          text: datum => {
            const d = datum ?? data[0];
            return d['type'];
          }
        }
      },
      {
        visible: true,
        style: {
          fontSize: 18,
          fill: 'orange',
          fontFamily: 'Times New Roman',
          text: datum => {
            const d = datum ?? data[0];
            return d['value'] + '%';
          }
        }
      }
    ]
  },
  legends: {
    visible: true,
    orient: 'left',
    item: {
      shape: {
        style: {
          symbolType: 'circle',
          texture: datum => datum['texture']
        }
      }
    }
  },
  tooltip: {
    mark: {
      content: [
        {
          key: datum => datum['type'],
          value: datum => datum['value'] + '%'
        }
      ]
    }
  }
};
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/pie-chart-with-indicator-card-4ypr2k

Online demo：https://codesandbox.io/s/pie-chart-with-indicator-card-4ypr2k

  
![Sep-13-2023 16-53-36](https://github.com/VisActor/VChart/assets/2384516/e42c1e4d-48bb-4040-b154-7cd95024932b)


## 相关文档 Related Documentation

带指标卡饼图demo：https://www.visactor.io/vchart/demo/pie-chart/pie-indicator

指标卡教程：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Indicator

相关api：https://www.visactor.io/vchart/option/pieChart#indicator

github：https://github.com/VisActor/VChart

  


Pie Chart with Indicator Card Demo：https://www.visactor.io/vchart/demo/bar-chart/stack-column

Indicator Tutorial：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Indicator

Related api：https://www.visactor.io/vchart/option/pieChart#indicator

github：https://github.com/VisActor/VChart
