### ISSUE TITLE
How to configure chart adaptive container width and height?

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#819]
### What problem does this feature solve?

When I use a VChart chart, I want the chart to automatically adapt to the size of the container. What should I do?

### What does the proposed API look like?

n/a

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart的图表提供autoFit属性，在默认情况下就是自适应容器大小的。该配置的优先级高于构造函数中的 autoFit 配置。如果用户配置了 width，则以用户配置的 width 为准，height 同理。

你这边没有提供更多的背景信息，我猜测一下图表没有自适应的原因：

1.  如果你在spec里指定的大小，此时将不会再自适应容器大小
1.  spec中的autoFit开关被关闭了
1.  外部通过css限制了Dom的尺寸

  


一般来说前两种情况是常见的，你可以输出一下你的最终spec排查一下你得情况。

  


  


VChart's charts have the `autoFit` property, which is set to automatically fit the size of the container by default. This configuration takes precedence over the `autoFit` configuration in the constructor. If the user configures the `width`, it will be based on the user's `width` configuration, and the same principle applies to `height`.

Without any more information on your problem, I guess why the chart is not adaptive:

1.  If you specify the size in spec, the container size will no longer be adaptive
1.  The autoFit switch in spec is turned off
1.  The size of the Dom is limited by css

In general, the first two cases are common, so you can output your final spec and check your situation.

  


## 代码示例 Code Example

```
const spec = {
  type: 'common',
  autoFit:true,
  (...)
  }
```

  


## 相关文档 Quote

tooltip option：https://visactor.io/vchart/option/barChart#autoFit

github：https://github.com/VisActor/VChart
