### ISSUE TITLE
[FAQ] When hovering over a donut chart, how to configure the style of donut chart?

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#822]
In the interaction of a donut chart, how can the border color, border thickness, radius, and fill opacity of the sectors be changed when the pointer hovers over them?
Additionally, how should the styles of other arc marks, i.e., the ones not being hovered over, be handled?

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart图表已经提供了对应的功能，VChart对图元上的各种常用交互抽象为了图元的状态，将图元的状态分为了以下几种：

-   `hover` 指针悬浮状态，图元被鼠标指针悬浮时的状态。
-   `hover_reverse` 非指针悬浮状态，当有图元进入了 `hover` 状态时，其他图元的状态。
-   `selected` 选中状态，图元被选中时的状态。
-   `selected_reverse` 非选中状态，当有图元进入了 `selected` 状态时，其他图元的状态。
-   `dimension_hover` 维度悬浮状态，鼠标指针悬浮在某一段 `x` 轴区域内时的状态。
-   `dimension_hover_reverse` 非维度悬浮状态，当有图元进入了 `dimension_hover` 状态时，其他图元的状态。

  


如果想要hover到环形图时，改变图元的样式，可以在pie配置中，设置图元的hover状态。

[参考文档：图元的状态](https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Series/Mark)

  


* * *

The [VChart](https://github.com/VisActor/VChart) already provides corresponding functions for this. VChart abstracts various common interactions into mark state. The mark states in VChart are divided into the following categories:

-   `default`: Default state, the initial state of the graphic element.
-   `hover`: Pointer hover state, the state of the graphic element when it is hovered over by the mouse pointer.
-   `hover_reverse`: Non-pointer hover state, the state of other graphic elements when a graphic element enters the `hover` state.
-   `selected`: Selected state, the state of the graphic element when it is selected.
-   `selected_reverse`: Non-selected state, the state of other graphic elements when a graphic element enters the `selected` state.
-   `dimension_hover`: Dimension hover state, the state when the mouse pointer hovers within a certain `x` axis area.
-   `dimension_hover_reverse`: Non-dimensional hover state, the state of other graphic elements when a graphic element enters the `dimension_hover` state.

  


If you want to change the style of pie mark when hovering over a donut chart, you can configure the mark's `hover` state in the pie configuration.

[Reference documentation: State of Mark](https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Series/Mark)

  


## 代码示例 Code Example

在以下示例中，`pie.state`中设置了4个状态

1.  `hover`: 指针悬浮到的图元， 显示描边，填充透明度变低，扩展外半径。
1.  `hover_reverse`：其它未悬浮到的图元，缩小外半径。
1.  `selected`：指针选中的图元，扩大内半径和外半径。
1.  `selected_reverse`：其它未选中的图元，填充透明度变低。

  


In the following example, the `pie.state` configuration includes four states:

1.  `hover`: The state of the mark when the pointer hovers over it. It displays a border, reduces the fill opacity, and expands the outer radius.
1.  `hover_reverse`: The state of other marks when they are not being hovered over. It reduces the outer radius.
1.  `selected`: The state of the mark when it is selected by the pointer. It enlarges both the inner and outer radii.
1.  `selected_reverse`: The state of other marks when they are not selected. It reduces the fill opacity.

```
import { useEffect, useRef } from "react";
import VChart from "@visactor/vchart";

export const Chart = () => {
  const containerRef = useRef(null);

  useEffect(() => {
    const spec = {
      type: "pie",
      data: [
        {
          id: "data",
          values: [
            { type: "oxygen", value: "46.60" },
            { type: "silicon", value: "27.72" },
            { type: "aluminum", value: "8.13" },
            { type: "iron", value: "5" },
            { type: "calcium", value: "3.63" },
            { type: "sodium", value: "2.83" },
            { type: "potassium", value: "2.59" },
            { type: "others", value: "3.5" },
          ],
        },
      ],
      valueField: "value",
      categoryField: "type",
      outerRadius: 0.8,
      innerRadius: 0.5,
      padAngle: 0.5,
      pie: {
        state: {
          hover: {
            stroke: "#0FF",
            lineWidth: 1,

            fillOpacity: 0.9,
            outerRadius: 0.85,
          },
          hover_reverse: {
            outerRadius: 0.7,
            innerRadius: 0.5,
          },
          selected: {
            outerRadius: 0.85,
            innerRadius: 0.6,
          },
          selected_reverse: {
            fillOpacity: 0.25,
          },
        },
      },
    };

    const vchart = new VChart(spec, {
      dom: containerRef.current,
      onError: console.error
    });

    vchart.renderAsync();

    return () => vchart.release();
  }, []);

  return (
    <div
      ref={containerRef}
      style={{
        width: 520,
        height: 520,
        border: "1px solid #ccc",
      }}
    />
  );
};
```

## 结果展示 Results

在线示例：https://codesandbox.io/s/pie-hover-llxwgy?file=/src/App.js

Online Demo: https://codesandbox.io/s/pie-hover-llxwgy?file=/src/App.js

![image](https://github.com/VisActor/VChart/assets/2384516/154ec981-ba58-4ba0-b56f-fd0739eab66d)

## 相关文档

[VChart Github](https://github.com/VisActor/VChart)

[图元状态教程](https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Series/Mark)

[图表示例](https://visactor.io/vchart/demo/pie-chart/ring?keyword=pieChart)

  


[VChart Github](https://github.com/VisActor/VChart)

[Mark State Tutorial](https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Series/Mark)

[Chart Demo](https://visactor.io/vchart/demo/pie-chart/ring?keyword=pieChart)
