### ISSUE TITLE
[FAQ] How can the background color of the funnel chart's conversion layers be modified?

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#823]
The conversion layers in a funnel chart are used to depict the transition process between different stages or steps.
By default, the background color of the conversion layers in a funnel chart is usually set to a single color. How can the background color of the funnel chart's conversion layers be modified to enhance visualization and readability?

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart的漏斗图已经提供了对应的功能，允许用户在`transform`配置中设置转化层的图元样式。

若要改变漏斗图转化层的背景颜色，可以通过配置`transform.style.fill` 修改转化层的背景色。

  


VChart's funnel chart already provides the corresponding functionality that allows users to configure the mark style of the conversion layers in the `transform` configuration.

To change the background color of the funnel chart's conversion layers, you can modify the `transform.style.fill` configuration to adjust the background color of the conversion layers.

## 代码示例 Code Example

```
import { useEffect, useRef } from "react";
import VChart from "@visactor/vchart";

export const Chart = () => {
  const containerRef = useRef(null);

  useEffect(() => {
    const spec = {
      type: "funnel",
      maxSize: "75%",
      minSize: "10%",
      isTransform: true,
      shape: "rect",
      transform: {
        style: {
          fill: "#44b15920",
          lineWidth: 4,
          stroke: "white",
        },
      },
      label: {
        visible: true,
      },
      outerLabel: {
        visible: true,
        position: "right",
        style: {
          text: (datum) => {
            return `${datum.percent * 100}%`;
          },
        },
      },
      transformLabel: {
        visible: true,
        style: {
          fill: "#000000",
        },
      },
      data: [
        {
          name: "funnel",
          values: [
            {
              value: 100,
              name: "Resume Screening",
              percent: 1,
            },
            {
              value: 80,
              name: "Resume Evaluation",
              percent: 0.8,
            },
            {
              value: 50,
              name: "Evaluation Passed",
              percent: 0.5,
            },
            {
              value: 30,
              name: "Interview",
              percent: 0.3,
            },
            {
              value: 10,
              name: "Final Pass",
              percent: 0.1,
            },
          ],
        },
      ],
      categoryField: "name",
      valueField: "value",
    };

    const vchart = new VChart(spec, {
      dom: containerRef.current,
    });

    vchart.renderAsync();

    return () => vchart.release();
  }, []);

  return (
    <div
      ref={containerRef}
      style={{
        width: 520,
        height: 520,
        border: "1px solid #ccc",
      }}
    />
  );
};
```

## 结果展示 Results

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/5db0ddac68dc4e0cb73de2adb2178140~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=1050&h=1056&s=51863&e=png&b=fefefe)

在线示例：https://codesandbox.io/s/funnel-chart-transform-c7s9fk?file=/src/App.jsx

Online Demo：https://codesandbox.io/s/funnel-chart-transform-c7s9fk?file=/src/App.jsx

## 相关文档

[VChart Github](https://github.com/VisActor/VChart)

[漏斗图转化层 示例](https://visactor.io/vchart/demo/funnel-chart/rect-funnel?keyword=funnelChart)

[漏斗图配置项 文档](https://visactor.io/vchart/option/funnelChart#transform)

  


[VChart Github](https://github.com/VisActor/VChart)

[Funnel Chart Transform Demo](https://visactor.io/vchart/demo/funnel-chart/rect-funnel?keyword=funnelChart)

[Funnel Chart API](https://visactor.io/vchart/option/funnelChart#transform)
