### ISSUE TITLE
[FAQ] How to automatically update chart data in React components?

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#824]
How can we achieve automatic updating of chart data in a chart component wrapped with React?

**Comment by xuanhun** [comment]
## 解决方案 Solution

在VChart中，可以调用updateSpec或者updateData进行图表更新。

In VChart, you can update the chart by calling either updateSpec or updateData.

![image](https://github.com/VisActor/VChart/assets/2384516/8a50da2d-83f0-470d-af22-d7d5ccc5c88b)


你可以在初始化图表实例时，在React组件中使用ref保存图表实例。随后使用useEffect，将deps设置为数据更新的依赖项，在回调函数中调用图表实例的updateData实现数据更新。

To update the chart data, you can save the chart instance using ref when initializing the chart instance in a React component. Then, use useEffect to set the dependencies to the data that needs to be updated, and call the chart instance's updateData method in the callback function.

VChart还提供了React-VChart封装：

VChart also provides a React-VChart wrapper:

https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/react

你可以参考下面的代码示例，使用React-VChart实现图表数据更新。

You can refer to the code example below to update the chart data using React-VChart.

## 代码示例 Code Example

代码参考 Code Example

点击 Update the data of bar chart 按钮，可以实现更新图表数据。

Clicking the "Update the data of bar chart" button allows for the updating of the chart's data.

```
import "./styles.css";
import { BarChart } from "./BarChart";
import { LineChart } from "./LineChart";
import { AreaChart } from "./AreaChart";
import { getBarData } from "./bar-data";
import { useState } from "react";

const colorMaps = {
  default: [
    "#6690F2",
    "#70D6A3",
    "#B4E6E2",
    "#63B5FC",
    "#FF8F62",
    "#FFDC83",
    "#BCC5FD",
    "#A29BFE",
    "#63C4C7",
    "#F68484"
  ],
  red: [
    "#c12e34",
    "#e6b600",
    "#0098d9",
    "#2b821d",
    "#005eaa",
    "#339ca8",
    "#cda819",
    "#32a487"
  ]
};

export default function App() {
  const [barData, setBarData] = useState<any[]>(getBarData());
  const [colors, setColors] = useState<string[]>(colorMaps.default);
  const handleUpdateBarData = () => {
    setBarData(getBarData());
  };

  const handleUpdateColors = () => {
    if (colors === colorMaps.default) {
      setColors(colorMaps.red);
    } else {
      setColors(colorMaps.default);
    }
  };

  return (
    <div className="App">
      <div>
        <img src="https://lf9-dp-fe-cms-tos.byteorg.com/obj/bit-cloud/logo_500_200_light.png" />
      </div>
      <button onClick={handleUpdateBarData}>
        Update the data of bar chart
      </button>

      <button onClick={handleUpdateColors}>update colors</button>

      <h2>A Bar Chart</h2>

      <BarChart data={barData} colors={colors} />

      <h2>A Line Chart</h2>
      <LineChart colors={colors} />

      <h2>A Area Chart</h2>
      <AreaChart colors={colors} />
    </div>
  );
}
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/visactor-vchart-react-demo-forked-jsqqjj

Online demo：https://codesandbox.io/s/visactor-vchart-react-demo-forked-jsqqjj

  
![Sep-07-2023 11-08-34](https://github.com/VisActor/VChart/assets/2384516/1a6cef56-b8f5-425d-b142-1a09790ef956)



## 相关文档 Related Documentation

相关文档 Related Documentation

react-vchart教程：https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/react

github：https://github.com/VisActor/VChart

  


react-vchart Tutorial：https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/react

github：https://github.com/VisActor/VChart
