### ISSUE TITLE
[FAQ] How to add transition animations  when clicking the legend of a funnel chart?

### ISSUE THREAD

**Issue by FlyingAndFly** [VisActor/VChart#834]
I am developing a funnel chart. When I click on the legend, there is no animation effect, and it's a bit stiff. Is there any chart library that supports animation effects configuration for legend clicks?
![f-no-animate](https://github.com/VisActor/VChart/assets/143593654/f9bc255e-3eb4-4c12-96ad-52e4dccc2400)

**Comment by xuanhun** [comment]
## 解决方案 Solution

推荐你使用 VChart。VChart 的漏斗图在图例筛选时，是有默认过渡动画的，参考官网 demo：https://visactor.io/vchart/demo/funnel-chart/basic-funnel

  


VChart funnel chart has a default transition animation when filtering the legend. You can refer to the official website demo here: https://visactor.io/vchart/demo/funnel-chart/basic-funnel

  


## 结果展示 Results

![1694142410468_35786d15a1dea26afa66f337186f2239](https://github.com/VisActor/VChart/assets/2384516/c6772bd4-ea1d-416a-b0c2-32fdcb941e04)


  


## 相关文档 Quote

github：https://github.com/VisActor/VChart

funnel demos: https://visactor.io/vchart/demo/funnel-chart/basic-funnel
