### ISSUE TITLE
[FAQ] How to generate a simplified mini line chart?

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#841]
I would like to create an extremely simplified line chart that minimizes space usage while efficiently conveying the trends and variations in the data. 
Therefore, I expect this line chart to exclude components such as axes, labels, and legends, focusing solely on the line segments.

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart的各个图表组件提供了丰富的样式配置，在组件中配置`visible:false`就能够让组件隐藏，以绘制更加精简的图表。

The various chart components in VChart provide rich style configurations.

By setting `visible:false` in the component configuration, you can hide the component and create a more simplified line chart.

## 代码示例 Code Example

```
import { useEffect, useRef } from "react";
import VChart from "@visactor/vchart";

export const Chart = () => {
  const containerRef = useRef(null);

  useEffect(() => {
    const spec = {
      type: "line",
      // type: 'area',
      data: {
        values: [
          {
            time: "2:00",
            value: 8
          },
          {
            time: "4:00",
            value: 9
          },
          {
            time: "6:00",
            value: 11
          },
          {
            time: "8:00",
            value: 14
          },
          {
            time: "10:00",
            value: 16
          },
          {
            time: "12:00",
            value: 17
          },
          {
            time: "14:00",
            value: 17
          },
          {
            time: "16:00",
            value: 16
          },
          {
            time: "18:00",
            value: 15
          }
        ]
      },
      xField: "time",
      yField: "value",
      padding: 0,
      margin: 0,
      point: {
        visible: false
      },
      line: {
        style: {
          curveType: "monotone"
        }
      },
      axes: [
        {
          type: "linear",
          orient: "left",
          nice: true,
          zero: true,
          visible: false
        },
        {
          type: "band",
          paddingOuter: 0,
          paddingInner: 0,
          orient: "bottom",
          visible: false
        }
      ],
      legends: [
        {
          visible: false
        }
      ]
    };

    const vchart = new VChart(spec, {
      dom: containerRef.current
    });

    vchart.renderSync();

    return () => vchart.release();
  }, []);

  return (
    <div
      ref={containerRef}
      style={{
        width: 520,
        height: 520,
        border: "1px solid #ccc"
      }}
    />
  );
};
```

## 结果展示 Results

在线示例：https://codesandbox.io/s/mini-line-chart-xlrxhd?file=/src/App.jsx

Online Demo: https://codesandbox.io/s/mini-line-chart-xlrxhd?file=/src/App.jsx

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/621a9ad3656d4b25b539b29250a4a587~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=1066&h=1066&s=9323&e=png&b=ffffff)

## 相关文档 Documents

[VChart Github](https://github.com/VisActor/VChart)

[VChart Axes Guide](https://visactor.io/vchart/guide/concepts/axes)

[VChart Line Chart Guide](https://visactor.io/vchart/guide/chart/line)

  


[VChart Github](https://github.com/VisActor/VChart)

[VChart 坐标轴教程](https://visactor.io/vchart/guide/concepts/axes)

[VChart 折线图教程](https://visactor.io/vchart/guide/chart/line)
