### ISSUE TITLE
[FAQ] How to customize the image and color of a legend?

### ISSUE THREAD

**Issue by TingLittleKang** [VisActor/VChart#848]
类似 （https://www.visactor.io/vchart/demo/pie-chart/basic-pie）这样的饼图，图例的图像、颜色、内容可以自定义？如何自定义配置？
![image](https://github.com/VisActor/VChart/assets/143469603/1dd0e59d-2114-41b5-81d8-0ed267a03317)

Can a pie chart similar to (https://www.visactor.io/vchart/demo/pie-chart/basic-pie) have customizable legend icons, colors, and content? How can the customization be done?

**Comment by xuanhun** [comment]
## 解决方案 Solution

图例是图表中常用的组件，很多类型的图表都支持图例的展示和配置，在VChart中：

-   通过配置`legend.item`来对所有的图例项设置统一的样式
-   通过配置`legend.data`回调函数来对每个图例项设置不同的内容以及样式

  


The legend is a commonly used component in charts, and many types of charts support the display and configuration of legends. In VChart: - Use the legend.item configuration to set a uniform style for all legend items. - Use the legend.data callback function to set different content and styles for each legend item.

  


## 代码示例

-   通过配置`legend.item`来对所有的图例项设置统一的样式
-   Use `legend.item` configuration to set a unified style for all legend items.

```
const spec = {
  type: 'pie',
  data: [
    {
      id: 'id0',
      values: [
        { type: 'oxygen', value: '46.60' },
        { type: 'silicon', value: '27.72' },
        { type: 'aluminum', value: '8.13' },
        { type: 'iron', value: '5' },
        { type: 'calcium', value: '3.63' },
        { type: 'sodium', value: '2.83' },
        { type: 'potassium', value: '2.59' },
        { type: 'others', value: '3.5' }
      ]
    }
  ],
  outerRadius: 0.8,
  valueField: 'value',
  categoryField: 'type',
  title: {
    visible: true,
    text: 'Statistics of Surface Element Content'
  },
  legends: {
    visible: true,
    orient: 'left',
    item: {
      width: '15%',
      shape: {
        style: {
          background: 'https://lf9-dp-fe-cms-tos.byteorg.com/obj/bit-cloud/log.jpeg',
          symbolType: 'rect',
          fill: false
        }
      },
      label: {
        style: {fontSize: 14, fontWeight: 'bold' }
      },
      value: {
        alignRight: true,
        style: {
          fill: '#333',
          fillOpacity: 0.8,
          fontSize: 10
        },
        state: {
          unselected: {
            fill: '#d8d8d8'
          }
        }
      }
    }
  },
  label: {
    visible: true
  },
  tooltip: {
    mark: {
      content: [
        {
          key: datum => datum['type'],
          value: datum => datum['value'] + '%'
        }
      ]
    }
  }
};
```

![image](https://github.com/VisActor/VChart/assets/2384516/ee1b7888-b545-437e-bfd4-c54ee711d4fb)

-   通过配置`legend.data`回调函数来对每个图例项设置不同的内容
-   Use the `legend.data` callback function to set different content for each legend item.

```
const values = [
  { type: 'oxygen', value: '46.60' },
  { type: 'silicon', value: '27.72' },
  { type: 'aluminum', value: '8.13' },
  { type: 'iron', value: '5' },
  { type: 'calcium', value: '3.63' },
  { type: 'sodium', value: '2.83' },
  { type: 'potassium', value: '2.59' },
  { type: 'others', value: '3.5' }
];
const spec = {
  type: 'pie',
  data: [
    {
      id: 'id0',
      values, 
    }
  ],
  outerRadius: 0.8,
  valueField: 'value',
  categoryField: 'type',
  title: {
    visible: true,
    text: 'Statistics of Surface Element Content'
  },
  legends: {
    visible: true,
    orient: 'left',
    data: (items, scale,c, d) => {
      console.log(items, scale, c, d);
      return items.map(item => {
        item.value = values.find(entry => entry.type === item.label).value;
        item.shape.symbolType = 'rect';
        item.shape.background = 'https://lf9-dp-fe-cms-tos.byteorg.com/obj/bit-cloud/log.jpeg';
        item.shape.fill = false;
        return item;
      });
    },
    item: {
      width: '15%',
      label: {
        style: { 
          fontSize: 14, 
          fontWeight: 'bold'
        }
      },
      value: {
        alignRight: true,
        style: {
          fill: '#333',
          fillOpacity: 0.8,
          fontSize: 10
        },
        state: {
          unselected: {
            fill: '#d8d8d8'
          }
        }
      }
    }
  },
  label: {
    visible: true
  },
  tooltip: {
    mark: {
      content: [
        {
          key: datum => datum['type'],
          value: datum => datum['value'] + '%'
        }
      ]
    }
  }
};
```

  


  


## 结果展示 Results

在线效果参考：https://codesandbox.io/s/pie-chart-legend-2kzv8w

Online demo：https://codesandbox.io/s/pie-chart-legend-2kzv8w

![image](https://github.com/VisActor/VChart/assets/2384516/e942874f-d0aa-47ef-9ae0-920bf80eb216)

## 相关文档 Related Documentation

Legend配置：https://www.visactor.io/vchart/option/pieChart-legends-discrete#type

图例教程：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Legend

github：https://github.com/VisActor/VChart

  


Legend options：https://www.visactor.io/vchart/option/pieChart-legends-discrete#type

Legend tutorial：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Legend

github：https://github.com/VisActor/VChart
