### ISSUE TITLE
[FAQ] How to disable the default interactive behavior of legends?

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#850]
When displaying charts on the mobile end, in order to facilitate user reading, the legend size of the chart will be expanded. But almost every chart library's legend component defaults to setting default interactive behavior for the legend, such as filtering data when clicked.

How to cancel the default interaction of the legend in the chart, which is prone to accidentally touching it when sliding your fingers?

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart中为可交互的图元或组件提供了`interactive`配置用来控制启用或禁用交互功能，例如图例、图表标注、各种类型的图元等。

这个配置虽然默认开启的，但用户可以自己控制图表的交互行为。

  


VChart provides interactive configurations for interactive marks or components to control whether interactive features are enabled or disabled, such as legends, chart annotations, various types of elements, etc.

Although this configuration is enabled by default, users can control the interactive behavior of the chart themselves.

## 代码示例 Code Example

```
import { useEffect, useRef } from "react";
import VChart from "@visactor/vchart";

export const Chart = () => {
  const containerRef = useRef(null);

  useEffect(() => {
    const spec = {
      type: "bar",
      data: [
        {
          id: "barData",
          values: [
            { type: "Autocracies", year: "1960", value: 126 },
            { type: "Autocracies", year: "1970", value: 117 },
            { type: "Autocracies", year: "1980", value: 114 },
            { type: "Autocracies", year: "1990", value: 111 },
            { type: "Autocracies", year: "2000", value: 89 },
            { type: "Autocracies", year: "2010", value: 80 },
            { type: "Autocracies", year: "2018", value: 80 },
            { type: "Democracies", year: "1960", value: 29 },
            { type: "Democracies", year: "1970", value: 38 },
            { type: "Democracies", year: "1980", value: 41 },
            { type: "Democracies", year: "1990", value: 57 },
            { type: "Democracies", year: "2000", value: 87 },
            { type: "Democracies", year: "2010", value: 98 },
            { type: "Democracies", year: "2018", value: 99 }
          ]
        }
      ],
      xField: ["year", "type"],
      yField: "value",
      seriesField: "type",
      legends: {
        visible: true,
        orient: "bottom",
        position: "middle",
        interactive: false
      }
    };

    const vchart = new VChart(spec, {
      dom: containerRef.current
    });

    vchart.renderSync();

    return () => vchart.release();
  }, []);

  return (
    <div
      ref={containerRef}
      style={{
        width: 520,
        height: 520,
        border: "1px solid #ccc"
      }}
    />
  );
};
```

## 结果展示 Results

在线示例：https://codesandbox.io/s/interactive-legend-dy2wdf?file=/src/App.jsx

Online Demo: https://codesandbox.io/s/interactive-legend-dy2wdf?file=/src/App.jsx

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/537fd6fe8e80440592d2c045b9b4f37c~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=1052&h=1050&s=27044&e=png&b=ffffff)

## 相关文档

[VChart Github](https://github.com/VisActor/VChart)

[VChart Legend Guide](https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Legend)

[VChart Legend API](https://visactor.io/vchart/option/barChart-legends-discrete#interactive)

  


[VChart Github](https://github.com/VisActor/VChart)

[VChart 图例 教程](https://visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Legend)

[VChart 图例 配置](https://visactor.io/vchart/option/barChart-legends-discrete#interactive)
