### ISSUE TITLE
[FAQ] When the data is all 0, how to configure the position of the x-axis?

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#878]
Similar to (https://www.visactor.io/vchart/demo/line-chart/basic-line) such a line chart with all 0 data,
![image](https://github.com/VisActor/VChart/assets/40026218/1f088d8f-3113-49c7-90c2-a0d4e21a2f43)
The position of the x-axis will center the polyline. I want to adjust the position of the X-axis so that the X-axis is aligned with the Y scale of 0. How to achieve this?

**Comment by xuanhun** [comment]
## 解决方案 Solution

不同图表库的解决方案不一样，根据你给的demo，只需要将Y轴的`axes-linear.``zero` 设置为`true`即可。

-   `barChart-axes-linear.``zero``  = true ` **仅当轴为线性轴时生效**，是否包含 0 值。当配置了 min 和 max，该配置项失效。

Different chart libraries have different solutions. According to the demo you gave, you only need to set the `axes-linear.zero` of the Y axis to `true`.

-   `barChart-axes-linear.zero = true` only works if the axis is a linear axis, whether to include 0 value. When min and max are configured, this configuration item becomes invalid.

  


![image](https://github.com/VisActor/VChart/assets/2384516/ec50aa5b-0684-4a1e-8a56-09b41733e2f8)

  


  


## 代码示例 Code Example

代码参考 Code Example

```
const spec = {
  type: 'line',
  data: {
    values: [
      {
        time: '2:00',
        value: 0
      },
      {
        time: '4:00',
        value: 0
      },
      {
        time: '6:00',
        value: 0
      },
      {
        time: '8:00',
        value: 0
      },
      {
        time: '10:00',
        value: 0
      },
      {
        time: '12:00',
        value: 0
      },
      {
        time: '14:00',
        value: 0
      },
      {
        time: '16:00',
        value: 0
      },
      {
        time: '18:00',
        value: 0
      }
    ]
  },
  xField: 'time',
  yField: 'value',
  axes:[
    {
      orient: 'left',
      zero: true,
    }
]
};
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/data-is-all-0-smhq6h

Online demo：https://codesandbox.io/s/data-is-all-0-smhq6h

![image](https://github.com/VisActor/VChart/assets/2384516/a01c7a1e-57b1-4a87-956a-7cf43027054e)

  


  


## 相关文档 Related Documentation

基础折线图demo：https://www.visactor.io/vchart/demo/line-chart/basic-line

坐标轴教程：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Axes

相关api：https://www.visactor.io/vchart/option/lineChart-axes-linear#zero

github：https://github.com/VisActor/VChart

  


Basic Line Chart Demo：https://www.visactor.io/vchart/demo/line-chart/basic-line

Axes Tutorial：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Axes

Related API：https://www.visactor.io/vchart/option/lineChart-axes-linear#zero

Github：https://github.com/VisActor/VChart
