### ISSUE TITLE
[FAQ] How to get the corresponding data point information in a click event using @visactor/react-vchart? 

### ISSUE THREAD

**Issue by TingLittleKang** [VisActor/VChart#890]
How to implement a bar chart like this (https://www.visactor.io/vchart/demo/bar-chart/basic-column) in React using @visactor/react-vchart? How can I bind a click event? Is it possible to retrieve the corresponding data information from the click event? 

![image](https://github.com/VisActor/VChart/assets/143469603/061757f3-38df-406d-9f83-8fa572396b8f)

**Comment by xuanhun** [comment]
## 解决方案 Solution

通过VChart 官方提供的React 封装库`react-vchart` [教程可参考](https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/react)，react-vchart支持两种组件：

-   使用`VChart`组件，组件支持 `onAbc`格式来绑定事件，支持的[事件名参考](https://www.visactor.io/vchart/api/API/event)
-   使用`LineChart`类似的语义化组件实现的时候，在`Line`等子组件上，支持通过`onAbc`格式的props来绑定事件，支持的[事件名参考](https://www.visactor.io/vchart/api/API/event)

[The tutorial](https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/react) for using the React wrapper library react-vchart provided by VChart can be referred to. react-vchart supports two types of components: - When using the VChart component, events can be bound using the onAbc format. [The supported event names can be referred to](https://www.visactor.io/vchart/api/API/event). - When implementing components similar to LineChart using semantic components, such as Line, events can be bound to props using the onAbc format. [The supported event names can be referred to.](https://www.visactor.io/vchart/api/API/event)

  


## 代码示例

```
import { VChart, VChartProps } from "@visactor/react-vchart";
import { Component } from "react";

export interface BarChartProps {
  colors?: string[];
  data: any[];
}

export class BarChart extends Component<BarChartProps> {
  state: { active: any } = {
    active: null
  };
  parseSpec = () => {
    const colors = this.props.colors;
    return {
      type: "bar",
      data: [
        {
          id: "barData",
          values: this.props.data
        }
      ],
      xField: "name",
      yField: "value",
      color: {
        type: "ordinal",
        domain: [],
        range: colors
      }
    } as VChartProps["spec"];
  };

  handleClick = (e: any) => {
    this.setState({ active: e.datum });
  };

  render() {
    return (
      <>
        <p>{`active bar: ${this.state.active?.name ?? ""}`}</p>
        <VChart spec={this.parseSpec()} onClick={this.handleClick} />
      </>
    );
  }
}
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/visactor-vchart-react-event-q6jzwv

Online demo：https://codesandbox.io/s/visactor-vchart-react-event-q6jzwv
![image](https://github.com/VisActor/VChart/assets/2384516/4b0d120e-cfff-4bdf-8ff8-c67d24f1d83e)

## 相关文档 Related Documentation

react-vchart教程：https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/react

github：https://github.com/VisActor/VChart

  


react-vchart Tutorial：https://www.visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/react

github：https://github.com/VisActor/VChart
