### ISSUE TITLE
[FAQ]How to define the number of decimal places of a value displayed by a label?

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#894]
I find that if the decimal places of the numbers are longer, the display is very unattractive. Is there any way to control the length of the decimal places displayed by the labels?
![ada5214a-6f76-47e3-a246-6b0197644e40](https://github.com/VisActor/VChart/assets/8744196/9e44276d-c7bc-4543-bd60-db01fe7700e4)

**Comment by xuanhun** [comment]
## 解决方案 Solution

通过VChart的标签格式化函数可以解决这个问题，此外格式函数还可以支持自定义数字单位等需求

  


VChart label formatting function can solve this problem. In addition, the format function can also be supported for custom numerical units.

  


## 代码示例 Code Example

```
// two decimal places
spec.label.formatMethod = (value: number) => (+value).toFixed(2)

// numerical unit
spec.label.formatMethod = (value: number) => ((+value)/1e3).toFixed(2) + 'k'
```

  


## 结果展示 Results

![image](https://github.com/VisActor/VChart/assets/2384516/4ea152f2-c7aa-4de4-9126-f75853195aaf)


Demo: https://codesandbox.io/s/label-formatter-d34xrm?file=/src/index.ts

  


## 相关文档 Quote

formatMethod option：https://visactor.bytedance.net/vchart/option/barChart#label.formatMethod

label tutorials: https://visactor.bytedance.net/vchart/guide/tutorial_docs/Chart_Concepts/Series/Label

github：https://github.com/VisActor/VChart
