### ISSUE TITLE
[FAQ] How do I configure the default scroll position for chart scrollbars?

### ISSUE THREAD

**Issue by skie1997** [VisActor/VChart#906]
What do I do when I need to configure where the scrollbar scrolls by default? Sometimes I want the scrollbar to start and end at a point that I specify, rather than a default range.

**Comment by xuanhun** [comment]
## 解决方案 Solution

你需要配置表示范围的参数`scrollBar.start`和`scrollBar.end`，它们表示滚动条的起点和终点，取值为`[0, 1]`，表示的该位置所在的百分比布局范围。

除此之外，你还可以通过`scrollBar.startValue`和`scrollBar.endValue`来配置起点和终点，它们分别表示起点和终点的数据值。

You need to configure the parameters `scrollBar.start` and `scrollBar.end`, which represent the start and end points of the scroll bar, and take the values `[0, 1]`, which represent the percentage layout range where the position is located.

In addition to this, you can configure the start and end points with `scrollBar.startValue` and `scrollBar.endValue`, which represent the data values of the start and end points, respectively.

![image](https://github.com/VisActor/VChart/assets/2384516/ac016b92-931a-42ae-8d8a-57b28c7c2d8e)


## 代码示例 Code Example

代码参考 Code Example

```
const spec = {
  type: 'bar',
  data: [
    {
      id: 'barData',
      values: [
        { year: '2000', sales: 22 },
        { year: '2001', sales: 13 },
        { year: '2002', sales: 25 },
        { year: '2003', sales: 29 },
        { year: '2004', sales: 38 },
        { year: '2005', sales: 49 },
        { year: '2006', sales: 58 },
        { year: '2007', sales: 29 },
        { year: '2008', sales: 78 },
        { year: '2009', sales: 19 },
        { year: '2010', sales: 23 },
        { year: '2011', sales: 20 },
        { year: '2012', sales: 98 },
        { year: '2013', sales: 49 },
        { year: '2014', sales: 28 }
      ]
    }
  ],
  direction: 'horizontal',
  yField: 'year',
  xField: 'sales',
  scrollBar: [
    {
      orient: 'right',
      startValue: '2011',
      endValue: '2014',
      roam: true
    }
  ]
};
```

## 结果展示 Results

在线效果参考：https://www.visactor.io/vchart/demo/scrollbar/scrollbar-specified-value

Online demo：https://www.visactor.io/vchart/demo/scrollbar/scrollbar-specified-value

  
![image](https://github.com/VisActor/VChart/assets/2384516/7e822ecc-1b57-4ee3-8660-eda20485bc05)



## 相关文档 Related Documentation

滚动条demo：https://www.visactor.io/vchart/demo/scrollbar/scrollbar-specified-value

滚动条教程：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Scrollbar

相关api：https://www.visactor.io/vchart/option/barChart#scrollbar.orient

github：https://github.com/VisActor/VChart

  


ScrollBar Demo：https://www.visactor.io/vchart/demo/scrollbar/scrollbar-specified-value

ScrollBar Tutorial：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Concepts/Scrollbar

Related api：https://www.visactor.io/vchart/option/barChart#scrollbar.orient

github：https://github.com/VisActor/VChart
