### ISSUE TITLE
[FAQ] How to display the center value when selecting an arc in a pie chart?

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#907]
In a circular chart, there is a large amount of blank space in the center area, and I want to use these areas to display the numerical value corresponding to a sector in the middle of the chart when clicking on it.

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart的为饼图了设计了indicator组件，支持配置指标的标题与多行文本内容，提供对`fixed` 和 `hover` 两种交互方式与常用的样式配置功能。

VChart has designed an indicator component for pie charts, supporting the configuration of indicator titles and multi-line text content.

It provides, `fixed` and `hover` two interaction modes, and commonly used style configuration functions.

  


## 代码示例 Code Example

```
import { useEffect, useRef } from "react";
import VChart from "@visactor/vchart";

export const Chart = () => {
  const containerRef = useRef(null);

  useEffect(() => {
    const spec = {
      type: "pie",
      data: [
        {
          id: "data",
          values: [
            { type: "oxygen", value: "46.60" },
            { type: "silicon", value: "27.72" },
            { type: "aluminum", value: "8.13" },
            { type: "iron", value: "5" },
            { type: "calcium", value: "3.63" },
            { type: "sodium", value: "2.83" },
            { type: "potassium", value: "2.59" },
            { type: "others", value: "3.5" },
          ],
        },
      ],
      outerRadius: 0.6,
      innerRadius: 0.4,
      padAngle: 0.6,
      valueField: "value",
      categoryField: "type",
      pie: {
        style: {
          cornerRadius: 10,
        },
        state: {
          hover: {
            outerRadius: 0.65,
          },
          selected: {
            outerRadius: 0.65,
          },
        },
      },
      label: {
        visible: true,
      },
      indicator: {
        visible: true,
        trigger: "fixed",
        title: {
          visible: true,
          style: {
            fontSize: 18,
            text: (data) => {
              if (data) {
                const value = data["type"];
                return value ? value : null;
              }
              return null;
            },
          },
        },
        content: [
          {
            visible: true,
            style: {
              fontSize: 18,
              text: "",
            },
          },
          {
            visible: true,
            style: {
              fontSize: 18,
              text: (data) => {
                if (data) {
                  const value = data["value"];
                  return value ? `${value}%` : null;
                }
                return null;
              },
            },
          },
        ],
      },
    };

    const vchart = new VChart(spec, {
      dom: containerRef.current,
    });

    vchart.renderSync();

    return () => vchart.release();
  }, []);

  return (
    <div
      ref={containerRef}
      style={{
        width: 520,
        height: 520,
        border: "1px solid #ccc",
      }}
    />
  );
};
```

## 结果展示 Results

在线示例：https://codesandbox.io/s/quizzical-babycat-wcgpzk?file=/src/App.js

Online Demo: https://codesandbox.io/s/quizzical-babycat-wcgpzk?file=/src/App.js

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/8e0956d7d1c142bbbbd2b19ff7ba8ee6~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=1052&h=1048&s=51908&e=png&b=fefefe)

## 相关文档

[VChart Github](https://github.com/VisActor/VChart)

[VChart Pie Chart Indicator Demo](https://visactor.io/vchart/demo/pie-chart/pie-indicator)

[VChart Pie Chart Indicator API](https://visactor.io/vchart/option/pieChart#indicator.visible)

  


[VChart Github](https://github.com/VisActor/VChart)

[VChart 饼图指标示例](https://visactor.io/vchart/demo/pie-chart/pie-indicator)

[VChart 饼图指标配置文档](https://visactor.io/vchart/option/pieChart#indicator.visible)
