### ISSUE TITLE
[FAQ] How to display the legend title and legend with left-right separation in the same row?

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VChart#908]
I would like to add some textual descriptions to a legend, expecting to create a legend and its corresponding text description at the bottom of the chart. The desired layout effect is to have the text left-aligned and the legend right-aligned, both in the same row.
Is there any charting library that can accommodate this specific custom layout logic?

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart的图例组件和标题组件提供了绝对定位的布局方式，通过设置`layoutType:'absolute'`即可开启该布局模式。

随后为图表设置足够的padding，将标题组件放在左下角，图例组件放在右下角，即可实现让图例的标题和图例左右分开显示。

  


VChart provides the legend component and title component, both have absolute positioning layout mode. By setting `layoutType: 'absolute'`, you can enable this layout mode.

Next, you can set sufficient padding for the chart and place the title component in the bottom left corner, and the legend component in the bottom right corner. This will display them into left-right separation in the same row.

## 代码示例 Code Example

```
import { useEffect, useRef } from "react";
import VChart from "@visactor/vchart";

export const Chart = () => {
  const containerRef = useRef(null);

  useEffect(() => {
    const spec = {
      type: "bar",
      data: [
        {
          id: "barData",
          values: [
            { type: "Autocracies", year: "1930", value: 129 },
            { type: "Autocracies", year: "1940", value: 133 },
            { type: "Autocracies", year: "1950", value: 130 },
            { type: "Autocracies", year: "1960", value: 126 },
            { type: "Autocracies", year: "1970", value: 117 },
            { type: "Autocracies", year: "1980", value: 114 },
            { type: "Autocracies", year: "1990", value: 111 },
            { type: "Autocracies", year: "2000", value: 89 },
            { type: "Autocracies", year: "2010", value: 80 },
            { type: "Autocracies", year: "2018", value: 80 },
            { type: "Democracies", year: "1930", value: 22 },
            { type: "Democracies", year: "1940", value: 13 },
            { type: "Democracies", year: "1950", value: 25 },
            { type: "Democracies", year: "1960", value: 29 },
            { type: "Democracies", year: "1970", value: 38 },
            { type: "Democracies", year: "1980", value: 41 },
            { type: "Democracies", year: "1990", value: 57 },
            { type: "Democracies", year: "2000", value: 87 },
            { type: "Democracies", year: "2010", value: 98 },
            { type: "Democracies", year: "2018", value: 99 }
          ]
        }
      ],
      xField: ["year", "type"],
      yField: "value",
      seriesField: "type",
      padding: [12, 12, 40, 12],
      legends: {
        visible: true,
        orient: "top",
        position: "start",
        layoutType: "absolute",
        bottom: -40,
        right: 12,
        padding: 0
      },
      title: {
        visible: true,
        text: "Two Series Category",
        layoutType: "absolute",
        bottom: -40,
        left: 12,
        textStyle: {
          fontSize: 12
        },
        padding: 0
      }
    };

    const vchart = new VChart(spec, {
      dom: containerRef.current
    });

    vchart.renderSync();

    return () => vchart.release();
  }, []);

  return (
    <div
      ref={containerRef}
      style={{
        width: 520,
        height: 520,
        border: "1px solid #ccc"
      }}
    />
  );
};
```

## 结果展示 Results

在线示例：https://codesandbox.io/s/layout-legend-q6sht5?file=/src/App.js

Online Demo: https://codesandbox.io/s/layout-legend-q6sht5?file=/src/App.js

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/ee4fe9d3b99f41d792ef87117b051bc1~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=1058&h=1062&s=36237&e=png&b=ffffff)

## 相关文档 Documents

[VChart Github](https://github.com/VisActor/VChart)

[VChart Title API](https://visactor.io/vchart/option/barChart#title.layoutType)

[VChart Legend API](https://visactor.io/vchart/option/barChart-legends-discrete#layoutType)

  


[VChart Github](https://github.com/VisActor/VChart)

[VChart 标题组件配置文档](https://visactor.io/vchart/option/barChart#title.layoutType)

[VChart 图例组件配置文档](https://visactor.io/vchart/option/barChart-legends-discrete#layoutType)
