### ISSUE TITLE
[FAQ]Can users click on data points within the VChart to show a list of actions?

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#929]
How can a data point in the chart be clicked to trigger a display of available actions, just like shown in this screenshot?
![image](https://github.com/VisActor/VChart/assets/8744196/893f77e8-4a26-4a5c-9111-c4bf29f55ff3)

**Comment by xuanhun** [comment]
## 解决方案 Solution

通过VChart图表的事件交互可以实现这个功能

1. 注册图表元素的点击事件

2. 通过事件回调参数可以拿到点击事件的信息，例如事件坐标等

3. 渲染一个菜单，菜单中添加你需要响应的操作

  


This can be achieved through the event interaction of the VChart chart

1. Register click events for chart elements

2. Through the event callback parameter, you can get the information of the click event, such as event position

3. render a menu, add the actions you need to respond to in the menu

  


## 代码示例 Code Example

```
vchart.on("pointerdown", { level: "mark" }, ({ event }) => {
  // show your menu
  event.preventDefault();
  menu.style.display = "block";
  menu.style.left = `${event.pageX}px`;
  menu.style.top = `${event.pageY}px`;
});
```

  


## 结果展示 Results

![image](https://github.com/VisActor/VChart/assets/2384516/b709070b-30e3-4834-ae9d-5df42bf60e6c)

Demo: https://codesandbox.io/s/click-menu-m42d9j

  


## 相关文档 Quote

Event option: https://visactor.io/vchart/api/API/event

Event tutorials: https://visactor.io/vchart/guide/tutorial_docs/Event

github：https://github.com/VisActor/VChart
