### ISSUE TITLE
[Feature] The effect of arc label is improved in small sizes

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#964]
### What problem does this feature solve?

There are two questions:

- The outerRadius has been changed to a smaller size, but the text is no longer displayed. It feels a bit counter-logical;
- Obviously the effect is not as good as 3.x, 3.x can display at a height of 60px

![img_v2_c9074ea5-d17e-4929-aedf-e8de8dc6052g](https://github.com/VisActor/VChart/assets/40026218/c93fe54a-3659-41aa-9f79-340ecaba6e13)

### What does the proposed API look like?

![img_v2_ad8155b6-2977-4ef1-80d4-f12ff62fb59g](https://github.com/VisActor/VChart/assets/40026218/529a857e-430a-43a4-912a-1463a835157b)

**Comment by xiaoluoHe** [comment]
duplicated with #1742
